### ISSUE TITLE
Is List slot with leading comma

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#100]
I managed to make this happen earlier:

may be related to #99 

<img width="297" alt="2018-02-06_15-42-41" src="https://user-images.githubusercontent.com/1779894/35883173-608336ba-0b54-11e8-849e-8f17d129703e.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/f46d0063f1baeb44b281f699a1096696e04e973e
