### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by stevemr03** [samtecspg/articulate#1001]
Operating Environment:
Version 80.0.3987.149 (Official Build) (64-bit) Version 0.31.1 Ubuntu 18.04 running on Chrome over the cloud on a AWS C5.2xlarge instance.

What is the recommendation for switching an agent from English to Spanish? Does an entirely new Spanish agent need to be created?

**Comment by wrathagom** [comment]
Are you using system entities at all?

If not you can likely build it all in one agent, just with one action for English and one for Spanish.

But to answer the main question, generally yes we recommend one agent per language. Sometimes there is a third agent that handles greeting and language detection.
