### ISSUE TITLE
Articulate converse service error

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#1003]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*
Make an agent
Train agent
Test agent
Receive error
Error: I'm sorry. An error occurred calling Articulate's converse service. This is not an issue with your agent. 

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release? 
latest
- What operating system are you running?
centos 7.7
- Are you running locally or in the cloud?
locally
- Which browser are you using?

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by wrathagom** [comment]
can you provide an export of your agent so we can try to identify the problem?

How much memory does your VM have?

**Comment by wrathagom** [comment]
Also, there may be an error in the terminal that may provide us some extra info. Can you paste/upload the output of `docker-compose logs api` in a gist?

**Comment by aermike** [comment]
Yes
qa is agent
[vm.zip](https://github.com/samtecspg/articulate/files/4435968/vm.zip)

8GB RAM
Screen attached
[qa.zip](https://github.com/samtecspg/articulate/files/4435963/qa.zip)

**Comment by wrathagom** [comment]
thanks, we'll take a look.

**Comment by aermike** [comment]
Thank you

**Comment by wrathagom** [comment]
@aermike can you tell me what the program category was for? Did it at some point in time have sayings in it? As soon as I deleted it the error went away. 

I tried to create a new agent and get it to fail in the same way by having an empty category, or a category where I had deleted stuff out of, but was unable to reproduce.

**Comment by aermike** [comment]
Hi
First agent's name was q&a, after see this error, I was rename the agent.
Categorii was hello, and action to respond at hello

**Comment by wrathagom** [comment]
I can rename agents just fine. :( still can't find a way to reproduce.

**Comment by aermike** [comment]
ok
I put vm on line again, and retest
Come back in ticket after

**Comment by aermike** [comment]
After reinstall is not reproduced
[robot.zip](https://github.com/samtecspg/articulate/files/4444878/robot.zip)

**Comment by aermike** [comment]
thank you for suport
