### ISSUE TITLE
Analytics Tab could not be Opend

### ISSUE THREAD

**Issue by dtamm** [samtecspg/articulate#1004]
- Pulled from master, v0.31.1 running it locally inside a debian VM with latest Docker version (via docker-compose)
- Using Google Chrome Browser (version 80)

Trying to open the Analytics Tab in an freshly set up agent will show just a blank page, the JS console is just showing the message 

```
main.988121522f5f9e046089.chunk.js:1 ReferenceError: _ is not defined
```
Seems like the Underscore Lib is missing somewhere!

**Comment by wrathagom** [comment]
this should be fixed on master. Make sure to clear your browser cache.
