### ISSUE TITLE
How to run local linux script as actions ?

### ISSUE THREAD

**Issue by anuragvohraec** [samtecspg/articulate#1006]
Is there a provision in articulate for running local unix scripts directly  as an action ?
For ex:
```bash runscripts.sh my_script_name```
Say I will create a script folder and and a script 'runscripts.sh', which will run one script file from that folder based on script name provided as argument.

I am building a personal desktop assistance for self help in my day to day job, which I will gradually extends to support my entire family. Say like personal assistance for my home.

If there would have been provisions to run linux/unix scripts directly as an action, I can quickly create many actions. I do not need to create webservices for them.

I can plugin many already build services and apps by running them via scripts.

**Comment by wrathagom** [comment]
Articulate only communicates web hooks, so you would need to wrap your scripts in some sort of web service or modify Articulate code to be able to run your scripts directly.
