### ISSUE TITLE
Internal Error at training

### ISSUE THREAD

**Issue by sabatale** [samtecspg/articulate#1012]
### Issues
Same as #856 . Where can I find detailed logs of the error?

### Reproduce
Click "Train" after adding the 2 standard categories "Weather" and "Small Talk".

```
POST http://35.211.44.163:8080/api/agent/1/train 500 (Internal Server Error)

Error: An error ocurred training Bobby. 🚒

Error: An internal server error occurred. 😮
```

**Comment by wrathagom** [comment]
how much memory do you have?

**Comment by sabatale** [comment]
Google Cloud VM n1-standard-1 (1 vCPU, 3.75 GB memory).

I've increased the RAM to 6.5GB and it fixed the issue. Thanks!
