### ISSUE TITLE
Error: I'm sorry. An error occurred calling Articulate's converse service. This is not an issue with your agent.

### ISSUE THREAD

**Issue by prabhakar29may** [samtecspg/articulate#1013]
This error starts showing up every few days. The api service goes down suddenly. What is the reason behind this error? Is there any error handling done at the articulate end which prevents the api service to go down? Why does the agent creation works and only the api service is down?
Our server is:
Ubuntu 18.04.
vCPU	Memory (GiB)	
8	        16	    
I can always replicate this if I start several sessions with an agent continuously for say 5 minutes. It can be a simple Hi/Hello chat bot doing nothing but accepting Hi and returning Hi

**Comment by wrathagom** [comment]
how many is several sessions?

**Comment by prabhakar29may** [comment]
Around 100 in a minute. But its not specific to several sessions. It happens for few sessions as well. This is happening every now and then.

**Comment by prabhakar29may** [comment]
What does this error mean?
An error occurred calling Articulate's converse service. What is it that throws this error?

**Comment by prabhakar29may** [comment]
For this: Are you monitoring CPU/memory usage while doing this?

Yes I have. The CPU goes to 120% and more. The memory is fine almost half available or free.

**Comment by wrathagom** [comment]
It means something happened in the API that prevented a response from being returned. You can look in your API logs for more info.

`docker-compose logs -f api`

**Comment by prabhakar29may** [comment]
Why does that happen? Is it the RASA NLU that causes this error? Can the error be handled so that it does not cause the converse api service to get down?

**Comment by wrathagom** [comment]
Open the logs and see if you find an error, or upload your API logs for us to take a look. I can't tell you why it happens unless I know what is happening.

**Comment by prabhakar29may** [comment]
There are tons of errors here. Why does it crashes the api service? Is there a way to prevent that from happening?

**Comment by prabhakar29may** [comment]
| Debug: handler, error
api_1            |     Error: mapper_parsing_exception
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            | Debug: internal, error
api_1            |     Error: mapper_parsing_exception
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            | { error:
api_1            |    { ResponseError: mapper_parsing_exception
api_1            |        at IncomingMessage.response.on (/usr/src/app/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
api_1            |        at IncomingMessage.emit (events.js:203:15)
api_1            |        at IncomingMessage.EventEmitter.emit (domain.js:448:20)
api_1            |        at endReadableNT (_stream_readable.js:1145:12)
api_1            |        at process._tickCallback (internal/process/next_tick.js:63:19)
api_1            |      name: 'ResponseError',
api_1            |      meta:
api_1            |       { body: [Object],
api_1            |         statusCode: 400,
api_1            |         headers: [Object],
api_1            |         warnings: null,
api_1            |         meta: [Object] } },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 500,
api_1            |      message: 'mapper_parsing_exception' },
api_1            |   message: null }


Most of the errors are like this.

**Comment by wrathagom** [comment]
can I see the logs from elasticsearch as well `docker-compose logs -f elasticsearch`

**Comment by prabhakar29may** [comment]
[apilogs.zip](https://github.com/samtecspg/articulate/files/4487997/apilogs.zip)
[elastLogs.zip](https://github.com/samtecspg/articulate/files/4488012/elastLogs.zip)
Attached both the logs.

**Comment by wrathagom** [comment]
thanks, reviewing now.

**Comment by wrathagom** [comment]
how much memory are you allocating to the JVM in Elasticsearch?

**Comment by prabhakar29may** [comment]
I have not allocated any memory.

**Comment by prabhakar29may** [comment]
When and how do we need to allocate the memory to JVM in elasticsearch? I did not come across anything like this when I installed articulate.

**Comment by wrathagom** [comment]
It's in the [compose file](https://github.com/samtecspg/articulate/blob/master/docker-compose.yml#L25). I would recommend splitting Elasticsearch our onto it's own VM with 8G of memory and changing that setting to be:

```
"ES_JAVA_OPTS=-Xms4g -Xmx4g"
```

Here's more background from ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

You'll also likely want to split Rasa out onto it's own VM as it eats CPU and can starve other processes.

**Comment by prabhakar29may** [comment]
Ok thanks!! I will make the changes as per your suggestion and will let you know what we experience.

**Comment by stevemr03** [comment]
When we have this error there was only two users on the system. There must be some other issue.

**Comment by prabhakar29may** [comment]
> It's in the [compose file](https://github.com/samtecspg/articulate/blob/master/docker-compose.yml#L25). I would recommend splitting Elasticsearch out onto it's own VM with 8G of memory and changing that setting to be:
> 
> ```
> "ES_JAVA_OPTS=-Xms4g -Xmx4g"
> ```
> 
> Here's more background from ES: https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
> 
> You'll also likely want to split Rasa out onto it's own VM as it eats CPU and can starve other processes.

Sir..the memory increase did help with elasticsearch not throwing any errors now. But I saw this error which I am not getting what it means. Can you please help with this:

[36mapi_1            | [0m 2020-04-18T14:34:29.704896903Z     Error: Agent id=[20]
[36mapi_1            | [0m 2020-04-18T14:34:29.704901069Z     at /usr/src/app/lib/routes/agent/agent.find-all-sessions.route.js:24:24
[36mapi_1            | [0m 2020-04-18T14:34:29.704904833Z     at Generator.throw (<anonymous>)
[36mapi_1            | [0m 2020-04-18T14:34:29.704908655Z     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.find-all-sessions.route.js:11:103)
[36mapi_1            | [0m 2020-04-18T14:34:29.704912415Z     at _throw (/usr/src/app/lib/routes/agent/agent.find-all-sessions.route.js:13:291)
[36mapi_1            | [0m 2020-04-18T14:34:29.704916116Z     at process._tickCallback (internal/process/next_tick.js:68:7)

The agent Id = [20]..if it is looking for the agent with agentId 20 then we deleted it. The guys who are developing the agent found that there is no way to update an agent and so they deleted an agent.
This same error happened several times and the UI and API service stopped responding.

**Comment by wrathagom** [comment]
How did you delete it? direct from Redis or using the delete button in the UI?

What does this mean?
>The guys who are developing the agent found that there is no way to update an agent

**Comment by prabhakar29may** [comment]
I mean one of our team member who was working on creating agents deleted the agent from the UI saying that there is no option to update an agent.

**Comment by stevemr03** [comment]
Delete was performed from the UI. We are not clear on how to update from development to the same production agent. We have had to create new agents each time, which is why we deleted the old agent.

**Comment by wrathagom** [comment]
@dakavisa can you make sure there's no problem with analytics/review page trying to lookup the records of deleted agents?

Also, see what happens when you try to go to the review page via URL of an agent that has been deleted.

**Comment by wrathagom** [comment]
I still don't understand this `We are not clear on how to update from development to the same production agent.` you can definitely go back into an agent and make changes.

**Comment by stevemr03** [comment]
Agent crashes after update see #1000 . We will try it again and see if we have the same problem. If we do, we will post the logs. Is the best method to export from development and import into production instance?

**Comment by wrathagom** [comment]
Can you try to capture that one on video? or capture terminal logs right after it happens?

**Comment by stevemr03** [comment]
This problem has not happened again. We think it was related to deleting an agent.
