### ISSUE TITLE
Regular expression based Keyword not working properly 

### ISSUE THREAD

**Issue by Neo032020** [samtecspg/articulate#1014]
### Issues
Hi,
as per our requirement we need to collect **Date Of Birth** of user
and i used sys.spacy_date and sys.duckling_time but both was accepting only yyyy-mm-dd format but we need all possible date format, specially mm-dd-yyyy so i used Regular expression "/(0[1-9]|1[012])[- \/.](0[1-9]|[12][0-9]|3[01])[- \/.](19|20)\d\d/" based Keyword but somehow it is not working for date 10-31-1991 etc.,
and it also not high-lighted saying when added some example, manually we have to do the same..

**Please guide me for using regular expression based keyword..**

thanks in advance     

System Info.
![Capture1](https://user-images.githubusercontent.com/62658685/79452830-691eb280-8006-11ea-9091-883e5afe8755.PNG)

we are using latest release of articulate
Operating Environment:
Version 80.0.3987.149 (Official Build) (64-bit) Version 0.31.1 Ubuntu 18.04 running on Chrome over the cloud on a AWS C5.2xlarge instance.

**Comment by wrathagom** [comment]
@dakavisa did you look at this one?

**Comment by dakavisa** [comment]
@Neo032020 I tested it using this regex. My keyword is of type regex and has the following value/synonym set with the regex expression:

![image](https://user-images.githubusercontent.com/53984674/79798398-2a467080-8316-11ea-9ef6-3126791b0665.png)

If you still see an issue please send me the exact value of regex you are using for value/synonym

**Comment by wrathagom** [comment]
Let us know if that doesn't get you going.

**Comment by Neo032020** [comment]
Sir,
please find the agent , i need your help regarding questions
Question 1. when No Slot define for date it accept all possible format, but when we define sys.spacy_date then it accept only yyyy-mm-dd! else show error of mapper_parsing_exception.
Question 2. when in define two separate keyword for Zip code[^\d{5}] and mobile number[^\d{10}] after entring ZipCode it is fine but when Mobile number entered then why it mix-up mobile into ZipCode
Question 3. sys.spacy_person not Supporting Only First Name, it accept when first name and last name like "John Lee" but not "john lee"
Question 4. I just need some thing like that ConfirmationAction it is working with Yes/No but not with their Synonyms

Please guide me if i should follow some specific flow for Articulate Development

Your product Articulate is nice but due to limited information available on web, like we did not know that in case of Regex we should put same Regex in values also!
many important information you are providing us, thanks 

[RD1.TXT](https://github.com/samtecspg/articulate/files/4527799/RD1.TXT)
