### ISSUE TITLE
Training Different Agents

### ISSUE THREAD

**Issue by stevemr03** [samtecspg/articulate#1015]
We are creating different agents for different feature sets, such as one to handle payment and collections and another to handle appointments. It appears that Rasa NLU only supports one unified model. (1) Has any method been found to prevent actions from switching to incorrect dialog or if they are different customer dialogs to ensure a certain branch can only be used?  (2) what is the best process to update the same agent and release from development to production without causing issues with the Rasa NLU?

**Comment by wrathagom** [comment]
this doesn't apply to Articulate, we use an older version of Rasa that allows concurrent models. one agent has no impact on another.

That being said, if you ever want someone to be able to pay and schedule a second appointment, etc you would want them in one agent.

**Comment by stevemr03** [comment]
Thanks. That is good to hear as it is critical to support multiple agents. So we can not use the webhook to switch between agents?  We are looking to package the services based on what each customers wants to use.

**Comment by wrathagom** [comment]
I've never done it that way, so I can't say for sure. You can definitely point your chat to one agent or the other. How to know when to switch back and forth would be worrisome to me.

**Comment by stevemr03** [comment]
At the end of capturing the information for an agent, I could pass it back to the original or main agent. For example, user has option to book an appointment or make a payment. If the make a payment, they are passed back to the main agent and can then make an appointment.
