### ISSUE TITLE
Redundant help videos on main page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#1017]
I can't really think what to talk about from this page for both of these help buttons, so let's eliminate the one besides connections

<img width="587" alt="image" src="https://user-images.githubusercontent.com/1779894/80145225-d938b580-857d-11ea-8658-cd0e314e5be7.png">

**Comment by dakavisa** [comment]
Closed by ea9fe7eed58438c4f1dc25ffca8cf18f01a2fbe5
