### ISSUE TITLE
What is the need and working of parameters for creating the agent 

### ISSUE THREAD

**Issue by akritimittal8171** [samtecspg/articulate#1021]
Issues

The Role of Parameters for creating the agent

**Comment by wrathagom** [comment]
They're completely optional. Parameters exist both at the agent level and on Categories. An example would be a webhook URL that gets used over and over. Let's say when you're developing you are hitting a dev webhook like `https://my-dev-webhook:7500/api/do-something` you could type that into the URL for each action. But then when you deploy your agent and want to change the webhook URL to `https://my-prod-webhook:7500/api/do-something` you would have to go into each action to change it.

Alternatively you could use a parameter for the root of the webhook. and reference that. In this way if you needed to change the URL you would only have to change it in one place. Then in the actions use handlebars to reference it: `{{agent.parameters.myUrl}}/do-comething`

**Comment by akritimittal8171** [comment]
Thank you for your response

But I am little bit confused in global webhook connection . Can you please explain with example and the usage of it ??

**Comment by wrathagom** [comment]
so each action can have a webhook, but we've seen that sometimes every action hit's the same webhook, just with a different path.

So you could configure action `get-orders` with a webhook of `http://my-api/get-orders` and action `palce-order` with a webhook of `http://my-api/place-order` or you could define a global webhook like `http://my-api/{{action.name}}` and then you wouldn't have to define a webhook on each action.

Hope that helps. Both parameters and global webhook would be considered convenience functions.
