### ISSUE TITLE
I want to train the chatbot with pdf and get data from MySQL

### ISSUE THREAD

**Issue by ngcgolf11** [samtecspg/articulate#1032]
Hi SPG,

You have done a great job by open source this chatbot. I am new developer and I want to train this chatbot from pdf and it is possible to get data from MySQL database if you like to suggest which database I have to use to implement this in production environment  for a education.
is there any dataset available for train this chatbot

**Comment by wrathagom** [comment]
Articulate provides a UI where you train the chatbot on sayings. I'm not directly clear what you mean by train it with a PDF.

Articulate cannot connect to MySQL directly. You're SQL queries would need to be wrapped in a webhook, then Articulate could call the webhook.

**Comment by ngcgolf11** [comment]
@wrathagom i want to train my chatbot from pdf book it is possible

**Comment by wrathagom** [comment]
Not with Articulate or Rasa, that's not how they work. What you're talking about sounds like a more direct Natural Language Processing capability.
