### ISSUE TITLE
Regarding customize buttons

### ISSUE THREAD

**Issue by Beherasaptami** [samtecspg/articulate#1033]
I just wanted to know if want my actions to be in button format then is it possible to achieve that using articulate

**Comment by wrathagom** [comment]
Yes it does.

We released this functionality in 0.31 under Rich Response Types. https://blog.spg.ai/articulate-v0-31-release-e4375647b568

**Comment by Beherasaptami** [comment]
Did you download a release or pull from Master? Which release?
pull from master
What operating system are you running?
Linux
Are you running locally or in the cloud?
Locally
Which browser are you using?
google chrome
![image](https://user-images.githubusercontent.com/54348413/80921110-d4e87580-8d91-11ea-849b-a0c509569f3b.png)

I want to try buttons but there is no option of button few day back you have send me a post in that post button option is there but i didn't found any button option any suggestion

**Comment by wrathagom** [comment]
Why did you post this here and create a new issue? I've already replied to your other issue.

**Comment by wrathagom** [comment]
See solution on #1039
