### ISSUE TITLE
Agent need permission to access 

### ISSUE THREAD

**Issue by Beherasaptami** [samtecspg/articulate#1036]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
downloaded a release
- What operating system are you running?
linux
- Are you running locally or in the cloud?
locally
- Which browser are you using?
chrome
----
i am facing issue like agent need permission to access
![image](https://user-images.githubusercontent.com/54348413/80834809-16044c80-8c0f-11ea-8b7e-f1b55554a106.png)

**Comment by wrathagom** [comment]
how did you start Articulate? Which release did you download?

**Comment by Beherasaptami** [comment]
i have downloaded (https://github.com/samtecspg/articulate/releases/tag/v0.31.1)release 0.31 from the above url have downloaded only articulate-0.31.1.zip file after that i unzip nd tried to run the commands which is mention on repository 
1.sudo chown -R 1000:1000 local-storage/elasticsearch
2.sudo docker-compose up

**Comment by wrathagom** [comment]
Can you clear your local browser cache and reload the page?

**Comment by Beherasaptami** [comment]
![image](https://user-images.githubusercontent.com/54348413/80841710-992c9f00-8c1d-11ea-8e18-bdb9a2c16f06.png)
I clear cache nd reload the page still m facing same error
