### ISSUE TITLE
Bring back Exit button for actions page

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#1038]
### Feature Request

31.1 Release Firefox

When making edits or saving an action, I think it should stay on the action page instead of going back to dialouge page. This will save time. Many users like myself will want to save something, then continue editing instead of having to go back to the action everytime an edit is saved. 

Or it could be a preference setting, that could be added in later.

**Comment by wrathagom** [comment]
This functionality hasn't changed. Clicking save stays on the page. Clicking exit exists the page. Are you saying your's is behaving differently?

Are you running master or 0.31.1?

**Comment by RussellSPG** [comment]
Yes not master, running 31.1 release. When I click save it saves, then exits to dialouge page.

**Comment by wrathagom** [comment]
Closing in favor of #1045
