### ISSUE TITLE
31.1 rel Modifers button not working when windowed mode

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#1041]
### Issues

When I have my browser in windowed mode, I am not able to click the modiers button. This only works if Browser window is a certain size.

![image](https://user-images.githubusercontent.com/42249324/80930760-82a05800-8d83-11ea-8d7c-08358e976db5.png)

Firefox Browser.
On step 13.22 in script.

**Comment by wrathagom** [comment]
On smaller windows (once the text disappears) the button gets disabled.

**Comment by wrathagom** [comment]
Closing in favor of #1045
