### ISSUE TITLE
31.1 rel Save icon in modifers when windowed not working before Save

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#1042]
### Issues
When clicking the save icon when browser in windowed where it shows the icons, there is no color/animation when hitting the save icon. Though it does save, it looks like its not being saved.

![image](https://user-images.githubusercontent.com/42249324/80931225-5934fb80-8d86-11ea-919f-d67cb0232b00.png)

**Comment by RussellSPG** [comment]
EDIT as of now: Just realized that in windowed mode the modifier button will work before Saving an agent. It's when clicking save, it will then be greyed out.

**Comment by wrathagom** [comment]
Closing in favor of #1045
