### ISSUE TITLE
Some queries to ask 

### ISSUE THREAD

**Issue by Beherasaptami** [samtecspg/articulate#1046]
Hello there , I have some queries to ask :
1.**Do articulate use 0.14 version of rasa or anything else**
2.**Do articulate use rasa core as well**
3.**How articulate is differentiating models,agents and training data** 
4.**How articulate using redis to store the models**
5.**Which version of rasa  will be better for using articulate**

**Comment by wrathagom** [comment]
1. Articulate uses Rasa and Duckling
2. No
3. We create a model for each time you click train and serve the latest model. You can see our outbput in the local-storage/rasa folder
4. It doesn't. It uses Redis to store the information needed for the UI
5. You can't change the version of Rasa, you have to run our image. Why do you want to change it?

**Comment by Beherasaptami** [comment]
i just want to know like which version of rasa is using in articulate ,and i just have rough idea so i am clearing my doubt like  do version of rasa will bother articulate or not .

**Comment by wrathagom** [comment]
We are using the last version where they supported multiple models 0.14.4

https://github.com/samtecspg/articulate/blob/master/rasa/Dockerfile#L5

**Comment by Beherasaptami** [comment]
and articulate have its own dialogue management why articulate didn't use rasa core any specific reason for that

**Comment by wrathagom** [comment]
We implement our own dialogue management. We only use Rasa for NLU. Core didn't exist when Articulate was first made and there is no way to integrate how we do dialogue with how Core does it.

if you want a GUI for Rasa core use Rasa X.

**Comment by Beherasaptami** [comment]
Okay thanks
