### ISSUE TITLE
Import option per agent

### ISSUE THREAD

**Issue by dakavisa** [samtecspg/articulate#1047]
Right now Import creates a new agent - new id, it would be nice if the user could import an agent directly over another (like dev to prod, local to server) so the user can apply changes by importing without rewiring all the connections

**Comment by broham89** [comment]
![agent list page v 2](https://user-images.githubusercontent.com/11262149/81343073-e83d5e80-9079-11ea-9924-6cd1e28e5bc5.png)

**Comment by broham89** [comment]
i believe at this point it's ok to take out the work export and import but have a hover tooltip to explain it. 

[import export.zip](https://github.com/samtecspg/articulate/files/4595709/import.export.zip)

**Comment by wrathagom** [comment]
@dakavisa we can close this right? Did you add test coverage for this as well?

**Comment by dakavisa** [comment]
@wrathagom  not yet but Im going to make that another issue so I dont forget

Closed by da4ca50471acc9d8e065783a1fcac2fb491d7cd4
