### ISSUE TITLE
Add delete button to action tab

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#1056]
In the case of trying to get rid of a bunch of actions, it's kind of handy to have the delete button in the action list.

**Comment by RussellSPG** [comment]
I literally was going to post this as an idea now. Definitely needs to be added. Deleting all the actions from say a pre made category is a pain.

**Comment by dakavisa** [comment]
Closed by f1dfe110201fdc2d25cc91a0b036ab3c708be650
