### ISSUE TITLE
Add error message when adding pre-made category when existing items aren't deleted

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#1057]
### Feature Request
We should have an error message for letting the user know there are existing actions, keywords or whatever that need to be deleted before importing the pre-made category again. Otherwise agent will crash to blank screen with error:
```
The above error occurred in task Fe
    created by takeLatest(app/CategoryPage/IMPORT_CATEGORY, Fe)
    created by Le
Tasks cancelled due to error:
takeLatest(app/CategoryPage/IMPORT_CATEGORY, Fe)
takeLatest(app/CategoryPage/LOAD_PREBUILT_CATEGORIES, ke)
```

Tested on Master

**Comment by wrathagom** [comment]
@dakavisa did this one get addressed already with the changes you made?

**Comment by dakavisa** [comment]
yeah, there should now be error messages for those cases:

![image](https://user-images.githubusercontent.com/53984674/83435418-6e3e9200-a3f9-11ea-8183-ceabd845766a.png)

If there is still any problem with this let me know @RussellSPG
