### ISSUE TITLE
Persist current page of action list when editing an action

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#1062]
### Feature Request
I constantly am using the actinos page and other users probably will be as well. When clicking the next to the action I want to select, then chosing it, making edit, and saving, it returns to page 1 of the actions. Its annoying having to go to the right page every time. I think it should save on its current page, once clicked on it, then when saving the action, it returns back to the same page.

**Comment by wrathagom** [comment]
I was thinking this worked on other list pages, so we just missed something on this one.

**Comment by dakavisa** [comment]
Closed by 39edbec8000d502b415f6b1aeaed8892861d1dec
