### ISSUE TITLE
Update some verbiage on Modifiers page

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#1063]
### Feature Request
This should say keyword value, as its a value your highlighting in the keyword
![image](https://user-images.githubusercontent.com/42249324/82353913-130aa980-99ce-11ea-9bf6-e2bd6d104066.png)

**Comment by wrathagom** [comment]
"Highlight a word to label it as a keyword value."

**Comment by dakavisa** [comment]
Closed by 7d055a5490c2fe53cfba5f2d2fa6bd6923b36896
