### ISSUE TITLE
Rich Response Edit modal shows edit button instead of save

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#1073]
If you've made it here you are already editing. I think this should be a save button.

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1779894/85204794-e4d9fb80-b2e4-11ea-8f0c-777a667c5f9e.png">

**Comment by dakavisa** [comment]
Closed by 6af10329dc5a8d41cab6d0c5c332d2e95730ac84
