### ISSUE TITLE
Allow markdown/formatting of message to users in web demo

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#1076]
Right now formatting, like my new lines here are ignored. We should enable markdown formatting of the `Message for Users` text.

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/1779894/85211808-c5f65c00-b31a-11ea-9e51-0760d983346d.png">

**Comment by dakavisa** [comment]
Closed by ffa3c103d6e7fbc465cbea35b720238bf43248dc
