### ISSUE TITLE
Slot Suggestions in Responses not working

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#108]

**Comment by wrathagom** [comment]
On second thought I imagine we broke this when we moved to handlebars?

**Comment by dcalvom** [comment]
Yes and no. We need to start to make suggestions based on the elements we expect to have on the CSO, but probably, those are going to be a lot. I think this requires more design, what you think?

**Comment by wrathagom** [comment]
My guess is that there should already be a library for object based auto complete we'll just have to find it. Agree either way it requires more design. I am thinking about adding a star or indicator of some sorts to the user says examples that way you can denote which example you'd like to test with...

**Comment by wrathagom** [comment]
Removed the bug tag. We just need to investigate how to do this. @dcalvom or @malave any clever ideas or is it just going to be a good chunk of code we need to write?

ideally it would auto-complete keys from the CSO, but also handlebars helpers like toJSON, #if, etc.

**Comment by wrathagom** [comment]
@dcalvom does this work in the new UI? I am thinking I should close this one in favor of #409
