### ISSUE TITLE
Validate forms and manage errors from the API

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#11]
A component called input warning already exists in the UI project. Use this component to validate each form of the UI in order to prevent bad requests to the API.

Related to this functionality is the error management. API returns different errors depending if some field is missing or bad data was sent. The idea is to show the proper alert to the user based on the error returned by the API.

**Comment by dcalvom** [comment]
Hapi.js allow us to specify custom errors in the API like in https://github.com/samtecspg/articulate/blob/master/api/modules/intent/config/intent.validator.js#L15 . So the next step is to pass through all the validators and create proper custom errors. Once that's done is jus master of test to check that the error is being shown properly.

**Comment by wrathagom** [comment]
@dcalvom what's the status of this?

**Comment by wrathagom** [comment]
@dcalvom status check?

**Comment by dcalvom** [comment]
There still a lot of messages to improve, but at least we are generating alerts for errors.

**Comment by wrathagom** [comment]
Closing, we'll address on a case by case moving forward. Not to mention we need an interface for managing overall bot status, errors, warnings, etc.
