### ISSUE TITLE
Create Domain button hidden by Nav Bar

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#111]
<img width="1576" alt="2018-03-04_21-27-46" src="https://user-images.githubusercontent.com/1779894/36954888-e9708984-1ff2-11e8-9696-37715151a5ca.png">

**Comment by wrathagom** [comment]
Only happening for my in the "Wizard" steps

**Comment by wrathagom** [comment]
Also on intent and entity part of wizard
<img width="1576" alt="2018-03-04_21-32-56" src="https://user-images.githubusercontent.com/1779894/36954996-a63fe23a-1ff3-11e8-853d-1222da1d8517.png">

**Comment by dcalvom** [comment]
Got it. It's already fixed. I will push the changes soon.

**Comment by dcalvom** [comment]
Fixed by https://github.com/samtecspg/articulate/commit/6ec327120ff750019675db2287d5fcb4889acafc
