### ISSUE TITLE
Where used for intent - no rows found misaligned

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#114]
<img width="1135" alt="2018-03-04_21-59-16" src="https://user-images.githubusercontent.com/1779894/36955582-5415eb9a-1ff7-11e8-9528-f44bef2256a2.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/830c1e3b88f01775faa24498cfa36e6e6eb646d2
