### ISSUE TITLE
Include Default JSON/XML payload when it is selected.

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#115]
See the original Basecamp post on this topic as I proposed a default payload there.

**Comment by dcalvom** [comment]
Lost track of this one! I will work on this

**Comment by dcalvom** [comment]
@wrathagom I alreadya added 
```
{
	"text": {{text}},
	"intent": {{intent}},
	"slots": {{slots}}
}
```
As the default payload for JSON payloads, could you tell me how the XML payload looks?

**Comment by wrathagom** [comment]
ah found the issue, this isn't working if it got merged. Anyway in hindsight the above isn't the proper format given that we have to use the `toJSON` helper.
