### ISSUE TITLE
"Are you sure you want to leave?" message

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#12]
Whenever the user is on a screen that has a form and tries to navigate outside that screen a message of "Are you sure you want to leave?" should be shown.

**Comment by wrathagom** [comment]
@broham89 any input on what these messages should look like? Or do we already have some sort of an alert/modal styling for Articulate?

**Comment by broham89** [comment]
[icon.zip](https://github.com/samtecspg/articulate/files/1624419/icon.zip)
![warning-popup](https://user-images.githubusercontent.com/11262149/34851702-e07ac158-f6f0-11e7-8e4b-e0956aa63009.png)

Here is a design that would work for a warning popup. I've also attached the icon with the confused face to display.

**Comment by dcalvom** [comment]
Nice! I will ask your for the css files

**Comment by wrathagom** [comment]
@dcalvom this isn't live yet?

**Comment by dcalvom** [comment]
Closed by
