### ISSUE TITLE
isList and isRequired aren't working

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#120]
Selecting these has no impact on the scenario that get's created.

**Comment by wrathagom** [comment]
Interestingly enough when I tried to updates these via the API the change still didn't stick so it may be an API problem?

**Comment by dcalvom** [comment]
@malave I solved this as it was needed for me for another bug. It was an error on the casting I did in the implementation of the webhook enhacement.

**Comment by dcalvom** [comment]
Fixed by https://github.com/samtecspg/articulate/commit/32d4ae2febe25e1b2eed2e416d3e49c8bea36521
