### ISSUE TITLE
Parallelize Training

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#121]
Looks like right now we are calling each training process in sequence, Rasa has the ability to parallelize these so we should investigate launching all at once. Though I don't know how Rasa handles it when it doesn't have more training processes available so we'll need to look into that.

**Comment by wrathagom** [comment]
@dcalvom did our discussion this morning about number of threads and number of training process mean that this is already setup in our API for parallelizing, but something's not right on the Rasa side?

**Comment by wrathagom** [comment]
Looks like all of our training sequences use async.waterfall, which wouldn't try to parallelize. Do we need waterfall or can we async.parallel?

**Comment by dcalvom** [comment]
Before the change of version of Rasa it was working as you said (paralleled) so it was async parallel. Now I'm using waterfall or series. Is just matter of change that.
