### ISSUE TITLE
Batch upload of entities

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#122]
If you want to add a new entity with a lot of examples it would be nice to have a batch upload option given.

**Comment by wrathagom** [comment]
@dcalvom can this key off of the type it receives. If it receives an object it's a single value, if it receives an array it's a batch?

@ewoo what's the RESTful approach?

**Comment by dcalvom** [comment]
So you would like to use the same endpoint `POST /entity` either to insert a single value or for a batch upload?

If so, that isn't an issue, we could handle that

**Comment by wrathagom** [comment]
Yep unless @ewoo has an objection

**Comment by dcalvom** [comment]
Sorry, @wrathagom I got confused about this one. The title I added was batch upload of entities, but my comment was actually referring to batch upload of entity examples, but know that I read all the comments I think you want a batch upload of entities.

Could you tell which one are you thinking?

**Comment by wrathagom** [comment]
yeah, I was thinking it was entities values/synonyms. 

Where would you be uploading the entity examples to? Right now they are all attached to an intent correct?

**Comment by wrathagom** [comment]
@dcalvom do we still need this one?

**Comment by dcalvom** [comment]
Is a nice to have, but not required or road block, your call

**Comment by dcalvom** [comment]
To bump up this one I think we could keep talking about this in issue https://github.com/samtecspg/articulate/issues/595
