### ISSUE TITLE
Scroll indicator get lost if the list of entities is to large

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#123]
![scroll entities](https://user-images.githubusercontent.com/7228045/37067494-b63130a4-216f-11e8-941e-564e18d69fd6.gif)

**Comment by broham89** [comment]
@dcalvom try using `overflow-y: hidden` or `overflow-y: auto`

**Comment by dcalvom** [comment]
@broham89 I tried both solutions you mentioned and even other workarounds but those weren't fruitful, do you think you can help me out here?

**Comment by broham89** [comment]
What is the css set for the main container height? I think take the height `px` of the header and **minus** the total height of the parent main container.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/381ff022efbeadd384ce75b17eb73ee946cf091c Thanks @broham89
