### ISSUE TITLE
Bug fixing in the UI

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#13]
These are open bugs in the UI that need to be fixed

 * Autoscroll down when new examples are created in the entity screen
 * Autoscroll down when new data is entered in the intent screen in user sayings, slots and responses tables
 * Fix issue with Chips component on delete in the entity screen for synonyms
 * Fix issue with Chips component on delete in the intent/scenario screen for text prompts
 * Fix position of the dropdown selector of slot in agent response in the intent/scenario screen.

**Comment by wrathagom** [comment]
I created a seperate issue #58 that seems to overlap a little bit with this one. Also #65 needs to scroll as well.

**Comment by dcalvom** [comment]
Fixed autoscroll bug with https://github.com/samtecspg/articulate/commit/4fbbb79e7bd71903ba8f27a9bdc2df464c70d0d2. Just missing the position of the dropdown in the agent responses

**Comment by wrathagom** [comment]
@dcalvom did the last item here get fixed?

**Comment by wrathagom** [comment]
@ecalvom status check?

**Comment by dcalvom** [comment]
The only missing is `Fix position of the dropdown selector of slot in agent response in the intent/scenario screen.` but this can be more a dessign task than an issue. Because the dropdown is always showing on top as the agent response input is always at the bottom of the screen.

**Comment by wrathagom** [comment]
@dcalvom is this still an issue or did you fix it when you were working with the auto complete inside of the responses?

**Comment by dcalvom** [comment]
We can close it now
