### ISSUE TITLE
Buttons on agent page are different from all the other buttons

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#130]
Is there a reason for this?

<img width="1904" alt="2018-03-09_22-33-05" src="https://user-images.githubusercontent.com/1779894/37237956-e83c061a-23e9-11e8-88f3-548990230868.png">

**Comment by dcalvom** [comment]
Well that was a @

**Comment by dcalvom** [comment]
Well that was a @broham89 suggestion. Given that there doesn't exist an agent's list screen, the edit and delete are over there

**Comment by broham89** [comment]
I'm thinking the edit should exist when an agent, intent, or domain is already created and set. When the user wants to go back and open the agent, intent, or domain then edit would appear. Delete button should always appear any process. If it's the first time creating an agent, intent, or domain then only the Create button and Delete button should appear next to each other.

**Comment by wrathagom** [comment]
@broham89 maybe in 2.0 we should make agent's consistent with domain and intents and have a list screen.

Either way I am fine with this one staying this way until we go to the new UI.
