### ISSUE TITLE
Add Beta disclaimer and contact info

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#131]
@ewoo @BrightMeow you all can suggest edits to the copy. @broham89 can you suggest styling?

Should read something like:

---
Thanks for trying Articulate! We're excited that you've joined us in testing this software. I hope you enjoy using it as much as we do.

This is a pre-release of Articulate and is certain to have bugs or short comings. If you have any questions please [create an issue](https://github.com/samtecspg/articulate/issues/new) or [join us on Gitter](https://gitter.im/samtecspg/articulate).

Built with [Rasa NLU](https://rasa.com)

---

The create an issue should link to the new issue page and the join us on Gitter should link to our Gitter channel.

I think we should put it here:
<img width="1904" alt="2018-03-09_23-39-23" src="https://user-images.githubusercontent.com/1779894/37238416-b2b864e8-23f3-11e8-9fda-ea167a5c5456.png">

**Comment by ewoo** [comment]
Your draft copy works!

**Comment by dcalvom** [comment]
There is any design available for this already?

**Comment by broham89** [comment]
@dcalvom I will send you a html/css version of it.

**Comment by broham89** [comment]
@dcalvom Here are the places i've added the code for above issue. 

- **Index.html line 38-41** 
- scss/components/**_sidenav.scss line 80-105** 

[nlu-styles.zip](https://github.com/samtecspg/articulate/files/1843413/nlu-styles.zip)

**Comment by wrathagom** [comment]
@dcalvom think you'll have a chance to get to this one soon? I want this in the release before we package up for the announement.
