### ISSUE TITLE
API/Swagger needs more Configuration Options

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#132]
Currently can't run swagger docs behind Nginx reverse proxy because I can't set the path correctly. We need to expose this as an environment variable.

Specifically the host, basePath, and schemes.
```
    "host": "api:8000",
    "basePath": "/",
    "schemes": [
        "http"
    ],
```

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5dc9193ef0eb1704ee4cf426c2721c10e7c9d97d
