### ISSUE TITLE
Possible error during parsing of textResponse

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#134]
On [/api/modules/agent/tools/respondFulfilledIntent.agent.tool.js#L10](https://github.com/samtecspg/articulate/blob/15df2979d97722cece08f3a72ab3e587571199c5/api/modules/agent/tools/respondFulfilledIntent.agent.tool.js#L10) we are merging the `CSO` with the `webhookResponse` using `_.merge()` this could cause a potential error if the `webhookResponse` contains a variable with the same name of an existing variable in the `CSO` since this last one will be overwritten, for example if the `webhookResponse` had a `context` variable then the `CSO` `context` will be replaced. 

I think we should just add a new variable to `CSO` and save the entire `webhookResponse` there.

**Comment by wrathagom** [comment]
I think this is the intended response, I asked @dcalvom to log a warning in the console when this happens. We're going to move fairly soon to allowing the webhook to override the context and slot values and it would make sense that they just pass them back in their original names.

Also with the templating stuff if you know the API you are using has a conflict you can move the request to a new key:

```
{
  "requestContext": {{toJSON context}}
}
```

Make sense or not?

**Comment by wrathagom** [comment]
@ewoo @dcalvom FYI

**Comment by malave** [comment]
@wrathago: yep, it makes sense if this is the expected behavior.
