### ISSUE TITLE
Domains without an agent

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#135]
Somehow I've managed to have domains showing the list of domains even though I don't have an agent selected.

@malave I know we're persisting some info to local storage, but maybe we need to back off what all we're storing there Maybe only store the current agent and the current page or something like that. I think this was a local storage problem, having deleted the agent from the API and then returning to the UI...

<img width="1648" alt="2018-03-26_09-08-59" src="https://user-images.githubusercontent.com/1779894/37927462-e5f80536-30d5-11e8-8a07-f494f508ca41.png">

**Comment by dcalvom** [comment]
Closed in favor of https://github.com/samtecspg/articulate/issues/241
