### ISSUE TITLE
UI/UX improvement

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#140]
After the video presentation did by @wrathagom I think there is some room for improvement with:

- [x] ~Fix how the user enable the webhook for intents and agent, because right now the user needs to scroll up to enable it, and then scroll down~
- [x] The fact of use the 3 dots menu in the lists screen seems a little bit rough. That's somehow tackled in the domain and intent screen because when you click on an item you navigate to the edit page, but in the case of the entities you need to use the 3 dots menu for that

- [x] Set focus on the payload input component whenever the use select `json` or `xml` payload type for the webhook

**Comment by wrathagom** [comment]
Moving the top item to a new issue
