### ISSUE TITLE
Fast Forward to Rasa Latest

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#141]
We're currently building using Rasa 0.11.0, they are nearing a 0.12 release and have made some pretty large changes. Placeholder for that work.

**Comment by wrathagom** [comment]
The biggest thing to watch out for will be the configuration changes they have made. Most all configuration is now done with yaml files. Specifically, you pass a new format to the `/train` endpoint that has the language and pipeline in it:

```
language: "en"

pipeline: "spacy_sklearn"

# data contains the same json, as described in the training data section
data: {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      }
    ]
  }
}
```

**Comment by wrathagom** [comment]
I know they've made a bunch of changes to how you configure Rasa, but I pulled the `lateslt-spacy` version down today and it was plug and play with Articulate, so this may be an easy change.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/bfdaad4254be120d32157181add107e8b0cd60c3
