### ISSUE TITLE
Fix Redis deprecation warning

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#143]
We're getting the following warning from Redis:

```
api_1       | node_redis: Deprecated: The HMSET command contains a argument of type Array.
api_1       | This is converted to "" by using .toString() now and will return an error from v.3.0 on.
```

We need to address this.

**Comment by dcalvom** [comment]
@wrathagom whenever you identify a scenario where this happens please let me know as I wasn't able to reproduce it.
