### ISSUE TITLE
Add the Comparison Handlebar helpers

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#148]
@dcalvom for whatever reason I didn't realize that handlebars couldn't do conditionals out of the box can you install the `comparison` helpers from here: https://github.com/helpers/handlebars-helpers#comparison

@btotharye this would allow you to do your Mycroft stuff without needing an additional API for fulfillment.

**Comment by dcalvom** [comment]
I added the comparison helper to Hanldebars. 

Closed by https://github.com/samtecspg/articulate/commit/42d51df55a3e84d7cc2aac576e9cc1340c3a8b72
