### ISSUE TITLE
Managing Advanced Functionality on Intents

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#151]
So had a few thoughts:

- We're only going to add more and more advanced options
- Already have webhook, but wanting to add scripting. Not just one scripting panel, but two!
- Shouldn't need a toggle to tell us if the webhook is being used. Same for scripting. If there is a script we use it, if not we don't.

So @dcalvom along those thoughts I am thinking that the webhook should be keyed off of the URL. If there is a url in the webhook section then we try to call it.

@broham89 @ewoo  if we no longer need toggles, just the input fields then I think we should add an advanced section at the bottom of the intent page, but before the agent responses. In my head I am thinking it should be an [expansion/collapse panel](https://material-ui-next.com/demos/expansion-panels/) It defaults to all closed, but they can open the webhook section if they want to use it.

I also like the expansion panels, because when we add the scripting we can place the expansion panels in the order that the advanced options get toggled.

1. Pre-Webhook Script
2. Webhook
3. Post-Webhook Script

then with Agent responses at the bottom.  

thoughts?

**Comment by broham89** [comment]
@wrathagom Would this design fit what you're saying
![6-intent-form](https://user-images.githubusercontent.com/11262149/39828461-b6b76604-5380-11e8-8ef8-3b8e62a11974.jpg)
? 
![expand-webhook](https://user-images.githubusercontent.com/11262149/39828466-bb82bc4c-5380-11e8-8aaa-4c01544a96dd.jpg)

**Comment by wrathagom** [comment]
Yep fine by me. This page is getting pretty heavy though isn't it :/

**Comment by wrathagom** [comment]
old UI, we'll deal with this again on #152 for the new UI.
