### ISSUE TITLE
Label bubbles in chat panel

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#158]
@ewoo suggested adding the Agent name to the agent's responses and `You` to what you type in the chat panel.

@broham89 we need some HTML/CSS.

**Comment by ewoo** [comment]
Here's a sample:
https://cl.ly/1T0q1X1Q2j1B

**Comment by wrathagom** [comment]
@broham89 did you see this one too?

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/1989403/nlu-styles.zip)
@dcalvom 

I've added these:

- **index.html** line 71 - 90
- scss/components/**_chat-bubble.scss**

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/dbfe745b5f4f70822af26ef50e870dbb3cc93740
