### ISSUE TITLE
Explore handlebars helpers categories and import those who seems useful

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#161]
Currently, 189 helpers in 20 categories exist on the handlebars helpers repo.

It's necessary to explore them and decide which ones could seem useful for articulate. Right now math and comparison are already being used by us.

**Comment by wrathagom** [comment]
Okay, let's go ahead and add in the below:

`'array', 'collection', 'comparison', 'inflection', 'math', 'misc', 'number', 'object', 'string', 'url'`

I didn't include `date` in the above, should we consolidate and use there date which includes moment? https://github.com/helpers/handlebars-helpers#date.

Also can you add to additional helpers for lists:
- andList: ['a', 'b', 'c'] -> 'a, b, and c'
- orList: ['a', 'b', 'c'] -> 'a, b, or c'

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5020a07659159f60d17f55eb92c739ea7b8a90ea
