### ISSUE TITLE
Login Interface

### ISSUE THREAD

**Issue by ajinkyapuar** [samtecspg/articulate#162]
Please add a login interface to the UI

**Comment by milutz** [comment]
Hi ajinkyapuar,

We do have auth stuff on our (distant) road map, but for the moment the best solution is to use an authenticating proxy in front of Articulate.   

Here is an example of how to do that from the Elasticsearch people (who have the same issue):  https://www.elastic.co/blog/playing-http-tricks-nginx (see the "Basic Authentication" section)

**Comment by wrathagom** [comment]
Related to #22
