### ISSUE TITLE
Allow re-ordering the slots

### ISSUE THREAD

**Issue by AbdurRub** [samtecspg/articulate#163]
Hi ,
This will be a great addition if we can arrange or make a dialogue like in which order system check slot.

**Comment by wrathagom** [comment]
slot's have start attributes? Sounds like entities?

**Comment by broham89** [comment]
<img width="1366" alt="slot-order-ex_1" src="https://user-images.githubusercontent.com/11262149/39897226-00952d5a-5477-11e8-8be0-7fe1c851a5e4.png">
<img width="1367" alt="slot-order-ex_2" src="https://user-images.githubusercontent.com/11262149/39897227-00a4b3f6-5477-11e8-9222-7b1ff9183c3e.png">

Here are two examples of slot ordering and I've also changed the design for slots if you would to consider a UI change.

**Comment by dcalvom** [comment]
@broham89 Abe we are going to use the click and drag method. Could you share me the css for the current UI style.

**Comment by broham89** [comment]
![artboard 3](https://user-images.githubusercontent.com/11262149/40204854-97ba0714-59ef-11e8-83e6-cea223fa592e.jpg)
@dcalvom if you need some other css style info message me.

**Comment by broham89** [comment]
[icon-organize.zip](https://github.com/samtecspg/articulate/files/2014805/icon-organize.zip)

**Comment by dcalvom** [comment]
Closed by 31accfe
