### ISSUE TITLE
Don't Allow empty strings from agent response generation

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#165]
There are some instances where handlebars can find all of it's variables, but still not produce meaningful output. As such we should validate that the string returned from the handlebars compilation isn't empty.

**Comment by dcalvom** [comment]
This was actually related to the scenario when the agent responses weren't fulfilled with the CSO (conversation state object) values. So we added a default response and we are now logging an error to the console.

Closed by https://github.com/samtecspg/articulate/commit/c53fff37bd88977ea35d3c021f667f5816362cf4
