### ISSUE TITLE
Portuguese Spacy Model

### ISSUE THREAD

**Issue by marcoaleixo** [samtecspg/articulate#166]
Please add portuguese as a supported idiom.
I actually use spacy pt model only with RASA and it is working very wel..

**Comment by dcalvom** [comment]
Boa Tarde Marco,

We will work on that and will let you know when it is ready. We need to make some configurations on the Rasa Dockerfile and the UI.

**Comment by dcalvom** [comment]
Closed by 78ffe059c0f0f972e07005a778ecefcff733f1ef
