### ISSUE TITLE
ui subproject yarn install errors

### ISSUE THREAD

**Issue by Johnz86** [samtecspg/articulate#168]
After cloning this repository, when I try to install the project in local environment, I get a lot of errors on ```yarn install```

```
ERROR in ./~/dotenv-webpack/index.js
Module not found: Error: Can't resolve './src' in 'C:\GIT\articulate\ui\node_modules\dotenv-webpack'
 @ ./~/dotenv-webpack/index.js 9:13-29
 @ dll reactBoilerplateDeps

ERROR in ./~/dotenv-webpack/dist/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\dotenv-webpack\dist'
 @ ./~/dotenv-webpack/dist/index.js 15:10-23
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/dotenv/lib/main.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\dotenv\lib'
 @ ./~/dotenv/lib/main.js 3:9-22
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in (webpack)/lib/node/NodeOutputFileSystem.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\webpack\lib\node'
 @ (webpack)/lib/node/NodeOutputFileSystem.js 5:9-22
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in (webpack)/lib/NormalModule.js
Module not found: Error: Can't resolve 'module' in 'C:\GIT\articulate\ui\node_modules\webpack\lib'
 @ (webpack)/lib/NormalModule.js 96:16-33
 @ (webpack)/lib/NormalModuleFactory.js
 @ (webpack)/lib/Compiler.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in (webpack)/lib/node/NodeMainTemplateAsync.runtime.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\webpack\lib\node'
 @ (webpack)/lib/node/NodeMainTemplateAsync.runtime.js 9:2-15 25:3-16
 @ (webpack)/lib/node/NodeMainTemplatePlugin.js
 @ (webpack)/lib/node/NodeTemplatePlugin.js
 @ (webpack)/lib/WebpackOptionsApply.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\graceful-fs'
 @ ./~/graceful-fs/graceful-fs.js 1:9-22
 @ ./~/enhanced-resolve/lib/NodeJsInputFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\mkdirp'
 @ ./~/mkdirp/index.js 2:9-22
 @ (webpack)/lib/node/NodeOutputFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/loader-runner/lib/LoaderRunner.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\loader-runner\lib'
 @ ./~/loader-runner/lib/LoaderRunner.js 5:9-22
 @ (webpack)/lib/NormalModule.js
 @ (webpack)/lib/NormalModuleFactory.js
 @ (webpack)/lib/Compiler.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/graceful-fs/fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\graceful-fs'
 @ ./~/graceful-fs/fs.js 3:9-22
 @ ./~/graceful-fs/graceful-fs.js
 @ ./~/enhanced-resolve/lib/NodeJsInputFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/chokidar/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\chokidar'
 @ ./~/chokidar/index.js 3:9-22
 @ ./~/watchpack/lib/DirectoryWatcher.js
 @ ./~/watchpack/lib/watcherManager.js
 @ ./~/watchpack/lib/watchpack.js
 @ (webpack)/lib/node/NodeWatchFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/chokidar/lib/fsevents-handler.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\chokidar\lib'
 @ ./~/chokidar/lib/fsevents-handler.js 3:9-22
 @ ./~/chokidar/index.js
 @ ./~/watchpack/lib/DirectoryWatcher.js
 @ ./~/watchpack/lib/watcherManager.js
 @ ./~/watchpack/lib/watchpack.js
 @ (webpack)/lib/node/NodeWatchFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/chokidar/lib/nodefs-handler.js
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\articulate\ui\node_modules\chokidar\lib'
 @ ./~/chokidar/lib/nodefs-handler.js 3:9-22
 @ ./~/chokidar/index.js
 @ ./~/watchpack/lib/DirectoryWatcher.js
 @ ./~/watchpack/lib/watcherManager.js
 @ ./~/watchpack/lib/watchpack.js
 @ (webpack)/lib/node/NodeWatchFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps
```
Is there some guide, how to run the project just locally not using complete docker container?

**Comment by wrathagom** [comment]
@dcalvom @milutz are these the same errors we get during the Docker build?

@Johnz86 does the UI fail to run?

At the moment we aren't targeting docker-less installs, simply because there are too many pieces that need orchestration. Are you after a local install because of the volume mapping problems you were having? We can likely eliminate the necessity of the volume mappings more easily than we can provide instructions on how to install everything locally.

Also, if you're on Windows would a vagrant box help?

**Comment by Johnz86** [comment]
I am running on Windows 7 with docker toolbox. At start I tried to use normal ```docker-compose up```
and with proper ```.env``` config all containers started. The problems was that ui after launch was not able create any bots on Create button. There were no errors in the console log. When I looked in the network traffic, no requests to the api container were created.

@wrathagom After ```yarn install``` and ```yarn start``` UI did work. According my investigation the errors were produced when ```build:dll``` was run as ```postinstall``` step. I made successfull setup of local api and ui. I run only rasa/redis/duckling containers. I wanted to explore ther project and maybe customize/add features. The chatbot/intents/entities work. What is failing are webhooks. I get a message ```We're having trouble fulfilling that request```. I was trying to replicate this tutorial => [bot-basics-with-articulate](https://blog.spg.ai/bot-basics-with-articulate-e5fe975cee88)

**Comment by milutz** [comment]
@Johnz86 To-date all of the sub-components that make up Articulate are only (natively) tested on Debian/Ubuntu/Alpine Linux - With the newest forms of Docker, the docker images will run anywhere that Docker does (because Docker is managing a bubble of Alpine Linux for the components).

For natively running Articulate (which we don't currently recommend because we haven't had time to document/refine the process of) we would currently say you need to be installing on a Debian-style Linux Distro, at least, for our testing to apply.

I believe @wrathagom comment about vagrant was hinting that you could use vagrant to load an OS that would let you run a newer version of Docker - or if you wanted to run native, let you load ubuntu-server.

**Comment by Johnz86** [comment]
@milutz I managed to run the articulate natively as described before. The only issue I encountered was with the webhooks. After investigation I found out that is because of proxy. After logging the error of the webhook I get this error
```
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1020:11)
       at TLSWrap.onread (net.js:580:26)
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read',
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url: 'https://api.chucknorris.io/jokes/random',
        data: '' },
     request:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Object],
        _currentUrl: 'https://194.138.0.3/https://api.chucknorris.io/jokes/random' },
     response: undefined },
  textResponse: 'We\'re having trouble fulfilling that request' }
```
It is known [proxy issue for Axios](https://github.com/axios/axios/issues/925).
So even If I switch to other OS, when I am running behind corporate proxy it would fail. 
I tried to switch to ```axios-proxy-fix```, but the test ```https://api.chucknorris.io/jokes/random``` still did not work.

**Comment by milutz** [comment]
@Johnz86 Great to hear you got it running locally! 

I'm a bit confused about your proxy comment - we use proxying in the code to make it so all the services funnel through the API sub-component (this is specifically to aid the docker design).

I'm unclear if your commenting on our proxy (which imagine could be a issue if the code is locally run) or if your saying you have a corp proxy - completely unrelated to Articulate - that is causing a problem.

**Comment by Johnz86** [comment]
@milutz I have a corporate proxy, that is completely unrelated with Articulate. It is between the outside world (global internet) and my locally running articulate setup. I have specific environment variables (http_proxy/https_proxy) with the proxy configuration. 
Articulate uses Axios library in the file ``` articulate/api/modules/agent/tools/callWebhook.agent.tool.js```.
Whenever articulate user configures a webhook in an intent with service url adress in outside world, Axios lib will fail to use http_proxy variables because of a bug. 
You see the url address ```https://api.chucknorris.io/jokes/random``` and proxy ```194.138.0.3``` in the provided error
```
{ 
   ....
        _currentUrl: 'https://194.138.0.3/https://api.chucknorris.io/jokes/random' },
     response: undefined },
  textResponse: 'We\'re having trouble fulfilling that request' }
```
So whatever setup docker/local native I would use with articulate, it would not run in my corporate environment because of bug in Axios library. 

Since then I overriden the functionality in callWebhook.agent.tool.js in my local environment with other library and webhooks started working.

**Comment by wrathagom** [comment]
@Johnz86 glad you were able to get it all up and running. Sorry it took so much effort.

Did you end up using Wreck or something similar? Let us know if there is anything we can do for you or anything we can do to make the project better. We're trying to make everything easy.

**Comment by Johnz86** [comment]
I used ```request-promise-native``` which we succesfully used in our previous project. It accepted proxy settings from environment variables without any setup needed. This is how the ```callWebhook.agent.tool.js``` file looks.
```js
'use strict';

const request = require("request-promise-native")
const Handlebars = require('handlebars');
const RegisterHandlebarHelpers = require('../../../helpers/registerHandlebarsHelpers.js');

module.exports = (webhook, conversationStateObject, callback) => {

    RegisterHandlebarHelpers(Handlebars);
    const compiledWebhookUrl = Handlebars.compile(webhook.webhookUrl);
    const processedWebhookUrl = compiledWebhookUrl(conversationStateObject);
    let compiledWebhookPayload;
    let processedWebhookPayload;
    if (webhook.webhookPayloadType !== 'None' && webhook.webhookPayload !== ''){
        compiledWebhookPayload = Handlebars.compile(webhook.webhookPayload);
        processedWebhookPayload = compiledWebhookPayload(conversationStateObject);
    }
    console.log("webhook",JSON.stringify({
        method: webhook.webhookVerb,
        uri: processedWebhookUrl,
        body: processedWebhookPayload ? JSON.parse(processedWebhookPayload) : '',
        json: true
    }));
    request({
        method: webhook.webhookVerb,
        uri: processedWebhookUrl,
        body: processedWebhookPayload ? JSON.parse(processedWebhookPayload) : '',
        json: true
    })
    .then((response) => {
        return callback(response);
    })
    .catch((error) => {
        return callback({error,
            textResponse: 'We\'re having trouble fulfilling that request'
        });
    });
};

```

**Comment by wrathagom** [comment]
need to re-test new UI/API for these.
