### ISSUE TITLE
Intent Confusion Matrix to UI

### ISSUE THREAD

**Issue by marcoaleixo** [samtecspg/articulate#171]
RASA provides that evaluation method.
It would be interesting if this option were available in the interface to better evaluate the performance of the training and which intentions are causing our model to be lost.

**Comment by wrathagom** [comment]
@marcoaleixo I agree, we've got an analytics focused update in the works and this is part of what we hope to be in it.

When you use the evaluate end point do you use it against your training data, or do you have a separate test data set?

**Comment by marcoaleixo** [comment]
In training dataset, I use to garantee I don't have similar intents, similar examples in different intents, for example.
I don't think I will use in separated test data set initially.
