### ISSUE TITLE
Entities not showing the "Used In" screen

### ISSUE THREAD

**Issue by Oceania2018** [samtecspg/articulate#173]
Custom entity type doesn't show referenced intents correctly, in the "Used in the following intents".

![image](https://user-images.githubusercontent.com/1705364/39270136-bd069f70-489a-11e8-8ea5-177df5131c36.png)

**Comment by wrathagom** [comment]
The custom entities not showing was a known and part of this issue #128.

I am going to transform this issue to be more about the "used in" screen.
