### ISSUE TITLE
Yes/No Answers

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#174]
We have an open debate about the confirmation responses like (yes/no). 

Different ideas had come up:

- Use input and output contexts
- Try ML
- Tag responses as waiting for confirmation and keep that in the context

**Comment by dcalvom** [comment]
On gitter @Ocenia2018 commented:

> Oceania @Oceania2018 17:44
@dcalvom Rasa NLU also has this kind of problem. Rasa Core use LSTM to training conversation in end to end way. In my opinion, there are a easy way to figure out, use the context-in and context-out, narrow the results per context-in, for example, the two "Yes" intents might belong different context. What do you think about ?

**Comment by Oceania2018** [comment]
I'm using google Dialogflow a lot, use the context-in and out to control conversation flow works perfectly.

**Comment by dcalvom** [comment]
This is a temporal workaround proposal by @wrathagom:

![image](https://user-images.githubusercontent.com/7228045/39287489-24921bc4-48e1-11e8-955b-fb65dd33ab78.png)

Given that a text promt of a required slot could make use of other slots values this workaround take advantanges of that. He created an entity called confirmation that represent yes/no answers and created an slot that is required in the intent in order to move forward.

**Comment by wrathagom** [comment]
Closing in favor of #223
