### ISSUE TITLE
Settings endpoint

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#175]
We need to create a `/config` endpoint for configuring defaults for the API and UI. Ideally the only environment variables that we would have would be the redis configuration options and the `API_URL` for the UI. With everything else being pulled from the config api endpoint.

Specifically we should have an API and UI for configuring the below (and probably more):

- The Rasa URL
- Default Rasa pipeline (yml code block???)
- Duckling URL
- Duckling dimensions
- spacy pre-trained entities
- available timezones (defaults to all)
- available languages
- default language
- default agent fallback responses

**Comment by wrathagom** [comment]
@broham89 we'll need to add a settings page to the current UI.

**Comment by wrathagom** [comment]
So looks like this one is already underway, but leaving open until we get more items built into endpoints and the UI designed.

**Comment by broham89** [comment]
<img width="1367" alt="settings page" src="https://user-images.githubusercontent.com/11262149/40095665-d86f31e8-5892-11e8-8790-c817bce3485a.png">
Note: Default Agent fallback responses would need some advice what would be required there?

**Comment by broham89** [comment]
<img width="1367" alt="artboard 27" src="https://user-images.githubusercontent.com/11262149/40096093-dcbd11fa-5894-11e8-8bfe-53ff000a0dec.png">

**Comment by broham89** [comment]
<img width="1367" alt="artboard 27" src="https://user-images.githubusercontent.com/11262149/40096126-13e127d4-5895-11e8-8309-e174b59848d6.png">

**Comment by broham89** [comment]
Here is another example for multiple links for settings located in the left navbar. 
<img width="474" alt="screen shot 2018-06-05 at 9 09 35 am" src="https://user-images.githubusercontent.com/11262149/40981393-6c131e1a-68a0-11e8-8e1c-5700bf58975f.png">

**Comment by dcalvom** [comment]
@wrathagom what is you preferred option for the UI?

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/2074464/nlu-styles.zip)

Things added: 
1. **settings.html** almost everything
2. **js/script.js** line 27-52
3. **components/_sidenav.scss** 107 - 152
4. **components/_base.scss** just added new css to the `h3` and `h4` line 43- 50. Also added article css line 74-76

* Also to note: I didn't have the correct `input` style css so just replace the input placeholders i currently have in **settings.html**

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/2076457/nlu-styles.zip)
Things added:

settings.html almost everything
js/script.js line 27-52
components/_sidenav.scss 107 - 152
components/_base.scss just added new css to the h3 and h4 line 43- 50. Also added article css line 74-76
Also to note: I didn't have the correct input style css so just replace the input placeholders i currently have in settings.html @dcalvom

**Comment by dcalvom** [comment]
Closed by a357f21738bd20465bc8d780fc7f25c2bad94bdf
