### ISSUE TITLE
Timezone list loads all examples when typeahead is empty

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#177]
I think this is unwanted behavior since it's such a long list. We should load only the top 10 matches also maybe require a search string length of 1 or 2 before searching... I think most type-aheads offer this type of functionality. @dcalvom let me know if those are options provided out of the box.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/8e7fc79f6bee4900085aa4ff18f834eca6fe90c7
