### ISSUE TITLE
Landing Page for when the UI can't communicate with the API

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#178]
### Issues

Right now even if the UI can't communicate with the API you still get taken to the welcome page and prompted to create an agent, when you do the wheel spins forever and there is a silent console error. This doesn't need to be on every page, but user coming directly to `http://localhost:3000` or whatever the root route is should be re-directed.

- [ ] Implement a landing page that the user is redirected to if the UI can't reach the API. Ideally, it would link to the docs/common troubleshooting problems.

@broham89 we could use some feel-good graphics here so people hate us less when it isn't working :)

**Comment by wrathagom** [comment]
Targeting #176

**Comment by broham89** [comment]
@wrathagom Would this also be a 404 error page design?

**Comment by dcalvom** [comment]
@broham89 it is a little bit different. Depending on the user configuration it could happen that something in their config is wrong and the the UI cannot access the API.

Then, the user will not be able to do anything in the UI.

**Comment by broham89** [comment]
<img width="619" alt="screen shot 2018-05-07 at 4 07 54 pm" src="https://user-images.githubusercontent.com/11262149/39725275-d58222ca-5210-11e8-8fc6-e8e92bbc6750.png">

Would you think design makes sense? @wrathagom

**Comment by broham89** [comment]
![missing-api](https://user-images.githubusercontent.com/11262149/39727464-65faafa0-5218-11e8-9455-3d929d59279c.jpg)

**Comment by broham89** [comment]
![missing-api](https://user-images.githubusercontent.com/11262149/39730945-24ff749c-522a-11e8-886f-2320652374d8.jpg)
@wrathagom would this graphic be appropriate for this issue?

**Comment by dcalvom** [comment]
@broham89 This isn't decided yet right?

**Comment by broham89** [comment]
@dcalvom

**Comment by wrathagom** [comment]
It's not a re-direct, I think I like the top image better. Especially if accompanied with some fun text: `Error: agent head missing` along with serious text `We couldn't connect to the API, for configuration instruction go to here`

Maybe with Gitter link as well.

**Comment by broham89** [comment]
![artboard 1](https://user-images.githubusercontent.com/11262149/39791163-c22ac49e-52ff-11e8-9772-0a6b7631dc65.jpg)
updated look to be consistent with 404.svg

**Comment by broham89** [comment]
updated look to be consistent with 404.svg

![artboard 1](https://user-images.githubusercontent.com/11262149/39791200-f928678a-52ff-11e8-8eae-fa47a801fa30.jpg)

**Comment by broham89** [comment]
@dcalvom here is the .svg
[missing-api.svg.zip](https://github.com/samtecspg/articulate/files/1988489/missing-api.svg.zip)

**Comment by dcalvom** [comment]
Thanks @broham89

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/8724e0bce947d99ecccb5037f8027e18d1a41a54
