### ISSUE TITLE
Uncaught errors in UI

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#179]
On pretty much any create or list screen if the API is unavailable the page never shows an error. 

To re-produce start Articulate normally and navigate to one of the create pages. Kill the API and then submit your edit/update. There is an error in the console, but none will show on the page.

**Comment by wrathagom** [comment]
Targeting #176

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3f7234ae3cdd468064a49935aad2c4250ad94d08
