### ISSUE TITLE
JSON output in the UI for converse feature

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#18]
Developers would like to check the output of the converse endpoint to check what has been sent by the system for debugging purposes.

**Comment by wrathagom** [comment]
@broham89 we need a design for this one, but it probably goes at the bottom of your current list.  In the chat side panel. How can we show complex information like the raw JSON payload behind messages/etc.

Dialog Flow it's a button + Modal
<img width="396" alt="2018-01-10_20-19-46" src="https://user-images.githubusercontent.com/1779894/34803876-a781f13a-f643-11e7-8739-ff9f24c4a2ee.png">

<img width="1648" alt="2018-01-10_20-19-47" src="https://user-images.githubusercontent.com/1779894/34803880-acf9043c-f643-11e7-9734-a06259ebf94f.png">

**Comment by wrathagom** [comment]
@broham89 I am going to close this issue, but we should target this for the next UI iteration as you already know.
