### ISSUE TITLE
Implement full 404 screen

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#180]
Right now if you try to go to a page that isn't there like http://localhost:3000/conversation you land on the below page. Let's implement a full 404 page with a link to back to the Articulate welcome page and a link to the docs.

@broham89 we'll need a design, HTML, CSS for this.

<img width="1648" alt="2018-04-28_13-24-51" src="https://user-images.githubusercontent.com/1779894/39399194-8e6cebca-4ae7-11e8-95a4-34f46b9a9d45.png">

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/1981073/nlu-styles.zip)
@dcalvom  

New things added: 

- **404.html**  line 58 - 68 
- **_404.scss** 
- **_primary-btn.scss** line 18 -26
- **img/404-img.svg**

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/1981093/nlu-styles.zip)
@dcalvom 

New things added:

- **404.html** line 58 - 68
- **_404.scss**
- **_primary-btn.scss** line 18 -26 
- img/404-img.svg

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/1981936/nlu-styles.zip)
New things added:

404.html line 58 - 68
_404.scss
_primary-btn.scss line 18 -26
img/404-img.svg

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/dbf2acc2c8f57eee9dc1e75602bee1919f6ce630
