### ISSUE TITLE
Getting "webhookPayloadType" is not allowed when creating an intent

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#182]
To reproduce create an intent fill out the required fields then:

- Enable the webhook
- change the payload type to JSON
- change the payload type back to none
- Disable the webhook

Try to submit your intent and you should receive the error message.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/0b3e8ffaf44b9731195e0164fec58808bf286131
