### ISSUE TITLE
Add more configuration options to the agent

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#185]
Ideally, the agent would be able to override global configuration options.

For example:

- Domain Classifier Pipeline
- Default domain pipeline
- Rasa URL
- Duckling URL

These items should be in an "advanced section" of the create agent screen.

**Comment by dcalvom** [comment]
@broham89 can you come up with some designs for this screen?

**Comment by broham89** [comment]
Could I get a little more info on what each bullet points configuration do and what input style you need from the user to override them? For example, `Domain Classifier Pipeline` is it just a simple input that you need from the User to override or is it more intricate where you need a have a code block?

However, would it be appropriate to just have an `advance option (down-icon)` and it would open up the below with all the global configuration options?

**Comment by wrathagom** [comment]
these are the same settings as from the settings page, just local to the agent. So you can set a Rasa URL for Articulate, but an individual agent could use a custom URL if it needed to be on a different server.

**Comment by wrathagom** [comment]
both of the pipelines are code blocks, but again this list will grow and will likely long term be a mix of toggles, code blocks, inputs, dropdown, etc.

**Comment by dcalvom** [comment]
Closed by 3ecf204c0c975e9aef913760e9e6683fef6243ee
