### ISSUE TITLE
Scenario and webhook changes are not saved in the UI if the creation or update of an intent fails

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#190]
Given that scenario and webhook are separated from the intent object in the Redis scheme we designed, we created to endpoints inside intent, one for `scenario` and one for `webhook`.

At the UI when we create the intent we need to wait until a successful response to proceed with the creation of the scenario and the webhook. 

We need to change this because changes are being lost if the intent fails.

Probably the best way is to include the creation/update of the scenario and the webhook in the `post intent` and `put intent` endpoints.

**Comment by wrathagom** [comment]
This all changes if we detach training from the save/update buttons. So I think we do nothing at the moment and just wait for us to detach the two. Once that happens I think the likelihood of this goes away/greatly reduced.

**Comment by wrathagom** [comment]
Is this addressed with the training changes?

**Comment by dcalvom** [comment]
Yes! I haven't had that issue anymore since that chnage
