### ISSUE TITLE
Entities still showing when agent is deleted

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#194]
Don’t know if it’s the cache or we aren’t deleting them properly.

**Comment by RicoLaaa** [comment]
i just created a test agent with domains, intents and entities:
- deleted it
- domains, itents and entities where still there.
- I switched to another agent, and everything looks fine

**Comment by wrathagom** [comment]
I'm pretty certain that is a caching issue then. Likely the switch to a new agent loads in a new cache.

**Comment by dcalvom** [comment]
Closed in favor of https://github.com/samtecspg/articulate/issues/241
