### ISSUE TITLE
Refactor settings endpoint to make it scalable

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#196]
If a setting just takes a single value we need to make it scalable in a way we don't need to format the output. In example, uiLanguage is a string. So, when you do a get /settings/uiLanguage you will have `en` as the response. Right now single value settings are being formatted to return an object.

Besides that, we need also to refactor the `settings` endpoint to be `settings/{name}` rather than a hardcoded name.

**Comment by wrathagom** [comment]
@dcalvom maybe a way to get around the object issue is that we don't allow a `PUT /settings/{name}` but rather just a `PUT /settings` where the object can contain one or more keys. Then `GET /settings` returns an object with keys for each value, but `GET /settings/{name}` returns an object with just that single key?

**Comment by wrathagom** [comment]
We also shouldn't pollute the Redis space by doing `settings:intentClassifierPipeline` for every setting.

Rather we should use `settings` as the hash and `intentClassifierPipeline` as the key with the value set to a stringified JSON of the pipeline.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/a357f21738bd20465bc8d780fc7f25c2bad94bdf
