### ISSUE TITLE
Detach Training from Saving/Updating Intents and Entities

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#198]
This one is going to be pretty involved. The gist of it is that when the user creates a new intent, updates an intent, or updates entities that are used by an active agent we should not immediately re-train. Rather we should mark the screen someway that the intent has "Un-Trained changes". We should also add indicators to the domain list, intent list, and entity list pages for those domains/intents/entities that have untrained changes.

Then on the domain list page, we add a train option to the drop-down menu. The message should be something like: `You are about to train the XYZ domain: The greet, goodbye, and gratitude intents have un-trained changes. Train Now?`

@dcalvom there is also a heavy API component here and we should try for restful solutions where we can. For example, we should have a `training: true/false` flag on the domain. To start training we `PATCH /agent/{1}/domain/{1}` and set the training flag to true.

Maybe it's best if you/I develop the model and API changes before starting to code and get it approved by @ewoo

**Comment by ewoo** [comment]
@wrathagom, yeah I like your intermediate proposal. I like the statuses too. Just a minor tweak suggestion in terms of location. I would propose that we move the status closer to the dialog input panel since the users mouse and focus tends to gravitate towards the lower right side when they're testing. We could also make the input deactivated as well while it's training.

![train-button](https://user-images.githubusercontent.com/278197/40116960-6b4050b0-58e3-11e8-861f-83d8ebfc3db1.jpg)

**Comment by wrathagom** [comment]
So challenging my original positioning as well:

I'm not certain we want users to naturally gravitate towards clicking a button that can completely change how their agent behaves? We also would have this in the opposite corner of where they select the agent? which may be less than desirable? We also don't have a navbar on the bottom, so if it was in the bottom right-hand corner it would look like it was part of the chat panel?

Maybe it should go below the select agent dropdown in the left nav panel?

**Comment by broham89** [comment]
<img width="1367" alt="artboard 28" src="https://user-images.githubusercontent.com/11262149/40148394-5d3868a4-5933-11e8-912b-0adadb5c2d7f.png">

**Comment by broham89** [comment]
@wrathagom @ewoo would it make sense to position it in the navbar?

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/2029109/nlu-styles.zip)
All the changes are in `settings.html` page

Files to look out for:
1. **_primary-button.scss**
2. **_right-panel.scss**
3. **header.scss**
4. **_base.scss**
5. settings.html

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/c2bb77388a05a9e303bed57800df33b6e02155ed, https://github.com/samtecspg/articulate/commit/7c7986cee0554d7bdca561e9a5af4ae67f984b44, and https://github.com/samtecspg/articulate/commit/f253d19a7586843d608d350b3dd27ce8d9d76997

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/2032848/nlu-styles.zip)

So I have the animation `bot-training.svg` in the zip file. It only shows in the `settings.html` after the user clicks on the training button.

Things that are edited:

1. **js/script.js** line 17 -24
2. **components/_primary-button.scss** line 27 -67
3. **settings.html** line 103 - 111
4. **_right-panel.scss** inside `.training-container` and `.right-panel`

Below img is what it should look like when it's fninished training.
<img width="636" alt="screen shot 2018-05-23 at 4 19 36 pm" src="https://user-images.githubusercontent.com/11262149/40452011-11bc9030-5ea6-11e8-9dd3-8525996d7eaa.png">
