### ISSUE TITLE
Implement Pagination in API and UI

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#2]

**Comment by wrathagom** [comment]
I'm going to remove this, we'll save pagination for the the next UI iteration.

**Comment by dcalvom** [comment]
UI Pagination in list screens has been implemented. Also the API pagination, the only part missing is connecting the API request to the UI pagination status

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/708543154d76f1bd924ac6fb4a2054642c426475
