### ISSUE TITLE
Sample agents to import data to new agents

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#20]
Define sample agents to provide developers with a base for their new agents.

**Comment by wrathagom** [comment]
@malave does the API you created require an API key to use?

**Comment by dcalvom** [comment]
@wrathagom could we close this given that you are thinking on one-click install domains here https://github.com/samtecspg/articulate/issues/203?

**Comment by wrathagom** [comment]
Closing in favor of #723
