### ISSUE TITLE
Add Agent/Domain parameters

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#203]
EDIT 11/2/2018 - Woo mentioned the need for Agent parameters. Should think about the level at which these should exist, maybe both?

I want to start working towards one-click install of pre-built domains. A lot of the APIs that these domains will consume will require some sort of an API key or custom parameters. I want to add a domain parameters section to the create/edit domain page. This will allow the user to create custom parameters.

![new wireframe 2](https://user-images.githubusercontent.com/1779894/39929465-202e2bfa-5506-11e8-921c-7352899b84f3.png)

This would then create a domain that looked like this:

```
{
  "id": 1,
  "agent": "Test",
  "enabled": true,
  "domainName": "Weather Domain",
  "intentThreshold": 0.5,
  "parameters": {
    "apiKey": "asdfb1234njksdf",
    "username": "weatherapiuser",
    "password": "asdfjkafh21341234jnsdfkasflaksnfljkn21341234jnsdf"
  }
}
```

the goal would be that this would allow the user to use these values in the webhook for fulfillment. For example the URL could be `http://openweather.com/api?apiKey={{domain.parameters.apiKey}}` and by pulling it out to the create domain screen we could have webhooks on all the different intents in the domain sharing that one key rather than having to update them individually.

**Comment by dcalvom** [comment]
Cool @wrathagom! Seems to be promising.

How domain parameters are going to be added? Is the table editable?

**Comment by wrathagom** [comment]
can be, probably needs an "add" button someplace. If it's easier for you I am fine with a pop up modal or some such for adding them.

**Comment by wrathagom** [comment]
@broham89 you want in on the design of this one? Or he can just re-use the current table component.

**Comment by dcalvom** [comment]
The component we are using could work

https://react-table.js.org/#/story/editable-table

Is just matter to adapt the style of the table

**Comment by broham89** [comment]
<img width="1367" alt="domain parameter - step 1" src="https://user-images.githubusercontent.com/11262149/40030517-aac50c64-57b0-11e8-9dfe-ddec430509f1.png">
<img width="1367" alt="domain parameter - step 2" src="https://user-images.githubusercontent.com/11262149/40030518-aad66748-57b0-11e8-9ee9-8d62013a5b9e.png">
<img width="1367" alt="domain parameter - step 3" src="https://user-images.githubusercontent.com/11262149/40030519-aaec333e-57b0-11e8-8313-dd9b2674a5a0.png">
<img width="1367" alt="domain parameter - step 4" src="https://user-images.githubusercontent.com/11262149/40030520-ab0562fa-57b0-11e8-975d-3d1d2ca1a6f6.png">

**Comment by broham89** [comment]
<img width="1367" alt="domain parameter - alternative" src="https://user-images.githubusercontent.com/11262149/40030536-c2a57166-57b0-11e8-96e5-c4cda9127088.png">
<img width="1367" alt="domain parameter - error" src="https://user-images.githubusercontent.com/11262149/40030537-c2d41642-57b0-11e8-857c-dfaeacee1bcf.png">

**Comment by broham89** [comment]
<img width="1367" alt="domain parameter - step 1" src="https://user-images.githubusercontent.com/11262149/40030719-d11bf0de-57b1-11e8-86c3-3dbb115096a3.png">
<img width="1367" alt="domain parameter - step 2" src="https://user-images.githubusercontent.com/11262149/40030720-d12d48d4-57b1-11e8-9868-8943925b9d4a.png">
<img width="1367" alt="domain parameter - step 3" src="https://user-images.githubusercontent.com/11262149/40030721-d1435e30-57b1-11e8-993e-6c27a6f6dba4.png">
<img width="1367" alt="domain parameter - step 4" src="https://user-images.githubusercontent.com/11262149/40030722-d153089e-57b1-11e8-93e4-a2061f27a6fb.png">

**Comment by broham89** [comment]
<img width="1367" alt="domain parameter - alternative" src="https://user-images.githubusercontent.com/11262149/40030734-df33dde4-57b1-11e8-8ab5-8cf2d9847681.png">
<img width="1367" alt="domain parameter - error" src="https://user-images.githubusercontent.com/11262149/40030735-df538ea0-57b1-11e8-899e-40e04a816ae6.png">

**Comment by wrathagom** [comment]
@broham89 I don't follow the flow. I do think I like the usage of a form over editing a table just for simplicity. But how do the above work:

1. The user clicks `Add`
2. A form shows up below that
3. Once they click submit it changes to a table?

How do they add more and what does that look like? How do they edit/delete ones that already exist?

**Comment by broham89** [comment]
@wrathagom yes once the user creates their first parameter a table showing their input is present. 
And when a User wants to create/add more the add button is still present next to the `Domain Parameter` title

**Comment by wrathagom** [comment]
So then the table get's pushed down and the form re-appears?

I think we'll likely support 4 types at the beginning: String, Number, Password, and JSON. Where the JSON one has a code block for input/editing. If that impacts the designs.

**Comment by broham89** [comment]
<img width="1367" alt="domain parameter - json" src="https://user-images.githubusercontent.com/11262149/40032336-596e2996-57b9-11e8-9a44-4a2283e13e1b.png">

**Comment by broham89** [comment]
<img width="1367" alt="domain parameter - json" src="https://user-images.githubusercontent.com/11262149/40032405-9ff8c0ba-57b9-11e8-9eab-d737ca98b741.png">

**Comment by broham89** [comment]
<img width="1367" alt="artboard 26" src="https://user-images.githubusercontent.com/11262149/40032989-100e08ae-57bc-11e8-992b-d9b4d56378fe.png">

**Comment by wrathagom** [comment]
The tooltip type warning is a departure in style from the modal type abandon/stay messages we already have. I'm sure @dcalvom can do it but may be best if we keep that in store for v2 and stick with the modal approach for now?

**Comment by wrathagom** [comment]
@dcalvom if you want to go for this one then my advice is:

- But them in an accordian "Domain Parameters"
- Have an add button
- For the moment when the add button is clicked create a new row of two inputs Side by side. The first input being the parameter name and the second one being the value. We will worry about the different types/code block later.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/1779894/41755737-d306c7b2-75a6-11e8-865d-2b88482e499c.png">

**Comment by wrathagom** [comment]
Latest designs:

![image](https://user-images.githubusercontent.com/1779894/51644656-f461e300-1f3e-11e9-98db-1ca8f998cee5.png)


![image](https://user-images.githubusercontent.com/1779894/51644676-0479c280-1f3f-11e9-911b-384c7c6af729.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/ff65ceb9041c1495288e0d77376ebd573b17dbd3
