### ISSUE TITLE
Create 0.9.X release

### ISSUE THREAD

**Issue by milutz** [samtecspg/articulate#205]
From template: https://gist.github.com/milutz/d3a975201c31d0d760719d7e9f8bd122

- [X] ~~Complete issues marked for this release: @dcalvom @wrathagom mark when we are good on issue #167~~ (issue moved to a future release)
- [X] ~~Cherry-pick the commit that resolves above~~ (same as above)
- [x] Update main compose with the version of this release
```
sed -i -- "s/repo-head/0.9.0/" docker-compose.yml
```
- [x] Do a test build and run to make sure it doesn't immediately blow for some reason
```
docker images
# Make sure there are any images matching the version your building in your cache!!
docker-compose -f docker-compose.yml -f build-compose-override.yml up
# jump in the web interface, give it a test spin
```
- [x] Get the changes checked back in then tag to kick off a build
```
git add docker-compose.yml
git commit -m "Updates for 0.9.0 release"
git tag -a v0.9.0 -m "Release tag for 0.9.0 release"
git push
git push origin v0.9.0
```
- [x] build the docker-compose zip file
```
./package.sh v0.9.0

```
- [ ] (after docker cloud is done with the build) unzip the zip - do a `compose up` and test
```
cd `mktest -d`
unzip [where-ever-package-is.zip]
cd articulate*
docker-compose up
```
- [ ] Make a new release on github off the release tag, upload zip made by the packaging script

**Comment by milutz** [comment]
Gang found bug, cherry-picking in 884d1ef4273061fa78b7c876f4ae8637da53464d

New tasks:

- [ ] Update main compose with the version of this release
```
sed -i -- "s/0.9.0/0.9.1/" docker-compose.yml
```
- [ ] Get the changes checked back in then tag to kick off a build
```
git add docker-compose.yml
git commit -m "Updates for 0.9.1 release"
git tag -a v0.9.1 -m "Release tag for 0.9.1 release"
git push
git push origin v0.9.1
```
- [x] build the docker-compose zip file
```
./package.sh v0.9.1

```
- [ ] (after docker cloud is done with the build) unzip the zip - do a `compose up` and test
```
cd `mktest -d`
unzip [where-ever-package-is.zip]
cd articulate*
docker-compose up
```
- [ ] Make a new release on github off the release tag, upload zip made by the packaging script

**Comment by wrathagom** [comment]
@milutz should we close this since we're going to jump it with 0.9.1?

@dcalvom what was still required on 0.9.1?

**Comment by dcalvom** [comment]
We need to cherrypick yesterday commits of 0.8.1 and check if there is need for any change

**Comment by milutz** [comment]
I've been reusing these until I complete a given 0.X release done - still haven't got a 0.9 out the door yet so I was going to keep going - BTW 0.9.1 was already used.  So if I cherry pick that will be 0.9.2

**Comment by milutz** [comment]
Gang found bug, cherry-picking in 884d1ef4273061fa78b7c876f4ae8637da53464d

New tasks:

- [ ] Update main compose with the version of this release
```
sed -i -- "s/0.9.1/0.9.2/" docker-compose.yml
diff docker-compose.yml docker-compose.yml--
#make sure the right things got changed
```
- [ ] Get the changes checked back in then tag to kick off a build
```
git add docker-compose.yml
git commit -m "Updates for 0.9.2 release"
git tag -a v0.9.2 -m "Release tag for 0.9.2 release"
git push
git push origin v0.9.
```
- [ ] build the docker-compose zip file
```
./package.sh v0.9.2

```
- [ ] (after docker cloud is done with the build) unzip the zip - do a `compose up` and test
```
cd `mktest -d`
unzip [where-ever-package-is.zip]
cd articulate*
docker-compose up
```
- [ ] Make a new release on github off the release tag, upload zip made by the packaging script

**Comment by milutz** [comment]
... and a 0.9.3 release...

New change - fix for synonyms

New tasks:

- [X] Update main compose with the version of this release
```
sed -i -- "s/0.9.2/0.9.3/" docker-compose.yml
diff docker-compose.yml docker-compose.yml--
#make sure the right things got changed
```
- [X] Get the changes checked back in then tag to kick off a build
```
git add docker-compose.yml
git commit -m "Updates for 0.9.3 release"
git tag -a v0.9.3 -m "Release tag for 0.9.3 release"
git push
git push origin v0.9.3
```
- [ ] Build the images and push them
```docker-compose -f docker-compose.yml -f build-compose-override.yml build
docker push [the images]
```
- [ ] build the docker-compose zip file
```
./package.sh v0.9.3

```
- [ ] (after docker cloud is done with the build) unzip the zip - do a `compose up` and test
```
cd `mktest -d`
unzip [where-ever-package-is.zip]
cd articulate*
docker-compose up
```
- [ ] Make a new release on github off the release tag, upload zip made by the packaging script

**Comment by milutz** [comment]
... and a 0.9.4 release...

New change - fix for synonyms

New tasks:

- [X] Update main compose with the version of this release
```
sed -i -- "s/0.9.3/0.9.4/" docker-compose.yml
diff docker-compose.yml docker-compose.yml--
#make sure the right things got changed
```
- [X] Get the changes checked back in then tag to kick off a build
```
git add docker-compose.yml
git commit -m "Updates for 0.9.4 release"
git tag -a v0.9.4 -m "Release tag for 0.9.4 release"
git push
git push origin v0.9.4
```
- [x] Build the images and push them
```docker-compose -f docker-compose.yml -f build-compose-override.yml build
docker push [the images]
```
- [x] build the docker-compose zip file
```
./package.sh v0.9.4

```
- [ ] (after docker cloud is done with the build) unzip the zip - do a `compose up` and test
```
cd `mktest -d`
unzip [where-ever-package-is.zip]
cd articulate*
docker-compose up
```
- [ ] Make a new release on github off the release tag, upload zip made by the packaging script
