### ISSUE TITLE
Articulate Needs Favicon

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#207]
Articulate needs a favicon. Also needs to rename the title to say "Articulate" instead of NLU.

![articulate-favicon](https://user-images.githubusercontent.com/278197/40118804-f0661144-58e8-11e8-8f12-dc20ba89e36f.jpg)

**Comment by broham89** [comment]
[favicon.zip](https://github.com/samtecspg/articulate/files/2010558/favicon.zip)
Inside located two types of favicon files `.ico` and 3 different sized `.png` Test and see which img works the best.

Link below shows how it should be structured inside the **head** document.  

`<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">`

**Comment by ewoo** [comment]
@broham89 favicon looks perfect!

**Comment by wrathagom** [comment]
@broham89 and this one for that matter? Want to try and tackle it yourself?

**Comment by wrathagom** [comment]
closed by 09272e48cb0bd1b5181c59a8ba657c4717ab8ff7
