### ISSUE TITLE
Jumping to Intents Using Navbar Must Keep User in Last Selected Domain

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#209]
When jumping from Agent or Domain editing views to Intents view--by clicking on the main left nav bar--user must be in the context of the last domain selected for that agent. It is convenient to have to re-select the domain again to see add or work on an existing intent.

![nav-to-intents](https://user-images.githubusercontent.com/278197/40125558-385d1ff0-58f9-11e8-8ec6-6a225014be91.jpg)

**Comment by wrathagom** [comment]
won't fix in old UI.
