### ISSUE TITLE
Intent Threshold Control Label Needs Explanation

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#210]
We should add the following text description below the label "Intent Recognition Threshold"--that describes what the value is and how it might affect the agent's behavior in determining which domain to select as a result by providing a simple example.

Something like this:
`The intent threshold is a value that determines how confident your agent has to be that a user's request matches an intent under this domain. The default value is 50. Setting this value higher will make agent less likely to select this domain. Do so only if you have many examples specified for intents under this domain.`

**Comment by wrathagom** [comment]
There now exists a tooltip for these. That being said given the above screenshot I think some CSS changes are needed. https://github.com/samtecspg/articulate/commit/7692bfa5fd8fb8bef40146fbcd583fadfd14d250

**Comment by broham89** [comment]
Yah definitely does seem too much.. possibly have the bg '#4e4e4e'

**Comment by wrathagom** [comment]
@broham89 

<img width="665" alt="2018-05-16_22-40-44" src="https://user-images.githubusercontent.com/1779894/40153972-2f923a16-595a-11e8-86df-a815e5f0a110.png">

**Comment by broham89** [comment]
Yah you're right it looks heavy with text

**Comment by wrathagom** [comment]
Closed with f742c3c852e87e550d3979f46fcdc0b1092a6d42
