### ISSUE TITLE
Add help text to create intent page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#212]
We need more of an indicator for users that they need to input multiple examples to the user says and agent responses. Something like the below:

@broham89 should we also add an `Add` button in case people want to click rather than press enter?

<img width="1077" alt="2018-05-17_09-56-08" src="https://user-images.githubusercontent.com/1779894/40182278-093ff060-59b9-11e8-826b-a8584df7cae2.png">

**Comment by broham89** [comment]
Could you give me the height of the input? I wanna create an enter icon for it

**Comment by dcalvom** [comment]
45px @broham89

**Comment by broham89** [comment]
<img width="922" alt="screen shot 2018-05-17 at 3 28 18 pm" src="https://user-images.githubusercontent.com/11262149/40202237-f8107700-59e6-11e8-98e1-4257b210e07c.png">
<img width="618" alt="screen shot 2018-05-17 at 3 27 59 pm" src="https://user-images.githubusercontent.com/11262149/40202241-fc1d2a96-59e6-11e8-83ae-ec947622772f.png">

I believe the plus icon is enough to signify to the user to click to add input

**Comment by ewoo** [comment]
@broham89 how about "Type sample dialogue and hit Enter."

**Comment by wrathagom** [comment]
Is the plus icon easy to add with the React components we're using?

**Comment by wrathagom** [comment]
addressed by 397193a94585930ee648dc56a96fafbf8c3935f7 but still waiting on confirmation that it is good.

**Comment by wrathagom** [comment]
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/1779894/40571992-02611af4-6070-11e8-9153-57558c94fafd.png">

**Comment by broham89** [comment]
The plus icon is in materialize named add

**Comment by wrathagom** [comment]
Fixed the colors a little bit here: ca22ecb89299196ee6fe31f37a725d23393d04c3

Consider this one closed.
