### ISSUE TITLE
Make conversation panel full height

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#213]

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/2014512/nlu-styles.zip)

1. In **index.html** file, add class="top-header" to => `<header class="valign-wrapper">` and then move it inside `<section class="content-area">`

2. In **_header.scss** file, remove `~~main > header~~` and replace it with `.top-header` and inside `.top-header` add in `margin-bottom:40px;`

3. In **_base.scss** file, inside css `.content-area` remove `~~padding-top~~` and add in `height: 100vh;`

4. Again in **_base.scss** file, remove `~~padding-bottom:100px;~~` in css selector`main`

**Comment by wrathagom** [comment]
@broham89 have any interest in trying to tackle this one yourself first? @dcalvom and I can guide as needed.

**Comment by broham89** [comment]
[nlu-styles.zip](https://github.com/samtecspg/articulate/files/2029115/nlu-styles.zip)

open `settings.html` for the fixed header layout

**Comment by wrathagom** [comment]
Does this conflict or go with the training button?

**Comment by broham89** [comment]
it goes with the training button

**Comment by wrathagom** [comment]
Closed with training button release
