### ISSUE TITLE
Weird corner case on building training data

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#214]
So an user contact us because his agent wasn't been training. 

The scenario is something like this:

He had an example when an entity was tagged twice in different places:

`Some text entity some text entity`. So entity are the same in this text

In the entity definition there where only two synonyms, therefore, the combination built for that entity synonyms was just one: 

`[[ { entityValue: entity, entityText: synonym1 }, { entityValue: entity, entityText: synonym2 } ]]`

So when the building of the training process arrived to that example it blowed away because this line flattened the array:

```javascript
//If there is just one entity in the text of this intent, flat the array of combinations
combinationsForThisIntent = combinationsForThisIntent.length === 1 ? _.flatten(combinationsForThisIntent) : combinationsForThisIntent;
```

The result after the flatenning was:

`[ { entityValue: entity, entityText: synonym1 }, { entityValue: entity, entityText: synonym2 } ]`

So when it iterate over combinations it took each of the above elements as separate combinations instead of one combination, so in this line:

`entitiesList.forEach( (entity, i) => {`

when it tried to access the combination with the index 1 (i = 1) it was undefined and the process thrown the error:

```
api_1       | Debug: internal, implementation, error 
api_1       |     TypeError: Uncaught error: Cannot read property 'entityText' of undefined
api_1       |     at entitiesList.forEach (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:44:67)
api_1       |     at Array.forEach (native)
api_1       |     at _.map (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:42:38)
api_1       |     at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1       |     at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
api_1       |     at _.map (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:34:46)
api_1       |     at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1       |     at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
api_1       |     at _.uniq._.flatten._.map (/usr/src/app/modules/domain/tools/buildTrainingData.domain.tool.js:22:47)
api_1       |     at arrayMap (/usr/src/app/node_modules/lodash/lodash.js:660:23)
api_1       |     at Function.map (/usr/src/app/node_modules/lodash/lodash.js:9571:14)
```

I know this is not as clear as you may want, but if you need to know more about this issue contact me

**Comment by wrathagom** [comment]
addressed in new UI, won't fix in old UI.
