### ISSUE TITLE
More entity colors

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#215]
We are assigning a new color to every entity we create. Currently we are using material UI colors as you can see in this image:

![image](https://user-images.githubusercontent.com/7228045/40212179-ecd7682e-5a0b-11e8-8de5-0c88fd6d645b.png)

Currently we are using the CirclePicker of this component:

https://casesandberg.github.io/react-color/

@broham89 I'm pretty sure we can expand the colors of the picker. Do you want to create a pallete of colors for us?

**Comment by dcalvom** [comment]
Also, system entities use this color, it should be nice if those system entities could have a different color. Currently, they are sharing colors

**Comment by broham89** [comment]
If you're using a generator to pick those colors then it's totally fine to use that. Just make sure the colors are not too light to the point you can't see the text behind a white bg.

**Comment by wrathagom** [comment]
Closed with 5e951ea02a32cbf14021398128f0520f5202f634
