### ISSUE TITLE
Allow formatting POST response with Handlebars

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#218]
1. Move `Webhook Definition` directly below slots.
2. Add a new header below that that says `Response Definition`
3. Move the Agent Responses section below that
4. Add a new input below Agent Responses for `Response formatting` that’s a code block. it defaults to whatever handlebars would generate the current response.

**Comment by wrathagom** [comment]
Per request from @BreadAndRoses95

**Comment by BreadAndRoses95** [comment]
Could try to work on it but I'm wondering if this should not be done at an higher level so that it can be set for every intent? And maybe let the user override this behavior at the intent level?

**Comment by wrathagom** [comment]
The way the webhook works anyway is that it has a default. So in this case we could default to the current payload which is something like:

```
{
  "textResponse": {{textResponse}}
}
```

**Comment by wrathagom** [comment]
yeah, makes sense to me.

**Comment by dcalvom** [comment]
This issue was solved by @BreadAndRoses95 already. But this shouldn't be closed until we fix this part of the UI

![image](https://user-images.githubusercontent.com/7228045/40866314-46958580-65ba-11e8-9927-2d59058fd8f8.png)

**Comment by wrathagom** [comment]
@BreadAndRoses95 @dcalvom this one is complete with #228 right?
