### ISSUE TITLE
Need a Quick Way to View Parse Results & CSO

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#219]
We've had the need for the developer to review parse results and conversation state object. A quick way to meet this need without too much effort (that's reasonably acceptable) would be to provide a two tiny icons next to the dialog bubbles. 

- One would link (POST) to take (new tab) the user to the parse API and display the results to the user.
- Another would link to the take the user to another pay that shows the CSO contents

@broham89 need some links or tiny icons that would appear in the text bubbles

**Comment by broham89** [comment]
On it, I'm trying out different effects to click on the chat bubble that shows the links.  I'm thinking that links text like `POST` and `CSO` explain more to the user what they are instead of icons. 

Currently this is what i'm thinking of doing (image)... But ran into issues like, what would happen if the user only typed 1 word the chatbubble would be tiny and the View links would just visually hang off. Still working on it.

<img width="543" alt="screen shot 2018-05-24 at 4 45 56 pm" src="https://user-images.githubusercontent.com/11262149/40515350-185653f0-5f72-11e8-835a-63397441a8d0.png">

**Comment by broham89** [comment]
<img width="668" alt="screen shot 2018-05-24 at 4 53 44 pm" src="https://user-images.githubusercontent.com/11262149/40515926-6f6a0de2-5f74-11e8-9456-846b4a8a584d.png">
<img width="671" alt="screen shot 2018-05-24 at 5 03 23 pm" src="https://user-images.githubusercontent.com/11262149/40515927-6f7bc438-5f74-11e8-9cf2-06325311242c.png">

This is another version i'm currently thinking of working on.

**Comment by ewoo** [comment]
I was thinking the options would appear inside the bubble right-aligned (see image). Also, the buttons would be "Parse Results" and "Context" but they're kind long. I wonder if you could have icons for each like a book and a speech bubble? (Need to work on ideas for what iconography are appropriate for those.)

![bubble-inspection-actions](https://user-images.githubusercontent.com/278197/40525165-8a4a98ba-5fac-11e8-86af-b3e7da411367.png)

**Comment by ewoo** [comment]
Maybe the wording should say, "Debug: [Parsing] [Context]"?

@wrathagom your preference?

**Comment by broham89** [comment]
@ewoo @wrathagom  Could you provide some examples snapshots of what `Parse` and `context` looks like and what they are used for? Just enough for me to understand how I can start designing the icons for them.

**Comment by wrathagom** [comment]
they are both big ass JSON snippets. one has the NLU (intent/entity) information the other has the slots/historical information.

**Comment by wrathagom** [comment]
@ewoo why the duplicate tag, is there another issue for this someplace. I'll read through them all here in a minute.

**Comment by broham89** [comment]
<img width="185" alt="screen shot 2018-05-27 at 6 14 30 pm" src="https://user-images.githubusercontent.com/11262149/40591600-dd9ead24-61d9-11e8-9db8-08124900db50.png">
How about these icons? @ewoo @wrathagom

**Comment by broham89** [comment]
<img width="272" alt="screen shot 2018-05-28 at 11 46 31 am" src="https://user-images.githubusercontent.com/11262149/40623462-e879fd00-626c-11e8-8039-6668ceba56c4.png">

**Comment by broham89** [comment]
<img width="273" alt="screen shot 2018-05-28 at 11 51 28 am" src="https://user-images.githubusercontent.com/11262149/40623630-7fd99a66-626d-11e8-8d17-fb5486318698.png">
^ here is a simpler look having the JSON brackets to quickly signify to the user too see the code behind it.

**Comment by wrathagom** [comment]
I think without text the user will be baffled of what it means. I think a simple `view source` type text would suffice. Or maybe the icon as an indicator of a debug type area and then several buttons for parse, context, etc.

**Comment by broham89** [comment]
Things that I edit/added:

1.  js/**script.js** line 27-30
2. scss/components/**_chat-bubble.scss** line 140-190
3. **settings.html** `div class="source-links"` lines 108-115 and 122-129
4. added img/**json.svg**

[nlu-styles.zip](https://github.com/samtecspg/articulate/files/2050375/nlu-styles.zip)

**Comment by wrathagom** [comment]
new ui address the viewing of `/parse` we con't store the CSO anywhere, so that will have to be addressed later.
