### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#22]
There exist some cloud services that manage users like firebase and Auth0.

Auth0 offers free services for open source projects. 

> Have an open source project? Get Auth0 for free with our Open Source ProgramLEARN MORE

Once the authentication issue is solved, then we need to manage the sessions in the DB for two purposes. The first one to allow the platform to be multi-user, and the second one to enable session management in the converse side.

**Comment by wrathagom** [comment]
https://github.com/jedireza/aqua for future reference

**Comment by dcalvom** [comment]
just brainstorming https://github.com/andreasasprou/react-boilerplate-auth

**Comment by wrathagom** [comment]
This has been broken out into several steps: #597, #598, #599, #600, and #601 closing in favor of those.
