### ISSUE TITLE
Entity dependancy not removed when examples/slots removed from intent.

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#220]
I believe this is what is plagueing Marco.

Steps to reproduce:

1. Create an agent
2. Create a domain
3. Create an entity `toppings`
4. Create an intent and make sure to use that entity in your examples. Save that intent
5. Go back into the intent and remove all user examples that use that entity
6. delete the slot
7. save your intent changes
8. go to entity page and look at where used... it is still showing being used by that intent even though all references to that entity have been removed.

**Comment by wrathagom** [comment]
I also tried deleting the entire intent, but that didn't work either.

**Comment by wrathagom** [comment]
This is the suspect method https://github.com/samtecspg/articulate/blob/master/api/modules/intent/tools/updateEntitiesDomain.intent.tool.js

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/219d435159f705b018f5c8648e9e3a1e801e90ad
