### ISSUE TITLE
If training fails agent get's stuck in training status

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#221]
I forgot to change the memory allocation in Docker and so training failed. I thought I would just add more memory/restart docker and away I would go. But now my agent is stuck in training status and I can't fix it.

Steps to re-produce:
1. Start an agent training
2. Ctrl+c while training is going on.
3. Try to `docker-compose up`
4. agent should be stuck in training status.

**Comment by wrathagom** [comment]
Okay never mind, I waited longer and it fixed itself.

@dcalvom any idea how/why it switched to an error status? I'm glad that it did, just curious how/why.

**Comment by wrathagom** [comment]
er, I clicked train and it immediately changed to ready, without any real training taking place. So maybe didn't handle things perfectly.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e982eff194b00f906db297af4add24a224acb933
