### ISSUE TITLE
Import is failing when regex = null

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#222]
If an entity doesn't have a regex then the exported value is null. Then the import fails with the following error:
```
{
 "statusCode": 400,
 "error": "Bad Request",
 "message": "child \"entities\" fails because [\"entities\" at position 0 fails because [child \"regex\" fails because [\"regex\" must be a string]]]",
 "validation": {
   "source": "payload",
   "keys": [
     "entities.0.regex"
   ]
 }
}
```

**Comment by cjhurst** [comment]
@dcalvom Is there any sort of error stack trace that comes back from the http request as well as the json body? It would be exceedingly helpful for me if that was always included... so that I could see the exact line of code to go look at and trace the logic. @wrathagom Is there a different way in which this is usually handled?

**Comment by wrathagom** [comment]
There probably is in the docker logs, but this is coming from a user... so we get what we get. We probably could've asked Marco for the logs.

That being said my guess is that @dcalvom already knows where to look for this as we fought something similar in the API when this regex functionality was pulled in.

**Comment by cjhurst** [comment]
I see. thanks :)

**Comment by dcalvombl** [comment]
When tackle this we are going to add a unit test where you export, delete and import the same agent.

**Comment by dcalvom** [comment]
When tackle this we are going to add a unit test where you export, delete and import the same agent.

**Comment by Johnz86** [comment]
I monkey patched this by replacing ```"regex": null,``` with ```"regex": "",```.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/79da66f1fab6b40e1278c39877a3569076b4fe03

Tests included
