### ISSUE TITLE
UI yarn error file

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#233]
We need to remove this file from the repo and add an entry into the .gitignore for it

```
ui/yarn-error.log                                                                           | 8875 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5c1ffc0759ac3f143b18ad209f97387643b8c5d6
