### ISSUE TITLE
Bad Status on a clean install/restart

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#234]
I had a trained an agent, but then restarted Articulate to pull in the latest changes. I did a `git clean xdf` as well as a `docker-compose pull` There are a bunch of console errors and the agent still shows a ready status. There is no active agent.

![image](https://user-images.githubusercontent.com/1779894/40870302-a716b7ea-65fa-11e8-822f-f49696cad624.png)

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/1779894/40870295-9018c8a8-65fa-11e8-8ebd-fc9286ba5b18.png">

**Comment by dcalvom** [comment]
This is part of a lot of annoying actions related with the local storage stuff

**Comment by wrathagom** [comment]
@malave did you implement the localStorage stuff? Should we move to sessionStorage instead? It's weird what things persist even on fresh loads.

We do have the query hitting the API frequently... maybe we should just clear the agent out if we get an agent not found error.

**Comment by dcalvom** [comment]
I think sessionStorage would not be the fix given that if the user open a new tab of Articulate he would need to select the agent again:

**sessionStorage:** 

1. It is similar to localStorage.
2. Changes are only available per window (or tab in browsers like Chrome and Firefox). Changes made are saved and available for the current page, as well as future visits to the site on the same window. Once the window is closed, the storage is deleted
3. The data is available only inside the window/tab in which it was set.
4. The data is not persistent i.e. it will be lost once the window/tab is closed. Like localStorage, it works on same-origin policy. So, data stored will only be available on the same origin.

**Comment by dcalvom** [comment]
Closed in favor of https://github.com/samtecspg/articulate/issues/241
