### ISSUE TITLE
Add indents to default response format code block

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#236]
I think this should be formatted as:

```
{
  "textResponse" : "{{ textResponse }}"
}
```

rather than

```
{ "textResponse" : "{{ textResponse }}" }
```

which is is currently. Also are the `"` around `{{textResponse}}` necessary?

**Comment by BreadAndRoses95** [comment]
As it's a text field I think they are to be properly parsed as json after the handlebar processing, would work without " with int or bool though

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b582ebafb5bd9d35ac432544f5466f0cfea48ab6
