### ISSUE TITLE
Webhook and response format are missing from edit agent page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#237]
Uh yeah, where'd they go?

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/1779894/40870395-7171e2ca-65fc-11e8-9720-c7e092f5a079.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/d0deff53252370622e2fffc850b171e44ef60980
