### ISSUE TITLE
Drag handle not showing up

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#238]
Sorry @dcalvom but the drag handle isn't showing up for me in Chrome or Safari:

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/1779894/40870436-455c1ad8-65fd-11e8-85bf-2fe2954a2717.png">

**Comment by dcalvom** [comment]
According to @broham89 design, the card doesn't have a drag. Maybe we can reopen the sort slot issue if you think it should have it
