### ISSUE TITLE
Allow custom webhook headers

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#240]
If I create a webhook and specify a BodyType or None, I do not have access to the response content when the webhook is returned. This may be because Articulate is expecting a return content type of JSON and is unable to parse the results when it's something else.

Consider that a valid return type might be HTML, XML (heaven forbid), or text--not just JSON. Articulate should be able to handle any of these--and provide the developer access to this content.

Solution Strategy
- We may consider allowing the user to specify ACCEPT-HEADERS (not sure if it's the best way)
- At the least, Articulate's parser should be able to access the content as plain text

![edit_intent](https://user-images.githubusercontent.com/278197/40994980-c95f6f4e-68cb-11e8-992b-4836ad3bc759.jpg)

**Comment by ewoo** [comment]
{{ response.Content }} << by default, all content is available as plain text as a _flattened_ string

{{ response.Property.SubProperty }} << when available, the response content is traversable via properties

**Comment by dcalvom** [comment]
If you want the full JSON from webhookResponse then you need to call the JSONstringify helper and escape it with another set of brackets like this `{{{JSONstringify webhookResponse}}}`

**Comment by ewoo** [comment]
Thanks @dcalvom got that to work. But when calling a simple GET without using JSON, I am unable to access any response content.

**Comment by wrathagom** [comment]
@ewoo I want to morph this into a more generic "Allow webhook header configuration" which I think would solve both problems. Good with that?

**Comment by wrathagom** [comment]
@dcalvom this one can use a similar interface as what I am proposing for the domain parameters:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/1779894/41756033-37552ae6-75a8-11e8-9e89-37c280d8d27c.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b8803e97f98b4980a513409861c605999464cab1
