### ISSUE TITLE
Installation without Docker?

### ISSUE THREAD

**Issue by macasas** [samtecspg/articulate#247]
Is it possible to install Articulate without using Docker?

I have tried with Docker on both mac and pc, and have wasted 2 days without success. Docker has multiple issues on each OS.

So what do I need to do to run Articulate without Docker?

**Comment by dcalvom** [comment]
Hi Dave,

This is not straightforward given that you need to coordinate multiple services. You will need to setup and run rasa, duckling, redis individually and then setup Articulate. 

We do start Articulate locally without docker for development purposes but given the time to set up the other services individually, we prefer to use docker.

If you want to give it a try go ahead and start by [installing rasa](https://nlu.rasa.com/installation.html) and then by [starting it up as an HTTP server](https://nlu.rasa.com/http.html).

Then, in [Duckling's readme](https://github.com/facebook/duckling) you will find how to install it and run it locally.

Finally, install redis. They have a [quick start guide](https://redis.io/topics/quickstart). There seems to be some [windows exe realeases](https://github.com/rgl/redis/downloads).

Once you have this pieces up and running then just pull the tag of the version you want to use. Don't pull master as it is not stable.

Once you pull it do the following:

1. Be sure you have node.js and docker installed
2. Pull articulate and checkout desired branch
3. cd api
4. yarn install
5. cd ..
6. cd ui
7. yarn install
8. npm run start 
9. open another terminal
10. cd api
11. npm run start:server

As you can see this not straighforward, so we only do these for development purposes. If you wish you could also try to spin up cloud instance and follow our [guide for cloud installation](https://samtecspg.github.io/articulate/getting_started/cloud-installation)

**Comment by macasas** [comment]
Thanks for your quick reply.

I will give it a try, but it doesn’t look promising. :-)


On 14 June 2018 at 20:22:44, Daniel Calvo Marin (notifications@github.com)
wrote:

Hi Dave,

This is not straightforward given that you need to coordinate multiple
services. You will need to setup and run rasa, duckling, redis individually
and then setup Articulate.

We do start Articulate locally without docker for development purposes but
given the time to set up the other services individually, we prefer to use
docker.

If you want to give it a try go ahead and start by installing rasa
<https://nlu.rasa.com/installation.html> and then by starting it up as an
HTTP server <https://nlu.rasa.com/http.html>.

Then, in Duckling's readme <https://github.com/facebook/duckling> you will
find how to install it and run it locally.

Finally, install redis. They have a quick start guide
<https://redis.io/topics/quickstart>. There seems to be some windows exe
realeases <https://github.com/rgl/redis/downloads>.

Once you have this pieces up and running then just pull the tag of the
version you want to use. Don't pull master as it is not stable.

Once you pull it do the following:

   1. Be sure you have node.js and docker installed
   2. Pull articulate and checkout desired branch
   3. cd api
   4. yarn install
   5. cd ..
   6. cd ui
   7. yarn install
   8. npm run start
   9. open another terminal
   10. cd api
   11. npm run start:server

As you can see this not straighforward, so we only do these for development
purposes. If you wish you could also try to spin up cloud instance and
follow our guide for cloud installation
<https://samtecspg.github.io/articulate/getting_started/cloud-installation>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/247#issuecomment-397373550>,
or mute the thread

**Comment by dcalvom** [comment]
Hey @macasas just by curiosity. What are the issues you are experimenting with docker? Do you think those are related with your docker configuration or with Articulate?

**Comment by macasas** [comment]
Docker all the way, but the end result is no Articulate.  I’m a
conversational architect, not a software guru, and if something is this
hard to install, it will eventually not get installed and I’ll end up
having to use something else.  I’ve tried on mac and windows.

Login issues, then container issues, then wouldn’t allow shared drive
selection.  Docker takes 30 minutes to make a settings change, then needs a
reboot, then looses previous settings.

Whenever I run "docker-compose up" it never finishes, now saying not enough
space even though I have 186Gb free. I’ve tried the shared drives, just
cannot see how Docker is saving people time, every step has been a struggle.

On 14 June 2018 at 20:53:54, Daniel Calvo Marin (notifications@github.com)
wrote:

Hey @macasas <https://github.com/macasas> just by curiosity. What are the
issues you are experimenting with docker? Do you think those are related
with your docker configuration or with Articulate?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/247#issuecomment-397382967>,
or mute the thread

**Comment by dcalvom** [comment]
I see. Well then I think we can close this one. Remember to give a try to cloud instance, the setup could be pretty easy and we could give you a hand.

In my case we use Vultr for cloud instances and it works fine.
