### ISSUE TITLE
Error after restarting machine

### ISSUE THREAD

**Issue by utiq** [samtecspg/articulate#248]
I just restarted my computer without doing `docker-compose down` first and now when I try to parse some text using the API, I get this error in the log

```
rasa_1      | 2018-06-15 23:48:05+0000 [-] "172.20.0.5" - - [15/Jun/2018:23:48:04 +0000] "POST /parse HTTP/1.1" 404 51 "-" "-"
api_1       | Debug: internal, implementation, error
api_1       |     Error: Error calling rasa to parse text on domain Meeting planning
api_1       |     at Wreck.post (/usr/src/app/modules/agent/tools/parseText.agent.tool.js:21:32)
api_1       |     at read (/usr/src/app/node_modules/wreck/lib/index.js:530:24)
api_1       |     at finish (/usr/src/app/node_modules/wreck/lib/index.js:375:16)
api_1       |     at wrapped (/usr/src/app/node_modules/hoek/lib/index.js:871:20)
api_1       |     at module.exports.internals.Recorder.onReaderFinish (/usr/src/app/node_modules/wreck/lib/index.js:421:16)
api_1       |     at Object.onceWrapper (events.js:291:19)
api_1       |     at emitNone (events.js:91:20)
api_1       |     at module.exports.internals.Recorder.emit (events.js:186:7)
api_1       |     at finishMaybe (_stream_writable.js:510:14)
api_1       |     at afterWrite (_stream_writable.js:384:3)
```
What can I do?

Docker: Version 17.12.0-ce-mac49 (21995)
OS: MacOS High Sierra 10.13.3
Articulate version: articulate-v0.9.4

**Comment by wrathagom** [comment]
Where you training or any other activity when you shutdown your PC?

Can you verify that Rasa is running? `docker-compose ps`

**Comment by utiq** [comment]
No, I wasn't training or any other activity. I see this when `docker-compose ps`

```
articulatev094_api_1        node start.js                    Up      0.0.0.0:7500->7500/tcp
articulatev094_duckling_1   /bin/sh -c stack exec duck ...   Up      0.0.0.0:8000->8000/tcp
articulatev094_rasa_1       ./entrypoint.sh start --pa ...   Up      0.0.0.0:5000->5000/tcp
articulatev094_redis_1      docker-entrypoint.sh redis ...   Up      0.0.0.0:6379->6379/tcp
articulatev094_ui_1         yarn start                       Up      0.0.0.0:3000->3000/tcp
```

**Comment by wrathagom** [comment]
So let's start with a `docker-compose down` and a `docker-compose up`

If that doesn't work you may need to re-train. It may be beneficial to see the result of `curl localhost:5000/status`

**Comment by utiq** [comment]
I've done that plenty of times.

Actually where are those model files stored? when I delete the Docker Articulate instances and images the files are still there. This is what I see when I curl `localhost:5000/status`

```
{
current_training_processes: 0,
available_projects: {
my_agent: {
status: "ready",
available_models: [
"Meeting planning_d74af10e-2df1-bc0e-e4e4-4ad2b67537b0",
"Meeting planning_7bf845a6-ec45-e461-991c-8596c443b654",
"Meeting planning_1f9e0ca5-b9cc-cf86-37b6-5c3b16e6989b",
"Meeting planning_a7f34307-f3a0-0261-83e6-846e16a2464c",
"Meeting planning_b5d3c04c-1c49-38f2-69b8-008e6ea7e9b8",
"Meeting planning_a9abb53d-34eb-25ee-dd1a-9d3393795853",
"Meeting planning_12226214-cfe7-3625-ab7a-9d5ef341afe6",
"Meeting planning_f4e744f1-e2f7-0621-d3f6-0d2c86326948",
"Meeting planning_0fd7dc80-cc94-66e2-26b8-13515269f704",
"Meeting planning_just_er_ce8d924a-f42c-a7ff-c6a9-48218172c726",
"Meeting planning_b438e2c8-0770-95b4-6226-4834a445d9b4"
],
loaded_models: [ ]
},
.gitignore: {
status: "ready",
available_models: [
"fallback"
],
loaded_models: [
"fallback"
]
}
}
}
```

**Comment by wrathagom** [comment]
By default they are stored in the `local-storage/rasa/nlu-model` directory.

Do you have more than one domain? I don't see a domain classifier model.

@dcalvom any thoughts?

**Comment by dcalvom** [comment]
@utiq Could you provide us the result of listing your agent domains with `http://localhost:8000/agent/{yourAgentId}/domain`

**Comment by dcalvom** [comment]
@utiq sorry the right port is the `7500` for the API

**Comment by utiq** [comment]
@dcalvom this is what I get
```
[
  {
    "id": 1,
    "agent": "my_agent",
    "model": "b5d3c04c-1c49-38f2-69b8-008e6ea7e9b8",
    "enabled": true,
    "domainName": "Meeting planning",
    "lastTraining": "Fri Jun 08 2018 21:48:24 GMT+0000 (UTC)",
    "intentThreshold": 0.5,
    "extraTrainingData": false
  }
]
```

**Comment by utiq** [comment]
Thanks @wrathagom 
Do you guys think the data or configuration was corrupted at some point?

**Comment by wrathagom** [comment]
Have you tried making some small change to re-train? I was trying to re-produce, but no matter how I restarted my Mac it came back up fine :/ I'll keep trying to re-produce this weekend. If possible. Can you zip your local-storage folder and upload it?

**Comment by utiq** [comment]
Do you have an email where I can send it?

**Comment by dcalvom** [comment]
Send it to caleb.keller@samtec.com or daniel.calvo@samtec.com

**Comment by wrathagom** [comment]
@utiq any luck?

**Comment by dcalvom** [comment]
@utiq I could assume this was already solved?

**Comment by wrathagom** [comment]
Never was able to re-produce. @utiq you've been running fine though since this instance right?
