### ISSUE TITLE
Regex auto-highlight doesn't work when regex string appears at beginning of sentence

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#254]
![image](https://user-images.githubusercontent.com/1779894/41517951-0db52a2e-728d-11e8-8e55-7cac3ec86122.png)

**Comment by BreadAndRoses95** [comment]
Sorry didn't see this one,  didn't know how to handle the fix so created a branch https://github.com/samtecspg/articulate/pull/260

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/713a3cbead0e2bbbed5265f563ad68037ee155c9
