### ISSUE TITLE
Add preset pipeline buttons beside pipeline setting code blocks

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#255]
This is an enhancement idea. Right now we have code blocks where the users can type in their own pipelines. This is very useful but we could make it easier to use If we provided button somewhere beside the code blocks for loading the default pipelines: keyword, tensorflow, spacy, etc.

**Comment by wrathagom** [comment]
@broham89 this one could use a design. and then I may try to tackle the code.

**Comment by broham89** [comment]
<img width="736" alt="screen shot 2018-07-02 at 12 18 20 pm" src="https://user-images.githubusercontent.com/11262149/42177362-1de109d4-7df2-11e8-93a8-9a4e527fd72b.png">

**Comment by broham89** [comment]
<img width="768" alt="screen shot 2018-07-02 at 12 36 11 pm" src="https://user-images.githubusercontent.com/11262149/42178046-88d983ea-7df4-11e8-8f75-958706d0594b.png">

Below is the icon
[icon.zip](https://github.com/samtecspg/articulate/files/2156220/icon.zip)

**Comment by broham89** [comment]
<img width="532" alt="screen shot 2018-07-02 at 12 38 14 pm" src="https://user-images.githubusercontent.com/11262149/42178128-d2e72d3e-7df4-11e8-8015-3176c240b67f.png">

[icon.zip](https://github.com/samtecspg/articulate/files/2156222/icon.zip)
