### ISSUE TITLE
Error: agent head missing - on AWS 

### ISSUE THREAD

**Issue by AniketRoy** [samtecspg/articulate#256]
**Version:** Articulate 0.9.4 
**OS:** Ubuntu 16.04 server, Docker version 18.05.0-ce, docker-compose version 1.21.2
**Deployment:** AWS EC2
**Browser:** Firefox 60.0.1

### Issues
Having problem to run Articulate on AWS EC2 instance. 
Followed [cloud installation docs](https://samtecspg.github.io/articulate/getting_started/cloud-installation). Added `DOCKER_HOST` veriable and updated `SWAGGER_HOST` and `API_URL` with my ip.
After running `docker-compose up -d` showing below error. 

##Error
>*Error: agent head missing*
>*We couldn't connect to the API. This could be because the API ports aren't configured properly in your environment. For configuration instruction go to here:*

My [docker-compose.yml]() file:
>*version: '3.0'*
>*
 services:
   api:
     image: samtecspg/articulate-api:0.9.4
     ports: ['0.0.0.0:7500:7500']
     networks: ['alpha-nlu-network']
     # The following (crazy) block is about both:
     # 1) setting default values for app parameteres
     # 2) projecting any changes to those values set in the .env file
     # a line should be added to this list for any env-var/param that the
     # app might need, and its easiest to follow if the var name is kept the
     # same for both the var thats projected into the app (the first name)
     # and the name thats expected in the .env (the second name)
     environment:
       - REDIS_HOST=${REDIS_HOST:-redis}
       - REDIS_PORT=${REDIS_PORT:-6379}
       - RASA_URL=${RASA_URL:-http://rasa:5000}
       - DUCKLING_URL=${DUCKLING_URL:-http://duckling:8000}
       - MODEL_DIR=${MODEL_DIR:-./local-storage/rasa/nlu-model}
       - DOCKER_INSTANCE=${DOCKER_INSTANCE:-localhost}
       - SWAGGER_HOST=${SWAGGER_HOST:-XX.XXX.XXX.XXX}:7500
       - DOCKER_HOST=${DOCKER_HOST:-XX.XXX.XXX.XXX}
     volumes: ["${MODEL_DIR:-./local-storage/rasa/nlu-model}:/app/projects"]
     entrypoint: ['node', 'start.js']
     healthcheck:
       test: ['CMD', 'curl', '-f', 'http://${DOCKER_INSTANCE:-localhost}:7500/agent']
   ui:
     image: samtecspg/articulate-ui:0.9.4
     ports: ['0.0.0.0:3000:3000']
     environment:
       - API_URL=${API_URL:-http://XX.XXX.XXX.XXX:7500}
     networks: ['alpha-nlu-network']
   rasa:
     image: samtecspg/articulate-rasa:0.9.4
     ports: ['0.0.0.0:5000:5000']
     volumes: ["${MODEL_DIR:-./local-storage/rasa/nlu-model}:/app/projects", "${RASA_CONFIG:-./local-storage/rasa/rasa-config.yml}:/app/config.yml", "./local-storage/rasa/logs:/app/logs"]
     networks: ['alpha-nlu-network']
  duckling:
     image: samtecspg/duckling:0.1.6.0
     ports: ['0.0.0.0:8000:8000']
     networks: ['alpha-nlu-network']
   redis:
     image: redis:4.0.6-alpine
     ports: ['0.0.0.0:6379:6379']
     networks: ['alpha-nlu-network']
     command: redis-server --appendonly yes
     volumes:
       - ${REDIS_DATA:-./local-storage/redis-data}:/data 
>
> networks: {alpha-nlu-network: {}}*

**Comment by wrathagom** [comment]
@AniketRoy can you start over on a clean VM? Or re-download our latest release (0.10.1) it simplifies the cloud installation if you are just trying to get it up and running. On that version once you have it downloaded and cd into the articulate directory you can just run this command:

```
PUBLIC_IP=XXX.XX.XX.XXX docker-compose up
```

and everything should work.

**Comment by AniketRoy** [comment]
@wrathagom I'm going to try this. Will give you status.

**Comment by AniketRoy** [comment]
**Update:** 
@wrathagom, followed your instruction, but same issue. 

After running, `sudo PUBLIC_IP=XX.XXX.XXX.XXX docker-compose up`, got this at the end of process:
>*Attaching to articulate-0101_ui_1, articulate-0101_duckling_1, articulate-0101_api_1, articulate-0101_rasa_1, articulate-0101_redis_1
ui_1        | yarn run v1.7.0
redis_1     | 1:C 19 Jun 05:32:08.150 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 19 Jun 05:32:08.152 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 19 Jun 05:32:08.152 # Configuration loaded
redis_1     | 1:M 19 Jun 05:32:08.155 * Running mode=standalone, port=6379.
redis_1     | 1:M 19 Jun 05:32:08.155 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 19 Jun 05:32:08.156 # Server initialized
redis_1     | 1:M 19 Jun 05:32:08.156 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 19 Jun 05:32:08.156 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 19 Jun 05:32:08.157 * Ready to accept connections
ui_1        | $ cross-env NODE_ENV=development node server
rasa_1      | 2018-06-19 05:32:09+0000 [-] Log opened.
rasa_1      | 2018-06-19 05:32:09+0000 [-] Site starting on 5000
rasa_1      | 2018-06-19 05:32:09+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f91fcd56a28>
ui_1        | Server started ! ✓
ui_1        | 
ui_1        | Access URLs:
ui_1        | -----------------------------------
ui_1        | Localhost: http://localhost:3000
ui_1        |       LAN: http://172.18.0.4:3000
ui_1        | -----------------------------------
ui_1        | Press CTRL-C to stop
ui_1        |     
duckling_1  | no port specified, defaulting to port 8000
duckling_1  | Listening on http://0.0.0.0:8000
api_1       | Server running at:   http://1e4ff385b8b8:7500
api_1       | Explorer running at: http://1e4ff385b8b8:7500/documentation
ui_1        | webpack built 42d7c6ee84b486c536fb in 13904ms *

and got stuck there. Later took another ssh and check checked `sudo docker ps`:

>*CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS                    NAMES
1e4ff385b8b8        samtecspg/articulate-api:0.10.1    "node start.js"          17 minutes ago      Up 17 minutes (unhealthy)   0.0.0.0:7500->7500/tcp   articulate-0101_api_1
27751781267a        samtecspg/duckling:0.1.6.0         "/bin/sh -c 'stack e…"   17 minutes ago      Up 17 minutes               0.0.0.0:8000->8000/tcp   articulate-0101_duckling_1
bdc2561e9017        samtecspg/articulate-ui:0.10.1     "yarn start"             17 minutes ago      Up 17 minutes               0.0.0.0:3000->3000/tcp   articulate-0101_ui_1
7fa8cb11f05a        samtecspg/articulate-rasa:0.10.1   "./entrypoint.sh sta…"   17 minutes ago      Up 17 minutes               0.0.0.0:5000->5000/tcp   articulate-0101_rasa_1
1a587c857aba        redis:4.0.6-alpine                 "docker-entrypoint.s…"   17 minutes ago      Up 17 minutes               0.0.0.0:6379->6379/tcp   articulate-0101_redis_1*

Here is the browser output:

![image](https://user-images.githubusercontent.com/11561192/41580359-4bf9d718-73b8-11e8-881f-62b05d8a4ab9.png)

**Comment by wrathagom** [comment]
@AniketRoy it's interesting, because if the UI actually couldn't connect there would be an error in the console. I'm curious if there isn't some sort of cash problem that's showing you that page even though are connected just fine.

What happens when you click on the Articulate logo on in the top left hand corner?

**Comment by AniketRoy** [comment]
@wrathagom apparently, the problem is with my systems. Tried on my different systems, and working smoothly. v0.10.1 solved the issue. Thanks for the help :100:

**Comment by wrathagom** [comment]
sorry that you had trouble in the first place :/ but glad you got it working!!! I'll close this issue, but feel fret open a new one if you have more troubles.
