### ISSUE TITLE
Add Setting to agent disable domains

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#257]
Discussing

**Comment by dcalvom** [comment]
According to our discussion, the goal of this feature is to let the user select whether they prefer one model per agent or one model per each domain.

This maybe doesn't have to much use right now, but depending on the pipelines the user will use then it would allow users to tune the usage of their model.

This feature came up after thinking on the inclusion of the tensorflow pipeline. Given that this processor allows multi intent recognition is better to handle all the training data in a single domain.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/4c4dfaadb9ee739b6f9e6eb4d5cc13f487bce6f5
