### ISSUE TITLE
Use postFromat

### ISSUE THREAD

**Issue by malpet** [samtecspg/articulate#261]
Hi, we have a problem to import agent on the newest version of the articulate-v0.10.1 (release). Agent is exported from the version v0.9.4.

articulate-v0.10.1 - is running locally in Windows10
articulate-v0.9.4 - is running in Linux in AWS

used browser Chrome Version 67.0.3396.87 (Official Build) (64-bit)

exception during import is:

{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "child \"usePostFormat\" fails because [\"usePostFormat\" is required]",
  "validation": {
    "source": "payload",
    "keys": [
      "usePostFormat"
    ]
  }
}
 

Thanks
Peter M.

**Comment by dcalvom** [comment]
Hi Peter M.

Sorry about this, the reason is that we included a new feature called Post Format that let you specify additional data for your converse endpoint.

To fix this just add an attribute in the root of your exported agent:

`usePostFormat: false`

And that will fix the issue

**Comment by wrathagom** [comment]
@malpet did that resolve your troubles? If not you can provide your training data as an attachment or e-mail it to us and we will make the modifications necessary for you to import it into 0.10

**Comment by malpet** [comment]
@wrathagom We tried to add this attribute to the root of the agent but it didn't help. I've created gist with training data. Will send you email with the link.
Thanks.

**Comment by dcalvom** [comment]
Hi @malpet we really sorry about this issue. We need to improve our compatibility between versions. We fixed your agent and we are going to send it to you.

Give the inclusion of the response definition feature every export from previous versions need to add the `"usePostFormat": false` attribute not only to the root agent, but, in every intent of the agent.

Also now the agent are managing their own settings, so if you export an agent from previous you need to add a settings attribute at the same level of entities and domains. The default settings for agents are:

```
"settings": {
    "domainClassifierPipeline": [
      {
        "name": "nlp_spacy"
      },
      {
        "name": "tokenizer_spacy"
      },
      {
        "name": "intent_featurizer_spacy"
      },
      {
        "name": "intent_classifier_sklearn"
      }
    ],
    "intentClassifierPipeline": [
      {
        "name": "nlp_spacy"
      },
      {
        "name": "tokenizer_spacy"
      },
      {
        "name": "intent_featurizer_spacy"
      },
      {
        "name": "ner_crf"
      },
      {
        "name": "ner_synonyms"
      },
      {
        "name": "intent_classifier_sklearn"
      },
      {
        "name": "ner_spacy"
      }
    ],
    "entityClassifierPipeline": [
      {
        "name": "nlp_spacy"
      },
      {
        "name": "tokenizer_spacy"
      },
      {
        "name": "ner_crf"
      },
      {
        "name": "ner_synonyms"
      },
      {
        "name": "ner_spacy"
      }
    ],
    "rasaURL": "http://rasa:5000",
    "ducklingURL": "http://duckling:8000",
    "ducklingDimension": [
      "amount-of-money",
      "distance",
      "duration",
      "email",
      "number",
      "ordinal",
      "phone-number",
      "quantity",
      "temperature",
      "time",
      "url",
      "volume"
    ],
    "spacyPretrainedEntities": [
      "PERSON",
      "NORP",
      "FAC",
      "ORG",
      "GPE",
      "LOC",
      "PRODUCT",
      "EVENT",
      "WORK_OF_ART",
      "LAW",
      "LANGUAGE",
      "DATE",
      "TIME",
      "PERCENT",
      "MONEY",
      "QUANTITY",
      "ORDINAL",
      "CARDINAL"
    ]
  }
```

When you add those values you are going to be good to import your agent.

**Comment by dcalvom** [comment]
@malpet I just commented your gist with another secret gist with the fixed agent. Please let us know if it worked for you

**Comment by wrathagom** [comment]
@malpet let us know if you still are having troubles. I am closing until we hear back otherwise.
