### ISSUE TITLE
Domain and Intent Settings should be moved into Accordions to match Agent

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#262]
We cleaned up the agent screen now we need to do the same on the intent and domain pages.

**Comment by dcalvom** [comment]
What would you like to group on these screens?

**Comment by wrathagom** [comment]
On Intent it would be "Intent Webhook Configuration" and "Intent Response Configuration"
On Domain it would just be "Domain Settings" with the threshold and generate extra training example inside

**Comment by dcalvom** [comment]
Great, given that the slider is going to be part of the `Domain Training Settings`, should we move the slider in the agent too?

**Comment by wrathagom** [comment]
bah, yeah probably. 🤔 where to put it. in Both cases it isn't really correct to put it into training right? It's more like dialogue settings.

**Comment by dcalvom** [comment]
Yeah, didn't saw is a different context? Can we keep it on Training for now?

**Comment by wrathagom** [comment]
yeah
