### ISSUE TITLE
Separate saving intents from updating NLU model.

### ISSUE THREAD

**Issue by hadils** [samtecspg/articulate#265]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
- What operating system are you running?
- Are you running locally or in the cloud?
- Which browser are you using?

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.
Each time I save an intent the RASA NLU model is recomputed. I would like to have the option to create several intents then have the model refreshed. This would require two separate buttons.
Thanks,
Hadil G. Sabbagh, Ph. D.

**Comment by dcalvom** [comment]
Hi @hadils if you move to our latest release this is already done
