### ISSUE TITLE
GPE & LOC not available in @sys

### ISSUE THREAD

**Issue by ncklrs** [samtecspg/articulate#267]
### Issues

I have pulled the current release - 0.10.2, running locally using Chrome

I am trying to note Cities and locations on intents but @sys.spacy_gpe and @sys.spacy_loc are not available. 

They are listed in the Spacy Entities /settings/rasa

![screen shot 2018-06-26 at 2 42 07 pm](https://user-images.githubusercontent.com/15656145/41932513-278be15e-794f-11e8-9900-580d5b49495d.png)

![screen shot 2018-06-26 at 2 41 30 pm](https://user-images.githubusercontent.com/15656145/41932470-10e7b112-794f-11e8-909a-41153aada026.png)

**Comment by wrathagom** [comment]
@ncklrs sorry about that, we discovered this yesterday and have incorporated a fix on https://github.com/samtecspg/articulate/commit/a54fe78144e548649b40ff0526408b9b05fa26ab which will be incorporated into our 0.11.0 release.

I've attached the 0.11.0 release zip you can give that a try or wait for us to formally release it. Sorry for the inconvenience.

[articulate-v0.11.0.zip](https://github.com/samtecspg/articulate/files/2138520/articulate-v0.11.0.zip)

**Comment by ncklrs** [comment]
Thanks @wrathagom I appreciate that.

**Comment by wrathagom** [comment]
I'm closing, but please comment or open a new issue if you have more troubles!
