### ISSUE TITLE
Unable to add Entity Examples once entity is created

### ISSUE THREAD

**Issue by ncklrs** [samtecspg/articulate#268]
Running Locally - Chrome 

If you create an entity and do not initially add any examples, you are unable to add any examples to that entity in edit mode.

-- there are no issues adding examples if you add at least one when you create the Entity

![awesomescreenshot-2018-06-26t20-03-48-686z](https://user-images.githubusercontent.com/15656145/41936622-c46030be-795b-11e8-8464-f26dcfcd8b5c.gif)

**Comment by wrathagom** [comment]
thanks for the report, we'll look into it.

**Comment by wrathagom** [comment]
This is fixed with https://github.com/samtecspg/articulate/commit/ba28cb5b80d2920560ae4cb3c4a68dfc9b8eaae8 the solution I chose was to require at least one example.

We'll get a 0.11.1 release going soon.
