### ISSUE TITLE
Extract user conversation

### ISSUE THREAD

**Issue by malpet** [samtecspg/articulate#269]
Hi,

I have just question, is it possible to extract with handlebars user sentences? I checked all CSO objects, but there is only bot context. What should I do to extract user conversation context?

e.g. 
User is asking some information from the bot, but bot doesn't know how to response and in this case I'd like to store whole conversation for further analysis. 

Thanks
Regards Peter M.

**Comment by malpet** [comment]
One more question:
Why CSO object context doesn't contain feelback responses?

**Comment by wrathagom** [comment]
@malpet I'll take a look at this shortly. We store the `parse` results at the `/doc` endpoint in the API. but you are correct that we don't store the entire conversation information. There's a lot of data there so we would have to decide how and where to store all of that information historical.

**Comment by malpet** [comment]
Can you please be more specific how to access /doc? I'll try to check if there are some relevant information for me. Thanks

**Comment by wrathagom** [comment]
If you have everything running locally go to http://localhost:7500/documentation to see the API explorer and look at the `/doc` endpoint.

**Comment by wrathagom** [comment]
Will be addressed by #402
