### ISSUE TITLE
Doesn't seem to work as expected

### ISSUE THREAD

**Issue by ajinkyapuar** [samtecspg/articulate#270]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

Trained a basic small talk bot which greets when you interact with it. It always gives a reply "We&#x27;re having trouble fulfilling that request". 

- Did you download a release or pull from Master? Which release?
 Release v0.11.0

- What operating system are you running?
MacOS X 10.13.5

- Are you running locally or in the cloud?
Locally

- Which browser are you using?
Chrome
----
<img width="327" alt="screen shot 2018-06-27 at 6 34 49 pm" src="https://user-images.githubusercontent.com/9402461/41976228-38c5bf3a-7a3a-11e8-8245-86a1bfea1c65.png">

**Comment by dcalvom** [comment]
Hi @ajinkyapuar when that happens is because there was an issue calling your webhook. What configuration are you using?

**Comment by ajinkyapuar** [comment]
Do you have a setup tutorial?

**Comment by dcalvom** [comment]
We have a blog where we post tutorials of Articulate features https://blog.spg.ai/

Check the `A Bot with a Handlebar Mustache` blog post

**Comment by wrathagom** [comment]
@ajinkyapuar I'll take the thumbs up as you getting it working. If not feel free to comment back or create a new issue.
