### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#275]
Hi i dev a new language in spacy . how can i add them ?

**Comment by dcalvom** [comment]
Hi,

There are some places were you need to add your languge. The first one is in the docker file of the Rasa container we use:

https://github.com/samtecspg/articulate/blob/master/rasa/Dockerfile

Look at the other languages you have there. If you are using our latest version, then just go to settings and update the language settings and add your new language. Please let me know if this worked for you.

**Comment by kurodenjiro** [comment]
Thank you

**Comment by wrathagom** [comment]
@kurodenjiro feel free to create a new issue if you have any other questions or troubles. I'll close this one.
