### ISSUE TITLE
docker-compose up command not responding

### ISSUE THREAD

**Issue by saurabhbidwai** [samtecspg/articulate#278]
Please describe the issue you are having here and answer the question below.
trying to start the docker by command
docker-compose up
but it's not responding, stuck after that.

previously it was running fine but was taking too much time to train sometimes never stopped

- Did you download a release or pull from Master? Which release?
yes, 0.9.4
- What operating system are you running?
windows 10
- Are you running locally or in the cloud?
locally
- Which browser are you using?
chrome
----

**Comment by wrathagom** [comment]
@saurabhbidwai Sorry for the start up troubles.

- Can you tell us which version of Docker and Docker Compose you have installed?
- Also how much memory do you have allocated to Docker?
- What is the console output when you do `docker-compose up`?

**Comment by dcalvom** [comment]
Hi @saurabhbidwai we were experimenting that issue in the past. I see you are using version 0.9.4. We recommend you to update to our latest release. You can export your agent using the `/export` endpoint in the API.

If you find any issue during your export let us know. A quick step by step guide would be:

1) Find your agent id: You can find this by going to the Articulate UI and selecting your agent from the drop-down, in the url you will see: `http://YOUR_IP_ADDRESS:3000/agent/ID`
2) With your ID, go to `http://YOUR_IP_ADDRESS:7500/agent/ID/export?withReferences=false`. And copy the output
3) Once you have that, then setup the latest version of Articulate. You can follow our (docs)[https://samtecspg.github.io/articulate/] to know how to run it.
4) When you have the latest version running, go to `http://YOU_IP_ADDRESS:7500/documentation` and search the `POST /agent/import` endpoint and paste you exported agent. You are going to have some compatibility issues, please post those here to help you out.

**Comment by wrathagom** [comment]
@saurabhbidwai can you tell us if you had luck getting things going?

**Comment by wrathagom** [comment]
never mind, closing as it looks like you got it running.
