### ISSUE TITLE
Endless requests to API server from browser

### ISSUE THREAD

**Issue by michaelmior** [samtecspg/articulate#283]
Running Articulate v0.11.0 on Ubuntu 18.04. When connecting remotely via Firefox, I see an endless string of requests to the following two URLs (as in, several times per second). Everything seems to be mostly working OK, but this seems like it's probably a bug.

http://my_hostname:7500/agent/1
http://my_hostname:7500/swagger.json

**Comment by wrathagom** [comment]
Slowed down the polling on our latest release. Waiting on a small change to implement sockets for this use case.
