### ISSUE TITLE
Up date npm i on articulate/ui/

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#284]
in articulate/ui/ you should update npm i on dockerfile articulate-ui

**Comment by dcalvom** [comment]
Hi @kurodenjiro could you add more info about this?

**Comment by wrathagom** [comment]
I imagine he's suggesting that we update the node version of the UI. Did you use the latest node version when you started working on the new UI, if so then we'll just close this and wait for that.

**Comment by kurodenjiro** [comment]
i got it close it thank
