### ISSUE TITLE
i got some erroor here . How can i fix it ?

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#287]
ERROR in ./~/dotenv-webpack/index.js
Module not found: Error: Can't resolve './src' in '/home/articulate/ui/node_modules/dotenv-webpack'
 @ ./~/dotenv-webpack/index.js 9:13-29
 @ dll reactBoilerplateDeps

ERROR in ./~/dotenv-webpack/dist/index.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/dotenv-webpack/dist'
 @ ./~/dotenv-webpack/dist/index.js 15:10-23
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/dotenv/lib/main.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/dotenv/lib'
 @ ./~/dotenv/lib/main.js 3:9-22
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in (webpack)/lib/node/NodeOutputFileSystem.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/webpack/lib/node'
 @ (webpack)/lib/node/NodeOutputFileSystem.js 5:9-22
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in (webpack)/lib/NormalModule.js
Module not found: Error: Can't resolve 'module' in '/home/articulate/ui/node_modules/webpack/lib'
 @ (webpack)/lib/NormalModule.js 96:16-33
 @ (webpack)/lib/NormalModuleFactory.js
 @ (webpack)/lib/Compiler.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in (webpack)/lib/node/NodeMainTemplateAsync.runtime.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/webpack/lib/node'
 @ (webpack)/lib/node/NodeMainTemplateAsync.runtime.js 9:2-15 25:3-16
 @ (webpack)/lib/node/NodeMainTemplatePlugin.js
 @ (webpack)/lib/node/NodeTemplatePlugin.js
 @ (webpack)/lib/WebpackOptionsApply.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/graceful-fs'
 @ ./~/graceful-fs/graceful-fs.js 1:9-22
 @ ./~/enhanced-resolve/lib/NodeJsInputFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/mkdirp/index.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/mkdirp'
 @ ./~/mkdirp/index.js 2:9-22
 @ (webpack)/lib/node/NodeOutputFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/loader-runner/lib/LoaderRunner.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/loader-runner/lib'
 @ ./~/loader-runner/lib/LoaderRunner.js 5:9-22
 @ (webpack)/lib/NormalModule.js
 @ (webpack)/lib/NormalModuleFactory.js
 @ (webpack)/lib/Compiler.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/graceful-fs/fs.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/graceful-fs'
 @ ./~/graceful-fs/fs.js 3:9-22
 @ ./~/graceful-fs/graceful-fs.js
 @ ./~/enhanced-resolve/lib/NodeJsInputFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/chokidar/index.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/chokidar'
 @ ./~/chokidar/index.js 3:9-22
 @ ./~/watchpack/lib/DirectoryWatcher.js
 @ ./~/watchpack/lib/watcherManager.js
 @ ./~/watchpack/lib/watchpack.js
 @ (webpack)/lib/node/NodeWatchFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/chokidar/lib/nodefs-handler.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/chokidar/lib'
 @ ./~/chokidar/lib/nodefs-handler.js 3:9-22
 @ ./~/chokidar/index.js
 @ ./~/watchpack/lib/DirectoryWatcher.js
 @ ./~/watchpack/lib/watcherManager.js
 @ ./~/watchpack/lib/watchpack.js
 @ (webpack)/lib/node/NodeWatchFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

ERROR in ./~/chokidar/lib/fsevents-handler.js
Module not found: Error: Can't resolve 'fs' in '/home/articulate/ui/node_modules/chokidar/lib'
 @ ./~/chokidar/lib/fsevents-handler.js 3:9-22
 @ ./~/chokidar/index.js
 @ ./~/watchpack/lib/DirectoryWatcher.js
 @ ./~/watchpack/lib/watcherManager.js
 @ ./~/watchpack/lib/watchpack.js
 @ (webpack)/lib/node/NodeWatchFileSystem.js
 @ (webpack)/lib/node/NodeEnvironmentPlugin.js
 @ (webpack)/lib/webpack.js
 @ ./~/dotenv-webpack/dist/index.js
 @ ./~/dotenv-webpack/index.js
 @ dll reactBoilerplateDeps

**Comment by wrathagom** [comment]
Those are related to the web pack build of our UI and they aren’t errors that block anything or cause the build to fail.

We’re working on a UI update that will address this.

Is it causing you any problems that you know of? We see them during our builds as well, but they do not impact functionality.

**Comment by kurodenjiro** [comment]
@wrathagom  i cant fix error now :(

**Comment by kurodenjiro** [comment]
@wrathagom  i understand hehe thank you so much

**Comment by wrathagom** [comment]
Glad I could help, let us know if you have any other troubles.
