### ISSUE TITLE
How to install local packages language spacy using pip as part of a docker build?

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#288]
my country is too lag to download form github so where is folder i can save to install language on rasa ?

**Comment by kurodenjiro** [comment]
RUN pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link en_core_web_md en 

is like RUN pip install en_core_web_md-2.0.0/en_core_web_md-2.0.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link en_core_web_md en 

i try but it's error not found file

**Comment by wrathagom** [comment]
So I take it that you moved past this problem?

**Comment by kurodenjiro** [comment]
close it thank
