### ISSUE TITLE
API Language validation needs to pull from settings

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#289]
i update my new language but it cant show how can i fix it ? 
![untitled](https://user-images.githubusercontent.com/26534614/43682626-77b393b0-98a4-11e8-9279-69ff804613cb.png)

**Comment by wrathagom** [comment]
Hey @kurodenjiro sorry that we didn't see this problem coming. For the time being you'll need to update this validation line in the API. https://github.com/samtecspg/articulate/blob/master/api/modules/agent/config/agent.validator.js#L169

We'll work on making the validation pull from the settings.

**Comment by kurodenjiro** [comment]
@wrathagom  i updated . how to rebuild images by docker ? . it's stille like that

**Comment by wrathagom** [comment]
Try

```
docker-compose down
docker-compose -f docker-compose.yml -f build-compose-override.yml build api
docker-compose up
```

**Comment by dcalvom** [comment]
Fixed in the new-ui, new-api
