### ISSUE TITLE
Clicking the Train Button Should immeadietly show train animation

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#294]
Right now it feels like the train button submits the training data, but the button isn't disabled and the training animation doesn't start until the agent status is updated to come back with a status of training. This works well locally, but remotely or when the polling of status is slowed this causes the user to not think training has begun and to try and click the button again.

**Comment by RussellSPG** [comment]
Even then, it seems that you need to refresh the page. Then hit the training button again, and its completed.

**Comment by wrathagom** [comment]
@RussellSPG this is in relation to something I was seeing on master, not on 0.11.1. Can you explain your problem in more detail? 

You should **never** have to refresh the page and **never** hit the training button more than once. if you do then you need to log an issue/bug.

**Comment by RussellSPG** [comment]
Sometimes When I hit the training button sometimes it just hangs showing the waiting even 10+ minutes. So If I hit the refresh button it will show its training, and be completed within 2-4 seconds

**Comment by wrathagom** [comment]
Fixed with aafc80c76885a17de05164dc4d259efb9d0728e2
