### ISSUE TITLE
 Can't import language vi from spacy.lang.

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#295]
![untitled](https://user-images.githubusercontent.com/26534614/43726546-a2f17a4e-99c9-11e8-8107-a15db1b63f57.png)
i got some error on this my language file https://drive.google.com/file/d/1d5boGovdupmynsgDRhHyk3E6pNhwFXff/view
Hope you can fix it for me

**Comment by wrathagom** [comment]
Does it work if you use it in spacy? without rasa or Articulate.

**Comment by kurodenjiro** [comment]
@wrathagom yes

**Comment by wrathagom** [comment]
Does your model have all of these pieces? Vocabulary, syntax, entities, vectors?

**Comment by wrathagom** [comment]
Also, is that the full Rasa stack trace?

**Comment by kurodenjiro** [comment]
@wrathagom hope ypu can fix it on rasa

**Comment by wrathagom** [comment]
Can you tell me how you installed it, what command you used?

**Comment by kurodenjiro** [comment]
FROM alpine:3.7


ENV RASA_RELEASE=0.12.3.b \
    RASA_NLU_HOME=/app \
    RASA_NLU_PYTHON_PACKAGES=/usr/local/lib/python2.7/dist-packages

# -----below from https://github.com/abn/scipy-docker-alpine
# Linking of locale.h as xlocale.h
# This is done to ensure successfull install of python numpy package
# see https://forum.alpinelinux.org/comment/690#comment-690 for more information.

RUN apk --update add --virtual scipy-runtime python py-pip \
    && apk add --virtual scipy-build \
        build-base python-dev openblas-dev freetype-dev pkgconfig gfortran \
    && ln -s /usr/include/locale.h /usr/include/xlocale.h \
    && pip install --no-cache-dir numpy \ 
#    && pip install --no-cache-dir matplotlib \
    && pip install --no-cache-dir scipy \
#    && apk del scipy-build \
    && apk add --virtual scipy-runtime \
        freetype libgfortran libgcc libpng  libstdc++ musl openblas tcl tk \
    && rm -rf /var/cache/apk/*
# -----above from https://github.com/abn/scipy-docker-alpine
#  Watchout for the 'apk del' above - it will delete that package _AND_ anything --virtual'ed with it

RUN apk add git bash --update-cache

RUN wget -O - http://pantado.edu.vn/rasa_nlu-0.12.3.b.tar.gz | zcat | tar xvf -
RUN mv rasa_nlu-${RASA_RELEASE} ${RASA_NLU_HOME}

WORKDIR ${RASA_NLU_HOME}

RUN sed -i '/matplotlib/d' alt_requirements/requirements_bare.txt

#only turn on if you want mitie too (in which case turn on the wget below too
#RUN pip install -r alt_requirements/requirements_full.txt

#just install the spacy stuff
RUN pip install -r alt_requirements/requirements_spacy_sklearn.txt

RUN pip install -e .
RUN pip install pyvi 
RUN pip install http://pantado.edu.vn/en_core_web_md-2.0.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link en_core_web_md en
RUN pip install http://pantado.edu.vn/de_core_news_sm-2.0.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link de_core_news_sm de
RUN pip install http://pantado.edu.vn/fr_core_news_md-2.0.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link fr_core_news_md fr
RUN pip install http://pantado.edu.vn/es_core_news_md-2.0.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link es_core_news_md es
RUN pip install http://pantado.edu.vn/pt_core_news_sm-2.0.0.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link pt_core_news_sm pt
RUN pip install http://pantado.edu.vn/vi_core_news_md-2.0.1.tar.gz --no-cache-dir > /dev/null \
    && python -m spacy link vi_core_news_md vi


RUN pip uninstall msgpack-python -y
RUN pip install msgpack-python==0.5.2

#only turn on if using mitie
# RUN wget -P data/ https://s3-eu-west-1.amazonaws.com/mitie/total_word_feature_extractor.dat

RUN cp  sample_configs/config_spacy_duckling.yml ${RASA_NLU_HOME}/config.yml

EXPOSE 5000

ENTRYPOINT ["./entrypoint.sh"]
CMD ["start", "--path", "/app/projects", "-c", "config.yml", "--max_training_processes", "4"]
