### ISSUE TITLE
New Feature - Add a custom Action on an Intent

### ISSUE THREAD

**Issue by jechazelle** [samtecspg/articulate#297]
I would like to know, how can I set a custom Action on an Intent ?

Maybe it's a new feature : 

<img width="884" alt="new_feature_action" src="https://user-images.githubusercontent.com/6713790/43911700-6d72c40c-9c00-11e8-8455-a751b3ebc328.png">

To have in response  **"action": "user_asks_color"**

```
"results": [
      {
        "domain": "Personality",
        "project": "TestBot",
        "entities": [],
        "model": "Personality_just_er_c1b8cd7c-5f8a-5bfe-8650-e464208564e7",
        "intent": {
          "confidence": 1,
          "name": "User asks a color"
          "action": "user_asks_color"
        },
        "elapsed_time_ms": 233.009869,
        "domainScore": 0.8294703084715257
      }
]
```

Currently, it's possible with Dialogflow : 

![feature](https://user-images.githubusercontent.com/6713790/43952532-8295481e-9c96-11e8-9bf7-80744d7b45d3.jpg)

**Comment by wrathagom** [comment]
added in new UI, won't add too old.
