### ISSUE TITLE
Add web chat widget connection

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#300]
### Feature Request

There's a React based chat widget, which we should add to our Ubiquity connections. I believe it uses sockets.  https://github.com/Wolox/react-chat-widget

There was a fork, which connected to Rasa, but not certain it's status: https://github.com/mrbot-ai/rasa-webchat

**Comment by wrathagom** [comment]
@dcalvom I'll go ahead and put this one in for this milestone. I'm assuming it's a web-socket ubiquity channel. Which then can be configured to connect to this other open source project.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/a863636edfd1c3feb0a09be6448e0f5d8221c2c7
