### ISSUE TITLE
Unable to Update the Domain name for a Intent

### ISSUE THREAD

**Issue by BHARATHPABBA** [samtecspg/articulate#303]
I couldn't update domain name for a existing intent.

**Comment by RussellSPG** [comment]
Should work now that the UI is updated. Click on:

1. Domains
2. Look for the domain you want to edit
3. On the right there is a 3-dotted symbol that appears, and select Edit.

Let us know if thats not working ;)

**Comment by wrathagom** [comment]
For the moment we are not going to support changing domains. We are in the process of a significant UI re-write and our code would be incompatible with that re-write. We will make an effort to add this to that new version.
