### ISSUE TITLE
when i highlight entity in a sentence  in page 5 it comes back to page 1

### ISSUE THREAD

**Issue by BHARATHPABBA** [samtecspg/articulate#304]

**Comment by BHARATHPABBA** [comment]
In the intent editor where are set of sentences shown, when I update a intent in one page 5 it goes back to page 1

**Comment by wrathagom** [comment]
Fixed with 3bf5903ce55247e4a1402ce30067a2538ee0ff68, but not in a release yet.

**Comment by wrathagom** [comment]
Fixed in 0.11.2 release
