### ISSUE TITLE
 UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#305]
rasa_1      | 2018-08-18 16:04:23+0000 [-] 2018-08-18 16:04:23 ERROR    rasa_nlu.train  - Failed to
rasa_1      | 2018-08-18 16:04:23+0000 [-] Traceback (most recent call last):
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "rasa_nlu/train.py", line 120, in do_train_in_work
rasa_1      | 2018-08-18 16:04:23+0000 [-]     component_builder)
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "rasa_nlu/train.py", line 149, in do_train
rasa_1      | 2018-08-18 16:04:23+0000 [-]     interpreter = trainer.train(training_data, **kwargs)
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "rasa_nlu/model.py", line 190, in train
rasa_1      | 2018-08-18 16:04:23+0000 [-]     **context)
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "rasa_nlu/extractors/crf_entity_extractor.py", lin
rasa_1      | 2018-08-18 16:04:23+0000 [-]     self._train_model(dataset)
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "rasa_nlu/extractors/crf_entity_extractor.py", lin
rasa_1      | 2018-08-18 16:04:23+0000 [-]     self.ent_tagger.fit(X_train, y_train)
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "/usr/lib/python2.7/site-packages/sklearn_crfsuite
rasa_1      | 2018-08-18 16:04:23+0000 [-]     trainer.append(xseq, yseq)
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "pycrfsuite/_pycrfsuite.pyx", line 312, in pycrfsu
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "stringsource", line 48, in vector.from_py.__pyx_c
rasa_1      | 2018-08-18 16:04:23+0000 [-]   File "stringsource", line 15, in string.from_py.__pyx_c
rasa_1      | 2018-08-18 16:04:23+0000 [-] UnicodeEncodeError: 'ascii' codec can't encode character
rasa_1      | 2018-08-18 16:04:23+0000 [-] 2018-08-18 16:04:23 WARNING  rasa_nlu.data_router  - [Fai
rasa_1      | 2018-08-18 16:04:23+0000 [-] ]
rasa_1      | 2018-08-18 16:04:23+0000 [-] "172.18.0.3" - - [18/Aug/2018:16:04:23 +0000] "POST /trai
api_1       | Debug: internal, implementation, error

**Comment by wrathagom** [comment]
Can you test https://github.com/samtecspg/articulate/releases/lates to let us know if that fixed your encoding issues?

**Comment by wrathagom** [comment]
Let us know if this is still an issue, but if I remember correctly you changes Rasa version and it fixed it.
