### ISSUE TITLE
Follow-up Intents

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#310]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
- What operating system are you running?
- Are you running locally or in the cloud?
- Which browser are you using?

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

Follow-up intents. I'm guessing this is already on the road map, but will be useful. 

If possible provide the use case for the feature and how you would use it. 
For my case,  I would like a follow up intent where the bot asks the user if he's sure of something e.g. ("are you sure you don't want to order?"), Because a user may change his mind either way when conversing with the bot.

**Comment by wrathagom** [comment]
This is being discussed in #223
