### ISSUE TITLE
Text prompts are not saved in slots

### ISSUE THREAD

**Issue by ferasodh** [samtecspg/articulate#312]
I'm using the latest release of articulate and running locally (chrome browser & Mac OS 10.13.6).  Text prompts are not saved in slots as shown in the attached screenshot.

![screen shot 2018-09-06 at 2 52 57 pm](https://user-images.githubusercontent.com/1456776/45155849-f839d680-b1e4-11e8-8c29-af6049dd416f.png)

**Comment by wrathagom** [comment]
I can confirm that this is working for me as intended on the latest release. You can have multiple prompts, so after typing them in you need to hit enter. They should then show up as a pill:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1779894/45156269-b476ab00-b1ab-11e8-88a8-a3475a82df37.png">

Once you've got that be sure to remember to hit update at the top of the page.

Let me know if that doesn't solve your problem.

**Comment by ferasodh** [comment]
Thanks Caleb,

This solves my problem but I think the system should warn the user in this cases

**Comment by wrathagom** [comment]
Agreed, we just had this conversation a few days ago. We do give a warning when navigating away from the page with unsaved content, now we just need to add a warning when you hit update if you still have active inputs.

**Comment by ferasodh** [comment]
agreed I will close this issue
