### ISSUE TITLE
I'm still learning problem

### ISSUE THREAD

**Issue by ilysorc** [samtecspg/articulate#314]
I trained my bot but always returns I'm still learning response. Can you help me? 

- Pulled from Master.
- Linux Docker Container.
- Locally running.
- Chrome version 68.

![capture](https://user-images.githubusercontent.com/2563790/45338347-668be980-b595-11e8-9c48-32bb3cdaae53.PNG)
![containers](https://user-images.githubusercontent.com/2563790/45338348-67248000-b595-11e8-9a85-1c17a5927b1b.PNG)

**Comment by ilysorc** [comment]
Sorry i opened issue to false repository. Can you close this issue please.

**Comment by Oceania2018** [comment]
Should go to [BotSharp](https://github.com/Oceania2018/BotSharp).

**Comment by wrathagom** [comment]
@ilysorc are you saying that you figured your problem out? I see that your using Botsharp, which is great.

However I also see that you're not using the interface correctly. Please see our tutorial here for getting started with Articulate: It should work whether you are using Botsharp or Rasa.

https://blog.spg.ai/bot-basics-with-articulate-e5fe975cee88

**Comment by ilysorc** [comment]
@wrathagom yes i figured my problem thanks for your response.
