### ISSUE TITLE
Text Prompt issue

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#315]
- Did you download a release or pull from Master? Which release?
 --> Downloaded it from here : https://github.com/samtecspg/articulate/releases/download/v0.12.0/articulate-v0.12.0.zip

- What operating system are you running?
--> Linux Fedora 28 x64.

- Are you running locally or in the cloud?
--> Running Locally.

- Which browser are you using?
--> Chrome/Firefox mostly chrome
---------------------------------------------------------------------------------------------------------------------------
Hi Guys, I observed there were similar problems in here,  but I could not figure out exactly what could be wrong in my case.
I am attaching the screenshot of my case below:

![screenshot from 2018-09-11 11-56-50](https://user-images.githubusercontent.com/40358189/45356121-50445480-b5ba-11e8-8d04-ddf9bccf027c.png)

So I can not access the return value from the user. I think I might mixed up the Agent Responses value. I have two in there for the test only.
I would really appreciate some help with this.
Thank you guys.

**Comment by wrathagom** [comment]
Hey @bkurowski check out this blog post here and see if it helps you figure out some of the handlebars usages: https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241

In your case though you need to change how you reference slots in your responses: `{{slots.[sampleName_Prompt].value}}`

**Comment by bkurowski** [comment]
![screenshot from 2018-09-11 13-41-01](https://user-images.githubusercontent.com/40358189/45360964-dff0ff80-b5c8-11e8-8e7b-cc4f2b8bdca6.png)

I am still having the same trouble. Not sure what could be causing it to act this way .

**Comment by wrathagom** [comment]
Looks like there were a couple of problems then. Those are fallback responses when the agent doesn't have enough confidence in what the user is saying.

Do you have an intent trained with saying similar to `My name is Jonny?`

**Comment by bkurowski** [comment]
No. Do i need to create separate intent with sample answers ??

**Comment by wrathagom** [comment]
Not necessarily, but you do need to teach the bot what the expected response is to those prompts and if they have entities you'll need to highlight those entities in the user sayings. Or use a a system entity for names. Maybe take a look at our Bot Basics tutorial: https://blog.spg.ai/bot-basics-with-articulate-e5fe975cee88

**Comment by wrathagom** [comment]
@bkurowski Articulate keeps track of conversation history and an use that to fill slots, what we refer to as context.

If you are trying to test different ways of starting a conversation click on the three dots besides the chat input and click `Reset Session` that will clear the chat window and the context.

**Comment by wrathagom** [comment]
@bkurowski see if this answers your questions: https://blog.spg.ai/how-our-chatbot-chats-b5b633fec376

**Comment by bkurowski** [comment]
So far all good. Thanks for your help. Ive more questions about the actual background of that system. I hope it is OK if ill leave email to you with some questions. 
Thanks.

**Comment by wrathagom** [comment]
of course you can e-mail. Though it's easier for my team to help me respond if communication is done here or on Gitter. But I will look for your e-mail.
