### ISSUE TITLE
THP - Redis ERROR

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#321]
- Did you download a release or pull from Master? Which release?
    Using release : 0.11.2
- What operating system are you running?
    Windows 10
- Are you running locally or in the cloud?
   Locally
- Which browser are you using?
   Firefox

----------------------------------------------------------------------------
Hey guys. My redis ran into problem and I'm not really sure how to tackle that problem inside Windows 10. 
![image](https://user-images.githubusercontent.com/40358189/45559566-b8a16900-b83a-11e8-8e73-ae6234d3f79d.png)
"Transparent Huge Pages" --> How can i disable this bit in Windows 10 ?

**Comment by wrathagom** [comment]
@milutz you looked into this right and it had more to do with Docker if I remember right.

**Comment by bkurowski** [comment]
It seems like it is Docker problems i have observed. I did not have such problems when i was working from linux. But now i have to use windows ... It would be cool if someone has resolved this problem before.
Thanks !

**Comment by wrathagom** [comment]
A few pertinent links:
- https://github.com/docker-library/redis/issues/55
- https://forums.docker.com/t/disable-transparent-huge-pages-thp/17240

**Comment by wrathagom** [comment]
@bkurowski I may have mistakingly glossed over your real issue. To be clear we ALL get the Redis warning when we start up Articulate unless we are running directly on a linux server and have made the appropriate changes there.

I don't think your problem has anything to do with THP.

The real problem seems to be with your append only file. Did you try manually editing it, copying it, moving it?

**Comment by bkurowski** [comment]
Hey sorry for late reply, i did not edit any files manually. If its not THP, it is docker problem so. Seems like i can not run it at all having windows OS ;/ .... I downloaded fresh version of 0.12.1, and it still did not run with the new version. Is the only option to come back to Linux ? As when i started using articulate on Windows all these problems started.

**Comment by bkurowski** [comment]
Now i am getting completely different error after restarting .. 

<img width="947" alt="articulate-prob" src="https://user-images.githubusercontent.com/40358189/45597279-a867c600-b9c1-11e8-835a-2c3d49ea1ae2.PNG">

Not sure how to fix that.

**Comment by wrathagom** [comment]
Are you using the docker QuickStart terminal? Can you try just a normal command prompt or power shell?

**Comment by bkurowski** [comment]
The picture you see above is ran through Git Bash terminal, but ordinary cmd or power shell gets errors too. Now these. 
<img width="948" alt="capture" src="https://user-images.githubusercontent.com/40358189/45597638-372b1180-b9c7-11e8-94ab-bfc082b8ff75.PNG">

Btw same instance of files (copy/paste) to linux and it works from first hit.

Sorry i did not know its gonna be so much hassle when OS change occur.

**Comment by wrathagom** [comment]
Have you tried a fresh clone on Windows?

**Comment by wrathagom** [comment]
Have you tried restarting Docker? Also, which version of Windows did you say this was?

We have user and team members who regularly use Articulate on Windows 10 and 7. So it’s possible. Though especially on Windows 7 the process can be painful.

Caleb

**Comment by bkurowski** [comment]
I restarted Docker & machine few times.
It is Windows 10 x64.
Docker and windows are up to date.
I thought win 7 would the less problematic in this case.

**Comment by wrathagom** [comment]
Are you running Docker toolbox or Focker for Windows.

HVe you tried running with the `COMPOSE_CONVERT_WINDOWS_PATHS=1` env variable set?

**Comment by bkurowski** [comment]
Running Docker for Windows.
And I have set the variable at the start.
I will reinstall docker and update first thing in morning.

**Comment by bkurowski** [comment]
After reinstalling Docker, everything came back to normal. But it still seems not to be stable, while training the bot, Error comes up straight after pressing train. (Not every time). 
Best option will be to comeback to Linux, thank you for your time and help.
I observed I have less problems using Linux.

Best Regards,
Bart

**Comment by wrathagom** [comment]
What option comes up after training? How much memory do you have allocated to Docker machine? Keep in mind that Rasa/Articulate need a minimum of 4Gb even for basic configurations. I believe the default Docker machine config is only 1-2G.

**Comment by bkurowski** [comment]
The console says nothing after hitting train it comes as Error instead of green state Ready. Without taking time while training as usually, so it changes the state straight away without waiting.. 
I have allocated 6 GB of memory.

**Comment by wrathagom** [comment]
Are you using the generate extra training data anywhere? There was a known bug with this fixed in 0.12.1 that had symptoms as you describe.

**Comment by bkurowski** [comment]
I observed that error a while back, so i decided not to use it. 
No I am not using any extra training in there.

**Comment by bkurowski** [comment]
Just to update, error is fixed. Not sure what it was but the error was saved inside cache of Docker which was not allowing me to run Articulate. After clearing cache / reinstalling Docker everything came back to normal, but only with a fresh version of Articulate.
As the previous version that I was using still contained that error.

Thanks for help ! 

BR,
Bart
