### ISSUE TITLE
When Formatting Webhook payload is it possible to return any handlebar errors

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#324]
See #320, right now the server just throws a 500 error and doesn't return any useful information.

**Comment by wrathagom** [comment]
Rather than only return successes we should return the errors as well and make the developer handle them. For example DELETEing a non-existent item might throw a value other than 200 and the developer might want to return a message saying `We couldn't delete that item because it doesn't exist.`

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/6e5a4cb09c11b06b4336c56a567128818958d2f0 

Please check if you agree with this solution

**Comment by wrathagom** [comment]
@dcalvom success looks all good, but the statusCode is returned when there are errors.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/bb904d3406534b8af5cb61fb73359326afb968e7
