### ISSUE TITLE
Working with stories/Dialog

### ISSUE THREAD

**Issue by ATS-Official** [samtecspg/articulate#326]
@wrathagom I have a challenge related to building a dialogue or stories, how would you recommend doing this with Articulate? considering the pizza order example, if i wish to up-sell (would you like to order a drink) or ask more options related to toppings (full, 50:50 etc) how would that work here?

**Comment by wrathagom** [comment]
The drink or upsize could just be an additional slot, but that's more of a hack. The toppings on half would be really hard with current level of Dialogue supported.

We have a planned feature that we are designing right now called `Modifier Intents` - we need to work on the name a bit - that will address both of these concerns to some extent.

**Comment by wrathagom** [comment]
#223 needs to be able to handle this request.
