### ISSUE TITLE
Any entity?

### ISSUE THREAD

**Issue by mike23333** [samtecspg/articulate#328]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
- What operating system are you running?
- Are you running locally or in the cloud?
- Which browser are you using?

----
Hi, great app. Very well done. I was wondering what do I use for "any entity." Is there one? Where it grabs whatever they say in response like dialogflow has. Because I want to use it for names so I can get first and last name.

Thanks for your help!

**Comment by wrathagom** [comment]
Hey @mike23333 we don't have a `sys.any` like Dialogflow though you're not the first person to ask.

If you're just after names. I would recommend the `sys.spacy_person` system entity.

**Comment by mike23333** [comment]
Thanks for the quick reply. Yes I just need it for names. Ok will use that. Does the sys.spacy_person entity get first and last name? And does it get hard to spell names too and all names?

**Comment by wrathagom** [comment]
We've had good luck with it, but certainly you should try it in your use case.

**Comment by mike23333** [comment]
Ok cool. I appreciate your help.
