### ISSUE TITLE
Answer button inside chat window.

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#329]
Hi Guys ! 
Just a quick Articulate ability question.
I am producing a chat product which needs to be able to produce buttons inside the chat window just like below. Buttons works as an user answer. 

![articulate_question](https://user-images.githubusercontent.com/40358189/45811079-1531d780-bcc4-11e8-9a0b-925251e2bf8c.png)

I am able to do it my self from scratch, but my question is is there anything like that, that Articulate already has built in ?. 

Thanks for answers ! 

Bart.

**Comment by wrathagom** [comment]
what delivery platform re you targeting: facebook, Slack, custom, etc?

**Comment by bkurowski** [comment]
It is a custom platform i am using.

**Comment by wrathagom** [comment]
@spg-matt this is a ubiquity type feature I know you are already working on.

@bkurowski we don't support this yet, but you can use the response format JSON box to pass back some JSON to your custom platform and use that to create the box. Or you can wait on us to support it natively in Ubiquity.

**Comment by bkurowski** [comment]
Oh yes I have sorted this out before, actually forgot to mention it here. 
That is alright just asked because it would cut out few bits of work. 
Anyway thanks a lot !
