### ISSUE TITLE
Working with the entity

### ISSUE THREAD

**Issue by pnija** [samtecspg/articulate#332]
@wrathagom I have followed this video https://www.youtube.com/watch?v=tXCYQ4BTjD0&feature=youtu.be for tarining the bot. I have added the entites.  The issue is - for example consider this dialog "I want to book an appoinment on monday at 4pm" in this statement there are two slots one for date and time. If user only says he want to book appoinment on monday without time then ideally the bot should ask the text prompt which i configured in the slots( what time works for you please say AM or PM after time). But it does not ask always. sometimes it fail to ask the question in the text prompt. Why it not always ask the questions for the slot added? this is happening for all slots which is added. I'm attaching the Gdrive video link with this post. Please refer the video. What i'm doing wrong here? Please list the misconfiguration if you have found any. Thank you.

https://drive.google.com/file/d/1lvmEwt-oSGFQumbPrqz_EnSkuwgXXjg4/view

**One** more issue:

Our application is booking appoinment through the bot. From the screenshot you can see that i'm configured slots for day and time. So when users asks "I want to book appoinment" then bot will ask for the day when user user replies one of the week days(monday, tuesday...) it will accpect. After the day it will ask for the time then sometimes the times  like (4am, 4 am, 4AM, 4 AM) not recognizing but it will accepect the 4 pm or 4PM. What will be the possible issue? 

Another issue regarding the time entity is when i'm add "I want to book appointment on monday at 4am" it does not automatically highlight the time entity and also i can't highlight the time entity. This is the reason may be it does not recoganize the time entity(4am, 4 am, 4 AM) when users says. It working for PM only issue in AM. I have attached another video showing that it not highlighting the time enitity. 

Please help us to identify the issue.

https://drive.google.com/file/d/1rUsfSdO4WSoPpskmX-W9GSM7EEtK0iK0/view?usp=sharing

![g1](https://user-images.githubusercontent.com/7920806/46414940-e09d3180-c741-11e8-92fd-c924487beeb7.png)

![g2](https://user-images.githubusercontent.com/7920806/46414941-e09d3180-c741-11e8-99bf-83b0cc9404a7.png)

![g3](https://user-images.githubusercontent.com/7920806/46414942-e09d3180-c741-11e8-8898-6049609f5934.png)

![g4](https://user-images.githubusercontent.com/7920806/46414944-e135c800-c741-11e8-9b29-94affc0b5ec8.png)

Thank you.

**Comment by ewoo** [comment]
@wrathagom @dcalvom it seems @pnija is experiencing two separate issues. The first (one word replies to slot values) requires _intent modifiers_ and the second is a bug I've also seen--where no entities are displayed in the drop-down when the user selects a desired entity from their sample utterance.

**Comment by wrathagom** [comment]
Sorry @pnija for the complete oversight here. I can't remember if I was able to help you with this one at all on Gitter or not. Did you get past your issues?

**Comment by dcalvom** [comment]
Closed since there has not been any recent activity. Please open a new issue for related bugs.
