### ISSUE TITLE
A Duplicate button in the Agent Responses list would be very useful

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#334]
### Feature Request
I find myself often needing to edit existing Agent Responses (especially to correct handlebars syntax errors). Since a user cannot Edit the existing responses, it would be handy to have a "Duplicate" button that would copy the responses content into the input field above. This would be a time saver! (See image)

![7298606b1916b1f32c2394d6f3bcbd89 _image 202018-10-04 20at 209 50 04 20am](https://user-images.githubusercontent.com/278197/46478738-9bb5e100-c7bb-11e8-92cc-b2e18555f582.png)

**Comment by wrathagom** [comment]
Closing in favor of #409 We'll consider it there for the new UI.

**Comment by ewoo** [comment]
Reopening for new UI. #409 seems more effort to create. Until then...

**Comment by ewoo** [comment]
@broham89 copy button needs an icon.

**Comment by dcalvom** [comment]
I will use the same icon for copy sayings in the review page 
![image](https://user-images.githubusercontent.com/7228045/52977804-507c2380-3394-11e9-9116-be955a14396c.png)

**Comment by broham89** [comment]
[icon-copy.svg.zip](https://github.com/samtecspg/articulate/files/2877656/icon-copy.svg.zip)
@ewoo Daniel wanted me to recreate/update a better copy icon ^

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5b729f9035b101edb3e4261461fb22bd84b4e23b
