### ISSUE TITLE
UI 2.0 UX issues (Draft)

### ISSUE THREAD

**Issue by broham89** [samtecspg/articulate#335]
### Issues
1. (Debatable) When in Agent page, the user clicks on an Agent and throws them to the sayings tab instead of the agent tab. 

 2. When a user hovers over a title input it will pop up the tool-tip. Possibly add the link examples 

3. no need for a back arrow button if there isn't a slide animation

4. Categories should first say "Start here" Placeholder

5. When a user switches to a different category it will also switch all sayings to said category. So in a sense category dropdown would be a filter.

6. Action Page: after the user makes a name for his action it update in h1

7. Action page: maybe have a problem with having the finish button at response tag/page.

**Comment by wrathagom** [comment]
Closing in favor of individual issues.
