### ISSUE TITLE
Expose Articulate

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#336]
### Issue

- Did you download a release or pull from Master? Which release?
       - 0.12.3 - Release
- What operating system are you running?
       -VM(Ubuntu) On Win 10
- Are you running locally or in the cloud?
       -Locally
- Which browser are you using?
       -Chrome
----

### Feature Request

Hey ! I was trying to run Articulate on Virtual Machine on Ubuntu which runs smooth.
I was trying to forward ports so I could access Articulate from main OS Win 10.

What happens, is when I will forward ports i can access the page from windows but it says that the head is missing. Trouble communicating with API. 

![image](https://user-images.githubusercontent.com/40358189/46615486-31c96e80-cb10-11e8-9f1e-3713b2d057ce.png)

I am not sure did I miss some step of configuration ? 
Ports were forwarded using Virtual Box.

BTW: Articulate works great on Ubuntu system. It looses head when connecting through windows.

Thanks

Best Regards

**Comment by milutz** [comment]
Hi @bkurowski !

Can you tell me which ports you forwarded and how you did it (config (or worst case screenshots) would be helpful)

Thanks!

**Comment by bkurowski** [comment]
Sorry for not clear description, let me explain please. 
What I did is, I started Ubuntu in Virtual Box sitting on Windows 10.
On Ubuntu I run Articulate engine. For which i wanted to forward ports, so I could access Articulate from the main system Windows 10.

The forwarding of ports took place in virtual box see below.

![port_forwarding](https://user-images.githubusercontent.com/40358189/46656929-0b0a4700-cba7-11e8-8d35-620cb9973a2c.PNG)

I can access the page on both Ubuntu and Windows but on Windows it appears the connection is not 100 % good, as the "Head gets missing".  See screen below for Windows.

![missing_head](https://user-images.githubusercontent.com/40358189/46657227-b4e9d380-cba7-11e8-924c-1409fd3d23e3.PNG)


Where as on Ubuntu I can access Articulate and "Head is not missing".

![linux_side](https://user-images.githubusercontent.com/40358189/46657351-f8444200-cba7-11e8-9ce3-a40b0ba3c4cf.PNG)



Thank you.

**Comment by bkurowski** [comment]
Thank you for your reply ! 
So i have tried not to remap the port as you advised but nothing has happened.
See below.

![image](https://user-images.githubusercontent.com/40358189/46729794-3f046b80-cc7e-11e8-8cea-9755a44d8081.png)

It is still missing head afterwards.

Also setting the URL API in yml file did not help too, screenshot below.

![image](https://user-images.githubusercontent.com/40358189/46729751-21370680-cc7e-11e8-848c-d37fcc179b1e.png)

Would there be any other reason for it not to work ? 

Thank you, for your reply ! 

Bart.

**Comment by milutz** [comment]
@bkurowski it will be a few hours until I can get back to you on this (because I need to test the pattern myself) but I should have 2 or three steps to debug a connection issue.   Will post soon

**Comment by bkurowski** [comment]
Thank you really much ! Waiting for your reply,
Thank you !

**Comment by dcalvom** [comment]
@bkurowski what commando are you using to start the docker containers? @wrathagom isn't necessary to specify that API_URL in the command to start the docker, given that is an "external" server.

**Comment by wrathagom** [comment]
He was already advised to do that by Mike, but I think the IPs are confused.

**Comment by bkurowski** [comment]
Hi @wrathagom.
 TBH i am a bit confused too. 
But according to this page: https://searchservervirtualization.techtarget.com/definition/guest-virtual-machine-guest-VM 

It seems correct i think.
But  IP: 10.0 .... is Ubuntu system which in this example is Guest.
IP: 159.. is the host machine. On which the main OS is (Win 10 :( ) 
When I had it setup "Other way around" it was not even triggering the page at all.

Also, the docker for windows is giving me constant errors and is way slower. So I decided to install Virtual Box to run Ubuntu in it and start Articulate there. I will need to expose articulate soon anyway, so it is a good practice too. I know i could of just get Linux and install it there. But according to the conditions i have to work, I only have Win 10 machine available. 

And yes I did it through the terminal too. I thought i can just specify the URL in yml config file.

If I am mistaken please correct me, as I am not 100 % sure about that.

Thank you

**Comment by bkurowski** [comment]
Ok guys ! I got it ! .
I mistaken the IP, the one to run with API URL.
Thanks for your help.

BR,
Bart

**Comment by milutz** [comment]
@bkurowski does "I got it !" mean it's working for you now?

**Comment by bkurowski** [comment]
Sorry, yes it is working now.

**Comment by milutz** [comment]
No need to be sorry its working! :)
Great to hear! - I'll close this issue then.
