### ISSUE TITLE
Text Format

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#337]
It is not an issue but a simple question, as I can not find how to format the text correctly the way I want.
If I would like the chat content to look more readable, how can I add "New Line" in Agent Response something like "\n" or <"br"> is not working. 
Sorry as I am still learning on Articulate abilities

Thank you guys for answers,

Best Regards,
Bart

**Comment by milutz** [comment]
@bkurowski thats a good question (as-in I don't know the answer :) ) 

@dcalvom do know if we have a way to do that today?

**Comment by dcalvom** [comment]
Hi, @bkurowski I'm testing different ways to do it in Articulate. I will let you know if I can figure out, but I'm almost sure that this is not going to be possible in the Articulate UI.

But, what I would like to tell you is that this depends on the channel you are going to use to deliver messages to the user. I mean if it is going to be Facebook Messenger, SMS or whatever platform you need to know what is the right way to send a new line into these channels.

**Comment by bkurowski** [comment]
Thank you for your answer, I am using custom messaging platform. 
That means I have to figure out the way for "New Line" in my platform.

It would be great if Articulate would actually have such an option.

Thank You,

Best Regards.

**Comment by wrathagom** [comment]
@spg-matt this is more a question for you, do any of the delivery platforms we are targeting allow new lines? Certainly slack would, how about Facebook? What syntax in their payloads denotes a new line.

**Comment by dcalvom** [comment]
Closed since there has not been any recent activity. Please open a new issue for related bugs.
