### ISSUE TITLE
"train" button not working 

### ISSUE THREAD

**Issue by salmanef** [samtecspg/articulate#338]
hello , 
i have installed docker using docker-compose up. it was working fine last time i used it yesterday . the issue is that train button has faded out and when i update some intents or entities ,i cant click the train button and train the bot.
---i am running it on windows 10 pro 64 bit
---i am running it locally

thanks

**Comment by wrathagom** [comment]
@salmanef are you still having troubles? Can you tell me how much memory you have allocated to Docker?

**Comment by wrathagom** [comment]
Also are there any errors in the logs? `docker-compose logs`

**Comment by salmanef** [comment]
> 
> 
> @salmanef are you still having troubles? Can you tell me how much memory you have allocated to Docker?

@wrathagom thankyou for your prompt response .....i still don't know what went wrong but i re-installed articulate and its working fine now...by the way i allocated 2gb memory  to docker

**Comment by wrathagom** [comment]
2gb is likely not enough, we recommend a minimum of 4G for small agents. Let us know if you have more issues.
