### ISSUE TITLE
add login screen 

### ISSUE THREAD

**Issue by kurodenjiro** [samtecspg/articulate#339]
I want to login screen on artilcule how can i do it ?

**Comment by milutz** [comment]
Hi @kurodenjiro !

We have a blog post that talks about how to wrap Articulate to add a login screen here: https://blog.spg.ai/basic-access-restrictions-for-articulate-58e77c931ca3

Jump on our Gitter: https://gitter.im/samtecspg/articulate if you have any troubles with it
