### ISSUE TITLE
Please make last selected Domain stick on Create Intent form!

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#342]
### Feature Request
It's a huge pain in the butt to select the domain again when saving an intent. Please make the Create Intent form remember the last selected domain. Thank you!

**Comment by wrathagom** [comment]
Given that we're replacing the old UI eventually, I would say this one only get's done if it takes less than an hour.

Maybe @ewoo we should move you to the new UI so you can start poking holes in it's usability.

**Comment by wrathagom** [comment]
Wont fix in old UI, similar issue covered by #389 for new UI.
