### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by BotGenius** [samtecspg/articulate#349]
Hello, i was in contact with a supporter on your facebook.
Asking if there were a possibility for a Tensorflow version, which i was told there was :) 

I was told to make a issue here, and then i would receive the dockerfile code :) 

If there are any information you need from me please say, tho its hard to deliver information since this isn't a "Issue" more of a "Request" if possible :) 

Have a nice day, hope to hear from you soon :)

**Comment by wrathagom** [comment]
Hey @BotGenius we're working out how best to get the Dockerfile stuff committed and documented, shouldn't need more than another day or two to pass it off to you.

**Comment by BotGenius** [comment]
Thanks for the response :) 

I will wait for a bit then - when its up - if you have the time for it ofc. i wouldn't mind if you replied at that time :) - Since we will keep working with the version without to test the limits of sklearn :) 

Do you know if Tensorflow and Sklearn can run at the same time ? :)

**Comment by dcalvom** [comment]
@wrathagom don't we have our TF already on master?

**Comment by wrathagom** [comment]
master has been updated to use TF by default with 
https://github.com/samtecspg/articulate/commit/f620da3c321996f869abc96e80c803d8e2743b4d

A new release with this should be coming out end of this week or early next... hopefully.
