### ISSUE TITLE
Can't update intent with sys.duckling_time

### ISSUE THREAD

**Issue by cjhurst** [samtecspg/articulate#353]
I am trying to create an intent trained on utterances which have two user defined entity types and one sys.duckling_time entity type. I get an error that says: "The value is required for all entities."

![image](https://user-images.githubusercontent.com/3117898/47793927-bebdad00-dcf5-11e8-8e5c-60291140c792.png)

It gives this error when I click the update button:

![image](https://user-images.githubusercontent.com/3117898/47793974-d85ef480-dcf5-11e8-8bec-f0f5f565bbb9.png)

here is the PUT call :

Request URL: http://localhost:7500/intent/186
Request Method: PUT
Status Code: 400 Bad Request

payload of put :
```
{
	"useWebhook": true,
	"intentName": "get_sales_comparison_by_period",
	"usePostFormat": false,
	"examples": [{
		"userSays": "Get me sales for FTE for cadence for the last 6 months vs previous 6 months.",
		"entities": [{
			"end": 20,
			"value": "FTE",
			"start": 17,
			"entity": "partnumber",
			"entityId": 33
		},
		{
			"end": 32,
			"start": 25,
			"value": "cadence",
			"entity": "customer",
			"entityId": 30
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		}]
	},
	{
		"userSays": "Get me sales for TFM for cadence for the last 6 months vs previous 6 months.",
		"entities": [{
			"end": 20,
			"start": 17,
			"value": "TFM",
			"entity": "partnumber",
			"entityId": 33
		},
		{
			"end": 32,
			"start": 25,
			"value": "cadence",
			"entity": "customer",
			"entityId": 30
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		},
		{
			"entity": "sys.duckling_time",
			"start": 41,
			"end": 54,
			"extractor": "system",
			"entityId": 0
		}]
	}]
}
```
at one point, it did seem to actually update the intent, though it gave me the error each time. But it does not seem to be actually updating for me at the moment. I don't know why. Here is a parse result for one of those utterances with the entity having been updated on the intent. 

*It seems to be working only just after the session has been cleared out

 https://slack-files.com/T3Z3JBY9E-FDRUATV3M-47d0134f02

**Comment by wrathagom** [comment]
restricted to old UI, won't fix.
