### ISSUE TITLE
Trying to Delete entities that are in use silently fails in the UI

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#355]
This is good, we don't want entities that are in use to be able to be deleted, but the failure shouldn't be silent. This should trigger a notification.

**Comment by wrathagom** [comment]
@dcalvom have you started on this? If not I am going to move to 0.16 since I have the rest of the notification stuff there.

**Comment by dcalvom** [comment]
This one was tackled by https://github.com/samtecspg/articulate/commit/72c0c62597c7390b80a269d75aab0c97bedc9865, but it's still under consideration to know if the notification on the chat panel is the way to go.

**Comment by wrathagom** [comment]
I'll open a new issue if we think we should move it some place else.
