### ISSUE TITLE
Adding regex matching to a learned entity doesn't trigger out of date message

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#356]
When adding/modifying/deleting the regex pattern on a learned entity the model needs to be re-trained. But it is not changing its status.

Again no as concerned about this on current UI, but should fix in new UI.

**Comment by dcalvom** [comment]
Ok, will tackle this one

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/a3d33ef0e402a8e488d40933d4f22b455e55f462
