### ISSUE TITLE
Regex escape issue

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#357]
I am trying to use regex on a learned entity. `\d{0,4}$` is what I type into the regex input. but in the training data this shows up as `\\d{0,4}$` which doesn't match anything.

**Comment by dcalvom** [comment]
I tested this none and despite it escape the regex, it does match the desired value, In example for the text `I'm a digit 0004`, this is how the slot is being filled:

`
...
      "slots": {
        "Digit": {
          "keyword": "Digit",
          "value": "\\d{0,4}$",
          "original": "0004",
          "promptCount": 0
        },
...
`
