### ISSUE TITLE
Design and Implement a Conversation Loop (Was issue #12)

### ISSUE THREAD

**Issue by milutz** [samtecspg/articulate#36]
> From May 23 on language-api, @wrathagom entered:

API.ai had the idea of context. We're looking for something similar here, but in a much more targeted manner.

Internal to the NLU agent we are looking for something that can have basic back and forth communication to gather missing entities or clarify unknown ones.

This one still needs a lot of design :)

> Jun 14 @dcalvom replied

Researching on this...

An issue has been opened in RASA repo RasaHQ/rasa_nlu#423

> Jun 14 @wrathagom replied

I'm already in talks with the RASA guys to try and get early access to their dialogue manager. Supposed to know something by end of this week.

> Jul 3 @wrathagom replied

Just updating in case I/we forget. We've got access to the Rasa DM Repo, so this one is on hold pending research of their offerings.

> Aug 4 @wrathagom replied

This is all we've been doing for the past two days, I will add a link here once I transcribe as much of our conversation as I can.

Though the`implementation` of this is going to get split into multiple/smaller issues.

**Comment by wrathagom** [comment]
This is in the current version of Articulate in a relatively simple rule based form. Primary issue has been completed, though I am sure there will be follow on instances as find weaknesses of the current implementation.
