### ISSUE TITLE
Highlighting entities changes the utterance list.

### ISSUE THREAD

**Issue by cjhurst** [samtecspg/articulate#361]
Whenever I highlight a user entity on the second page of examples within an intent, it reverts back to the first page of examples but still displays that it is on page 2 of 2. I think it would be best if it did not revert back to the first page of the list because I have to switch back to where I was at in the list 
of utterances every time I highlight one. 
[screen cast.zip](https://github.com/samtecspg/articulate/files/2548942/screen.cast.zip)

**Comment by wrathagom** [comment]
Closed in favor of #368 on the new-ui. won't fix in the old UI.
