### ISSUE TITLE
Articulate restrictions

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#362]
### Issues

- Did you download a release or pull from Master? Which release?
/articulate v0/12.3
- What operating system are you running?
/Linux Ubuntu
- Are you running locally or in the cloud?
Locally but forwarding ports so i can access it in all of my network
- Which browser are you using?
/Chrome, Firefox

----

### Feature Request
@milutz Hi ! I was looking at your article on the page:

https://blog.spg.ai/basic-access-restrictions-for-articulate-58e77c931ca3

I got it working, But i have a small problem. When am trying to access localhost:7500/documentation
It says the page is not found or the page might have been relocated.
After installing Nginx step by step as you explained, the access to localhost:7500/documentation was gone.
Is there any extra step for me to complete? Or maybe i have missed something?.

Thanks in advance !

**Comment by bkurowski** [comment]
thanks for your answer @wrathagom. Yes you are correct. I just missed that bit. 

Thank you, this has helped me. 
Kind Regards

**Comment by wrathagom** [comment]
Great, glad we could help and sorry for the delayed response.
