### ISSUE TITLE
problem agents training indefinitely

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#363]
After importing an older agent I ran into a problem and we tried troubleshooting it. It would just be stuck on training indefinitely, after hitting the train button. 

it seems like our platform is failing to generate a separate model per domain when there is just one intent on each domain

We don't know though however if this is the issue, we need to look into it more.

The fix for the moment disabling the slider on the "generate separate models for each domain"

**Comment by wrathagom** [comment]
@dcalvom I had already fixed this for single domain (thought I had for multi domain). I made the change in the [single domain training](https://github.com/samtecspg/articulate/commit/f512f3fff7c8410c27a2c3a8cb53e622c04e7724) file and [multi domain training](https://github.com/samtecspg/articulate/commit/f02b79e5e771b746bf3d4f079a101e24e6554e7f) file. But looks like I missed the same problem in the domain recognizer:

https://github.com/samtecspg/articulate/blob/master/api/modules/domain/tools/buildDomainRecognitionTrainingData.domain.tool.js#L27

I can make the change and get back with @RussellSPG for testing. Just want to document that I think this is likely the problem and see if you agree.

**Comment by wrathagom** [comment]
Closed with https://github.com/samtecspg/articulate/commit/aee812506148114436e3b86110ad1a2d77779f67
