### ISSUE TITLE
When adding more than 5 sayings the latest saying should show by default

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#368]
Steps:

- Add more than 6 saying
- Go to page 2 where you will see the 6th saying
- When adding the 7th saying the page will show the first 5 sayings (page 1) instead of where the new saying is (page 2)
- Also the index will show that you are on page 2 but shows the results of page 1.

**Comment by wrathagom** [comment]
@dcalvom this is still happening for me.

**Comment by dcalvom** [comment]
closed by dd2d04af7246dd594e9b6c11baedf1c0b7637761

**Comment by wrathagom** [comment]
@dcalvom this isn't fixed for me.

**Comment by wrathagom** [comment]
![2018-11-28_17-40-41](https://user-images.githubusercontent.com/1779894/49187262-efb0f200-f334-11e8-9f14-662e6c84f636.gif)

**Comment by dcalvom** [comment]
Fixed by https://github.com/samtecspg/articulate/commit/e7769fcbb70dceed31b5d8b4a67dcee1dbb63ac0
