### ISSUE TITLE
Design and implement a better training Loop (was issue #6)

### ISSUE THREAD

**Issue by milutz** [samtecspg/articulate#37]
> From May 16 on language-api, @wrathagom entered:

At the moment we are just going to kick off training at each POST/PUT that modifies a model. But this is less than ideal. We should have control over when we train such that all modifications can be completed.

We also need to implement a training test and feedback loop. When a model is first created we make sure that we can parse all intents and entities supplied in the training data. Whenever that model is modified we need to make sure we still can pass it.

**Comment by dcalvom** [comment]
I think this is tackled with training detachment:

> At the moment we are just going to kick off training at each POST/PUT that modifies a model. But this is less than ideal. We should have control over when we train such that all modifications can be completed.

Regarding this:

> We also need to implement a training test and feedback loop. When a model is first created we make sure that we can parse all intents and entities supplied in the training data. Whenever that model is modified we need to make sure we still can pass it.

Is something that we could include alongside with the https://github.com/samtecspg/articulate/issues/171 in some section for Agent test

**Comment by wrathagom** [comment]
In my mind it's not #171 this is a UI specifically geared towards reviewing user requests and labeling them if mislabeled. Agree that we have implemented the training control piece of this.

**Comment by dcalvom** [comment]
Oh I see. And what would happen with those? are they going to be part of the training data after relabel?

**Comment by wrathagom** [comment]
yep, similar to https://dialogflow.com/docs/history
