### ISSUE TITLE
Create articulateUI context if this doesn't exists

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#374]
Create from conversation on #370 to keep them separate

The ui should check if the context exists and if doesn't then create it

**Comment by wrathagom** [comment]
@malave you're missing the point. It isn't that it has no body, it is that we are specifying the ID.

In fact, I think the UI performing a GET and POST if it doesn't exist is the wrong approach. I think that in the converse code we should take a 404 from `GET /context/{sessionId}` and treat it no differently than an empty context. Then when we store off context we use a `PUT /context/{sessionId}` in this way there is no code for handling the UI as a special case.

**Comment by malave** [comment]
Yeah I can't replicate it anymore either. 

So I'm closing this

**Comment by malave** [comment]
Opps wrong ticket

**Comment by wrathagom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e417f24169dbdeb329c6bbf2e54c6707d433c65b
