### ISSUE TITLE
Combining Intents in one Question

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#381]
### Question

Hi Guys ! I think I have seen this coming up before but cant find it anymore.
Can we attach two or more intents to one question ?
So imagine i have two intents for example. Time Intent and Date Intent.

Can i ask a question and to trigger both to get one answer from two intents ? 

Thank you.

Kind Regards

**Comment by wrathagom** [comment]
not currently no. the new UI is built to handle this with Rasa tensorflow pipeline, but the current UI doesn't.

**Comment by bkurowski** [comment]
Nice one ! I see you are building many functions that will make my day ! 
Thank you for your quick answer.
