### ISSUE TITLE
Implement Sayings search functionality in the UI

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#382]
Currently you can't filter agents, sayings, domains or keywords because the filter is not implemented in the API

**Comment by wrathagom** [comment]
I am going to create a separate issue for search in the API and leave this one as implementing that search in the UI.

**Comment by dcalvom** [comment]
Just a note, this feature was fully working with the old api. So it is just matter of having the endpoints to do so.

**Comment by wrathagom** [comment]
Especially on the saying page, given that we've lumped them all together we need something more than just basic filtering.

**Comment by malave** [comment]
On the API side: 

This requires the attributes that we need to use for the search be marked as `indexed` in the redis model 

Also if we are going to use more than one then we need to modify `server/plugins/redis/lib/base-model.searchByField()` to accommodate more than one field at a time.
Look at ["Finding by Index"](https://maritz.github.io/nohm/#finding-by-index) documentation for how to do this.

**Comment by wrathagom** [comment]
@malave I am giving this one to you. Hoping that the API work you did will make it easy for you to modify things as necessary. Also hoping the UI work is minimal.

The goal is that on the sayings page the user should be able to type in search tags, that are Slack like in how they functions. Like:

- `category:Small Talk, action: Greet` and the list will be filtered to the small talk category, Greet action.
- `action:Greet hi` would filter to the greet action with text containing _hi_

Here is what it looks like in Slack:

![image](https://user-images.githubusercontent.com/1779894/50431792-6c36e200-089b-11e9-8d61-851de0bbf9e9.png)

**Comment by wrathagom** [comment]
okay so the functionality is there, we just need to figure out the UI pieces. I'm closing this one, but will open a new one for the UI components.
