### ISSUE TITLE
Remove 3 dots from Agent card on main page

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#383]
The menu in the agent card will open to allow the user to delete the agent. Right now is difficult to open this menu due that you don't know if you are in the right place to open the menu.

**Comment by wrathagom** [comment]
yeah we have a few places where we use the actual text as the button rather than creating a button with the icon/text inside of it.

You can actually see I miss the three dots the first time I try to click on them in the gif on #378

**Comment by broham89** [comment]
If it's not too late it think it's best for consistency sake to have the delete option inside the agent at the bottom like in other pages. This will help the user remember where the delete option is. 
![v 2 - agent create screen](https://user-images.githubusercontent.com/11262149/49112347-1ea56600-f258-11e8-9f34-56f6b09f689a.png)

**Comment by dcalvom** [comment]
@wrathagom, @ewoo, what you think about this one?

**Comment by wrathagom** [comment]
Even on super long pages? Is there any reason we aren’t using a red color for destructive options?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5994723f48f97f426b0f004d28a3e35af03e81ef
