### ISSUE TITLE
UI languages

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#385]
All the UI have been templated in order to easily create language files for support multiple languages. It is necessary to add UI language options in settings and create the language files for the other languages.

Also is necessary to implement the method to change the language when the dropdown of ui languages changes.

**Comment by dcalvom** [comment]
Please note that we already have a dropdown in the general settings page

**Comment by wrathagom** [comment]
I didn't realize we already had a dropdown, but it likely needs to be someplace on the front page so people don't have to search through English to find how to switch it to not-english.

**Comment by broham89** [comment]
So a button/dropdown for language change in all pages fixed? Like in pic example (top-right)
![language-switch](https://user-images.githubusercontent.com/11262149/49480186-50d03e00-f7eb-11e8-90a9-4e2dc97093fc.png)

**Comment by wrathagom** [comment]
yep

**Comment by wrathagom** [comment]
@dcalvom are you going to add the drop down as @broham89 designed it above?

**Comment by dcalvom** [comment]
Yes!
