### ISSUE TITLE
Filter for timezones dropdown

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#387]

**Comment by dcalvom** [comment]
This would be the solution for #307 right?

![44602263-b3ee1580-a7a4-11e8-9dd5-e48d7fb2fc8b](https://user-images.githubusercontent.com/7228045/49051652-16621200-f1e9-11e8-8555-e3e24e7934ce.png)

**Comment by wrathagom** [comment]
@ewoo would the X solve your problems/concerns or not?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e57016913e4b4e5744f68c73139492a5837bbecc
