### ISSUE TITLE
Show a no domains label in the domains dropdown when it applies

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#388]
Whenever the sayings screen loads the dropdown of domain is empty, a sort of label should be shown in order to be more clear. Any suggestion @broham89 ?

![image](https://user-images.githubusercontent.com/7228045/49044219-6c28c100-f1cd-11e8-8b5f-28ceffbf1ff0.png)

**Comment by wrathagom** [comment]
@dcalvom at one point in time I had thought about automatically using the `default` domain when no domains exist. Do you like that idea or not? So in other words the dropdown would never start empty.

**Comment by dcalvom** [comment]
I know we talked about that. Is just I wasn't 100% sure if that was the path to follow.

My only concern is that, despite the fact is not relevant for put the agent to work, every agent will have a domain called default because they didn't took the risk of delete it.

But, I understand it is a good way to put the user in a fast track to create sayings.

**Comment by broham89** [comment]
I believe I had one version that had a `select` placeholder in category drop-down. The user would need to select/create their own category and then start inputting sayings.
![category-start](https://user-images.githubusercontent.com/11262149/49116435-274f6980-f263-11e8-8748-331f6cbc58ac.png)

**Comment by wrathagom** [comment]
I am good with that.

**Comment by dcalvom** [comment]
fixed by https://github.com/samtecspg/articulate/commit/89a0089b975ac50a3f511eae69bd5f02f20ff3f2
