### ISSUE TITLE
Option to delete domains

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#390]
If you create a domain in the new ui, but you want to delete it you are not able to do so because there isn't a way to do it in the ui.

**Comment by wrathagom** [comment]
Wasn't this in @broham89's original designs as a trashcan/X beside the edit icon?

**Comment by broham89** [comment]
![domain - step4](https://user-images.githubusercontent.com/11262149/49110947-6de99780-f254-11e8-89a5-b2348e11cb76.png)
Yes, when the user goes into the create/edit page in domain page there should be a delete and warning <p> at the bottom.

**Comment by wrathagom** [comment]
Closing in favor of #399
