### ISSUE TITLE
New UI notifications feature

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#397]
Currently, we have all implemented to send notifications to the user. We need to define what kind of notifications we would like to show. This are examples of notifications:

![image](https://user-images.githubusercontent.com/7228045/49044634-acd50a00-f1ce-11e8-845a-8af6480fec76.png)

**Comment by wrathagom** [comment]
@dcalvom have you created the code in the UI to create these, something that can be easily triggered?

I think we should go ahead and add a few notifications:

- New Action
- New Domain
- Training Completed (error's included)

**Comment by dcalvom** [comment]
Yes, it is just matter of pushing a notification to the array of notifications very straightforward

**Comment by wrathagom** [comment]
do they have a timeout that can be applied or a default one?

**Comment by dcalvom** [comment]
No, but sounds as a good feature. They are disposable one by one by the user, or if he clicks clear all, the notifications are also cleared all at once

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5790cda520b8de111e9a617acb8223b3ecc5c98e, https://github.com/samtecspg/articulate/commit/4c622949210774f876242583c9f40ada3c58e7fa, https://github.com/samtecspg/articulate/commit/8c741943cf9c9b62df41947dba5aba1df72d6064, https://github.com/samtecspg/articulate/commit/4753a360c644ce82d4b6f20fa613690e8ec1238f, https://github.com/samtecspg/articulate/commit/24f9ce4501bc83f55e4b11c1e281b77c00ca1c45, https://github.com/samtecspg/articulate/commit/72c0c62597c7390b80a269d75aab0c97bedc9865, https://github.com/samtecspg/articulate/commit/f600bbf1e27daf059ab2cce809fd7c6e22412e95
