### ISSUE TITLE
Add Delete Footer to Agent, Domain, Keyword, and Sayings pages.

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#399]
If you create and action and you wish to delete it there is no way to do so in the UI. This feature needs to show an alert if there are sayings that are using the action to delete.

**Comment by broham89** [comment]
![action slot page - add modifiers stacked](https://user-images.githubusercontent.com/11262149/49110311-c3bd4000-f252-11e8-8f6a-d7687b529974.png)
One simple way is to add the delete button inside the action page.

**Comment by wrathagom** [comment]
Doesn’t that look like it applies to all slots as opposed to just the one you are selected on?

**Comment by broham89** [comment]
![action slot page - add modifiers stacked](https://user-images.githubusercontent.com/11262149/49111624-472c6080-f256-11e8-8131-f2df04f9407a.png)
Supposed having the delete option at the bottom like other pages with a warning tag to tell users the whole action will be deleted. This will be fixed on every tab being switched. 

If not the other option is to have a three dot icon next right to the `[next >]` btn and it will drop down for the delete option.

**Comment by wrathagom** [comment]
Would you do this same thing on the agent and keyword pages?

**Comment by wrathagom** [comment]
Related to #383

**Comment by wrathagom** [comment]
@dcalvom do you still need html/CSS from @broham89 ?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/fb2ebea47893695071e90290a9961c1b51693db0
