### ISSUE TITLE
Help videos

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#400]
All the screens in the new UI have a `help?` button where users can watch a video to get help in the process of using the screen.

We need to record, edit, and upload this videos to help users.

**Comment by wrathagom** [comment]
Videos that we will need:

- [ ] Agent Page
- [ ] Sayings Page
- [ ] Keyword Page
- [ ] Action Page
- [ ] Review Page

**Comment by dcalvom** [comment]
I added all the currently available videos. These screens are still missing the video:

Actions Responses
Action Slots
Action Webhooks
Review Page
Settings Page

**Comment by wrathagom** [comment]
I'll try to record these soon.

**Comment by wrathagom** [comment]
Close in favor of #702
