### ISSUE TITLE
Move new UI and API to master

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#404]
So  in the dialog flow branch we need to:

- [ ] remove the old `ui` and `api` directories
- [ ] rename the `new-ui` and `new-api` directories
- [ ] put the compose and compose override files back
- [ ] replace Rasa docker file with the Dockerfile for `daniel-test-may25-2018-try03` image.
- [ ] (force ?) merge to master

what else?

@milutz any inputs?

**Comment by wrathagom** [comment]
also @dcalvom @milutz where is the Dockerfile for the tensorflow image?

**Comment by dcalvom** [comment]
It is in the new-api / new-ui branch and it is called rasa-tf

**Comment by wrathagom** [comment]
I see it referenced as an image, but I don't see the actual Dockerfile that built that image. Which @malave will need in order to replace the current rasa image.
