### ISSUE TITLE
Last Trained time shown in the UI doesn't update

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#405]
We used to poll every N seconds for the agent status, but now a web socket sends the status to the UI whenever it changes. This is good, but we have text in the UI that says `Last trained: 1 m ago` and right now it doesn't update unless the page is refreshed. Seems like we should be able to add a simple timeout every 15 seconds just to that element to update the friendly text.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/edf7010882767f931d590366edaa3cc6ed793d8b
