### ISSUE TITLE
Deleting and Re-Arranging Slots

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#406]
@broham89 we need to know what this looks like if we don't already.

**Comment by broham89** [comment]
https://share.goabstract.com/cbca8be8-d718-4fa3-bf9c-d13b3bb376db

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/1ce59f0aaf5e3eadbc2b34f981291f9b47109c47
