### ISSUE TITLE
Color on confirmation windows

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#408]
To me this modal needs more color:
![image](https://user-images.githubusercontent.com/1779894/49055572-0b49ba80-f1c6-11e8-8591-eee62827407d.png)

**Comment by broham89** [comment]
<img width="372" alt="screen shot 2018-11-28 at 4 09 51 pm" src="https://user-images.githubusercontent.com/11262149/49185665-1288d980-f328-11e8-8b63-2331d6d56af3.png">
Red is fine.

**Comment by dcalvom** [comment]
fixed by https://github.com/samtecspg/articulate/commit/89a0089b975ac50a3f511eae69bd5f02f20ff3f2
