### ISSUE TITLE
Multi Actions - Phase 1 [WIP]

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#410]
@dcalvom let's step into the context changes and the multi-action, multi-response work.

Let's:
- [X] Move the current array of frames into the `frames` key.
- [ ] Add an actionQueue and responseQueue key, arrays to hold the respective values.

Action Queue:
```
[
  {
    "action": "greet"
  }, {
    "action": "orderPizza",
    "slots": {
      ...
    }
  }
]
```

Response Queue:
```
[
  {
    "textResponse": "Hello"
  },{
    "textResponse": "with webhook format",
    "slots": {
       ...
    }
  }
]
```

- [ ] Add `PATCH /context/{sessionId}` so that we can use the API to update the queues. We don't have to support PATCH on frames, but should on the queues.
- [ ] Modify Converse code
  - Logic to consider:
    - Return all responses on prompt or all actions complete
```
{
  "textResponse": "Hello", //summary response at top level
  "responses": [
    {
      ..
    }
  ]
}
```

For the most part the existing conversation rules will apply, but you're going to have questions regarding how different aspects of conversation are handled with the multi-actions. Here's a first pass at a few different situations you'll encounter, ask as you uncover more:

- actionQueue is empty, new request, actions get added to the queue.
- actionQueue is not empty:
  - new request with a high confidence that matches first value in queue - fulfill the 1st action
  - new request with a high confidence matches nth action in queue, nth action in queue moves to top of queue
  - new request with a high confidence that doesn't match queue, action is added to top of queue
  - new request with a low confidence with entities, try to apply to first action in queue
  - new request with a low confidence without entities, try to fulfill first action in queue

The response queue

**Comment by dcalvom** [comment]
The frames are already in a frame key. I think I understand the logic.

**Comment by wrathagom** [comment]
@dcalvom I will mark this one as closed. Any thing else I'll create bugs for.
