### ISSUE TITLE
Deep links not working - Or the page must load all the needed resources

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#414]
Load the resources needed for a page to work without the need to go back and click on each link individually.

For example: if I go directly to `http://localhost/agent/1/sayings` then we should load the agent 1 and then load the sayings for that saying.

Right now you need to go to the agents page, select the agent then click on sayings.

The router should handle loading the resources as they are needed and they correct order during page load or when a link is clicked, that way if you refresh the current page you will get the same results as clicking thru.

**Comment by wrathagom** [comment]
addressed with 
https://github.com/samtecspg/articulate/commit/7e2f0be9c3cdcf26397db43b5e9ec86983dc2472
