### ISSUE TITLE
Re-arrange Page Headers

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#416]
We discussed changing the page headers from this:

![image](https://user-images.githubusercontent.com/1779894/49251627-d4ef8380-f3ef-11e8-8f05-2169e363d4ca.png)

to this:

![image 1](https://user-images.githubusercontent.com/1779894/49251634-dae56480-f3ef-11e8-9146-a3d6233007db.png)

**Comment by broham89** [comment]
https://share.goabstract.com/b23cc89b-3d0f-47de-b52e-6af05f7d3894

**Comment by dcalvom** [comment]
@wrathagom @broham89 do you have the designs for sayings and keywords page?, as they don't have tabs in the header I don't know what should be the layout?

**Comment by wrathagom** [comment]
@dcalvom @broham89 I would propose something like this. Sorry the green line didn't move I'm copy/pasting to get stuff in the right position. But hopefully you get the idea.

![image](https://user-images.githubusercontent.com/1779894/50225246-f946dc00-036d-11e9-8222-058974ccb32b.png)


@broham89 can you clean this up in abstract? Also open to any other suggestions.

**Comment by dcalvom** [comment]
> 
> to this:
> 
> ![image 1](https://user-images.githubusercontent.com/1779894/49251634-dae56480-f3ef-11e8-9146-a3d6233007db.png)

Please consider, that we're missing the save button here

**Comment by broham89** [comment]
I like the thought of save appears next to the training button when things change. And disappears after a save. My only concern is that users will forget that they need to save or get confused it with training btn. There should be a warning pop up if they exit a page or browser with unsaved changes

**Comment by dcalvom** [comment]
Ok so the save button will go on the right side of the training button when something changed?, and we are going to show an alert like the one when you delete an agent?

**Comment by wrathagom** [comment]
we'll show an alert when you try to navigate away with unsaved changes was my understanding. Which we might do already? dunno.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/0006f043e37c3fb32c6b01c2fe8246de809dd9d6, https://github.com/samtecspg/articulate/commit/9fbf18fd84f7cdf0af91987a046a7c7fe2bc1347, and https://github.com/samtecspg/articulate/commit/00f4c54e4c0f2800514365f94dbf7cff2b59ce4b
