### ISSUE TITLE
Help - Using nested handlebar templates

### ISSUE THREAD

**Issue by sumanthkulkarni13** [samtecspg/articulate#420]
Disclaimer: I'm not a dev, kindly excuse my limited knowledge in coding.

I'm trying to use nested handlebar templates inside an agent response, something like below:

There are {{webhookResponse.plays.0.tasks.0.hosts.**{{slots.environment.value}}**-manager.stdout}} services deployed in {{slots.environment.value}}. Out of which {{webhookResponse.plays.0.tasks.1.hosts.{{slots.environment.value}}-manager.stdout}}

{{slots.environment.value}} is a string that Im trying to interpolate with a json path which is basically an ansible json output of a shell command.

Without nesting the template would look something like below:

{{webhookResponse.plays.0.tasks.0.hosts.**devv**-manager.stdout}} 

Im trying to slot-fill **devv** instead of hardcoding that will be called in complement to my webhook something like below:

http://x.x.x.x:9000/hooks/swarm-{{slots.environment.value}}

Thank you in advance!
Sumanth

**Comment by wrathagom** [comment]
@sumanthkulkarni13 I will have to play with handlebars a little bit. If `{{slots.environment.value}}` was the entire key name you could use the [pick](https://github.com/helpers/handlebars-helpers#pick) helper. Something like

```
{{#pick (slots.environment.value) webhookResponse.plays.0.tasks.0.hosts}}
   {{stdout}}
{{/pick}}
```

Given that you have to add the `-manager` to the end I will have to investigate.

**Comment by sumanthkulkarni13** [comment]
Hi @wrathagom, I can remove "-manager" from my json output to parse.

**Comment by sumanthkulkarni13** [comment]
I removed the -manager from my returned json objects.

However, this is still not working:

{{#pick (slots.environment.value) webhookResponse.plays.0.tasks.0.hosts}}
   {{stdout}}
{{/pick}}

Just to note that **stdout** is a string property of (slots.environment.value) (ex: devv).

**Comment by wrathagom** [comment]
Sorry I am still not at a position I can test myself.

Does `{{#pick (slots.environment.value) webhookResponse.plays.0.tasks.0.hosts}} {{{stringify .}}} {{/pick}}` return anything?

**Comment by sumanthkulkarni13** [comment]
Sorry, no luck, Below the json for your reference if that might help.
https://gist.github.com/sumanthkulkarni13/26b90d6cdd9dd23dd6a6fdf71dbf98be

**Comment by wrathagom** [comment]
Okay, two other things to try:

```
{{#pick slots.environment.value webhookResponse.plays.0.tasks.0.hosts}} {{{stringify .}}} {{/pick}}
```

or

`{{lookup webhookResponse.plays.0.tasks.0.hosts slots.environment.value}}`

I'll be able to run Articulate tomorrow and try for myself.

**Comment by sumanthkulkarni13** [comment]
Yep! 
`{{lookup webhookResponse.plays.0.tasks.0.hosts slots.environment.value}}`
This is promising, this returns as `[Object Object]` in agent response.

How do we address the attribute of `slots.environment.value` from the lookup result?

**Comment by wrathagom** [comment]
Nope, that's were we were going to end up. Glad you got it. Let us know if you have other troubles.

**Comment by sumanthkulkarni13** [comment]
Thanks again @wrathagom is there a cheatsheet that you know of, for handlebar templating?

**Comment by wrathagom** [comment]
The best places for handlebars in general are the main [handlebars](http://handlebarsjs.com) website and the [handlebar helpers](https://github.com/helpers/handlebars-helpers) website.

We're working on a multi-part blog/document that will have some common patterns.

**Comment by sumanthkulkarni13** [comment]
Thanks @wrathagom
