### ISSUE TITLE
Ubiquity Multiple Message Responses

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#422]
Need to design how this will be handled. More specifically how ubiquity can tell converse that it can send intermediate messages. And how converse will pass these back.

If we want to expose this in the UI it get's really messy.

**Comment by wrathagom** [comment]
We need to add a property to each Ubiquity channel specifying whether or not it can send outgoing messages. probably a key like `outgoingMessages: true` or some such. These are for channels like Twilio, Slack, and Rocketchat where a message is just a POST request and not a reply. So for these channel if we have multiple messages to send we should send them as soon as possible rather than adding them to the responseQueue.

**Comment by wrathagom** [comment]
Keep in mind that this needs to be done in such a way that future Ubiquity channels can easily take advantage of it if they can send outgoing messages.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3d8465d1cea610ae6e6a152695184b0b8a87dc1a

Still testing by @wrathagom
