### ISSUE TITLE
Conversational History

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#424]
### Question

Hi, I have got a question here, I was looking at some information on "Conversational History", but could not find any answer that would satisfy me.
Is there a way to keep track of the actual conversation inside a file or some type of global context ? 
When the user is chatting away with bot, I would like to be able to track what was said by the user or the bot. I would like to use that conversation later on for help or analytics.

Is there a way to do such a thing ? 

Thank you,
Best regards,

Bart

**Comment by wrathagom** [comment]
Yep, we'll get there.

**Comment by bkurowski** [comment]
Nice to know, thank you for your answer. 
And is there any estimated release date for new UI ? 
Not to be hurrying you up, I am just curious.

Cheers

**Comment by wrathagom** [comment]
I'd say the first release of the new UI will happen by the end of this week or next. We're cleaning everything up now.

**Comment by bkurowski** [comment]
OK, thank you for your answer.
This topic can be closed now.

Kind Regards.
Bart
