### ISSUE TITLE
Add system entities to slot entity dropdown

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#425]
Let's go ahead and add the system entities back to the entity dropdown, just like it was originally in the old UI. That way they can at least be used. This only applies to the action screen.

I'll work on a new design for auto-highlighting.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/d3b06f21ebf02f85825ccd24b0bca198cc05f437
