### ISSUE TITLE
Fix alignment of add button

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#427]
This is just me being picky, but the alignment of this button, when the search field is highlighted, bothers me. Is is an easy fix?

![image](https://user-images.githubusercontent.com/1779894/49400290-d2539d80-f711-11e8-8ed8-c84d2a28ed21.png)

**Comment by dcalvom** [comment]
Fixed by https://github.com/samtecspg/articulate/commit/89a0089b975ac50a3f511eae69bd5f02f20ff3f2
