### ISSUE TITLE
Action Chaining

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#428]
As part of #223 the idea is to allow agent responses to chain to another action. Below is what the UI for this will look like. The idea being that if the agent responds with a response that has an action attached to it, that action get's added to the `actionQueue`.

![image](https://user-images.githubusercontent.com/1779894/49479810-58dfac00-f7f2-11e8-90b4-ac1c9bb9d122.png)

**Comment by dcalvom** [comment]
Closed by 25ad1e507892853fd21c8f721ad11ee076cfd34a
