### ISSUE TITLE
Action Tag misaligned

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#429]
In Safari the action tag is mis-aligned in the sayings input

![image](https://user-images.githubusercontent.com/1779894/49544973-4b85f880-f8aa-11e8-920b-b1faac32e68e.png)

**Comment by dcalvom** [comment]
Closed by 94da4bbd75ba631be04d926b2adb0d383ee1e9b6

@wrathagom I wasn't able to reproduce this on Safari. Could you please try to clear safari data related with articulate to check this out
