### ISSUE TITLE
Help-handlebar template

### ISSUE THREAD

**Issue by sumanthkulkarni13** [samtecspg/articulate#432]
I'm trying to use 
`dashcase {{slots.service.value}}` to convert an entity into hyphenated from underscore.

But dashcade is not interpolating the value to the entity.

Is there something that I'm trying wrong?

**Comment by wrathagom** [comment]
But it in the curly brackets. `{{dashcase slots.service.value}}` try that.

**Comment by sumanthkulkarni13** [comment]
Thanks @wrathagom that worked. 

Secondly, Is there a way to capture dump of the `webhookResponse` as an agent response?
I tried `{{JSONStringify WebhookResponse}}` but the result doesn't seem to be consistent.

**Comment by wrathagom** [comment]
Whenever you want to output JSON rather than a string use triple curly brackets. Like `{{{JSONstringify webhookResponse}}}`

**Comment by sumanthkulkarni13** [comment]
Thanks @wrathagom
