### ISSUE TITLE
RBAC Features 

### ISSUE THREAD

**Issue by sumanthkulkarni13** [samtecspg/articulate#435]
Are there any feature available to implement RBAC towards slack integration.
Fundamentally Either 
1. I'm looking for only a set of users to be able to call the bot 
OR
2. Bot will only listen to the conversations from a specific channel.

**Comment by wrathagom** [comment]
Hey @sumanthkulkarni13 our platform integrations are still young/basic in functionality. The one that we have built for Slack filters down to replying to direct messages and direct mentions. You could expand on this to include a list of people/channels.

Hopefully this functionality will be improved and wrapped in a UI before too long.

https://github.com/samtecspg/articulate/blob/master/api/ubiquity/services/slack-rtm/index.js#L82

**Comment by wrathagom** [comment]
@sumanthkulkarni13 I'm closing this for now, but please keep checking back. We're likely to release a UI for our integration channels in the next several months and our goal will be to support this feature.
