### ISSUE TITLE
Convert unix Timestamp to regular date format

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#436]
#### Questions

Hi Guys, cant find a way to convert unix timestamp like = "1485792967" to a regular date format.
Is there a way to approach it in Articulate ? 

Thanks !

**Comment by wrathagom** [comment]
there is a handlebar for this. `{{dateTimeFormat webhookResponse.myDate 'ddd, hA'}}` where the third parameter is a valid [moment.js date format](https://momentjs.com/docs/#/displaying/)

Try that and let me know.

**Comment by wrathagom** [comment]
@bkurowski did that get you going?

**Comment by bkurowski** [comment]
Sorry for late message, yes that works. I just need to play with viewing format of the output, but that is not a problem.
Cheers thank you.

Question answered.
