### ISSUE TITLE
More then one webhook

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#437]
### Question

Hi Guys, is there a way to call 2 or 3 different webhook urls in one question ? . Each one will have to depend on each other. 
The idea is to pass one detail from one webhook to another webhook. Using one question.

Cheers.

**Comment by wrathagom** [comment]
no, for now you would have to call some middleware, which calls the other three in succession. Though it is planned https://github.com/samtecspg/articulate/issues/276
