### ISSUE TITLE
Iterating through JSON using handlebars

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#440]
### Question

Hi Guys, I am having a small difficulty iterating through webhook that contains JSON type data.
I am trying to see if a key called "name" contains word "node1" and return its "id" and then place the value of "id" to a link.

This is a sample JSON I am based on:
`[{
	"name": "This is a test string node1, node2, node3" },
	"children": [],
	"events": {},
	"incidents": [],
	"id": "htf-56783-hytrhjk-44432",
},{
	"name": "This is a test string node1, node2, node3",
	"children": [],
	"events": {},
	"incidents": [],
	"id": "htf-56783-hytrhjk-44432",
}]`

Originally the JSON contains multiple keys with name "name".
What I am trying to do is as follows:

`{{#forEach webhookResponse}}{{name}}{{#contains name "node1"}}HERE !!!!!!!!!!{{this.id}}{{/contains}}{{/forEach}}`

This works for me. But it returns the whole data that is not required + the data I want to return. My problem is that I can not figure out a way to return only the id of the node I am looking for.

Would anyone have some suggestions for this approach ?

Thank you,
Kind Regards,

Bart

**Comment by bkurowski** [comment]
This is what i was looking for. I was looking at template of {{#forEach}} and thats why it was giving me the whole UNWANTED data, because {{name}} was giving all the data. 
I see now that it is not required. 
The agent response you provided me with is working as i was expecting it to work.

That helped me.
Thank you.

**Comment by wrathagom** [comment]
glad to help.
