### ISSUE TITLE
Pagination Length choice should persist page changes/refreshes

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#442]
yep, it should.

**Comment by dcalvom** [comment]
I don't get this one. Do you mean that if you page size if 5, and you are on page 3, and you change to a page size of 10, then the page should still be 3?

**Comment by wrathagom** [comment]
If you change the length to show 25 sayings and then refresh the page it changes back to 5. It should save your choice.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/999784c512b44a1de786414e214ce8b62a3c5e2f
