### ISSUE TITLE
On creating agent, no text error for "must enter fallback response"

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#446]
If fallback responses are deleted, and user hasn't entered one, there is no error after hitting save when creating agent

**Comment by dcalvom** [comment]
I wasn't able to replicate this one, and it seems to work fine for me. I will close it, and please try again, if you have the error please specify the exact steps you took to reproduce it. Just in case make sure you are using the latest version, although I haven't made any specific change on this piece of code.

![image](https://user-images.githubusercontent.com/7228045/50526753-d8873080-0aa9-11e9-9f1c-a3d7a15fd295.png)
