### ISSUE TITLE
Change text on sayings for category 

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#447]
Suggesting change from "Select" to "Category" or "Select Category"  title for easier readability to user
![image](https://user-images.githubusercontent.com/42249324/50487540-cbe0da80-09cc-11e9-84b5-26ccce3d7cce.png)

**Comment by wrathagom** [comment]
@dcalvom the text above the box should definitely be `Category:` then the text in the box can stay as Select.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b071f5a3de5a5737c50d381c55712763759c1705
