### ISSUE TITLE
API shouldn't allow to delete an action if it is being used by a saying

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#448]

**Comment by wrathagom** [comment]
@dcalvom the alternative here is we allow the delete and unlink it from all the sayings using it...

**Comment by dcalvom** [comment]
Which option would you like to implement?

**Comment by dcalvom** [comment]
For consistency, I will follow the same behavior than with categories and keyword. It would be to block the action of delete until it's unlinked from all the sayings.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/f981fba5762c52d6679e52c01584931bd850c02b
