### ISSUE TITLE
Control actions with just one saying

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#451]
We need to handle actions with just one saying, either for block training or managing them properly in the training data generation.

**Comment by spg-matt** [comment]
@dcalvom per Slack you were working on this last Wednesday, were you able to complete it?

**Comment by dcalvom** [comment]
Sorry for the delay!...closed by https://github.com/samtecspg/articulate/commit/4c02f7cfe749c62ffd0c0d52a374392766e0d212
