### ISSUE TITLE
Scroll bar is not visible when there are multiple actions and it is confusing

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#452]
![image](https://user-images.githubusercontent.com/7228045/50570004-f240a600-0d3d-11e9-87e7-541a49796aa4.png)

**Comment by dcalvom** [comment]
I changed the height of the dropdown, which takes advantage of the space

![image](https://user-images.githubusercontent.com/7228045/50660616-0ebf2700-0f66-11e9-873c-8a0afa0ae41f.png)

@broham89 do you have any suggestion for this?

**Comment by broham89** [comment]
there is a way to signal the user if there are more listed items in a dropdown by showing half of the text from the bottom up. Even better with a light inner-shadow
![listdropdown](https://user-images.githubusercontent.com/11262149/50669284-d2052700-0f89-11e9-800e-8cc5d2cebfc5.png)

**Comment by dcalvom** [comment]
Got it @broham89 I checked in both browser and the scroll bar is being show for long lists.
