### ISSUE TITLE
Release date.

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#458]
### Question

Hi, I have been asking about the new release date of Articulate just before Christmas. I see many updates here on Issues tab. 
Can anyone estimate, when is the new release of Articulate coming out. 
Not rushing ye up guys ! You are doing great work ! 

Cheers !

**Comment by spg-matt** [comment]
@wrathagom says we're likely talking another week or two. He has several features he wants in before the release.

**Comment by bkurowski** [comment]
Thank you. Great work !
