### ISSUE TITLE
Missing Synonyms heading in keyword tab New UI

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#461]
When clicking new keyword, there is a heading for Value, but nothing on the right for synonyms

![image](https://user-images.githubusercontent.com/42249324/50865144-64367200-1372-11e9-94bb-7cfd2578e21e.png)

**Comment by spg-matt** [comment]
A label of `synonyms` seems appropriate.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/f965e9a416ecacd87f2792515a26427d10629980
