### ISSUE TITLE
Add multiple new entities in one API call

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#463]
### Question

Hi guys, I am using an API to add new Entities to the system. Like visible below.

![image](https://user-images.githubusercontent.com/40358189/50907899-60612900-1420-11e9-887f-c61d067b5022.png)

My question is, is it possible to add more than one entity at once ? Rather than adding it one by one ? 

As when I try to add 2 entities at once  just like below.
`[{
		"entityName": "test11",
		"agent": "testAgent",
		"uiColor": "red",
		"regex": "string",
		"type": "learned",
		"examples": [{
			"value": "Test",
			"synonyms": [
				"test1", "test2"
			]
		}]
	},
	{
		"entityName": "test55",
		"agent": "testAgent",
		"uiColor": "red",
		"regex": "string",
		"type": "learned",
		"examples": [{
			"value": "Test1",
			"synonyms": [
				"test1", "test2"
			]
		}]
	}
]`

I get this type of error.

![image](https://user-images.githubusercontent.com/40358189/50908078-dd8c9e00-1420-11e9-8eeb-35204c2fe4fc.png)

Am I doing something wrong ? Or this procedure is not allowed.

Thanks,
Best Regards.

**Comment by spg-matt** [comment]
At current you cannot create two entities in this way. We can change this into a feature request if you need to do this often.

I have heard @wrathagom mention a bulk endpoint for entities.

**Comment by bkurowski** [comment]
Thanks, sure if possible you can change the state to a feature request. As maybe others might  need it in future. 

Thank You.

**Comment by dcalvom** [comment]
Related with https://github.com/samtecspg/articulate/issues/122
