### ISSUE TITLE
Stop the next/back buttons from appearing as moved in Sayings page New UI

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#465]
### Feature Request

I think for people who use Articulate in windowed mode along with other things it would be handy if the Next/Back buttons would stay in same place. For example, So when going to a new page, the cursor doesn't move, and having to scroll back down to click to go to the next/back. Example Attached. 
[windowed sayings.zip](https://github.com/samtecspg/articulate/files/2745700/windowed.sayings.zip)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/11cdec4b31402fae7708897c95c7c26c439c30a9
