### ISSUE TITLE
Using slots as variables!

### ISSUE THREAD

**Issue by drpdishant** [samtecspg/articulate#466]
### Feature Request
I am talking about something similar to the Alexa Skill Development Console, there we can create slots and add them as variables in user utterances, which lets the user to say something filling the blank slot with a value which can be used in the bot responses!

**Comment by wrathagom** [comment]
Unless I misunderstand this is already possible in Articulate. You can use handlebars in the responses to include slot values.

`sure we’ll get a {{slots.toppings.value}} pizza ready.` will pull the value from that slot and use it in the response.

Here some info on where all you can use handlebars https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241

**Comment by dcalvom** [comment]
@drpdishant Please let us know if @wrathagom helped you out.

**Comment by drpdishant** [comment]
I know that we can pull the value from a slot, but I don't know if we can input a value into the slot via user input. I tried using entities and used them as slot, that worked well, but consider an example of the bot asking for users name, then user inputs the name triggering an intent, and the intent utterences take the input of users name and save it into a slot..
e.g i create a slot named username, and intent will be triggered with something like "Hi, My name is <username>" 
"My name is <username>"
" I am <username>"
 
Then what ever name the user says witll be saved in that variable. I hope you understood what I am trying to say.

**Comment by wrathagom** [comment]
yep this can be done using slots, prompts and handlebars. Let me know which version of Articulate you are using and I can try to provide you with a demo agent that does what you are asking.

but for the most part you would create an intent with a slot for username. Set that slot to use a custom trained entity for names or `sys.spacy_person`, This slot could have a prompt like `I haven't caught your name yet, what is it?` when the user replies it will fill the slot and then your response could be something like `Well, {{slots.userName.value}} it is nice to meet you.`

**Comment by drpdishant** [comment]
Ok! I'll try it this way! btw I am using Articulate 0.13.0, the latest one
