### ISSUE TITLE
Create intent using API problem

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#467]
### Question

Hi guys am trying to use intent API to load intents using script for example.
What happens here is as follows:

![image](https://user-images.githubusercontent.com/40358189/51031394-5e1fdb80-1594-11e9-902f-bafa2f5d5cbf.png)

I am using this JSON code:
`{
  "agent": "Testing",
  "domain": "Test",
  "intentName": "Tester",
  "useWebhook": false,
  "usePostFormat": false,
  "examples": [
    {
      "userSays": ["This is example test" , "this is example test"],
      "entities": [
        {
          "entityId": 29,
          "start": 0,
          "end": 0,
          "value": "string",
          "entity": "Cells",
          "extractor": "string"
        }
      ]
    }
  ]
}`

But when I am trying to run it so it adds the intent into the system I get this message:

![image](https://user-images.githubusercontent.com/40358189/51031489-9f17f000-1594-11e9-9896-ecaf41c6f389.png)

Not sure what text it requires. 
And when adding an intent this way I can not see where is the agent response key in it. Is it the "value" that corresponds to Agent Response ? 
And what is the "start" & "end" keys used for ?

Thank you,
Best Regards.

**Comment by bkurowski** [comment]
I observed that, I have done it like that as it was asking me for more than one userSays. Can you tell me how to form the JSON articulate is providing in order so it will understand it as two separate userSays in the form of string ? 
Cheers.

**Comment by wrathagom** [comment]
You create multiple objects under the examples array:

```
{
  "agent": "string",
  "domain": "string",
  "intentName": "string",
  "useWebhook": true,
  "usePostFormat": true,
  "examples": [
    {
      "userSays": "saying 1",
      "entities": [
        {
          "entityId": 0,
          "start": 0,
          "end": 0,
          "value": "string",
          "entity": "string",
          "extractor": "string"
        }
      ]
    },
    {
      "userSays": "saying 2",
      "entities": [
        {
          "entityId": 0,
          "start": 0,
          "end": 0,
          "value": "string",
          "entity": "string",
          "extractor": "string"
        }
      ]
    }
  ]
}
```

**Comment by bkurowski** [comment]
Oh, cheers that is what i was looking for, was not sure of the format. Ill test that and i will contact you with the result. 
Thank you

**Comment by bkurowski** [comment]
Thanks, all works !
