### ISSUE TITLE
Access a webhook through Articulate that requires Basic Authentication

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#468]
### Question

Would you be able to tell me if there is a possibility to access a webhook containing JSON that requires a username & password through Articulate webhook call ?

I am trying to attach Username & Password in Body type as visible below:

![image](https://user-images.githubusercontent.com/40358189/51042367-03967780-15b4-11e9-8775-a59e5f463bb9.png)

I know I might be doing it wrong, is there anyone that can tell me what I am doing wrong ? 

As I have observed it passes the Username & Password but it passes as "data" not as "auth".
See below for more understanding.

![image](https://user-images.githubusercontent.com/40358189/51042310-df3a9b00-15b3-11e9-8897-4ac7c07e30ab.png)

Thank you !

**Comment by bkurowski** [comment]
I cant retest it at the moment as the server I am trying to gain access to is down.
But I think I found my mistake
This is how I think the JSON should be formatted.

`{
"auth": {
    "user": "username",
    "pass": "password"
  }
}`

I will test it as soon the server will be back on again.

**Comment by bkurowski** [comment]
Still not resolves my problem. 
Can anyone see what am I doing wrong ? 

Cheers.

**Comment by wrathagom** [comment]
Sorry @bkurowski lost track of this one.

If it is normal basic auth, then you actually include it in the URL like this:

```
https://gooduser:secretpassword@www.example.com/webcallback?foo=bar
```

from [SO](https://stackoverflow.com/questions/2716990/http-basic-authentication-credentials-passed-in-url-and-encryption)

The new-ui, which should have it's first release in the coming week or two make this easier with dedicated fields for basic auth.

**Comment by bkurowski** [comment]
Thank you, I was actually looking at it before, i know that way too. 
I was just wondering if we could do it somehow through Articulate. 
Now i see new UI will contain this option too. 

Perfect, thank you for your time,

Cheers.
