### ISSUE TITLE
BUG: Able to enter a blank response in Action New UI

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#469]
When creating action and going to the response tab, the user is able to just press enter in the response textbox, with no error message. Should not be allowed to enter a response with no text. The same situation if the user just puts a space in as well, should not be allowed to enter a blank response. Example attached below:
[blank response.zip](https://github.com/samtecspg/articulate/files/2756078/blank.response.zip)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/35944f506eb834eb3f1a6740523ece0e3b91f553
