### ISSUE TITLE
Save button after editing agent not centered New UI

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#471]
Seems when in windowed mode the Save button on creating agent is not properly aligned.
![image](https://user-images.githubusercontent.com/42249324/51223516-0b398180-1910-11e9-80bc-bbbe5b709f61.png)
It goes from top right to there at top left. A bit odd

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/9745d77ed1099f922f08f4bc4a3c91b8f12e62b9
