### ISSUE TITLE
Notification red dot indicates errors and successes

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#477]
The red dot used for notifications in the chat panel is the same red dot used as an error indicator for validation. This could cause confusion. I propose a multi-colored indicator to differentiate between errors and success notifications. Or no red dot at all for information notifications.

**Comment by dcalvom** [comment]
@broham89 what about a blue dot for non-error notifications?

**Comment by dcalvom** [comment]
@wrathagom @broham89 what color should we use?

**Comment by broham89** [comment]
Notification color can be blue `#358FEC` 
<img width="289" alt="screen shot 2019-02-18 at 2 49 15 pm" src="https://user-images.githubusercontent.com/11262149/52975770-68e84000-338c-11e9-812b-cceeab22a37d.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/428cf6aae289862873524335f387673805dd37cb
