### ISSUE TITLE
Add timeout for notifications so they disappear after a certain amount of time

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#478]
During initial agent creation and quick succession edits it is possible to fill up the chat panel with an abundance of alerts. I propose limiting notifications to one of each type: training, action creation, etc.

We should design a way to indicate stacked notifications in the case of multiple of the same type. As well as an interaction that allows clearing one at a time or all at once for a particular stack.

**Comment by dcalvom** [comment]
@broham89 @wrathagom what is thought about this one? I agree sometimes the notifications are too much. I have to be honest that for me those aren't quite useful as I'm the developer, so I think Matt's point of view as an external user is very valuable.

**Comment by wrathagom** [comment]
I think I am going to go a different direction. Let's combine this one with #477 and say errors persist forever, but let's put a timeout on notifications so they automatically clear from the list.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5ff2cf353aef95fc184910964e8ecf4f5175a6d7
