### ISSUE TITLE
Consolidate sayings and keywords into a dialogue tab

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#480]
Knowing the intention of adding more features in the coming months. We should consider re-locating the User Sayings and Keywords into a `Dialogue` tab. This would allow us the space to create a tab for actions and possible categories if desired.

**Comment by wrathagom** [comment]
I like it too. We're slowly moving every page to where it has tabs and sub-tabs. I like the consistency.

**Comment by broham89** [comment]
I think i need a walkthrough of what that might look like @wrathagom. I'm confused by if having the `Dialogue`> `sayings` + `keywords` > `actions` + `categories`?

**Comment by spg-matt** [comment]
The only change is to move sayings and keywords off of the main tab bar and into sub tabs under a new Dialogue tab.

Dialogue would have two sub tabs: sayings and keywords. Actions and categories don't have tabs anywhere right now. I can MS paint it if need be.

**Comment by broham89** [comment]
@spg-matt  like this?

![dialoguetab-example 1](https://user-images.githubusercontent.com/11262149/52017978-8d987880-24ae-11e9-8d2f-2370f3c85cd2.png)

**Comment by wrathagom** [comment]
I do like that... could probably leave the train button on the top row then.

@broham89 I can foresee needing tabs/pages for:

- Sayings
- Keywords
- Actions
- Categories
- Analytics
- Ubiquity
- Review
- Users

The goal is to find a neat place to tuck all of them so the screen is never overwhelming/overcrowded and nothing is ever more than a couple clicks away. In a lot of the screens we've established this idea of having two rows of tabs. Maybe we can use that to group similar pages:

- Dialogue
  - Sayings
  - Keywords
  - Actions
  - Categories
- Analytics
  - Review
  - Metrics
- Agent
  - Users
  - Ubiquity

Although really users and ubiquity exist at the same level as agents... Have to think about that one.

**Comment by wrathagom** [comment]
yeah, it's really more like:

- Agents
  - Dialogue
    - Sayings
    - Keywords
    - Actions
    - Categories
  - Analytics
    - Review
    - Metrics
- Users
- Channels (Ubiquity)

**Comment by wrathagom** [comment]
@broham89 when I envision this your [image](url
https://github.com/samtecspg/articulate/issues/480#issuecomment-459140943) is close, but not quite there.

On the line next to Agent: Samson there would still be two tabs for now: Dialogue and Review. When you click on Dialogue then you would get the second line of tabs. In this case just Sayings and Keywords

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/1e577161a2cabae443aed65785d79998b708fe6a
