### ISSUE TITLE
Keywords list requires clicking directly on keyword name

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#483]
This is inconvenient. We should allow clicking anywhere on the row.

**Comment by dcalvom** [comment]
@spg-matt this applies for all screen where keywords lists are used? If so, could you provide a gif or something?

As far as I understand you can't click any other place beside keyword name to tag an entity. This is what I did, tell me if this was your error pelase

![keyword list](https://user-images.githubusercontent.com/7228045/51693705-18680780-1fc5-11e9-8ccc-ca28673a7ef1.gif)

**Comment by spg-matt** [comment]
Sorry. @dcalvom I meant the list of keywords on the keywords tab.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/cc0b215aceae439abeab677ef1a7c84d623bd526
