### ISSUE TITLE
Allow save, exit, or save and exit on actions, keywords, and categories

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#484]
The exit button does what it says, but the save button **saves and exits** sometimes it is more convenient to stay in place while testing a web-hook response.

This could be consolidated into a save and exit button if the exit button prompted you to save and the save button prompted you to exit. Though that is more clicks. More clicks vs more screen real-estate.

**Comment by dcalvom** [comment]
Agree, sometimes is very annoying to be kicked out of the screen if you are editing

**Comment by dcalvom** [comment]
@wrathagom @broham89 what is the best way to approach this?

**Comment by broham89** [comment]
![action create page](https://user-images.githubusercontent.com/11262149/51707644-5c6c0400-1fe7-11e9-9121-ecfc739cb818.png)
I've currently have the buttons laid out like this... exit without saving will throw a warning prompt to save and exit or exit without saving.
![Uploading action page - exit prompt.png…]()

**Comment by wrathagom** [comment]
It what does save do?

And it wouldn’t be delete exit right? It would just be exit without saving. Meaning we’re not going to delete the entire object just because they left.

**Comment by broham89** [comment]
Maybe this prompt is better 
![action page - exit prompt](https://user-images.githubusercontent.com/11262149/51708938-c508b000-1fea-11e9-9bac-0a6d2fddf4b6.png)

**Comment by wrathagom** [comment]
What does save do?

**Comment by broham89** [comment]
If it's the user first time creating an action it should be `finish/create` but after that the btn should switch to `save` to tell the user they're now updating "saving"  their changes.

**Comment by wrathagom** [comment]
@dcalvom is it hard to detect whether something has been modified or not?

**Comment by dcalvom** [comment]
I think the proposed design doesn't fit to what @spg-matt is asking for. He would like to be able to save and remain on the screen.

**Comment by dcalvom** [comment]
I think @broham89 talked in the past about an animation, I think something like this:

![save](https://user-images.githubusercontent.com/7228045/52008725-de03dc00-2496-11e9-9fbf-d135e2da6adb.gif)

**Comment by wrathagom** [comment]
So I think in the end there are two buttons on the page: Save and Exit. Save leaves you on the same page. When clicking exit if there are no changes it just exits, if there are changes it prompts to save and exit or exit without savings.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/7b22b7197a3af1c42581bd717e476fe2a644c14c
