### ISSUE TITLE
Disable modifiers until keyword has been saved

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#485]
Defining modifiers that use the keyword value requires that the keyword has already been saved. We should disable the tab until the keyword has been saved. A tool-tip should inform the user that modifiers are only available after the keyword has been saved.

Or find a way to add the currently-being-created keyword in the modifiers sayings highlights.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/2ecdd53bc8122ea4b64963bf0bee7ae45d020126

**Comment by wrathagom** [comment]
@dcalvom this one isn't working for me. I still see the tab and can click on it even when creating a brand new keyword.

**Comment by wrathagom** [comment]
@dcalvom fixed this yesterday with https://github.com/samtecspg/articulate/commit/b6954fa8be7dfb27d97a8c79e24b0f93853ae7a2
