### ISSUE TITLE
Starting a conversation with a modifier returns an error

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#487]
Start a conversation with a modifiers. For example `remove the onions`.

```
api_1            | { error:
api_1            |    TypeError: Cannot read property 'action' of undefined
api_1            |        at action (/usr/src/app/lib/services/agent/agent.converse.service.js:484:125)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
```

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e066d5738b7c240a41d9c4c7c2e51fc09dd467b9

@wrathagom please reopen this one if you want to handle this differently. But now it throws the fallback action
