### ISSUE TITLE
Error with only a single modifier

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#488]
Create an agent with only a single modifier and this error causes converse to fail:

```
api_1            | { error:
api_1            |    TypeError: Cannot read property 'split' of null
api_1            |        at AgentService.split (/usr/src/app/lib/services/agent/agent.converse.service.js:417:98)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
```

**Comment by dcalvom** [comment]
@spg-matt I will need more information for debugging this case. I just create an agent with a single modifier but what `converse` endpoint returns me is that there aren't any categories for the agent. That's an error thrown by the `parse` method that it's called by `converse`.

Also, we did a couple of changes that could also change the behavior of this error.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e4aea83c008df974ec9ddb36b3c9bb918edaaa1d
