### ISSUE TITLE
No edit/delete button for fallback action New UI

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#489]
Need triple dots/edit/delete button under fallback action selection in agent screen. Can only create fallback action as of now, can't edit or delete on the agent page. Thought it can be edited int he Sayings tab, it should be able to be edited in the Agent tab IMHO.

**Comment by dcalvom** [comment]
This is something we have been saying as a must-have feature. Sorry, I'm not up to date with designs @broham89, but we already have something for edit actions?

**Comment by broham89** [comment]
@dcalvom Where exactly in fallback action page are you referring to? Could you screenshot the possible area?

**Comment by RussellSPG** [comment]
@broham89 
![fallback issue](https://user-images.githubusercontent.com/42249324/51711351-d4432a00-1ff9-11e9-9d11-088c1d3c1e85.jpg)

**Comment by wrathagom** [comment]
and If you add an x/delete button, then do we have that on every action drop down? There are three that I know of: sayings input, sayings list, fallback list.

**Comment by broham89** [comment]
![agent fallback 2](https://user-images.githubusercontent.com/11262149/51716285-da3d0900-2001-11e9-8c02-7c65b35d34a6.png)

**Comment by RussellSPG** [comment]
nice

**Comment by RussellSPG** [comment]
what about the delete button? It should be right near the edit.

**Comment by wrathagom** [comment]
Were doing away with delete buttons and going for a consistent delete button on the bottom of the page. So you edit the action, then delete it.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/12e0a6bad11c943874e914664b131cfb46f708e0
