### ISSUE TITLE
Add notification when trying to delete category if category has content

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#492]
### Feature Request
When clicking the drop down for category select and selecting a category, there is an edit button. However, others may not know that sayings should be deleted in order to make changes to it. I suggest implementing a help icon or a "!" may be better that tells the user any sayings must be deleted before making changes, and not allow the user to edit the category until they are.

This complicates things because the Category Name should be able to be changed without having to delete the sayings IMHO.

**Comment by dcalvom** [comment]
I think this could be tackled just by showing a notification that the category wasn't deleted and the reason why. @wrathagom what you think?

**Comment by wrathagom** [comment]
yep, makes sense to me. @dcalvom this API still does not allow re-naming Categories right?
