### ISSUE TITLE
Gain webhook data using dynamic body parse

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#494]
### Question

Hi guys, I am trying to gain data usong POST from one of the webhooks, but i need to pass some details in the body (JSON). It works when passing it like on picture below (HARDCODED) but i need to complete it for dynamic use.

![image](https://user-images.githubusercontent.com/40358189/51599673-1f751400-1ef8-11e9-94bd-4eaf81bb1855.png)

When passing this,
`{
               "nodename": {{slots.NodeNames.original}},
               "interval": {{slots.NodeTimes.original}}
}`

And this is the error i am getting on the console.

![image](https://user-images.githubusercontent.com/40358189/51600651-6106be80-1efa-11e9-9ff7-f585544222e7.png)

It is not working as expected. I know i am having problem with the actual syntax.
Any ideas ? 

Thanks.

**Comment by bkurowski** [comment]
Never mind it should be.

`{
               "nodename": {{{JSONstringify slots.NodeNames.original}}},
               "interval": {{{JSONstringify slots.NodeTimes.value}}}
}`

My Bad didn't look at the sample provided by articulate,
Cheers !

**Comment by wrathagom** [comment]
@bkurowski if you are interested in joining a private slack channel with the Articulate team and a few other power users can you send me an e-mail? My email is in my profile.
