### ISSUE TITLE
Can I use Articulate over my own Rasa NLU and Core installation?

### ISSUE THREAD

**Issue by github-contenta** [samtecspg/articulate#496]
I have Rasa Core and NLU up and running, integrated with Facebook and Rasa Webchat. I'd like to have an UI to manage intents, entities, training, etc. Can this be achieved with Articulate?

If not, can I migrate my bots to Articulate?

Also, I couldn't find any info on how to connect Articulate with Facebook or other platforms. I know how to do it with a native Rasa Core + NLU, but as I'm not the one launching Rasa with Articulate, I don't know how to do this.

**Comment by wrathagom** [comment]
Articulate doesn't take advantage of Core yet, we implement our own dialogue system. At the moment we don't have any easy way to convert Rasa NLU training data/stories into our format.
