### ISSUE TITLE
Worked, then didn't, now can't start APIs.

### ISSUE THREAD

**Issue by mike-wittmann** [samtecspg/articulate#497]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

I had the system installed and running. I created an agent and was working through the setup when I started getting Agent Head Missing errors. I rebooted the server and that didn't help. I did the docker-compose down, and now when I try to do the docker-compose up I get these messages:

root@lamp:/var/www/rvbot.me/public_html/articulate# API_URL=http://68.183.99.13:7500 docker-compose up
Creating network "articulate_alpha-nlu-network" with the default driver
Creating articulate_rasa_1 ... 
Creating articulate_ui_1 ... 
Creating articulate_api_1 ... 
Creating articulate_duckling_1 ... 
Creating articulate_rasa_1
Creating articulate_redis_1 ... 
Creating articulate_ui_1
Creating articulate_api_1
Creating articulate_duckling_1
Creating articulate_api_1 ... error

Creating articulate_ui_1 ... error

Creating articulate_duckling_1 ... error

Creating articulate_rasa_1 ... error

Creating articulate_redis_1 ... error

ERROR: for articulate_redis_1  Cannot start service redis: error while creating mount source path '/var/www/rvbot.me/public_html/articulate/local-storage/redis-data': mkdir /var/www: read-only file system

ERROR: for redis  Cannot start service redis: error while creating mount source path '/var/www/rvbot.me/public_html/articulate/local-storage/redis-data': mkdir /var/www: read-only file system

ERROR: for rasa  Cannot start service rasa: error while creating mount source path '/var/www/rvbot.me/public_html/articulate/local-storage/rasa/logs': mkdir /var/www: read-only file system

ERROR: for api  Cannot start service api: driver failed programming external connectivity on endpoint articulate_api_1 (c262451f43b5907501990905ed8dc98a10218a37ee4744a4144f06b695c7f213): Bind for 0.0.0.0:7500 failed: port is already allocated

ERROR: for ui  Cannot start service ui: driver failed programming external connectivity on endpoint articulate_ui_1 (d7bf5eee01275b89ab839df283dcf26ec27524c8aa61848613917be37c36528c): Bind for 0.0.0.0:3000 failed: port is already allocated

ERROR: for duckling  Cannot start service duckling: driver failed programming external connectivity on endpoint articulate_duckling_1 (501a682e5dabbd3858b4a792ed11dd359e3ade4678e494ef9d2def8eae73a6c8): Bind for 0.0.0.0:8000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
root@lamp:/var/www/rvbot.me/public_html/articulate# 

- Did you download a release or pull from Master? Which release?

Downloaded the release v0.13.0

- What operating system are you running?

Ubuntu on DigitalOcean

- Are you running locally or in the cloud?

Cloud - DigitalOcean LAMP install

- Which browser are you using?

Multiple
----

**Comment by wrathagom** [comment]
@mike-wittmann from the directory where you downloaded/cloned Articulate, can you tell me what `docker-compose ps` shows?

**Comment by mike-wittmann** [comment]
root@lamp:/var/www/rvbot.me/public_html/articulate# docker-compose ps
        Name                       Command                State     Ports
-------------------------------------------------------------------------
articulate_api_1        node start.js                    Exit 128        
articulate_duckling_1   /bin/sh -c stack exec duck ...   Exit 128        
articulate_rasa_1       ./entrypoint.sh start --pa ...   Exit 128        
articulate_redis_1      docker-entrypoint.sh redis ...   Exit 128        
articulate_ui_1         yarn start                       Exit 128

**Comment by wrathagom** [comment]
So there are two errors in your original issue:

```
Bind for 0.0.0.0:3000 failed: port is already allocated
```

Which suggest something is already using that port, Maybe you tried to start everything twice?

and

```
error while creating mount source path '/var/www/rvbot.me/public_html/articulate/local-storage/redis-data': mkdir /var/www: read-only file system
```

the `/var/www` location is owned by root usually so you don't have permissions to create a directory there. You'll need to modify the folder permissions or move to another location.

Rather than running from /var/www likely you should run in a different directory and use nginx/apache to create a reverse proxy. We have a tutorial that covers most of that: https://blog.spg.ai/basic-access-restrictions-for-articulate-58e77c931ca3

**Comment by wrathagom** [comment]
@mike-wittmann if you're just trying to test things then I can give you a cloud instance to play with, where we manage the infrastructure. If you're interested, then long term if you stuck with Articulate we could talk about helping you get it running on your own server.

As for your specific issue, I think you need to move it out of `/var/www` and run it in something like `/usr/local/src/` then you would use a [reverse proxy](https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html) to route traffic to the correct port.

**Comment by mike-wittmann** [comment]
For the time being, if you could set me up with a cloud instance that would be amazing. I'd love to figure out the rest of the issue, but for now just getting Articulate set up so we can play around with it would help a ton.

**Comment by wrathagom** [comment]
Hey @mike-wittmann I've got an instance ready for you. Can you send me an email (address in profile) or get ahold of me on Gitter. That way I can give you the password to your instance.
