### ISSUE TITLE
On agent page main tab and parameters tab need icons

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#499]
Settings has an icon, but the other tabs do not. So remove the one from settings or add one to the other tabs.

**Comment by wrathagom** [comment]
@broham89 for reference
![image](https://user-images.githubusercontent.com/1779894/51781403-26fa1000-20e6-11e9-93cd-4da965fc2086.png)

**Comment by wrathagom** [comment]
@dcalvom for now let's just remove the icon from settings. So icons on the top row, but none on the sub-tab row.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3e876812428d67ddc4f3d00ff78525b25ef9f32b
