### ISSUE TITLE
Editing an agent while training results in false up to date message

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#504]
If you start training an agent, and then add a saying to the sayings list while it is training, the agent will show as Out of Date. Once the training process completes it will change the agent status to trained. This message is misleading since there have been changes to the agent, which have not been trained. The expected status of the agent should still be out of date.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/7beeaf40c596f0c1ea6e06ed00982f20f42cde83
