### ISSUE TITLE
Small changes to main agents page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#505]
![image](https://user-images.githubusercontent.com/1779894/51789875-b261b880-215b-11e9-96a9-e2bfde89350c.png)

- The primary text should just say `Agents:`
- Let's remove the search bar for now
- Can you add a help video button after Agent

**Comment by wrathagom** [comment]
Should we even show the chat panel/button on the main page?

If we choose to keep it there we need to clean up this error message, or disable the chat input since we don't know which agent they are chatting with:

![image](https://user-images.githubusercontent.com/1779894/51789894-171d1300-215c-11e9-80db-5ac2835a8fc9.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5d47fb4521d845e29f6fd21747dfd9c37206d1c7
