### ISSUE TITLE
we need to update swagger configuration to respect env for base path, host, etc

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#508]
Right now we've lost all of our configurability that we had in the old API.

**Comment by wrathagom** [comment]
This was done, but still need to add handling for the other two I mentioned in Slack, will have to go looking for them.

**Comment by wrathagom** [comment]
I was under the impression that the old UI would magically find the right IP when API_URL was left unset and running on a cloud VM... I was wrong.

the old UI:

- assumes localhost and default ports
- requires a single ENV variable of API_URL when in a cloud VM/docker toolbox

Using the API_URL and inspecting the swagger.json file reveals that the swagger host is showing up as the host IP without being set.

Setting API_URL on the new UI causes another problem:
```
[Error] Failed to load resource: Could not connect to the server. (agent, line 0)
```

this is because in this instance the swagger.json reveals that the swagger host is being set to `0.0.0.0` additionally the.

This line in the API likely sets this: https://github.com/samtecspg/articulate/blob/42d3dc0d1f39d7f77758a587fd629fa99ed72b88/api/server/manifest.js#L22

whenever I remove that line the swagger host defaults to the ID of the container. Also not helpful. I can't quite figure out why in the new API it defaults to the container name and in the old UI it defaults to the host IP.

**Comment by wrathagom** [comment]
So at the moment to start on a VM you have to run:

```
API_URL=http://my.url:7500 WSS_URL=ws://my.url:7500 SWAGGER_HOST=my.url:7500 docker-compose up
```

yuck.

**Comment by wrathagom** [comment]
@malave maybe we should just re-adjust the env variables. For example we could use one global env variable for `API_HOST=123.45.68.456` then the web socket defaults to ws ad the API defaults to http. We then provide a `API_SCHEME` and `WS_SCHEME` to set https and was when needed.

**Comment by malave** [comment]
Closed with: https://github.com/samtecspg/articulate/commit/3a2be8b2ac3b05a63ece9fece3888b96de245927
