### ISSUE TITLE
Implement proper async call of sagas

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#51]
Right now where are mostly calling an action, wait for the response and then either update the UI or redirect. 

There are a few cases where another saga must be call and I had to perform some work arounds but there are some cases where this just created am unexpected behavior. 

According to the redux [page](https://redux.js.org/docs/advanced/AsyncActions.html#async-action-creators) we could use `redux-thunk` or other libraries.

Redux Sagas is supposed to be able to handle [this](https://redux-saga.js.org/docs/advanced/SequencingSagas.html) but so far I haven't been successful doing this.

The purpose of this issue is to investigate how to perform this with sagas or other libraries. Also part of the implementation should stop the rest of the actions after an error.

Here are the scenarios that I found so far:

- Delete Domain, Intent and Entity: This required that we re populate the lists after deleting. (working work around in place but is not ideal code)
- Agent delete: reload list of available agents, redirect current agent, redirect to `/` (currently the redirect doesn't work and sometime the agent list doesn't populate)
- Create Domain, Intent, Entity: Redirect to list (not implemented)

**Comment by wrathagom** [comment]
@malave when I select a domain in the intent list page the list doesn't always load is that related?

Also the client error console fills up with
```
Unhandled Promise Rejection: Invariant Violation: parentComponent must be a valid React Component
```

every time I navigate to a list page. Is that related?

**Comment by wrathagom** [comment]
I created #59 just in case

**Comment by malave** [comment]
Errors reported by @dcalvom:

- [ ] When you create an agent the redirect is to http://localhost:3500/wizard/entity-intent instead of http://localhost:3500/wizard/domain
- [ ] The intent post doesn't have the intent name inlcuded. In the past once the intent was created the reference to the id was pssed
- [ ] The list of domains wasn't loaded, if you click on the `domains` link in the menu twice, the list is loaded.
- [ ] The combo of domains in the intent list page was loaded, but was once you pick any domain the intents list isn't loaded. If you click again in the `intents` - link in the menu the domain list goes empty
- [ ] Agent entities wasn't loaded, if you click twice in the `entities` link in the menu, the list is loaded.
- [ ] AgentName is not being filled in the webhook request
- [ ] Delete agent doesn't works
- [ ] Delete domain, intent and entity doesn't works (I don't know if this is already implemented)
