### ISSUE TITLE
Request for confirmation

### ISSUE THREAD

**Issue by cloud1250x4** [samtecspg/articulate#510]
### Issues

I have a heard time figuring out how to ask for confirmation..

Client : Hi
Bot: Hello
Client: I'm looking for information about your cheapest vps
Bot: Just to confirm, you're looking for information about our cheapest vps?
Client: Yes
Bot: Here's a link that should cover that : link
Client: Thanks
Bot: Have a nice day

- Did you download a release or pull from Master? Which release? Latest release
- What operating system are you running? Mac OS
- Are you running locally or in the cloud? Local
- Which browser are you using? Firefox

**Comment by wrathagom** [comment]
@cloud1250x4 can you confirm me if you pulled from master? Or if you are running release 0.13.0? 0.13.0 is what is shown on our webpage: https://spg.ai/articulate

In 0.13.0 it was hard to do confirmations and follow-ups. The code that is on master (no official release yet) has new functionality to make this easier.

**Comment by cloud1250x4** [comment]
Hi, I'm using the 0.13.0 release..

I've been monitoring your latest commits and the new version looks amazing.. I know you're still working on it actively.. should I pull from master anyway?

Is there any breaking change between 0.13 and 0.15?

**Comment by wrathagom** [comment]
You can pull from master it is about 90% stable/complete. You'd be doing us a favor testing it out.

That being said it contains major breaking changes. So you will have to re-create your agent in the new UI.

**Comment by cloud1250x4** [comment]
Sure.

I'll try that today.

Is there anything I need to know before trying it?

**Comment by wrathagom** [comment]
I don't think so, jump on our Gitter if you need more live help or create another issue. Docs for that UI are completely non-existent, so the way to get confirmations may not be evident.

I could do a video call with you to walk you through the basics if you're interested.

**Comment by wrathagom** [comment]
click the pluses by the sayings and "tag" them with actions.

**Comment by wrathagom** [comment]
![image](https://user-images.githubusercontent.com/1779894/51938630-95d3b380-23db-11e9-824f-3bd22108a7fd.png)

**Comment by cloud1250x4** [comment]
so action response need action too?!

**Comment by wrathagom** [comment]
oh, sorry I mistook the screen I was looking at. 

The error says you are only providing one training example for each action Is that true? Per what it says and the notification in the UI all actions have to have at least two examples.

**Comment by cloud1250x4** [comment]
![screen shot 2019-01-29 at 4 07 11 pm](https://user-images.githubusercontent.com/2974803/51940439-fe249400-23df-11e9-8bb1-bd02af7205d0.png)

this is what I have currently

**Comment by wrathagom** [comment]
Why do the categories directly match the actions? Think of categories as groups. So we usually create a category called Small Talk which contains the sayings for actions like Greet, Goodbye, Gratitude, etc.

It is failing to train because you have one saying tagged with the goodbye action inside of the greetings category.

**Comment by cloud1250x4** [comment]
Okay, yes I remember now! 

It worked thanks!

Deleting category that has saying associated doesn't work.. it doesn't tell you why unless you look at the terminal

**Comment by wrathagom** [comment]
Is there not a notification in the chat panel?

**Comment by cloud1250x4** [comment]
Wow yes there is! but I couldn't notice it because I had a discussion with the bot and the notification was hidden because of that

**Comment by cloud1250x4** [comment]
Hm when creating an action.. my first intuition was to.. write the name of the action and click save.. At first, I didn't notice the notification about why it couldn't save or even the small red dot on the response tab..

About categories vs actions.. I think providing an example in the small text when you're creating a category would have made it clear (to me atleast)

Example:
The Smalltalk category will usually have "sayings" related to greetings and goodbye.

**Comment by wrathagom** [comment]
okay, again thanks for being the first test victim and providing wonderful feedback.

I'm still up for a video call if you think it will help you over the learning curve.

Did you see or try the help video buttons on any of the pages?

**Comment by cloud1250x4** [comment]
Yes I've clicked on the help button, it's a placeholder right now for future video guide right?

Also, for now, I'll try to see how far I can get without a video call.. but I won't forget that offer haha

Thank you!

**Comment by wrathagom** [comment]
Yeah, but good to know you clicked on it. If we had those in place hopefully they would’ve helped...

Good luck. And let us know if you run into more hurdles.
