### ISSUE TITLE
When disabled add a tooltip to modifiers tab

### ISSUE THREAD

**Issue by spg-matt** [samtecspg/articulate#513]
This should say:

> You must ave the keyword before creating modifiers.

**Comment by wrathagom** [comment]
@dcalvom @broham89 do we already have a style for tooltips? Or is there a better way to convey this info (a notification maybe)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/dff1d54a2582b3158eba6146ff05cb47731f38ab

**Comment by broham89** [comment]
we do have a style for tooltips and a notification could be useful here for more clarification. I also implemented an error box to appear on top to quickly summarize the issue. And the user could open flap also to see the error notification for more clarification. 
![error screen](https://user-images.githubusercontent.com/11262149/52017512-275f2600-24ad-11e9-92b7-f31d3544a301.png)
