### ISSUE TITLE
We need to apply a <th> style to the review page.

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#516]
Right now the header looks just like every other row:

![image](https://user-images.githubusercontent.com/1779894/51912056-54bead80-23a1-11e9-9dc9-b109c1f49fea.png)

**Comment by dcalvom** [comment]
@broham89 do you already have this implemented?

**Comment by broham89** [comment]
have a `max-width:{}` to the right portion of the review (caegory, action...) and position them `right:0` or `float:right`

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5d3baac4b11a2200aab8f1e5275fa7dc7837146e

**Comment by broham89** [comment]
[active.svg.zip](https://github.com/samtecspg/articulate/files/2830206/active.svg.zip)
here is an updated copy icon
