### ISSUE TITLE
Config rasa pipeline instead of having two rasa containers

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#52]
We have two rasa instances configured in the docker-compose file. One is for full training and the other one is just for train entity recognition. We need to get rid of the second one and use the pipeline parameter in the train call to avoid having two containers.

This is how you call the training process with a custom pipeline:

`http://localhost:5000/train?project=pipeline-test&fixed_model_name=pipeline3-test&pipeline=nlp_spacy,tokenizer_spacy,ner_crf,ner_synonyms,ner_spacy`

**Comment by wrathagom** [comment]
@dcalvom this is finished right?
