### ISSUE TITLE
review page copy fallback

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#522]
if you try copying a saying from the review page that wasn't recognized, it fails. I am assuming this is because you're copying direct to the list and if it isn't recognized then there is no category/action. Can we do a simple fallback here: if the utterance has an action and category copy it direct to the list. If it doesn't or if copying throws an error, then drop it into the sayings form input?

**Comment by dcalvom** [comment]
@wrathagom After a minor fix now you can copy any saying, but, the category that will be assigned will be the first category in the parse results, what about if we enable category selection for sayings without category recognized, so in that way users can choose the proper category and press copy
