### ISSUE TITLE
Distinguish difference between inputs

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#525]
### Issues

Using : 0.13 version. On Linux.

Hello there! I was trying to figure out one small issue i have, which is as follows:
I have been trying to add 3 separate questions in separate intents like:

User: Run survey for Berlin
User: Run survey for Paris
User: Run survey for Madrid

With each message i am passing body which includes different data to be passed to the same webhook.
The problem is that Articulate doesn't see difference between each of these three inputs.
When i say i want to run for Berlin, than data for Madrid is sending to the webhook.
My question is, how make articulate distinguish which city the user is specifying ?

Cheers

**Comment by wrathagom** [comment]
I would combine into a single intent with Berlin/Paris/Madrid as an entity.

Then you can use handlebars to format the web hook based on the slot value:

```
{{#eq slots.city.value 'berlin'}}
  berlin content here....
{{/eq}}
```

**Comment by dcalvom** [comment]
Based on the agent you share us for the other issue and given that we test that it works, we are going to close this issue
