### ISSUE TITLE
Add date to review table and allow sorting on it

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#528]
Right now the table starts out sorted by data (maybe id) so the most recent chats show up on top, but then you can sort by confidence. There is no way to go back to sorting by date. Feels like we should show a timestamp and allow sorting on it.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e80c4f45da2c5c6eae811e8023947fdb61a31fe3
