### ISSUE TITLE
Show "Modifier" if phrase is a modifier

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#529]
Right now the review screen show she full model name, which is a bit ugly/confusing. This should just say `Modifier` if the utterance was a modifier.

![image](https://user-images.githubusercontent.com/1779894/52131834-cf8b0100-260b-11e9-82b0-a43c348e84f4.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3485a0ca7df825f7ab21509d60d043000a8ad3a4
