### ISSUE TITLE
Recreate/Improve doc endpoint

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#53]
In the past we had an endpoint that let us retrieve the result of the document parsing. We need to recreate that endpoint to let users retrieve the result of a document parse.

**Comment by dcalvom** [comment]
I pushed 4 days ago a basic `doc` endpoint to find a document by id. I think we had in the past some other methods, but at least this is the first advance on recreating the `doc` endpoint.

The commit was https://github.com/samtecspg/articulate/commit/10c8685643f5e52f6efa983aba4521a41a99ebdd

**Comment by wrathagom** [comment]
We're going to take advantage of this issue to introduce Elasticsearch into the stack. So here's what I'd like to see done to address this particular issue:

- Add ES and Kibana into the compose
- Add ES URL to the settings page
- Make doc storage dependent upon ES connection - If we can communicate with ES then we store off the docs, if not then we don't. If there is a connection specified and the connection is failing we should throw a warning the console and probably in the UI.
 - Probably will need to manage index patterns/mappings. I'm most worried about how to map `webhookResponse` as we don't control it and it could contain an unknown data type.

Once we're storing these off in ES I'll probably have some adjustments to how they're stored. But for now let's just get them going into ES.

**Comment by wrathagom** [comment]
Done by @malave on 
https://github.com/samtecspg/articulate/commit/bdbc52fe870c04196f2ad6eae063c407f2c1d686
