### ISSUE TITLE
Sorting ignores N/A values

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#530]
Sorting the review table ignores NA values, so they always stay at the bottom of the table. Ideally these would behave the same as 0... so when sorting by category score Ascending, they show up at the top.

![image](https://user-images.githubusercontent.com/1779894/52131910-06611700-260c-11e9-96aa-4ed40adff0e6.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/2b18feb7a9bc7affdc2b91820f35e1854d2df5ef
