### ISSUE TITLE
Clear Validation errors on a successful save

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#533]
When clicking Sayings, adding category, and clicking save without a Name. Shows the error text. Which is fine, however when entering a name, and clicking save again, the red error text doesn't disappear.

**Comment by wrathagom** [comment]
@dcalvom I imagine this is easier to implement as just a `clear validation errors on save`, rather than watching each field to determine if they have been updated and removing the validation before saving?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/126aad44febfb11aeef77973d14f2a46ed7a0c9c
