### ISSUE TITLE
Implement edit/delete buttons for each keyword in Keywords menu.

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#534]
### Feature Request

As of now there is no edit/delete icon to quickly delete keywords from the menu. A keyword can only be deleted by clicking on it, then on its page, hitting the delete button. Being able to quickly remove them from the menu, saves time.

**Comment by wrathagom** [comment]
I don't think this makes sense for keywords. Given that you have to highlight a word for the menu to show-up, I don't know why you would highlight one and then choose to delete a keyword.
