### ISSUE TITLE
BUG: Click next button on keywords page results in blank page.

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#535]
### Issues

After clicking the Next button in keywords pages a few times, it may result in showing the keywords completely blank, instead of to the next page.
![image](https://user-images.githubusercontent.com/42249324/52171470-a8c3ec00-272b-11e9-9882-16f484ad4593.png)

**Comment by RussellSPG** [comment]
Edit: This may be a server issue on the instance, I'm not sure but the problem isn't occurring as of now. When it did occur, I forgot to gather the console error sorry.

**Comment by wrathagom** [comment]
I couldn't reproduce either. Agree that it may be network related. I'm closing for now, but we should keep an eye out for it happening again.
