### ISSUE TITLE
Slots are not being read by Agent Response

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#537]
### Issues
Using slots, issue.
Just decided to test slots option. Built sample questions like:

`
list problems on GTD_1234`
`show me problems in GTD_4321
`
GTD_1234, GTD_4321 these are keywords values assigned to name Cell.

For now I am just testing when the user enters this question I want to receive just the value of the Keyword which is GTD_1234 OR GTD_4321.
My agent response look like this:
`{{slots.Cell.original}}`
Webhook is not being used in this example.

So i want to view just the keyword value that is passed by the user.

The problem here is that I get `Sorry we're not sure how to respond.`
Where as this same approach worked for me on the older version. Has anything changed in order to complete this simple task ?

**Comment by wrathagom** [comment]
Can you make sure that GTD_1234 is being recognized as an entity? If this is on 0.13 you'll need to go to the API documentation page and try the `/agent/{agentId}/parse` endpoint.

**Comment by bkurowski** [comment]
I made sure that GTD_1234 is recognized as entity/keyword just like below:
![image](https://user-images.githubusercontent.com/40358189/52213739-da51ca00-2887-11e9-9c76-a1201f673605.png)

This is not on 0.13 currently. This one is from the master pull with new UI.

**Comment by bkurowski** [comment]
Also this is the error I have just observed I am getting after sending this query.

![image](https://user-images.githubusercontent.com/40358189/52214027-9ad7ad80-2888-11e9-9ab9-ffa6997a817d.png)

**Comment by dcalvom** [comment]
could you click the `See source` link in the agent response card and share us the data that is present in the different tabs.

**Comment by bkurowski** [comment]
***Rasa Parse Results***
`[
  {
    "docId": "NbRFvWgBvzXi618yXPCq",
    "category": "TestSlots",
    "project": "Ericsson",
    "model": "TestSlots_just_er_596d3382-903c-a0c6-6e67-4f55d9bb6163",
    "keywords": [
      {
        "start": 8,
        "end": 14,
        "value": {
          "value": "Madrid"
        },
        "confidence": 0.9118135031968373,
        "extractor": "ner_crf",
        "processors": [
          "ner_synonyms"
        ],
        "keyword": "City"
      },
      {
        "value": {
          "value": "Madrid"
        },
        "start": 8,
        "confidence": null,
        "end": 14,
        "extractor": "ner_spacy",
        "keyword": "sys.spacy_gpe"
      }
    ],
    "action": {
      "name": "SlotsAction",
      "confidence": 1
    },
    "elapsed_time_ms": 135,
    "categoryScore": 0.9585608839988708
  },
  {
    "docId": "NbRFvWgBvzXi618yXPCq",
    "category": "Greetings",
    "project": "Ericsson",
    "model": "Greetings_just_er_0afb44dd-e9b3-59a3-579b-59624eb1650c",
    "keywords": [
      {
        "value": {
          "value": "Madrid"
        },
        "start": 8,
        "confidence": null,
        "end": 14,
        "extractor": "ner_spacy",
        "keyword": "sys.spacy_gpe"
      }
    ],
    "action": {
      "name": "Greet",
      "confidence": 1
    },
    "elapsed_time_ms": 174,
    "categoryScore": 0.08021269738674164
  },
  {
    "docId": "NbRFvWgBvzXi618yXPCq",
    "category": "Date",
    "project": "Ericsson",
    "model": "Date_just_er_e979a206-23e2-2c2a-f51e-6190470add98",
    "keywords": [
      {
        "value": {
          "value": "Madrid"
        },
        "start": 8,
        "confidence": null,
        "end": 14,
        "extractor": "ner_spacy",
        "keyword": "sys.spacy_gpe"
      }
    ],
    "action": {
      "name": "DateAction",
      "confidence": 1
    },
    "elapsed_time_ms": 195,
    "categoryScore": 0.007127994671463966
  },
  {
    "docId": "NbRFvWgBvzXi618yXPCq",
    "category": "Time",
    "project": "Ericsson",
    "model": "Time_just_er_6b017c78-6e14-db55-785f-d622508d77c2",
    "keywords": [
      {
        "value": {
          "value": "Madrid"
        },
        "start": 8,
        "confidence": null,
        "end": 14,
        "extractor": "ner_spacy",
        "keyword": "sys.spacy_gpe"
      }
    ],
    "action": {
      "name": "TimeAction",
      "confidence": 1
    },
    "elapsed_time_ms": 154,
    "categoryScore": 0
  }
]`


***Context***
`{
  "id": "1",
  "sessionId": "articulateUI",
  "actionQueue": [],
  "responseQueue": [],
  "creationDate": "1549360827000",
  "modificationDate": "1549363655000",
  "frames": [
    {
      "id": "1",
      "action": "Greet",
      "slots": {},
      "creationDate": "1549360827000",
      "modificationDate": "1549363655000"
    },
    {
      "id": "2",
      "action": "TimeAction",
      "slots": {},
      "creationDate": "1549361648000",
      "modificationDate": "1549363655000"
    },
    {
      "id": "3",
      "action": "Greet",
      "slots": {},
      "creationDate": "1549363655000",
      "modificationDate": "1549363655000"
    },
    {
      "action": "SlotsAction",
      "slots": {},
      "creationDate": "2019-02-05T10:47:46Z",
      "modificationDate": "2019-02-05T10:47:46Z"
    }
  ]
}`


***Current Frame***

`{
  "action": "SlotsAction",
  "slots": {},
  "creationDate": "2019-02-05T10:47:46Z",
  "modificationDate": "2019-02-05T10:47:46Z"
}`

**Comment by wrathagom** [comment]
Here are the parse results properly formatted:

```
[
   {
      "docId":"NbRFvWgBvzXi618yXPCq",
      "category":"TestSlots",
      "project":"Ericsson",
      "model":"TestSlots_just_er_596d3382-903c-a0c6-6e67-4f55d9bb6163",
      "keywords":[
         {
            "start":8,
            "end":14,
            "value":{
               "value":"Madrid"
            },
            "confidence":0.9118135031968373,
            "extractor":"ner_crf",
            "processors":[
               "ner_synonyms"
            ],
            "keyword":"City"
         },
         {
            "value":{
               "value":"Madrid"
            },
            "start":8,
            "confidence":null,
            "end":14,
            "extractor":"ner_spacy",
            "keyword":"sys.spacy_gpe"
         }
      ],
      "action":{
         "name":"SlotsAction",
         "confidence":1
      },
      "elapsed_time_ms":135,
      "categoryScore":0.9585608839988708
   },
   {
      "docId":"NbRFvWgBvzXi618yXPCq",
      "category":"Greetings",
      "project":"Ericsson",
      "model":"Greetings_just_er_0afb44dd-e9b3-59a3-579b-59624eb1650c",
      "keywords":[
         {
            "value":{
               "value":"Madrid"
            },
            "start":8,
            "confidence":null,
            "end":14,
            "extractor":"ner_spacy",
            "keyword":"sys.spacy_gpe"
         }
      ],
      "action":{
         "name":"Greet",
         "confidence":1
      },
      "elapsed_time_ms":174,
      "categoryScore":0.08021269738674164
   },
   {
      "docId":"NbRFvWgBvzXi618yXPCq",
      "category":"Date",
      "project":"Ericsson",
      "model":"Date_just_er_e979a206-23e2-2c2a-f51e-6190470add98",
      "keywords":[
         {
            "value":{
               "value":"Madrid"
            },
            "start":8,
            "confidence":null,
            "end":14,
            "extractor":"ner_spacy",
            "keyword":"sys.spacy_gpe"
         }
      ],
      "action":{
         "name":"DateAction",
         "confidence":1
      },
      "elapsed_time_ms":195,
      "categoryScore":0.007127994671463966
   },
   {
      "docId":"NbRFvWgBvzXi618yXPCq",
      "category":"Time",
      "project":"Ericsson",
      "model":"Time_just_er_6b017c78-6e14-db55-785f-d622508d77c2",
      "keywords":[
         {
            "value":{
               "value":"Madrid"
            },
            "start":8,
            "confidence":null,
            "end":14,
            "extractor":"ner_spacy",
            "keyword":"sys.spacy_gpe"
         }
      ],
      "action":{
         "name":"TimeAction",
         "confidence":1
      },
      "elapsed_time_ms":154,
      "categoryScore":0
   }
]
```

As you can see your `Cell` slot is not being recognized. It's likely you need more training data. As a side note adding values to the keyword list DOES NOT train articulate to recognize them, they must be used in sayings before they will be recognized, this is the same as the old UI as well.

**Comment by bkurowski** [comment]
I will try to add more training data in sayings, cheers.
