### ISSUE TITLE
PageSize on sayings page is changed when going back from action page

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#538]
Steps to reproduce:

1) Create more than 5 sayings in the sayings page
2) Change to a page size different than 5
2) Enter to the action by editing an action or by trying to create a new action
3) Go back to the sayings page
4) BUG: page size is 5

**Comment by dcalvom** [comment]
I'm not pretty sure if this only happens with the back card at the left of the screen

**Comment by wrathagom** [comment]
Couldn't re-produce.
