### ISSUE TITLE
Error: agent head missing

### ISSUE THREAD

**Issue by winimy** [samtecspg/articulate#539]
Hi ,
I have download from https://github.com/samtecspg/articulate
Using Linux
I have checked both firefox and chrome
Pls check the following url : http://52.230.68.251:3000/missing-api , I m getting the following issue.
Can you help me on this

**Comment by wrathagom** [comment]
@winimy which command did you use to start Articulate? Can you try:

```
docker-compose down
API_URL=http://52.230.68.251:7500 docker-compose up -d
```

and see if that works better. Essentially you have to tell the UI where to reach the API bot providing the `API_URL` environment variable. Also, please note that once you do that your instance of Articulate will be publicy available for anyone to access. We have a tutorial here on how to secure it: https://blog.spg.ai/basic-access-restrictions-for-articulate-58e77c931ca3

**Comment by dcalvom** [comment]
@winimy did you were able to solve it?

**Comment by winimy** [comment]
Where we have to change the API_URL

**Comment by dcalvom** [comment]
in the command to start the containers. I'm assuming you started the containers with `docker-compose up` you need to add the API_URL param to that command as @wrathagom said: `docker-compose down API_URL=http://52.230.68.251:7500 docker-compose up -d`

**Comment by wrathagom** [comment]
@winimy any luck?

If you still can't get it running I can offer several other options:

1. We can give you a free trial of a hosted version of Articulate for testing purposes.
2. If you can temporarily give me access to your VM I can get Articulate installed and running
3. If you would like to have a screen sharing video call I could do that as well.

**Comment by winimy** [comment]
hi,
Sorry for the late reply,
My clarifications are as follow ,

1. How to change API_URL from 3000 to 7500 ?
2. 3000 has been added in many files, those files are 
configurestore.js
Dockerfile
docker-compose.yml 

we have to change it manually or if we change in docker-compose.yml file will it affect in all files ?

**Comment by wrathagom** [comment]
Winimy, you should be touching the code at all. if you have please delete everything and start over.

Assuming you downloaded the latest release, in a command line you should run:

```
API_URL=http://52.230.68.251:7500 WS_URL=ws://52.230.68.251:7500 SWAGGER_HOST=52.230.68.251:7500 docker-compose up
```

**there are no code changes required.**

Normally you don't have to specify so many env variables, but we are working through an issue related to that. #508

**Comment by wrathagom** [comment]
Reading things a different way if you are trying to run the API on a different port you only need to edit the docker-compose.yml file. Specifically this line.

https://github.com/samtecspg/articulate/blob/master/docker-compose.yml#L6

but you can't change the API to run on 3000 because the UI is running on 3000. To change it to 3001 you could edit the line above to read:

```
ports: ['0.0.0.0:30001:7500']
```

Then your start command would be:
```
API_URL=http://52.230.68.251:3001 WS_URL=ws://52.230.68.251:3001 SWAGGER_HOST=52.230.68.251:3001 docker-compose up
```

**Comment by wrathagom** [comment]
@winimy let us know if you didn't get up and running.
