### ISSUE TITLE
Move Helpers-Stuff and nlu-model folders

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#54]
Right now the helpers-stuff and nlu-model directory are stored inside of the API directory. To make it more clear that the folders are related to docker and to match styling with Conveyor I think we should move the helpers stuff to the root of the repo and move nlu-model into the helpers stuff directory.

Same thing for the config file.

**Comment by wrathagom** [comment]
@milutz also good for packaging for v0.5

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/99c7edb7605e023611fc57159f4b9209acb8f656
