### ISSUE TITLE
Training an empty agent succeeds

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#541]
We should throw a warning or error when the user tries to train an empty agent (no sayings). Rather than saying the training succeeded:

![image](https://user-images.githubusercontent.com/1779894/52271877-efc00600-2912-11e9-8365-e83d06e972a8.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/459cff5e25c2be29da2542d82a49b7de32653367
