### ISSUE TITLE
Internationalization (i18n) for Articulate

### ISSUE THREAD

**Issue by AlexeiDimitriCampos** [samtecspg/articulate#545]
Hello guys,

I'm a Brazillian government employee and we are first implementing a chatbot. We choose Articulate because is the most complete solution we found using RASA.

The first presentations for our IT Department can be almost fresh Articulate, but we need Internationalizate to Portuguese the interface, as set PT as our first language (pt-BR was desirable, BUT...)

Is there some chance or easy way to do i18n in GUI of Articulate?

**Comment by wrathagom** [comment]
Hey @AlexeiDimitriCampos this is on our roadmap (actually much of the groundwork is already in place) we just need to add the menu to swap out languages and then create the actual translations.

We'll bump it up the list on your behalf and we'll get back with you once we have some documentation on how you can contribute translations.

**Comment by dcalvom** [comment]
Sure I will do it

**Comment by dcalvom** [comment]
Related with #385

**Comment by dcalvom** [comment]
I already added the [es.json](https://github.com/samtecspg/articulate/blob/master/ui/app/translations/es.json) file fully translated. In case you have already started @AlexeiDimitriCampos, please update the file with the latest version I just uploaded

**Comment by AlexeiDimitriCampos** [comment]
This is nice!
PT - Portugal's Portuguese - and PT-BR - Brazilian Portuguese - is slightly different languages. For us, Brazilian folks, read Wikipedia in Portuguese kind a sucks - there is no Brazilian Portuguese Wikipedia.
I'll translate for Brazilian Portuguese, and ask for a friend from Portugal to help us.

**Comment by dcalvom** [comment]
Cool!...take your time. We still have to implement slight changes in the UI as proposed in the sketch of #385 but we already enabled language selection. So it's just matter of you translating that file and you will be able to select Portuguese as the language of your UI.

**Comment by dcalvom** [comment]
@AlexeiDimitriCampos this is done! We added our final piece to the UI. Whenever you have the translation for Portuguese if you want to help us, let us know.

Closed by https://github.com/samtecspg/articulate/commit/1d599eb92d3dbae82d233c2e158358da457adbca
