### ISSUE TITLE
Custom Rasa Docker Build

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#55]
The Default Rasa Docker build uses the `en_core_web_sm` Spacy model, we should move to one of the larger models since the sm model is known to be more case sensitive.

We should also not install the JRE since we don't use the standard duckling.

We should also run alpine if possible.

**Comment by wrathagom** [comment]
@milutz I think we should to this as part of our **packaging for v0.5** the 0.10.4 Rasa image has some bugs around model loading that I want to avoid running into. Plus, if we build with alpine maybe we can save some space?

**Comment by milutz** [comment]
@wrathagom ... to make sure I understand what your saying, you want to:

1: replace the line https://github.com/samtecspg/articulate/blob/master/docker-compose.yml#L40 with a rasa build controlled by our team
2: (because of above ... maybe??... ) clone rasa_nlu into our team
2.5: mod our build so it doesn't install JRE, and so it builds from alpine
3: (because of above) setup dockerhub/cloud to do builds off of ?our? rasa_nlu

Am I forgetting anything? (or confused)

**Comment by wrathagom** [comment]
Sounds good to me.

**Comment by milutz** [comment]
I'm trying to gear up for getting the rasa image built but need some more bits...

For our 0.5 release which RASA do we want to 0.10.4, .5, .6, or the just blessed 0.11.0?
Our compose in master is on 0.10.4 https://github.com/samtecspg/articulate/blob/master/docker-compose.yml#L41
Blame on the line has a comment from Daniel 3 months ago saying "Change docker file to use newest version of Rasa" that makes it sound like we just haven't got around to updating (but that we may want to?)

So what say you @wrathagom & @dcalvom ? which RASA should our 0.5 be using?

**Comment by wrathagom** [comment]
Let's do 0.11.0 nothing groundbreaking by the looks of things.

Let's make sure we have these models installed:
 - en_core_web_md
 - de_core_mews_sm
 - es_core_news_md
 - fr_core_news_md

essentially preferring the medium models with vectors were available.

**Comment by milutz** [comment]
The custom rasa docker build is done, but in a separate repo - we've decided that we want to pull it all in here, so all thats left is for me to make a new directory for it in here (and then add it to all the docker hub/cloud stuff for Articulate)

**Comment by milutz** [comment]
As-of the above commits, rasa build is in the Articulate repo and builds are configured on dockerhub - closing
