### ISSUE TITLE
UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown

### ISSUE THREAD

**Issue by harunkelesoglu** [samtecspg/articulate#550]
### UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown

I'am trying to my agent.i have never encountered an error before during training.But i typed new expression and create new intent. I tried to train again and got the following error.

 
<img width="1442" alt="screen shot 2019-02-06 at 09 17 27" src="https://user-images.githubusercontent.com/9349762/52324100-ec9b4780-29f0-11e9-8b4e-03d00e64771e.png">

**Comment by dcalvom** [comment]
Could you check docker stats while you train? just to confirm you aren't hitting your memory limit

**Comment by wrathagom** [comment]
Yep, this definitely looks like out of memory. How much RAM is on the machine/allocated to docker?

**Comment by harunkelesoglu** [comment]
Thanks @wrathagom @dcalvom .The problem is insufficient memory. I have a memory of 5 gb. Problem is solved.

**Comment by dcalvom** [comment]
Awesome @harunkelesoglu Thanks for sharing
