### ISSUE TITLE
Instability issues

### ISSUE THREAD

**Issue by harunkelesoglu** [samtecspg/articulate#553]
###Instability Error for 2 and more agent
First i created one agent.And it is work except action delete process. After i added another agent.But this agent  seems to be added but not added. And I can not take any action this agent.The first agent is no longer working.

![screen shot 2019-02-07 at 10 21 01](https://user-images.githubusercontent.com/9349762/52396258-4750a400-2ac2-11e9-81ab-046c37758f05.png)

For example I choose my first agent. Agent name,description does not appear like that is new agent
![screen shot 2019-02-07 at 10 25 45](https://user-images.githubusercontent.com/9349762/52396494-32284500-2ac3-11e9-8443-0a8c5ca021fd.png)

The sayings tab does not load when i choose.
![screen shot 2019-02-07 at 10 32 28](https://user-images.githubusercontent.com/9349762/52396688-c8f50180-2ac3-11e9-898c-b892bb4a65f2.png)

**Comment by harunkelesoglu** [comment]
Downloaded latest version v0.20.1. I tried it. When I change the settings of the agent and save it, I get a blank screen and the agent name is empty as the agent has never been created

**Comment by wrathagom** [comment]
Hey @harunkelesoglu a couple of these sound like bugs we've squashed in the last day or two that don't yet have a release.

I'm working my way through testing everything one more time before another release. I'll let you know when I've got that done and hopefully things a re a bit more stable.

Thanks for your patience as we try to get this new UI packaged up nice.

**Comment by wrathagom** [comment]
@harunkelesoglu I published 0.20.2 earlier today and have had really good luck with it's stability. Can you completely un-install your existing instance and download that one fresh?

https://github.com/samtecspg/articulate/releases/tag/v0.20.2

Feel free to create an issue if that one isn't more stable for you.
