### ISSUE TITLE
Full list of actions isn't showing up

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#554]
I'm on a fresh copy of Articulateand having quite a few issues, here's number one:

I've created greetings and goodbyes actions, but the action list seems to be filtered:

![image](https://user-images.githubusercontent.com/1779894/52402209-b2ce4d80-2a91-11e9-8c3c-d843817a3f6e.png)

**Comment by wrathagom** [comment]
The action isn't hidden by scrolling or anything like that I looked at the source. Also there are no errors on the page or console.

**Comment by dcalvom** [comment]
The actual error was that the actions were being overwritten.

Closed by https://github.com/samtecspg/articulate/commit/64f434cb456be98486b6266d899b24cb60710bb4
