### ISSUE TITLE
Clicking on an action leaves the filter in the URL

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#555]
When I click on my goodbye action to edit the url is: `http://localhost:3000/agent/1/action/2?filter=&page=1&pageSize=10` the extra url parameters don't seem to be doing anything is there a reason they are still there?

**Comment by dcalvom** [comment]
It's suppose that if you come back to the sayings screen you get back to the status you were before entering to the action screen. If that isn't happening then the bug is that we aren't restoring the state of the sayings screen.

**Comment by wrathagom** [comment]
it does, just looks kind of funny. I'll leave it for now.
