### ISSUE TITLE
Installing articulate using docker-compose up using locally stored docker images

### ISSUE THREAD

**Issue by gaurvipul** [samtecspg/articulate#557]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

**I am trying to install articulate using docker-compose up in an environment where I can't connect directly to dockerhub due to firewall restrictions.

I've downloaded the images directly on to my desktop. I wanted to check if somehow I can use those images to install articulate in that environment.**

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release? 0.20
- What operating system are you running? Red Hat 7.0
- Are you running locally or in the cloud? On Premise cloud
- Which browser are you using? Chrome

@wrathagom 
----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by milutz** [comment]
Hi @gaurvipul - I don't foresee any problems in doing what you describe - I'm not sure how you downloaded the images from dockerhub, but assuming you've found a way to, you should be able to `docker load` them into your firewalled system and as long as they have the same docker-tag name everything should just work.

If the above doesn't solve your issue, it would help me to have more details, such as:
 - What error are you getting that leads you to believe things aren't working
 - How are you fetching the images
 - After you've loaded the images, what do you get from a `docker images`

**Comment by wrathagom** [comment]
Here's a post with some commands, I've never done this either.

https://serverfault.com/questions/701248/downloading-docker-image-for-transfer-to-non-internet-connected-machine

**Comment by gaurvipul** [comment]
Thanks @wrathagom @milutz 
I will try this and update/close the issue

**Comment by wrathagom** [comment]
Please let us know if you run into any troubles with this.
