### ISSUE TITLE
Live review table doesn't respect pagination

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#560]
Not sure how to make this one work, but right now the socket just fills up the table infinitely. Ideally after the pagination length the results would be dropped from the screen.

Also if you are on a page > 1 and a new request comes in you get taken back to page 1, which shows all results, I think.

**Comment by wrathagom** [comment]
@dcalvom if this one is too hard to handle elloquentyl (I can see a lot of problems of having to manage both pagination and live loading) maybe we have a toggle that enables/disables the live loading. If it is enabled there is no pagination, if disabled there is? Just a thought.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/58a7f589ee60127bb0673174fdeabe0633bec056
