### ISSUE TITLE
Need to modify duckling interval conversion for Month

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#564]
This was a change made in the old API, but never in the new API.

https://github.com/samtecspg/articulate/blob/master/api/lib/services/duckling/duckling.convert-interval.service.js#L36

versus

https://github.com/samtecspg/articulate/blob/0.13/api/modules/agent/tools/ducklingOutputToInterval.agent.tool.js#L60

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/5840b6dde26df1c3393343f6d547abee64f5792b

**Comment by dcalvom** [comment]
Sorry I didn't noticed this was assigned to @spg-matt
