### ISSUE TITLE
api endpoint is not working

### ISSUE THREAD

**Issue by harunkelesoglu** [samtecspg/articulate#566]
### api endpoint is not working

I have installed the articulate to my server.And I executed the docker-compose with folowing command. 
`API_URL=http://116.203.68.43:7500 docker-compose up -d`

I'm trying access to api endpoints but i can not to api endpoint. I get the following the error:
<img width="1393" alt="ekran resmi 2019-02-10 13 27 15" src="https://user-images.githubusercontent.com/9349762/52532577-ac153400-2d38-11e9-87c0-7e1e2c32d7a5.png">

Also i can not access to ui.
<img width="1043" alt="ekran resmi 2019-02-10 13 37 46" src="https://user-images.githubusercontent.com/9349762/52532613-19c16000-2d39-11e9-95b1-e0b0a0a36b91.png">

At this time i tried both v0.20.2 and v0.20.3.

**Comment by wrathagom** [comment]
@harunkelesoglu we have an issue we're working through where one env variable isn't populating correctly.

Can you start your application with:
```
API_URL=http://116.203.68.43:7500 SWAGGER_HOST=116.203.68.43:7500 docker-compose up -d
```
Also, the API documentation page will be at http://116.203.68.43:7500/documentation the first image above actually looks like the API is running fine. but the second image suggests the UI can't find the API, which is what the SAGGER_HOST env variable should do.

**Comment by wrathagom** [comment]
@malave FYI issue 2

**Comment by wrathagom** [comment]
@harunkelesoglu did you mean to comment on this issue?

**Comment by harunkelesoglu** [comment]
Thanks @wrathagom I have to enter both Swagger and api environment. Problem solved

**Comment by wrathagom** [comment]
yeah, this isn't ideal and I know it. We're working to get it down to a single env variable.

**Comment by wrathagom** [comment]
related to #508
