### ISSUE TITLE
List Highlight alignment is off

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#57]
<img width="694" alt="2018-01-10_12-42-16" src="https://user-images.githubusercontent.com/1779894/34786973-b990713e-f603-11e7-819c-9b76e941b17f.png">

The check mark seems to be okay, but the text alignment is off.

@broham89 do you see it to?

**Comment by broham89** [comment]
@wrathagom hmm I think there is a weird padding/margin on the top of the gray list. The gray bar should touch the border above it with no white space between.

**Comment by wrathagom** [comment]
Also seeing this on Entities, even worse because of the big color box.

<img width="827" alt="2018-01-10_12-51-10" src="https://user-images.githubusercontent.com/1779894/34787346-f13cec9c-f604-11e7-9cd9-820da1b129b7.png">

**Comment by broham89** [comment]
@dcalvom @wrathagom I think it would be best if it was a tiny circular dot instead.
