### ISSUE TITLE
Help with a certain use case

### ISSUE THREAD

**Issue by cloud1250x4** [samtecspg/articulate#570]
!Currently using Articulate 0.20.3!

What would be the correct way to implement the following?

Client : Hi!
Chat : Hello! 
Chat : Is there anything I can help with? (On a different line then Hello!)
Client : Yes! I need help with my server... (Validation + request for help)
Chat : Sure, let's see what I can do for you! (Reply for Yes)
Chat : First, can you describe what's wrong with your server? (Reply for I need help)
Client : When I try to do this...
...

Also, what if I want to initiate a discussion ending survey?

Client : Thank for you help!
Chat : No Prob! Do you mind answering a 2-3 questions survey related to my performance?
Client : No.
Chat : Thanks for your time!
Chat : Good bye!

...

Client : Yes!
Chat : Perfect!
Chat : On a scale of 1 to 10, how would you rate my performance today?
Client : 8
Chat : Do you have any comment about your experience with me?
Client : No.
Chat : Perfect Thank you!
Chat : Have a nice day!

Thank you!

**Comment by wrathagom** [comment]
@cloud1250x4 I am working on building a simple agent to demo how to do this. I'll post it here once I am finished.

**Comment by cloud1250x4** [comment]
Perfect thank you!

**Comment by wrathagom** [comment]
So here are the different paths I have set up:

![image](https://user-images.githubusercontent.com/1779894/52661878-f6c9b400-2ed0-11e9-889b-165cf9bdca5d.png)

And here is the demo agent. Keep in mind, this is a bare bones example I set up quickly. You need a lot more work to turn it into a full scale bot.

https://gist.github.com/wrathagom/e9fd860dc3f905c4e5b0b33448d5ac99

There are three concepts at work here. The first is utilizing slots. Slots are placeholders on actions, you could also think of them as parameters. When they are required Article will prompt for them using some prompt you provide. Also, slots are tied to a keyword. For example the below screenshot shows a slot for Survey question 1, which is tied to the `Score` keyword.
![image](https://user-images.githubusercontent.com/1779894/52662146-9ab35f80-2ed1-11e9-9856-1426972f5049.png)

The next important topic are modifiers. Modifiers are special phrases that you train on keywords. They *modify* the slots that hold those keywords. So I am using two different keywords and modifiers in your example. The first modifiers are how I handle all of the yes/no type questions:
![image](https://user-images.githubusercontent.com/1779894/52662330-f847ac00-2ed1-11e9-8315-2ae12ddc56a0.png)

But I also use a modifier for capturing the scores:
![image](https://user-images.githubusercontent.com/1779894/52662385-12818a00-2ed2-11e9-852c-efe178babe8f.png)

The last concept is chaining. This is where one response immediately kicks off another action. By using this in combination with handlebars we can go to a certain action based off the slot value of a previous action.
![image](https://user-images.githubusercontent.com/1779894/52662487-54aacb80-2ed2-11e9-8113-6c6f9f3635dd.png)

Sorry for the lack of documentation, but hopefully this gets you going. We're working on the docs!

**Comment by cloud1250x4** [comment]
Looking good!

So I guess It's not possible to handle something like this? 

Chat : Is there anything I can help with? (On a different line then Hello!)
Client : Yes! I need help with my server... (Validation + request for help)
Chat : Sure, let's see what I can do for you! (Reply for Yes)
Chat : First, can you describe what's wrong with your server? (Reply for I need help)

Like multiple intent in one message?

**Comment by wrathagom** [comment]
You can tag sayings with multiple actions. `Can I get a pizza and a drink` could kick off both the orderPizza and orderDrink actions. At the moment. You can't combine what we call `modifiers` with other actions. So `Yes. I need help with my server` isn't possible because yes is a modifier where as request for help is a regular action. We may change this in the future.

**Comment by wrathagom** [comment]
@cloud1250x4 let us know if we can help more.
