### ISSUE TITLE
HAPI/API problems with Promises and callbacks

### ISSUE THREAD

**Issue by AlexeiDimitriCampos** [samtecspg/articulate#572]
Hey Guys, 
I already tried with Master and v0.20.3 branches.
I'm getting this error, can you help?

api_1            | Debug: internal, implementation, error
api_1            |     Error: handler method did not return a value, a promise, or throw an error
api_1            |     at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:52:29)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)

Seems a HAPI problem with callbacks and promises, like [this here](https://github.com/hapijs/hapi/issues/3757).

But I can't see what's going on.

**Comment by AlexeiDimitriCampos** [comment]
This error happens when i do a train task.

**Comment by wrathagom** [comment]
@malave can you try to reproduce. I'll let you know if I see it.

@AlexeiDimitriCampos can you tell us more about how you are running: OS, browser, etc?

**Comment by wrathagom** [comment]
@AlexeiDimitriCampos I am not seeing this problem when training. Do you mind re-cloning and re-pulling master to make sure you are running the latest and see if you can get it to happen again?

**Comment by AlexeiDimitriCampos** [comment]
Sure. I'm with Windows 10 Build 16299.936, using chrome and FF.

**Comment by wrathagom** [comment]
I still haven't managed to re-produce this. @AlexeiDimitriCampos have you tried pulling the latest from docker hub and trying again?

**Comment by AlexeiDimitriCampos** [comment]
Now i can't do swagger works.
CORS problem again.
And Environment variables SWAGGER_HOST and SWAGGER_BASE_PATH are ignored, so i can't do reverse proxy.
So neither I can reproduce the errror again kkkk

**Comment by AlexeiDimitriCampos** [comment]
Ok i'm pulling the repo-head image again

**Comment by wrathagom** [comment]
Make sure to `docker-compose pull` as well.

**Comment by AlexeiDimitriCampos** [comment]
Now the API service cant connect to Elasticsearch.

**Comment by AlexeiDimitriCampos** [comment]
So nothing is working XD

**Comment by AlexeiDimitriCampos** [comment]
I'm giving up Articulate, Guys.
I need to use Rasa Core, and the various problems for just testing make me crazy.

**Comment by wrathagom** [comment]
If you need Core then it's a show stopper. If you just can't get it running I can give you a hosted instance to develop on or you can give me access to a survey to get it running for you.

Either way, thanks for giving it a try.
