### ISSUE TITLE
Randomize Entity color when creating a new entity.

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#573]
Per @cjhurst suggestions on Basecamp:

> Can we suggest random (different) colors for new keywords so they aren't all red by default?

seems like a good idea.

**Comment by RussellSPG** [comment]
> 
> 
> Per @cjhurst suggestions on Basecamp:
> 
> > Can we suggest random (different) colors for new keywords so they aren't all red by default?
> 
> seems like a good idea.

+1

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/fdae39f56177748e2d9501b9ad517e06e6d99fd4
