### ISSUE TITLE
Fix position of language selection when conversation panel is open

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#576]
![image](https://user-images.githubusercontent.com/7228045/52904413-a369a580-31f1-11e9-9684-b5b41bda4010.png)

**Comment by wrathagom** [comment]
Should it only appear when you're at the top of the screen?

**Comment by dcalvom** [comment]
I think so, as when the conversation panel is closed. Doesn't it?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/eb39891f4c0c472fc13fe3b23a922aecf6c46822
