### ISSUE TITLE
For long sayings wrap text,  but not action tags

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#579]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/1779894/52984049-c942a600-33bb-11e9-8d95-c556b9a98606.png">

**Comment by dcalvom** [comment]
I tried some fixes but all of them looked odd. @broham89 is helping me to solve this issue. I don't think there is an easy fix.

**Comment by broham89** [comment]
I have a couple of versions:
![search list v 2](https://user-images.githubusercontent.com/11262149/53062971-2c9a0a00-3488-11e9-8bcb-769cc2b66108.png)
![search list v 3](https://user-images.githubusercontent.com/11262149/53062975-302d9100-3488-11e9-9c13-d8a89151575a.png)
![search list v 3 - step1](https://user-images.githubusercontent.com/11262149/53062984-3b80bc80-3488-11e9-921a-eea357f444ac.png)
![search list v 3 - step2](https://user-images.githubusercontent.com/11262149/53062985-3b80bc80-3488-11e9-948b-a456c7eb9dbb.png)

**Comment by wrathagom** [comment]
Thanks for diving in together and trying to get this sorted. v2 is definitely what was in my head, but the stretched category button looks off.

I could see v3 working as well, but am a bit curious on usability impacts if you have to wait for the hover to show. Some of the beauty of the UI right now is that you can make edits quickly.

I think there's a mother possibility if we are considering hovers where the text is full width and wraps, but the tags show up on top of the text on mouse over....

Maybe this is a good time to consider what editing the sayings looks like when combined with this one.

**Comment by wrathagom** [comment]
Maybe related to #455

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/0ccdbc50f6a3dc5d7e307ff409364abd6db02323

**Comment by broham89** [comment]
![saying list - v 2](https://user-images.githubusercontent.com/11262149/53380524-52655a00-3933-11e9-8c2e-efe8d288cb21.png)
@wrathagomI think this layout could help with organization visually. However, the tradeoff is the list would be long vertically.

**Comment by wrathagom** [comment]
yeah imo it loses the appeal that we had of a simplified interface. I don't think the 3+ tags is very realistic; though, I am sure someone will prove me wrong.
