### ISSUE TITLE
When creating a new slot, navigate to it

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#582]
Right now we don't

**Comment by bkurowski** [comment]
Please do, sometimes user might start editing already created ones as it does not navigate to new slot. I have tested that and sometimes seems to be annoying 👯‍♂️  👍

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/8754e8dedad49035de5d6eccd39dced4437f4756
