### ISSUE TITLE
Can't change Action threshold to default of 0.5 (Cloud)

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#587]
When editing a category, the default action threshold is 0.5 If you adjust the slider it goes in increments of 1. If you try to type 0.5, it does not allow decimals.

**Comment by wrathagom** [comment]
It's a percent, so in the UI the range is from 0-100

**Comment by RussellSPG** [comment]
ok so in that case, maybe its better to just set it to 1 percent by default.

**Comment by wrathagom** [comment]
it defaults to 50%

**Comment by wrathagom** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/1779894/53094256-a1e8f780-34e7-11e9-88a9-323eea087fab.png">

**Comment by dcalvom** [comment]
Please pull the latest version. Also, the threshold value is an integer.
