### ISSUE TITLE
Keep threshold settings to default values upon creating new (Cloud)

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#588]
I suggest to keep action, category etc threshold settings to default when creating new. For example, when setting a threshold to 10 from default, the new one you create will then default at 10. It's easy to forget that optimal would be 0.5 for others, and have everything at 10, not realizing it. So, if you edit a threshold to to, another words upon creating a new, it should start at 0.5 again, or w.e is best by default.

**Comment by wrathagom** [comment]
I can't reproduce this one. When I set the category threshold to some value and create a new category it defaults to 50%

**Comment by RussellSPG** [comment]
On a new agent, create a category. Put in the name and hit save. It automatically goes to 0.5 all the way to the bottom.

![image](https://user-images.githubusercontent.com/42249324/53094608-9ba74b00-34e8-11e9-8901-fd330422bbbd.png)

**Comment by wrathagom** [comment]
what browser? This doesn't happen for me.

**Comment by wrathagom** [comment]
Are you sure you're running the latest? We did have an issue with this, but it got fixed some time ago. Though it's possible it's still happening under certain circumstances.

**Comment by RussellSPG** [comment]
Firefox for me. As for the latest, I'm not sure, I'm running on the cloud instance, so whatever you have me on.

**Comment by dcalvom** [comment]
This is an old issue. It was closed, please use the latest version.
