### ISSUE TITLE
Making changes on agent screen, but then leaving before saving there is no are you sure prompt

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#590]
I just edited the pipeline and the threshold on an agent, but then navigated tot he sayings page without savings and it let me with no prompt of are you sure you want to leave.

**Comment by dcalvom** [comment]
This is a hard one, I already implemented a solution, but, the issue with this one is that the main tab is on top of the screen, so, if the user clicks on the dialogue or the review tab, he is leaving the form, therefore we need to capture those actions too.

Using `componentWillUnmount` do the trick for this, but, the UI still changes the tab values, therefore the state of the screen changes although the user didn't confirm the exit on the dialog.

I need to figure out this better.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/1b0a01b41c1115977ef5ac5781e2be589de486cc
