### ISSUE TITLE
Server error in a particular use case flow

### ISSUE THREAD

**Issue by shoaibmohommed** [samtecspg/articulate#592]
Hi,
I am getting the server in a particular use case flow of messages.

here is the screenshot attached please check
![issue](https://user-images.githubusercontent.com/6280803/53168021-a86a9280-35ff-11e9-84ec-e62b88aaecae.PNG)

**Comment by wrathagom** [comment]
Sorry @shoaibmohommed I completely missed this issue. Can you try with the latest patch version and let us know if you are still having troubles. I hope you got it working.
