### ISSUE TITLE
implement automatically highlighted keywords to include characters: ,? etc..

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#594]
### Issues
Please describe the issue you are having here and answer the question below.
When entering a saying, the detected/highlighted keyword does not detect if there is a ```?``` or ```,``` character included.

![image](https://user-images.githubusercontent.com/42249324/53291533-a977fd00-3782-11e9-89b1-6fdbb97795a3.png)

- Did you download a release or pull from Master? Which release?
Master, 0.21
- What operating system are you running?
Windows 10 Pro
- Are you running locally or in the cloud?
Locally
- Which browser are you using?
Firefox

----

### Feature Request

Please describe the feature you would like us to add.

Add support so keywords with , and ? or other characters are detected and automatically highlighted with the keyword.

**Comment by dcalvom** [comment]
Please update to latest version this is a duplicated issue

**Comment by RussellSPG** [comment]
When I just ran git pull from master is said "already up to date" Maybe I wasn't actually accessing the repo

**Comment by wrathagom** [comment]
what branch are you one?

**Comment by RussellSPG** [comment]
```
MiG-23@DESKTOP-DLRND62 MINGW64 ~/Documents/git stuff/articulate (master)         $ git describe --tags                                                            untagged-312ae2011b4394bbe044-207-g728cc903
--
```
But I may have the wrong command.. searching how to see the particular branch

**Comment by RussellSPG** [comment]
ran git branch, got 
```
.21
master
```

**Comment by RussellSPG** [comment]
Keeps saying I'm up to date.
```

MiG-23@DESKTOP-DLRND62 MINGW64 ~/Documents/git stuff/articulate (master)         $ git pull https://github.com/samtecspg/articulate                               From https://github.com/samtecspg/articulate                                      * branch              HEAD       -> FETCH_HEAD                                  Already up to date.
--


```

**Comment by wrathagom** [comment]
`git status` shows you the current branch and status

Did you `docker-compose pull` as well?

**Comment by RussellSPG** [comment]
Ah, now its updating something... Should I use docker-compose pull instead of git pull from now when updating or both?

**Comment by wrathagom** [comment]
it depends on what you want to update. `docker-compose pull` updates the docker images `git pull` updates the code. Likely you'll want to do both. Or you could just run and test from release zip files which you wouldn't do either for you would just download the latest zip.

**Comment by RussellSPG** [comment]
Got it, I'll run both for now on. @dcalvom got it, thanks.
