### ISSUE TITLE
Edit records in the UI

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#6]
Implement the screens that would allow the user to edit data.

Here is some food for thought. Whenever you add or update an intent, the whole model will be retrained. It could happen depending on the size of the agent, that the training lasts some time. We need to think about how we are going to present that training time to the user.

**Comment by wrathagom** [comment]
@malave think we can get this done today/tomorrow?

**Comment by wrathagom** [comment]
I think that does it right?
