### ISSUE TITLE
Chat Side panel wont accept input

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#60]
Starting from a forced refresh select an agent, then go to the intents page. Now trying typing something to the agent. The chat side panel wont accept an input, when I hit the `enter` key nothing happens.

**Comment by dcalvom** [comment]
I don't know if I'm not following the right steps, but I'm having a response. My steps:

1. load manually http://localhost:3000
2. Select an agent
3. Click on intents to enter in the intent list page
4. Talk with the agent
