### ISSUE TITLE
Unable to delete saying created with api

### ISSUE THREAD

**Issue by cjhurst** [samtecspg/articulate#605]
I edited an existing saying, assigning a test action. I am now unable to delete it.  This is on the samson-dev instance.
![image](https://user-images.githubusercontent.com/3117898/53586961-43f78800-3b57-11e9-971e-a383ca165a03.png)

**Comment by cjhurst** [comment]
@wrathagom

**Comment by wrathagom** [comment]
I can't reproduce at the moment.
