### ISSUE TITLE
Improve filter documentation in swagger

### ISSUE THREAD

**Issue by cjhurst** [samtecspg/articulate#606]
Unable to use the filter on the API to specify the results:

![image](https://user-images.githubusercontent.com/3117898/53592730-e2d6b100-3b64-11e9-8d9c-df19d9d1e369.png)

**Comment by cjhurst** [comment]
@wrathagom @dcalvom

**Comment by wrathagom** [comment]
per the field descriptions in the image above:

- the field applies to sorting not filtering
- filter expects an object and you are passing it a string

**Comment by cjhurst** [comment]
What kind of object? I found the other endpoint that accepts the id so that's fine. What should I put in there? 
{id:"534"}
?

**Comment by wrathagom** [comment]
Try it and let me know. And let me know which field takes a value for the filter.

**Comment by cjhurst** [comment]
doesn't seem to work that way.
![image](https://user-images.githubusercontent.com/3117898/53599788-07875480-3b76-11e9-80ce-15caae82b289.png)

**Comment by wrathagom** [comment]
Try double quotes on both.

**Comment by cjhurst** [comment]
Ok, thanks. Got it working.

**Comment by wrathagom** [comment]
Can we change the description to include an example? How about at least setting the data type as object?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/ff4e9480113e082b38248c3826a4a793e432eeaf
