### ISSUE TITLE
Action tag in saying input is being deleted after a new saying is created

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#607]
As title says

**Comment by dcalvom** [comment]
closed by https://github.com/samtecspg/articulate/commit/098a80771119e9f0d868b5f15364575342ec5a15

**Comment by wrathagom** [comment]
@dcalvom this still isn't working for me.

**Comment by dcalvom** [comment]
Are you sure isn't a browser issue?

**Comment by dcalvom** [comment]
This is my latest version:

![Mar-11-2019 10-00-55](https://user-images.githubusercontent.com/7228045/54111643-ab79c700-43e4-11e9-9a59-04110f110514.gif)
