### ISSUE TITLE
Actions should be sorted by name on dropdown

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#608]
When we tag sayings it could be easier by having the actions sorted by name

**Comment by wrathagom** [comment]
@dcalvom I think we should improve upon this even more and have the category/action dropdowns show:

- Search
- Most Recent (limited to 3 most recent)
- Full alphabetized list

**Comment by wrathagom** [comment]
May be a continuation of #638

**Comment by dcalvom** [comment]
Fixed the sort issue with https://github.com/samtecspg/articulate/commit/d355d4f6a9e0cc4e0f495f8f375b0cdefcf2c057, still missing the new order and filter.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b48e84234962060e798dcf10140d8c84f577d635
