### ISSUE TITLE
Language box

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#609]
### Issues/Fixes

Hi just observed the language box is hovering over the menu which doesn't look too beautiful.
Have a look on screenshot below .
![image](https://user-images.githubusercontent.com/40358189/53633981-e32c8600-3c10-11e9-8fa6-156dd6b1a7f0.png)

Best Regards

**Comment by wrathagom** [comment]
Thanks @bkurowski this was already reported by @dcalvom on #576. it's fixed on master. I'll either cherry pick it into the next release I build for you, or we'll make a whole new release.
