### ISSUE TITLE
Prompt bubble doesn't follow text over break

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#61]
<img width="720" alt="2018-01-10_13-03-49" src="https://user-images.githubusercontent.com/1779894/34787865-c314b06e-f606-11e7-9217-adf00eb3a29d.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/ef6a14127b9ab738a737a5be936d410b37ef0013

**Comment by wrathagom** [comment]
Can you post a screenshot of the final product?

**Comment by dcalvom** [comment]
![image](https://user-images.githubusercontent.com/7228045/35897781-8260fcc0-0b88-11e8-8028-b9f016a0789f.png)
