### ISSUE TITLE
Clicking "next" button on Dialogue, sayings page goes to blank Dialogue page

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#613]
When I typed in my sayings, set completed actions to them, and hit next button to go to next page, everything was erased and went to here:

![image](https://user-images.githubusercontent.com/42249324/53670934-7b932c80-3c4a-11e9-9447-12f0f2dff18b.png)

Refreshed, tried to re-produce and behavior is normal, but worth noting as its a one time thing it seems or occasional.

-Tried on a different browser, and no problem.
-When refreshing on same browser, no problem.
-No errors in console. 

- Did you download a release or pull from Master? Which release?
yes, v0.21.1
- What operating system are you running?
10 Pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
Firefox
----

**Comment by wrathagom** [comment]
What next button?

**Comment by RussellSPG** [comment]
In Dialogue sayings, page, when clicking the "Next" button to go to next page.

**Comment by wrathagom** [comment]
this isn't possible for this to be 0.21.1 because 0.21.1 doesn't have the Dialogue tab.

**Comment by wrathagom** [comment]
can't reproduce
