### ISSUE TITLE
Action delete button not functional 

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#614]
When deleting an action from the Dialogue page it works. But when deleting while in that action does not. Prompt comes up, but when hitting delete nothing happens. Also, I did save the action and checked when refreshed. So the action was created.

![image](https://user-images.githubusercontent.com/42249324/53671459-6e773d00-3c4c-11e9-8a27-fbdbb48f7a3d.png)

-Tested on edge browser, same result.
-No errors on console.

- Did you download a release or pull from Master? Which release?
Yes, 0.21.1
- What operating system are you running?
10 Pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
Firefox
----

**Comment by wrathagom** [comment]
Are there any errors showing in the chat panel?

**Comment by wrathagom** [comment]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/1779894/53673618-9f5c6f80-3c56-11e9-9e63-678e5ad41d89.png">

**Comment by RussellSPG** [comment]
Yes, there were errors in chat panel
![image](https://user-images.githubusercontent.com/42249324/53673677-0f6af580-3c57-11e9-9a37-87d8fde92908.png)
I added in other sayings and attached the action to them. Delete button to the action still is not functional.

**Comment by wrathagom** [comment]
In order to delete an action it **can't** be attached to any sayings so adding more is the opposite of what you needed to do.

**Comment by RussellSPG** [comment]
Alright, detached the actions, clicked on it, deleted and go something this time in console. Still not functionality though. 

Also with a loading screen, where action seems blank:

![image](https://user-images.githubusercontent.com/42249324/53673843-fe6eb400-3c57-11e9-9c23-011ca08d5baa.png)

```
uncaught at W at W 
 at d 
 at M 
 M/<@http://localhost:3000/0.193de0f01b0d0ae95b49.chunk.js:1:12698
x@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:125:27004
w/o._invoke</<@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:125:26794
S/</e[t]@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:125:27180
M@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:84:113792
w@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:84:114631
B/</<@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:84:115285
o@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:25:116703
l@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:25:116853
a@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:25:116752
B/<@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:84:115161
B@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:84:115108
M@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:84:113854
w@http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:84:114631
```

**Comment by wrathagom** [comment]
Hmm, we need to get you using the development startup commands so that we get human readable errors.

I’ll try to duplicate this.

**Comment by RussellSPG** [comment]
kk

**Comment by wrathagom** [comment]
Seems to work fine now. and given the process above there might have been other issues.
