### ISSUE TITLE
Allow editing responses in place

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#618]
Release 21.1

Please desribe the feature you would like us to add.

I think it would be nice to be able to not only have a copy (as that was already discussed) but an edit button for responses, and text with prompts.

If possible provide the use case for the feature and how you would use it.

For example, in the Response tab, if I enter my response in and press enter, its not changeable. I would have to delete the whole response if I wanted to make a change. Right now the process is always, copy the text, then delete, then paste, and make edits before hitting enter. It would save time if we could just edit them on the spot.

**Comment by wrathagom** [comment]
@dcalvom this sounds simpler than editing sayings in place since there is no highlighting, makes sense to do it to me.

**Comment by dcalvom** [comment]
Sure! I think it is easy too

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/8d567bbf50e4aee83f2d3cef0bb4a7dd4ee7747c
