### ISSUE TITLE
Implement a trash icon for action drop down

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#620]
21.1 Release
Please desribe the feature you would like us to add.

Add in a trash icon so we can delete actions quickly in the dialogue tab:

![image](https://user-images.githubusercontent.com/42249324/53890521-5c075580-3ff6-11e9-8ad4-fe7e1d6326a9.png)

**Comment by wrathagom** [comment]
I think for the moment we will stick with a consistent pattern of having to navigate to the page to delete it. I don't think we have a delete icon in any other dropdown?
