### ISSUE TITLE
Increase default size of help videos

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#626]
this likely needs some CSS to make sure we handle It right on different screen sizes, but the idea would be to leave just a slim 200px border on the sides of the video and take up the rest of the screen.

Since the videos are screenshots they need to be big.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/03e3bb254d789999935083c8c108a1e7ad2a4139
