### ISSUE TITLE
Response Icons stand out too much

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#627]
For whatever reason the icons on the responses pop out more than I remember. Did the color or styling change of them at all?

We should increase the spacing between them a little bit and mute their color. Maybe they're the standard grey and go darker on hover?

**Comment by dcalvom** [comment]
You mean those?

![image](https://user-images.githubusercontent.com/7228045/54079733-53f33280-42e2-11e9-9f77-72d0a7c79d03.png)

**Comment by wrathagom** [comment]
yep, spacing and color seems off.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3c0f6969f042ab6df76e4eafa29d9be38c0d8cd5
