### ISSUE TITLE
Creating an action didn't set it as the selected action in the sayings input

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#628]
Probably related in some way to #607

**Comment by dcalvom** [comment]
@wrathagom The issue with this is that every tag of keyword or action requires a full re render of the all syings being shown in the page. If you change the page size to 5, the response time is much less. Also the number of keywords tagged on each saying affects the result.

I will try to improve this by only re rendering the saying that was updated by the user. I will let you know how this goes.

**Comment by wrathagom** [comment]
@dcalvom did you post that on wrong issue?

**Comment by dcalvom** [comment]
Teo! Removing...

**Comment by dcalvom** [comment]
closed by https://github.com/samtecspg/articulate/commit/098a80771119e9f0d868b5f15364575342ec5a15
