### ISSUE TITLE
Adding and removing action tags takes too long

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#629]
It looks like we are completely reloading the sayings list for every modification? This doesn't make sense to me and causes the entire UI to feel slow.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/1779894/53955321-b4962b80-40a6-11e9-8110-d0c07ef83bcb.png">

**Comment by dcalvom** [comment]
@wrathagom The issue with this is that every tag of keyword or action requires a full re render of the all syings being shown in the page. If you change the page size to 5, the response time is much less. Also the number of keywords tagged on each saying affects the result.

I will try to improve this by only re rendering the saying that was updated by the user. I will let you know how this goes.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/177a6e217f606ca8f5827e7e8d7c0aa64a33ab11
