### ISSUE TITLE
Validate Slot Templates and entity highlights before Save/Submit

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#63]
When the save/submit button is checked we should validate all of the prompt and response strings for valid {} template variables.

**Comment by wrathagom** [comment]
Trim spaces or similar solution when highlighting entities.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/c853e3c40d425043c0787b27167f0cb3c34f6f36
