### ISSUE TITLE
Category dropdown is shifting entire page down

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#630]
![2019-03-07_08-43-44 1](https://user-images.githubusercontent.com/1779894/53960883-5de41e00-40b5-11e9-8d34-4f5dd20b5e0a.gif)

**Comment by dcalvom** [comment]
For me worked fined on chrome and safari. Any special condition in the browser or window size?...I tried different resolutions

**Comment by dcalvom** [comment]
@wrathagom please post if you have this under any particular condition. I wasn't able to reproduce it
