### ISSUE TITLE
search in category dropdown doesn't work

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#631]
nope, it doesn't

**Comment by dcalvom** [comment]
This feature was lost with the API update. I don't know if the filter endpoint already work for categories.

**Comment by wrathagom** [comment]
I would assume since you are loading the entire list that this search would take place client side?

**Comment by wrathagom** [comment]
@dcalvom looks like the endpoint works perfectly fine, but the call isn't being formatted correctly. Right now the search box is trying to GET like `http://localhost:7500/agent/3/category?skip=0&limit=-1&filter=s` but filter needs to be an object like `http://localhost:7500/agent/3/category?filter=%7B%0A%20%20%22name%22%3A%20%22s%22%0A%7D` or more cleanly: `http://localhost:7500/agent/3/category?filter={"name":"s"}`

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/719f0656ffb94a5dd26c8f117d59583967d1e538
