### ISSUE TITLE
Training fails for new agent

### ISSUE THREAD

**Issue by tdanecker** [samtecspg/articulate#632]
Hello,

when I create a new agent and just add one saying for one new category, training the agent fails because the following line just returns undefined:
https://github.com/samtecspg/articulate/blob/7fdeb0bad20f6db2ef804c460ca59c8d83902c14/api/lib/services/agent/agent.train.service.js#L155-L157

If I enable "Generate separate models for each category" for the agent, training works again.

I've only tested it with the newest version (v0.21.2), so I can't say if it's a regression or something, but at the moment it is broken because of this bogus return statement.

**Comment by wrathagom** [comment]
you can't have just one saying, there should be an error shown in the chat panel of the UI saying as much. If not then we definitely need to add that error.

**Comment by wrathagom** [comment]
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/1779894/53972091-246add00-40cc-11e9-9dcb-41c47eeb2f65.png">

**Comment by tdanecker** [comment]
It also happens with two sayings.

With one saying:
![one-saying](https://user-images.githubusercontent.com/12449262/53972894-f99a7c00-40ff-11e9-8bc4-6d8def0724cf.png)

With two sayings:
![two-sayings](https://user-images.githubusercontent.com/12449262/53972908-01f2b700-4100-11e9-8995-25e428112c53.png)

After changing the settings:
![after-changing-settings](https://user-images.githubusercontent.com/12449262/53972927-09b25b80-4100-11e9-9a22-08be338833f0.png)

**Comment by tdanecker** [comment]
And the logs of articulate-api say the following:
```
articulate-api_1            | Debug: internal, implementation, error 
articulate-api_1            |     Error: handler method did not return a value, a promise, or throw an error
articulate-api_1            |     at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:52:29)
articulate-api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by wrathagom** [comment]
None of your sayings have actions associated with them.

**Comment by wrathagom** [comment]
Definitely need a better error message for that.

**Comment by tdanecker** [comment]
Ah, yes, after adding an action, I get proper responses. Thank you!

**Comment by wrathagom** [comment]
Thanks for the bug we’ll get a better error in there.

**Comment by wrathagom** [comment]
Closing in favor of #611
