### ISSUE TITLE
Bad lastTraining date when training fails

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#633]
On Russell's agent I keep seeing `lastTraining: " Invalid Date"` which suggests to me that when training fails we are still writing the date, but to a bad one.

Investigate and correct if possible. Or strip lastTraining dates on export since they really won't apply to new imports.

**Comment by dcalvom** [comment]
This is probably due to the library in charge of translate the date to "time ago". Let me check

**Comment by dcalvom** [comment]
I imported and checked in multiple scenarios but wasn't able to reproduced it, I used bad date string but it didn't show `Invalid Date`. Please post what is your scenario.

**Comment by wrathagom** [comment]
Okay, we'll see if it creeps back up in Russell's testing.
