### ISSUE TITLE
Improve not-trained error in chat

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#635]
Right now if the user chats with an agent that hasn't been trained yet they get:

> I'm sorry. An error occurred calling Articulate's converse service. This is not an issue with your agent.

We should change this to say:

> I'm not quite ready to chat yet. Try again soon.

**Comment by wrathagom** [comment]
We should probably also through a UI error? If possible something like:

> Someone is trying to chat with your agent, but it hasn't been trained yet. :(

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/94b3c781c26fe94ce1eb0e83b57aed2a6f0e59b2
