### ISSUE TITLE
I changed a keyword color and then went back to existing slot and it wasn't showing

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#636]
1. Create a keyword
2. Create an action
3. Create a slot for that keyword
4. change the color of that keyword
5. go back to action slot

I observed that the keyword no longer shows as selected:

![image](https://user-images.githubusercontent.com/1779894/54098163-b6533e00-4389-11e9-89c9-b7b22fe64490.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/59db6f3150eb9a53b11ea7d4a95db28964721ef4
