### ISSUE TITLE
Add Agent Icons

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#641]
The idea here is to have @broham89 create 10-15 simply agent gravatar type graphics and allow the users to specify which one they want and change the primary color.

Then on the agent page and really all other pages we show a small version of their agent icon with their selected color. This is setting the stage for some of the Ubiquity UI pieces.

@broham89 we'll need designs for:
- Agent gravatar type icons
- Agent page for setting icon and color

**Comment by broham89** [comment]
[gravatar-robots.zip](https://github.com/samtecspg/articulate/files/2964075/gravatar-robots.zip)

**Comment by wrathagom** [comment]
love 'em @broham89, Can you also give us UI design for how to display them on the agent list page (home page), agent page, and maybe the chat panel?

**Comment by broham89** [comment]
![agent list page: hover export](https://user-images.githubusercontent.com/11262149/54869560-6e102480-4d68-11e9-9cba-9667d7ebb7d8.png)
![v 2 - Agent create screen](https://user-images.githubusercontent.com/11262149/54869561-7700f600-4d68-11e9-8470-c18a3243d143.png)
Ignore the text content inside the bubbles
<img width="345" alt="Screen Shot 2019-03-23 at 12 36 40 PM" src="https://user-images.githubusercontent.com/11262149/54869564-7cf6d700-4d68-11e9-9b8c-3decfee086fa.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/56df3b0a3e1de41706141bb75f9c807b8383e0ea, https://github.com/samtecspg/articulate/commit/1f64f590e7ec8f03d598caeddd8ec0470e4d3292, https://github.com/samtecspg/articulate/commit/518e48fe6ca2df17266687905ea6a8b541d0d03f, and https://github.com/samtecspg/articulate/commit/3124151393a82320caca9c5f39281d9cec3e9fca
