### ISSUE TITLE
Can you add context functionality like dialogflow?

### ISSUE THREAD

**Issue by zhangyanbo2007** [samtecspg/articulate#645]

**Comment by dcalvom** [comment]
Hi @zhangyanbo2007 it seems like this is a feature request. Would you mind to provide more information please? 

What you mean by context functionality?

**Comment by dcalvom** [comment]
@zhangyanbo2007 We appreciate if you could specify us more about what you have in mind.

**Comment by wrathagom** [comment]
Closing since the conversation has gone closed, but just to re-iterate Articulate has an advanced context functionality and now includes `lifespans` to manage slot life.
