### ISSUE TITLE
have modifers able to recognize all values in a keyword

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#648]
### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

So, I've found that when testing in conversation if I don't have the value of a modifer training phrase included from a keyword, it won't detect it in conversation. For example:
"Ok we have a pizza with green peppers and ham."

"Lets add onions"

Agent will respond with the same, not detecting onions. "onions" is set in the keyword, and is listed there in the modifer, however, because its not in the training phrase like "lets add some sausage" it doesn't detect onions.

**Comment by wrathagom** [comment]
Just like with all entities you probably need to add more training data.

**Comment by RussellSPG** [comment]
oh, I'm sure, its just in the future it would be nice to have

**Comment by wrathagom** [comment]
Might be a duplicate of #596

**Comment by RussellSPG** [comment]
ah, I was searching for duplicates

**Comment by RussellSPG** [comment]
yup, it is. closing.

**Comment by RussellSPG** [comment]
closed. duplicate #596
