### ISSUE TITLE
Chat Panel Alignment and Overlap

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#65]
So as you can kind of see from this image the input box isn't in the right spot, but more importantly the chat is actually going over the input box.

This is another place where we should scroll the list as more input comes in.

**Comment by dcalvom** [comment]
Can you attach the image you are referring?

**Comment by wrathagom** [comment]
<img width="337" alt="2018-01-10_20-19-46 1" src="https://user-images.githubusercontent.com/1779894/35078479-787ec84e-fbd0-11e7-9984-3baa468e14dd.png">

**Comment by wrathagom** [comment]
@broham89 do you think you can get Articulate up and running to inspect the page and see what's going on here?

**Comment by broham89** [comment]
@caleb sure. What are the steps to get it up and running?

**Comment by broham89** [comment]
@dcalvom to fix this you would need to target `.bottom-nav`

-  `.bottom-nav`  {
    ~~margin-top: 77vh;~~
    bottom: 75px;
    width: 100%;
    position: absolute;
    }

**Comment by dcalvom** [comment]
@wrathagom could you verify if this error is still happening. I tested multiple resolutions and seems to be solved. I'm going to close it, but feel free to reopen it if you still find some issues.

**Comment by wrathagom** [comment]
Can we fix this?
<img width="1904" alt="2018-03-09_22-30-41" src="https://user-images.githubusercontent.com/1779894/37237939-aae8e508-23e9-11e8-804c-5dff5f5380d3.png">

**Comment by wrathagom** [comment]
Also, I still think the chat input should be in the corner not 300px above the bottom.

**Comment by wrathagom** [comment]
Confirmed tha I wasn't seeing this behavior anymore.
