### ISSUE TITLE
Convert agents list to side scrolling

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#650]
I want to place the ubiquity connections on a second line below the agents list. So before we get there we need to convert the agent list to a side scrolling list. Up to @broham89 if we need an arrow for scrolling left/right or how we indicate that scrolling is possible.

![image](https://user-images.githubusercontent.com/1779894/54859777-ce12b680-4ce7-11e9-9f68-9cde9c8474a5.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b16ccc01fcb35bbe91d828d5d55703933bb1b0d8
