### ISSUE TITLE
Edge: Missing Pagination Up DownArrows for Action Rec Threshold

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#655]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
21.1
- What operating system are you running?
win 10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
Microsoft Edge

Missing Top/Bottom arrows in Agent screen when lowing/raising Action Recognition Threshold.

Step: 1.22 on script

![image](https://user-images.githubusercontent.com/42249324/54956870-7ebac900-4f27-11e9-9646-354f1ebf9af2.png)

All you can see is the "x" icon that clears the numerical value:

![image](https://user-images.githubusercontent.com/42249324/54956973-d0635380-4f27-11e9-91b1-0be47c8c6f32.png)

----

**Comment by dcalvom** [comment]
This seems to be a browser specific issue
