### ISSUE TITLE
Microsoft Edge: Missing Pagination Up Down arrows in page input on keywords screen

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#657]
This time, no "x" icon to delete the value let alone any arrows in the keywords screen. As the other issues, no errors found in console.

![image](https://user-images.githubusercontent.com/42249324/54957953-93e52700-4f2a-11e9-941a-dd6f2dafa12b.png)

Step: 3.33 on script

- Did you download a release or pull from Master? Which release?
21.1
- What operating system are you running?
win 10 pro 
- Are you running locally or in the cloud?
local
- Which browser are you using?
Microsoft Edge

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by wrathagom** [comment]
to delete a keyword you have to navigate to the keyword page and click delete at the bottom of the page. and I don't know what you mean about arrows?

**Comment by RussellSPG** [comment]
I know how to delete the keywords. The issue is about the top/bottom arrows near the next/previous botton. To go next/back page. They aren't visibile with ME browser

**Comment by wrathagom** [comment]
wow I had no clue what you were talking about.

**Comment by RussellSPG** [comment]
Yea, seems Edge has an issue with top/down arrows for scrolling through the pages.

**Comment by wrathagom** [comment]
This is probably inherent to the underlying library and I don't think we should chase it down.
