### ISSUE TITLE
Issue with elastic search

### ISSUE THREAD

**Issue by devotionsolutions** [samtecspg/articulate#659]
Hello everyone,
I'm trying to run articulate on Linux Ubuntu Server 18.04 LTS.
I've followed the steps for the basic installation and I'm experiencing an issue with elasticsearch initialization.

This is what I'm getting:

Creating network "articulate-v0212_default" with the default driver
Creating articulate-v0212_api_1_e710f4b75e84           ... done
Creating articulate-v0212_duckling_1_2908d68209a7      ... done
Creating articulate-v0212_ui_1_2d5a5eca059b            ... done
Creating articulate-v0212_elasticsearch_1_f1fb65b386b5 ... done
Creating articulate-v0212_redis_1_3c429579c690         ... done
Creating articulate-v0212_rasa_1_a4326d12ca05          ... done
Attaching to articulate-v0212_duckling_1_5aa35a59330a, articulate-v0212_ui_1_cbd                                                                                                                                                             973db533c, articulate-v0212_api_1_3d5e9c33b97e, articulate-v0212_elasticsearch_1                                                                                                                                                             _c2b0bd066a5a, articulate-v0212_redis_1_81bea3efb5ef, articulate-v0212_rasa_1_e4                                                                                                                                                             78642200fe
duckling_1_5aa35a59330a | no port specified, defaulting to port 8000
duckling_1_5aa35a59330a | Listening on http://0.0.0.0:8000
ui_1_cbd973db533c | yarn run v1.13.0
ui_1_cbd973db533c | $ cross-env NODE_ENV=production env-cmd .env node server
ui_1_cbd973db533c | Server started ! ✓
ui_1_cbd973db533c |
ui_1_cbd973db533c | Access URLs:
ui_1_cbd973db533c | -----------------------------------
ui_1_cbd973db533c | Localhost: http://localhost:3000
ui_1_cbd973db533c |       LAN: http://172.19.0.3:3000
ui_1_cbd973db533c | -----------------------------------
ui_1_cbd973db533c | Press CTRL-C to stop
ui_1_cbd973db533c |
api_1_3d5e9c33b97e | 2019/03/26 16:46:25 Waiting for: http://elasticsearch:9200
redis_1_81bea3efb5ef | 1:C 26 Mar 16:46:26.590 # oO0OoO0OoO0Oo Redis is starting                                                                                                                                                              oO0OoO0OoO0Oo
redis_1_81bea3efb5ef | 1:C 26 Mar 16:46:26.590 # Redis version=4.0.6, bits=64, c                                                                                                                                                             ommit=00000000, modified=0, pid=1, just started
redis_1_81bea3efb5ef | 1:C 26 Mar 16:46:26.590 # Configuration loaded
redis_1_81bea3efb5ef | 1:M 26 Mar 16:46:26.592 * Running mode=standalone, port=6                                                                                                                                                             379.
redis_1_81bea3efb5ef | 1:M 26 Mar 16:46:26.592 # WARNING: The TCP backlog settin                                                                                                                                                             g of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the l                                                                                                                                                             ower value of 128.
redis_1_81bea3efb5ef | 1:M 26 Mar 16:46:26.592 # Server initialized
redis_1_81bea3efb5ef | 1:M 26 Mar 16:46:26.592 # WARNING overcommit_memory is se                                                                                                                                                             t to 0! Background save may fail under low memory condition. To fix this issue a                                                                                                                                                             dd 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the com                                                                                                                                                             mand 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1_81bea3efb5ef | 1:M 26 Mar 16:46:26.593 # WARNING you have Transparent Hu                                                                                                                                                             ge Pages (THP) support enabled in your kernel. This will create latency and memo                                                                                                                                                             ry usage issues with Redis. To fix this issue run the command 'echo never > /sys                                                                                                                                                             /kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.loc                                                                                                                                                             al in order to retain the setting after a reboot. Redis must be restarted after                                                                                                                                                              THP is disabled.
redis_1_81bea3efb5ef | 1:M 26 Mar 16:46:26.593 * Ready to accept connections
elasticsearch_1_c2b0bd066a5a | OpenJDK 64-Bit Server VM warning: Option UseConcM                                                                                                                                                             arkSweepGC was deprecated in version 9.0 and will likely be removed in a future                                                                                                                                                              release.
api_1_3d5e9c33b97e | 2019/03/26 16:46:26 Problem with request: Get http://elasti                                                                                                                                                             csearch:9200: dial tcp 172.19.0.5:9200: connect: connection refused. Sleeping 1s
api_1_3d5e9c33b97e | 2019/03/26 16:46:27 Problem with request: Get http://elasti                                                                                                                                                             csearch:9200: dial tcp 172.19.0.5:9200: connect: connection refused. Sleeping 1s
elasticsearch_1_c2b0bd066a5a | [2019-03-26T16:46:28,508][WARN ][o.e.c.l.LogConfi                                                                                                                                                             gurator  ] [unknown] Some logging configurations have %marker but don't have %no                                                                                                                                                             de_name. We will automatically add %node_name to the pattern to ease the migrati                                                                                                                                                             on for users who customize log4j2.properties but will stop this behavior in 7.0.                                                                                                                                                              You should manually replace `%node_name` with `[%node_name]%marker ` in these l                                                                                                                                                             ocations:
elasticsearch_1_c2b0bd066a5a |   /usr/share/elasticsearch/config/log4j2.properti                                                                                                                                                             es
api_1_3d5e9c33b97e | 2019/03/26 16:46:28 Problem with request: Get http://elasti                                                                                                                                                             csearch:9200: dial tcp 172.19.0.5:9200: connect: connection refused. Sleeping 1s
elasticsearch_1_c2b0bd066a5a | [2019-03-26T16:46:28,951][WARN ][o.e.b.Elasticsea                                                                                                                                                             rchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
elasticsearch_1_c2b0bd066a5a | org.elasticsearch.bootstrap.StartupException: jav                                                                                                                                                             a.lang.IllegalStateException: Failed to create node environment
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Elasticsearch.ini                                                                                                                                                             t(Elasticsearch.java:140) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Elasticsearch.exe                                                                                                                                                             cute(Elasticsearch.java:127) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.cli.EnvironmentAwareCommand                                                                                                                                                             .execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.cli.Command.mainWithoutErro                                                                                                                                                             rHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.cli.Command.main(Command.ja                                                                                                                                                             va:90) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Elasticsearch.mai                                                                                                                                                             n(Elasticsearch.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Elasticsearch.mai                                                                                                                                                             n(Elasticsearch.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a | Caused by: java.lang.IllegalStateException: Faile                                                                                                                                                             d to create node environment
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.node.Node.<init>(Node.java:                                                                                                                                                             299) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.node.Node.<init>(Node.java:                                                                                                                                                             265) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Bootstrap$5.<init                                                                                                                                                             >(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Bootstrap.setup(B                                                                                                                                                             ootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Bootstrap.init(Bo                                                                                                                                                             otstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Elasticsearch.ini                                                                                                                                                             t(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  ... 6 more
elasticsearch_1_c2b0bd066a5a | Caused by: java.nio.file.AccessDeniedException: /                                                                                                                                                             usr/share/elasticsearch/data/nodes
elasticsearch_1_c2b0bd066a5a |  at sun.nio.fs.UnixException.translateToIOExcepti                                                                                                                                                             on(UnixException.java:90) ~[?:?]
elasticsearch_1_c2b0bd066a5a |  at sun.nio.fs.UnixException.rethrowAsIOException                                                                                                                                                             (UnixException.java:111) ~[?:?]
elasticsearch_1_c2b0bd066a5a |  at sun.nio.fs.UnixException.rethrowAsIOException                                                                                                                                                             (UnixException.java:116) ~[?:?]
elasticsearch_1_c2b0bd066a5a |  at sun.nio.fs.UnixFileSystemProvider.createDirec                                                                                                                                                             tory(UnixFileSystemProvider.java:385) ~[?:?]
elasticsearch_1_c2b0bd066a5a |  at java.nio.file.Files.createDirectory(Files.jav                                                                                                                                                             a:689) ~[?:?]
elasticsearch_1_c2b0bd066a5a |  at java.nio.file.Files.createAndCheckIsDirectory                                                                                                                                                             (Files.java:796) ~[?:?]
elasticsearch_1_c2b0bd066a5a |  at java.nio.file.Files.createDirectories(Files.j                                                                                                                                                             ava:782) ~[?:?]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.env.NodeEnvironment.lambda$                                                                                                                                                             new$0(NodeEnvironment.java:270) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.env.NodeEnvironment$NodeLoc                                                                                                                                                             k.<init>(NodeEnvironment.java:203) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.env.NodeEnvironment.<init>(                                                                                                                                                             NodeEnvironment.java:267) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.node.Node.<init>(Node.java:                                                                                                                                                             296) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.node.Node.<init>(Node.java:                                                                                                                                                             265) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Bootstrap$5.<init                                                                                                                                                             >(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Bootstrap.setup(B                                                                                                                                                             ootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Bootstrap.init(Bo                                                                                                                                                             otstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  at org.elasticsearch.bootstrap.Elasticsearch.ini                                                                                                                                                             t(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1_c2b0bd066a5a |  ... 6 more
rasa_1_e478642200fe | 2019-03-26 16:46:29+0000 [-] Log opened.
rasa_1_e478642200fe | 2019-03-26 16:46:29+0000 [-] Site starting on 5000
rasa_1_e478642200fe | 2019-03-26 16:46:29+0000 [-] Starting factory <twisted.web                                                                                                                                                             .server.Site object at 0x7f24fd031550>
api_1_3d5e9c33b97e | 2019/03/26 16:46:29 Problem with request: Get http://elasti                                                                                                                                                             csearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sle                                                                                                                                                             eping 1s
articulate-v0212_elasticsearch_1_c2b0bd066a5a exited with code 1
api_1_3d5e9c33b97e | 2019/03/26 16:46:30 Problem with request: Get http://elasti                                                                                                                                                             csearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sle                                                                                                                                                             eping 1s

Any idea?

**Comment by dcalvom** [comment]
Did you modify your compose file?

**Comment by devotionsolutions** [comment]
No, no modifications on the docker compose file this time.

**Comment by devotionsolutions** [comment]
I've just recreated the VM and started from the beginning, and I have the same error. Ubuntu  Server 18.04 LTS running on Azure

**Comment by wrathagom** [comment]
Sorry, just getting back to this, so you're saying on Ubuntu 18.04 with a fresh download of 0.21.2 you're getting the above error?

**Comment by devotionsolutions** [comment]
Hello, 

> 
> 
> Sorry, just getting back to this, so you're saying on Ubuntu 18.04 with a fresh download of 0.21.2 you're getting the above error?

Yes, exactly. I've switched to CentOS and everything went smooth

**Comment by wrathagom** [comment]
the access denied error for Elasticsearch just means that the user you're running Docker with isn't UID 1000

You probably could've solved this on Ubuntu with `sudo chown -R 1000:1000 local-storage/elasticsearch`

**Comment by wrathagom** [comment]
Glad you got it working though.
