### ISSUE TITLE
Unbalanced Intent Training Data

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#66]
Currently the way we generate training data creates a cross product of all entities, synonyms, and training examples. For intents like Greet, Goodbye, etc this results in the number of examples in the training data being equal to the number of examples given in the UI.

However for intents like ordering pizza this could result in thousands of possible combinations. When we take the cross of 10 intent examples, 20 pizza topping entity values, and 3 delivery method values that's something like 600 different training examples. Once we do this the training data (primarily domain recognizer) becomes way unbalanced.

Need to investigate a way around this (over sampling/undersampling/eliminating the cross product)

Also need to investigate how and where to apply it (just to the domain recognizer? Should it be configurable on an agent by agent basis? Domain by domain basis?)

**Comment by wrathagom** [comment]
I haven't encountered this since this day, I have a feeling it has to do with the move to spacy 2.0, but can't guarantee it.

@dcalvom do you have any intents that are highly unbalanced In Florence? Have you encountered a problem with this?

**Comment by dcalvom** [comment]
Yeah, indeed they are highly unbalanced. For example, I have the small talk domain with the greeting intent as the largest intent with 19 examples, on the other hand, I have the `Medical Tests` domain with the `Get Images` intent that haves 18300 examples. Also the `Get Patient Name` and `Get Vitals` intents sum 2449 distinct exampless in the `Bed Control` domain.

**Comment by dcalvom** [comment]
Is this question still open! at least for the tests, I have done so far is not something that causes me troubles, in example with Florence the recognition worked fine, and I think for Marco in his agent the performance wasn't affected by the number of examples in his intents.

**Comment by wrathagom** [comment]
I'm good with closing.

**Comment by wrathagom** [comment]
As a side note the generation was what would make it really unbalanced... so if you experience problems with unbalances data may be a sign you should turn off the generation.
