### ISSUE TITLE
Long single words overflow message box in chat panel

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#663]
![image](https://user-images.githubusercontent.com/7228045/55050088-8c01b180-5014-11e9-8c9b-a25c26fbedff.png)

@broham89 what would be the best way to manage this?

**Comment by dcalvom** [comment]
![image](https://user-images.githubusercontent.com/7228045/55050076-860bd080-5014-11e9-98e3-b971388adb28.png)

**Comment by broham89** [comment]
have the word wrapped like this example..
![IMG_0027](https://user-images.githubusercontent.com/11262149/55050364-4ea22180-501e-11e9-9f9a-0fefe2373551.PNG)

**Comment by broham89** [comment]
have the word wrapped like this example..
![unnamed-1](https://user-images.githubusercontent.com/11262149/55766793-da16ac00-5a3b-11e9-9308-70222b701d05.jpg)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/44810b0fa0f2e600c40bda41c82555ccbc91d02c
