### ISSUE TITLE
Properly handle concurrent training processes and errors

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#664]
Right now if you are training more models than allowed by your rasa config you aren't getting any warning about this, the UI just switch to the `training error` status. We need to improve this.

Also we need to review the current training process in order to check what is the status of parallel training.

**Comment by wrathagom** [comment]
I want to couple this with an improved Rasa API that we build. In other words I want to build queuing into the Rasa API I think. Rather than a part of how Arty handles Rasa.

**Comment by wrathagom** [comment]
https://github.com/Automattic/kue
