### ISSUE TITLE
Edge: Text Highlights on Sayings screen when select results displayed

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#665]
Please describe the issue you are having here and answer the question below.

When I click on the bottom left corner to show more results by page, text will highlight in the page again just as the previous posts.

![image](https://user-images.githubusercontent.com/42249324/55402802-597b1b80-5522-11e9-9b19-e7f0ed0ad364.png)

Step 7.21

- Did you download a release or pull from Master? Which release?
release 21.1
- What operating system are you running?
win 10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
Edge
----

**Comment by dcalvom** [comment]
I wasn't able to reproduce this one, please re open if you have this bug again.
