### ISSUE TITLE
Add MAIN action for Agent when using Google Home channel in ubiquity

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#668]
Google actions require the MAIN intent that is the intent that's going to be triggered when the user starts the app.

We should allow the user to pick from his list of actions the action that will be the MAIN action.

In example:

If we have the pizza bot and the user says `Ok Google, talk with Pizza Bot`, we should trigger the greeting action so the bot can respond `Hey, how can I help you today?`.

**Comment by wrathagom** [comment]
I would imagine this would be something configured during the creation of the Ubiquity connection?

**Comment by wrathagom** [comment]
I think this one is addressed right @dcalvom?

**Comment by dcalvom** [comment]
Yes. It is addressed with the docs. https://github.com/samtecspg/articulate/blob/master/api/lib/channels/google-home/README.MD
