### ISSUE TITLE
Improve Chat Panel

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#669]
Right now the chat panel in the Articulate interface has several drawbacks:

- [x] Session is shared across all instances `articulateUI` - propose that we use localStorage (maybe session Storage) to create a session ID for each agent, something like `Samson-session-s0m3-guid-here`.
- [x] Navigating away and back loses conversation history - This def shouldn't happen, but even more so we likely should add a dropdown so that we can load any session for review.
- [x] I think we should start with the chat panel open after agent creation and re-direct to the sayings page.
- [x] Make width adjustable to an extent
- [x] Change clear session button to be "new session" button

**Comment by dcalvom** [comment]
@wrathagom the `Clear All` button rigth now clear notifications and session data. If we change the text to `New Session` user will be confused why notification went away. What you think?

**Comment by dcalvom** [comment]
@broham89 could you take a look at the second bullet. @wrathagom wants a dropdown to select different sessions in the conversation panel.

I'm going to try to create a basic one, but if you can come up with a design let me know.

**Comment by wrathagom** [comment]
@dcalvom my vote would be to leave the clear all button at the top and add a couple of buttons at the bottom. Maybe something like:

![image](https://user-images.githubusercontent.com/1779894/56611922-06582e00-65e1-11e9-9c65-be554d196956.png)

forgive the bad paint job :D

**Comment by wrathagom** [comment]
I borrowed the dropdown from the category, but imagine that as saying `articulateUI` with a New button and a delete button beside it. Both of these smaller than our normal buttons since they are secondary type actions.

**Comment by broham89** [comment]
Currently working on a solution

**Comment by broham89** [comment]
<img width="215" alt="Screen Shot 2019-04-24 at 7 57 04 PM" src="https://user-images.githubusercontent.com/11262149/56702728-28c67600-66cb-11e9-807d-e86583826bdd.png">

**Comment by wrathagom** [comment]
looks good to me.

**Comment by broham89** [comment]
here's another version that takes away the clear button on top and put it inside the `three-dot` dropdown. 
<img width="178" alt="Screen Shot 2019-04-24 at 8 12 29 PM" src="https://user-images.githubusercontent.com/11262149/56703226-83f96800-66cd-11e9-9679-5b8f51e12c3e.png">
When a user clicks on `session history` it will bring up a popup like the first screenshot alowing the user to create or delete sessions

**Comment by wrathagom** [comment]
I'm not a big fan of menus in menus. And if we went with this one I would want some visual indicator of what the current session was.

Another potential wrinkle for either of these... sessions don't have friendly names. They have really ugly ids. 

Maybe rather than a dropdown/select for sessions we have an input with typeahead enabled. and a new icon inside that input for generating new sessions...???

**Comment by broham89** [comment]
<img width="421" alt="Screen Shot 2019-04-25 at 6 23 21 PM" src="https://user-images.githubusercontent.com/11262149/56774197-3c371700-6787-11e9-875c-111d192a538c.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/a752c32474bf10323786fd12600c9aac707d1dcc
