### ISSUE TITLE
Change lifespans to not rely on empty vs 0 vs number, I'd rather we have checkboxes

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#673]
![image](https://user-images.githubusercontent.com/1779894/55693170-99575e00-597b-11e9-88e3-71f35b0c6963.png)

I don't really like this help text below the input. I want the input itself to be self explanatory if possible. I think we should have a checkmark for `Remember Value?` and then a checkmark for `Remember Forever?` and then an input that shows up whenever remember value is checked but remember forever isn't.

are there parameters to remember forever? If not that then we can just omit that option for now.

@broham89 certainly open to your input here.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3084f980a4a84800cf9b7bac0fe26a40b83cdd31
