### ISSUE TITLE
Editing responses in line doesn't change checkmark back to save button

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#674]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
- What operating system are you running?
- Are you running locally or in the cloud?
- Which browser are you using?

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/2dbb2a446e6c1767d8476cb038c43a9ba85f2a78
