### ISSUE TITLE
Boolean operators in handlebars?

### ISSUE THREAD

**Issue by nanonaren** [samtecspg/articulate#675]
Is it possible to have boolean operators in handlebars? So for example, I want to respond when two slots have the 'yes' value in them. I only know how to check one variable in the response...

```
{{#eq slots.variable.value 'yes'}}Response{{/eq}}
```

In general, can you point me to where I can find out more about the handlebar syntax and its scope? Is it a subset of some existing language?

Thank you

**Comment by wrathagom** [comment]
the syntax you've written looks correct to me.

You can find more handlebars info at their own website: https://handlebarsjs.com

We also use an extra library for more functionality: https://github.com/helpers/handlebars-helpers

let us know if you're still having trouble with it.

**Comment by nanonaren** [comment]
Thanks! That extra library is great!
