### ISSUE TITLE
Need better error message when training agent without any sayings

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#676]
When training agent with just creating the agent and not create sayings/training phrases etc, it just shows an error on conversation window:

![image](https://user-images.githubusercontent.com/42249324/55762267-573c2400-5a30-11e9-9b3b-a0e70350df42.png)

I feel the error could be: "You have no training phrases for the agent to learn on" Or something like that.

Somebody who isn't familar with AI may just hit the train button thinking its needed because it says "never trained"
Also got an error in browser console:

```
TypeError: o is not a function[Learn More]
```
Step 1.7 on Break script. 

Add to this: training keywords that aren't even used doesn't result in any message/notification as well. IMO, an agent shouldn't be trained unless the keywords are actually used. 

- Did you download a release or pull from Master? Which release?
21.1
- What operating system are you running?
10 ori
- Are you running locally or in the cloud?
local
- Which browser are you using?
firefox

**Comment by wrathagom** [comment]
@dcalvom I thought we fixed this, but I can still get it to happen on master. Click training with a completely empty agent. Maybe throw an error with a message of `Add some sayings before training your agent.`

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/4b83727cedf6e7edbadf239df2d7be715c0bc7af
