### ISSUE TITLE
webhook response error

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#677]
I was testing a webhook that was returning a 500 error with a body:

```
{
    "Error": "\n---------------------------------------------------------------------------\nException encountered at \"In [8]\":\n---------------------------------------------------------------------------\nTypeError                                 Traceback (most recent call last)\n<ipython-input-8-7e4269b6811b> in <module>\n     14     sb.glue(\"executionCount\", executionCount)\n     15 else:\n---> 16     sb.glue(\"error\")\n\nTypeError: glue() missing 1 required positional argument: 'scrap'\n"
}
```

but I kept getting an error in the terminal:

```
api_1            | { error:
api_1            |    ReferenceError: response is not defined
api_1            |        at AgentService.response (/usr/src/app/lib/services/agent/agent.converse-call-webhook.service.js:91:29)
api_1            |        at Generator.throw (<anonymous>)
api_1            |        at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.converse-call-webhook.service.js:15:103)
api_1            |        at _throw (/usr/src/app/lib/services/agent/agent.converse-call-webhook.service.js:17:291)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
```

along with a `I'm sorry. An error occurred calling Articulate's converse service. This is not an issue with your agent.` message in the UI.

I would expect that this would get passed to the webhook responses just like normal for choosing how to reply.

**Comment by shraddha2806** [comment]
I am also getting the same message " I'm sorry. An error occurred calling Articulate's converse service. This is not an issue with your agent."
my articulate version is "articulate-0.21.2".


Can you show any example of webhook, like how it hits the given URL and gets the response.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/efe210acdfa19f71f829dce4f8f929f759983e2b
