### ISSUE TITLE
Add help bubble to generate extra training examples option

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#679]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

I think it would be better if we had a help bubble that appears, to explain when we'd need the extra training examples option. In case somebody runs into problems because of it not knowing what it is, just thinking "its better to have it on".

![image](https://user-images.githubusercontent.com/42249324/55911608-fa1aac80-5bae-11e9-95cc-a690971102c4.png)

Will post results if I do get errors

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
21.1 
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF
----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/30ea6bb1b2802bb6dad3cda52b481387c310d3e3
