### ISSUE TITLE
Move Save/Create buttons to breadcrumb bar on all screens.

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#68]
Currently the info/alerts cover up these buttons which is really annoying. The buttons also cover up actions on the page. So we should move the buttons to the breadcrumb bar.

**Comment by wrathagom** [comment]
<img width="1648" alt="2018-01-17_21-49-36" src="https://user-images.githubusercontent.com/1779894/35078459-5c7cbdcc-fbd0-11e7-960e-fd35d4d857dd.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3e914e1e6527abf0b6dc46c408aa3fc0ef839358
