### ISSUE TITLE
could have better error message when training agents without responses

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#680]
### Issues
Similar to my last post #676, when training an agent without a response but have phrases, it just shows:
![image](https://user-images.githubusercontent.com/42249324/55912032-d4da6e00-5baf-11e9-86c9-58efbecdde34.png)
Would be better to say something like "A response is needed for the training phrases or the agent cannot be trained!"

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
release 21.1
- What operating system are you running?
10 ori
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by wrathagom** [comment]
This is handled now.
