### ISSUE TITLE
don't allow fallback action to be used as other actions for phrases. 

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#681]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

A fallback action can be used right now for an action for a normal training phrase. I think the fallback actions created should be locked just to the agent settings and only created in the agent page. So for example, if you set the fallback action to a saying: I want a pizza, a window can come up that says "can not set fallback action as a standard action to a phrase!" Or something like that. 

![image](https://user-images.githubusercontent.com/42249324/55913180-ffc5c180-5bb1-11e9-8802-297301b45d07.png)

ver 21.1 release
local
win10 pro
FF browser

**Comment by wrathagom** [comment]
this is on purpose. We have places where we fall back to a more generic search, but that search my also be useful as a regular action.

**Comment by RussellSPG** [comment]
ok
