### ISSUE TITLE
Pre-Built Categories

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#683]
There are a lot of moving pieces to this one. I want to present the user with a list of pre-built categories that they can load into their agent. For the moment I am choosing to do this on the create Category screen.

There is also a large API component to this since the API will need to have some methodology for storing these and loading them into an agent.

Pre-Built categories will contain:

- Sayings (training data for the category)
- Keywords (for example locations for weather?)
 - we'll need to handle when the keyword we're trying to create already exists
- parameters
 - Webhooks
 - responses

Here's a rough rendition of how I see this looking in the UI:
![image](https://user-images.githubusercontent.com/1779894/55966620-b96e7200-5c46-11e9-944a-9f78de380802.png)

**Comment by RussellSPG** [comment]
I really like this idea, and maybe also prebuilt sayings & actions, keywords, slots to go along with those categories. Having an example of every entity in Articulate really makes it easier to understand how to use the platform IMO.

**Comment by broham89** [comment]
![Category - v 2: Pre-built Categories](https://user-images.githubusercontent.com/11262149/56251953-3c466100-607b-11e9-99db-a80c754ff207.png)
![Category - v 2: Pre-built Categories open](https://user-images.githubusercontent.com/11262149/56251959-40727e80-607b-11e9-9937-938ae6ce0887.png)

**Comment by wrathagom** [comment]
This is too understated. and doesn't provide a way for you to give info about it. I envisioned them as complete as cards.

**Comment by broham89** [comment]
![Category - v 2: Pre-built Categories](https://user-images.githubusercontent.com/11262149/56252594-166e8b80-607e-11e9-902e-23a7a0fcafb3.png)
Above img: I made the cards the same size at the inputs so that it doesn't stand out dominating too much 

![Category - v 3: Pre-built Categories](https://user-images.githubusercontent.com/11262149/56252724-ce9c3400-607e-11e9-8b37-8a6a87393f12.png)
Above Img: I made the cards even smaller to not draw more attention and let the pre-built feel more like a **suggestion** instead of a main point of creating categories

**Comment by wrathagom** [comment]
So in the end there could be 10-20 of these so we should think about what that could look like. Just a large side scrolling list?

Also, should we/could we add an info icon that pops up a modal of what types of sayings/etc are included inside that category?

**Comment by broham89** [comment]
I was thinking of having it as a button to expand towards a pop-up module presenting all 20+ pre-built categories that can be scrolled. 
![Category - v 4: Pre-built Categories](https://user-images.githubusercontent.com/11262149/56326688-b12d9f80-613c-11e9-827a-058c5110546f.png)

Once clicked on the button it will pop-up the category lists and a sayings icon on the hovered list-item to the right. if clicked there will slide to `image 4` below with the `<-back arrow` to go back to the category list. 
![Category - v 4: Pre-built popup](https://user-images.githubusercontent.com/11262149/56326696-b854ad80-613c-11e9-8f73-ba7f91112370.png)

If a user clicked on a prebuilt category, a little green notification status will be below the category name to confirm to the user the prebuilt is added. 
![Category - v 4: Pre-built added](https://user-images.githubusercontent.com/11262149/56326703-c5719c80-613c-11e9-9a0e-21683ba304e4.png)

**One thing to note here** if the user clicks on the sayings, the example above image, this module pop-up will not have the `<- Back` button. That button will only be present if the user clicks on the sayings icon in the category list (2nd image)
![Category - v 4: Pre-built sayings](https://user-images.githubusercontent.com/11262149/56326713-cacee700-613c-11e9-8944-95cb936d6d69.png)

**Comment by broham89** [comment]
Thoughts?

**Comment by wrathagom** [comment]
I kind of want to show them off more than any of those screens accomplish.

Also here's the Dialogflow equivalent:
![image](https://user-images.githubusercontent.com/1779894/56364648-0c9f7200-61bd-11e9-9be3-2cae0d710fdf.png)

**Comment by broham89** [comment]
![prebuilt category: step 1](https://user-images.githubusercontent.com/11262149/57418989-115ab300-71ca-11e9-9948-36fadf5bc3c9.png)
![prebuilt category: step2](https://user-images.githubusercontent.com/11262149/57418995-115ab300-71ca-11e9-8f4b-cd0a11ad45c5.png)
@wrathagom Is this something you would consider seeing?

**Comment by wrathagom** [comment]
I like it. @dcalvom @broham89 what about if instead of trying to integrate this into the current "Create a category" screen we added a routing step before it. Essentially the grid that is displayed above, but with the top left item being `Create Custom Category`

**Comment by broham89** [comment]
@wrathagom so to clarify, you want the grid to be the default when users get to this page and have a `custom create btn` as a secondary thing?
