### ISSUE TITLE
Traversal of action tree

### ISSUE THREAD

**Issue by nanonaren** [samtecspg/articulate#685]
I setup a chain of actions as follows
A -> B, C
B -> B2

When starting with A the order of actions unfolds as A,B,C,B2. But shouldn't it unfold in a depth-first manner as A,B,B2,C?

**Comment by wrathagom** [comment]
newest actions get added to the end of the queue. We're certainly willing to discuss whether that was a good choice or not.

I believe if you need finer grained control you should be able to manually manipulate the action queue via the context endpoint.

**Comment by wrathagom** [comment]
@dcalvom we could also give chained actions an extra parameter for choosing where it goes in the queue?

**Comment by nanonaren** [comment]
@wrathagom Could you please explain what you mean by "I believe if you need finer grained control you should be able to manually manipulate the action queue via the context endpoint."?

**Comment by wrathagom** [comment]
You could use the `PATCH /context/{sessionId}` Api endpoint to manually modify the action queue:

```
{
  "savedSlots": {},
  "actionQueue": [
    "string"
  ],
  "responseQueue": [
    "string"
  ],
  "creationDate": "string",
  "modificationDate": "string"
}
```

**Comment by nanonaren** [comment]
Thanks.
