### ISSUE TITLE
Trying to go to the Review page when on Spanish UI language setting

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#688]
Throws an error

```
[Error] TypeError: undefined is not an object (evaluating 'o.task.cancel')
	Ss (vendors~main.59943781a3768f87b902.chunk.js:33:97911)
	Rs (vendors~main.59943781a3768f87b902.chunk.js:33:99081)
	kn (vendors~main.59943781a3768f87b902.chunk.js:33:30885)
	kn
```

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e06e6293409a7aa49d53bb215e60d7ce9572db72

**Comment by wrathagom** [comment]
Still seeing this. Really it isn't just the review page. No matter what page I navigate too after changing languages I get a blank screen.

**Comment by dcalvom** [comment]
Wasn't able to reproduce this one, neither in chrome nor safari.

**Comment by wrathagom** [comment]
Can only re-create in "prod" mode. Maybe we should pause this one and see if it is still happening when @malave is done moving back to express.

**Comment by wrathagom** [comment]
Can't reproduce anymore
