### ISSUE TITLE
Language dropdown text disappears

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#689]
I think there used to be text describing what this dropdown was for, but now it's gone. I don't know if it disappeared when I clicked on it or somehow got removed, but at the moment the user wouldn't know what it is for.

![image](https://user-images.githubusercontent.com/1779894/56260019-5c8a1600-60a3-11e9-95e7-eb8e4b181ab5.png)

**Comment by wrathagom** [comment]
Still gone even when chat panel is collapsed:

![image](https://user-images.githubusercontent.com/1779894/56260043-85aaa680-60a3-11e9-9d4e-4c42c919c727.png)

**Comment by dcalvom** [comment]
closed by https://github.com/samtecspg/articulate/commit/e06e6293409a7aa49d53bb215e60d7ce9572db72
