### ISSUE TITLE
Explain why the user has to do choose a category in review page copy button

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#690]
![image](https://user-images.githubusercontent.com/1779894/56260375-fc946f00-60a4-11e9-9ca6-17a32540e1a8.png)

Should say instead something like:

```
This agent is configured to use a single classification model for all categories. To copy this text as a new saying please specify the category it belongs to:
```

**Comment by wrathagom** [comment]
also, can we increase the width or decrease the dropdown help text.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/4bbad5162d66df2fe8842319267d3f42baf8de7b
