### ISSUE TITLE
Justification of action tags is different on the sayings page vs action response page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#692]
![image](https://user-images.githubusercontent.com/1779894/56292624-85d39200-60f5-11e9-838f-c4186226d596.png)

![image](https://user-images.githubusercontent.com/1779894/56292674-9a178f00-60f5-11e9-8e77-818a2b8b4690.png)

**Comment by dcalvom** [comment]
I know it looks different, but the main issue is that the response row is editable inline, meanwhile the saying row is a span. Therefore, the alignment of action tags is totally different. I tried several ways to replicate the layout of the saying row in the response row but it wasn't fruitful.

Also is hard to replicate the response row layout into the saying row, as the saying row have the functionality for keyword highlighting.

**Comment by dcalvom** [comment]
@wrathagom Do you think we can close this one and start to think on inline edit of sayings?

**Comment by wrathagom** [comment]
I don't know if that really helps you, because I want the style on the sayings page not the one on the responses page. So one way or the other we have to figure out how to make it look like what the sayings page has now.

**Comment by wrathagom** [comment]
I am really hopeful on the responses side of things that it is as easy as chaning the list from `<input>`s to `<div contenteditable="true">`s

**Comment by dcalvom** [comment]
Ooook. I thought it was the opposite

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/010849bf4a47ecc7eaebc0fa4dea03783c0d424e
