### ISSUE TITLE
Replace Ubiquity Channel Dropdown with Grid

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#694]
The number of integrations we offer is something we should showcase. A grid of icons would do this better than a dropdown list.

This is what it looks like now:
![image](https://user-images.githubusercontent.com/1779894/56437548-ea395180-62ad-11e9-9d89-12100f9a7d2f.png)

**Comment by dcalvom** [comment]
@broham89 let me know when you come up with something for this one and I will make the change

**Comment by broham89** [comment]
![Connection:](https://user-images.githubusercontent.com/11262149/56544849-4c5ab680-653b-11e9-8ffb-dc6f0405e1c7.png)
![Connection: Agent value dropdown appears](https://user-images.githubusercontent.com/11262149/56544861-5381c480-653b-11e9-9907-f9957d975487.png)

**Comment by wrathagom** [comment]
The big box/icon next to the dropdown doesn't look right.

maybe we could have the channel icons/grid on the left and agent icons/grid on the right?

**Comment by broham89** [comment]
Note: The Icons should be `50px 50px` 
![Connection:](https://user-images.githubusercontent.com/11262149/56624010-6d371080-65fc-11e9-8d89-e96b1dfdbe99.png)

![Connection: Agent side avaliable](https://user-images.githubusercontent.com/11262149/56624025-82ac3a80-65fc-11e9-9fd8-70669375c99d.png)
![Connection: Agent Selected](https://user-images.githubusercontent.com/11262149/56624030-88098500-65fc-11e9-99f0-7f9bd5c7b2fd.png)

**Comment by dcalvom** [comment]
@wrathagom is this design approved?

**Comment by wrathagom** [comment]
yes and no. I think we should move forward with keeping the agent a full width drop down, then the connection grid below it.

```
<row>
  <input>Agent Dropdown</input>
</row>
<row>
  <grid>Connection list</grid>
</row>
```

that code above is verified to work ;)

**Comment by dcalvom** [comment]
@wrathagom we have some important info for the user presented in that screen, where user can get information of how to setup his callback on the channel he selected:

![image](https://user-images.githubusercontent.com/7228045/57810059-2a141d00-7724-11e9-8865-73fa2967dc20.png)

where this data should go?

**Comment by wrathagom** [comment]
Let’s make it like the pre-built categories. When clicking add they get a modal where they choose the channel.

**Comment by dcalvom** [comment]
Sorry guys. @wrathagom @broham89 I still don't have this one clear.

**Comment by wrathagom** [comment]
In typical bad graphic format

![image](https://user-images.githubusercontent.com/1779894/60268897-7756e300-98bb-11e9-9404-ef9d57a489fd.png)

**Comment by broham89** [comment]
![Connection:](https://user-images.githubusercontent.com/11262149/60301763-d0446c80-98f7-11e9-8f84-af5dc3760a37.png)
![Connection: agent dropdown](https://user-images.githubusercontent.com/11262149/60301767-d33f5d00-98f7-11e9-9d6c-0670cf7a61eb.png)

**Comment by wrathagom** [comment]
I like it.

**Comment by dcalvom** [comment]
Uuups, I commented in the chat widget issue that I closed this one with https://github.com/samtecspg/articulate/commit/a863636edfd1c3feb0a09be6448e0f5d8221c2c7

I fixed both references now
