### ISSUE TITLE
Able to train phrases without any action attached.. maybe add a error message or notification.

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#695]
### Feature Request
> *If you've got a feature request we want to hear it*

Aso of 21.1: 

An agent can be trained with just training phrases, and no action attached to it. 

When testing the conversation:

![image](https://user-images.githubusercontent.com/42249324/56472438-6e194800-642c-11e9-8467-4d8df404a0fb.png)

It gives a confidence score of 0 thus going to fallback which is correct, though IMO we should have an error message or a notification that says: no action was used for the following training phrase. This way a user can pinpoint that mishap because it is easy to look over or miss phrase without attaching an action.

**Comment by wrathagom** [comment]
@RussellSPG queue this one up to test in 0.22 because I think it's been addressed already.

**Comment by RussellSPG** [comment]
ok

**Comment by wrathagom** [comment]
We've added an error message for this.

**Comment by RussellSPG** [comment]
Checked, did get a error message when training without an action
