### ISSUE TITLE
error: an internal service error occured. Error then goes away to training. 

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#696]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

I was training the agent, every few minutes when I realized that I got a message in the conversation window: _An internal service error occurred._ After a couple of minutes, the Error changed to Training and eventually trained. I did have a saying with highlighted keyword values that were not set to the correction action, in my case "get order." No error messages were in the console, or on Gitbash. Just thought I'd mention it.

![image](https://user-images.githubusercontent.com/42249324/56474403-3d92d780-6447-11e9-937b-3fa4e8a57dd1.png)

Step 10.18 on Break Script.

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
release 21.1
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by wrathagom** [comment]
There may not be anything we can do on this one after the fact. In the future please include here or in Slack the terminal output, browser console logs, results of `docker-compose ps`

Did you try to click train again before the previous training had been completed?

**Comment by RussellSPG** [comment]
ok. No, I didn't hit train again it just automatically changed to training.
