### ISSUE TITLE
Change webhookResponse too webhook.response

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#697]
I have a case where my web hook returns an array, but our storing of time and statusCode is messing that up.

I am proposing we change our webhook structure to return something like:

```
  "webhook": {
    "response": ... could be any type,
    "elapsedTime": 137,
    "statusCode": 200,
    "error": shouldn't exist unless there is an error
  }
```

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/a000646ec087d778553068a1b5fda3bf6ee8cb4a
