### ISSUE TITLE
Inner tabs aren't obvious enough

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#698]
the Sayings/keyword tab kind of blend into their background is a way we can make them more obvious to the user? Maybe they do need icons after all? Or maybe that green bar needs to be thicker/an actual tab?

The tabs on top I think are more obvious since they're in a more typical navigation location, but these tw
![image](https://user-images.githubusercontent.com/1779894/56496423-60fd6700-64c7-11e9-8df7-b57d406b654c.png)

**Comment by broham89** [comment]
![v 2 - sayings page at the start](https://user-images.githubusercontent.com/11262149/56539410-74dab480-652b-11e9-8cc2-7678a5815f67.png)

**Comment by wrathagom** [comment]
good with me.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/dfb43fa725aa104cab50e3013925aad879f5e2fc
