### ISSUE TITLE
Highlighting entities in user examples is not working

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#70]
![2018-01-18_10-55-54](https://user-images.githubusercontent.com/1779894/35107211-610e7b0a-fc3e-11e7-9857-c9d39b1333d7.gif)

**Comment by wrathagom** [comment]
The last word in the example highlighted from left to right still doesn't work! fix it!

**Comment by dcalvom** [comment]
Caleb I fixed this last monday

**Comment by wrathagom** [comment]
We left this one open since the highlight of the last word is still a little bit broken. ideally you'd be able to highlight right to left or left to right, but at the moment left to right doesn't work for some reason.

**Comment by wrathagom** [comment]
Holding until @malave is done with these components and edit functionality.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/d018df6d06989b2411ad551e0230707d920dae9e
