### ISSUE TITLE
implement a new action button in action screen for chained actions. 

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#704]
### Feature Request
Its more convient to have a new action button from the drop down, instead of having to add it from the sayings screen. This is for chained actions.

My opinion would be have a small screen or box that allows a simple entering for the chained action data without switching back to a new action screen since you would already be in it.
currently, a new action cannot be added in the response. 

![image](https://user-images.githubusercontent.com/42249324/56805542-5f99aa80-67f7-11e9-9e73-c73e7b24be15.png)

**Comment by wrathagom** [comment]
Closing in favor of #734
