### ISSUE TITLE
connection refused - unable to run

### ISSUE THREAD

**Issue by Stolaine** [samtecspg/articulate#707]
I downloaded the latest release of articulate from following link:
(https://github.com/samtecspg/articulate/releases/latest)

when I ran the command docker-compose up - i got the following error.

[root@Hydidc-VoiceBOT-Srv1 articulate-v0.22.0]# API_URL=http://59.162.167.40:7500 docker-compose up
Starting articulate-v0220_ui_1            ... done
Starting articulate-v0220_redis_1         ... done
Starting articulate-v0220_elasticsearch_1 ... done
Starting articulate-v0220_duckling_1      ... done
Starting articulate-v0220_rasa_1          ... done
Starting articulate-v0220_api_1           ... done
Attaching to articulate-v0220_ui_1, articulate-v0220_rasa_1, articulate-v0220_elasticsearch_1, articulate-v0220_duckling_1, articulate-v0220_api_1, articulate-v0220_redis_1
ui_1             | yarn run v1.15.2
api_1            | 2019/04/29 08:33:00 Waiting for: http://elasticsearch:9200
api_1            | 2019/04/29 08:33:00 Problem with request: Get http://elasticsearch:9200: dial tcp 172.25.0.3:9200: connect: connection refused. Sleeping 1s
redis_1          | 1:C 29 Apr 08:33:00.335 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 29 Apr 08:33:00.335 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 29 Apr 08:33:00.335 # Configuration loaded
redis_1          | 1:M 29 Apr 08:33:00.337 * Running mode=standalone, port=6379.
redis_1          | 1:M 29 Apr 08:33:00.337 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 29 Apr 08:33:00.337 # Server initialized
redis_1          | 1:M 29 Apr 08:33:00.338 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:M 29 Apr 08:33:00.338 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1          | 1:M 29 Apr 08:33:00.338 * Ready to accept connections
ui_1             | $ cross-env NODE_ENV=production env-cmd .env babel-node server
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
api_1            | 2019/04/29 08:33:01 Problem with request: Get http://elasticsearch:9200: dial tcp 172.25.0.3:9200: connect: connection refused. Sleeping 1s
duckling_1       | no port specified, defaulting to port 8000
duckling_1       | Listening on http://0.0.0.0:8000
api_1            | 2019/04/29 08:33:02 Problem with request: Get http://elasticsearch:9200: dial tcp 172.25.0.3:9200: connect: connection refused. Sleeping 1s
api_1            | 2019/04/29 08:33:03 Problem with request: Get http://elasticsearch:9200: dial tcp 172.25.0.3:9200: connect: connection refused. Sleeping 1s
rasa_1           | 2019-04-29 08:33:03+0000 [-] Log opened.
rasa_1           | 2019-04-29 08:33:03+0000 [-] Site starting on 5000
rasa_1           | 2019-04-29 08:33:03+0000 [-] Starting factory <twisted.web.server.Site object at 0x7fc4b4694f28>
elasticsearch_1  | [2019-04-29T08:33:03,961][WARN ][o.e.c.l.LogConfigurator  ] [unknown] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:
elasticsearch_1  |   /usr/share/elasticsearch/config/log4j2.properties
api_1            | 2019/04/29 08:33:04 Problem with request: Get http://elasticsearch:9200: dial tcp 172.25.0.3:9200: connect: connection refused. Sleeping 1s
elasticsearch_1  | [2019-04-29T08:33:04,617][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:782) ~[?:?]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:270) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:203) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:267) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.5.1.jar:6.5.1]
elasticsearch_1  |      ... 6 more
ui_1             | [WS] Disconnect from http://api:7500
ui_1             | { code: undefined,
ui_1             |   explanation: 'Unknown',
ui_1             |   reason: undefined,
ui_1             |   wasClean: undefined,
ui_1             |   willReconnect: true,
ui_1             |   wasRequested: false }
ui_1             | [WS] Will Reconnect = true
ui_1             | ws-proxy-plugin
ui_1             | Error: Connection terminated while waiting to connect
ui_1             | http://207f1a1b83cb:3000
ui_1             | method  path       description
ui_1             | ------  ---------  -----------
ui_1             | AUTH    /nes/auth
ui_1             |
ui_1             | Server started ! ✓
ui_1             |
ui_1             | Access URLs:
ui_1             | -----------------------------------
ui_1             | Localhost: http://localhost:3000
ui_1             |       LAN: http://172.25.0.2:3000
ui_1             | -----------------------------------
ui_1             | Press CTRL-C to stop
ui_1             |
ui_1             | http://207f1a1b83cb:3000
ui_1             | method  path           description
ui_1             | ------  -------------  -----------
ui_1             | *       /api/{paths*}
ui_1             | AUTH    /nes/auth
ui_1             |
articulate-v0220_elasticsearch_1 exited with code 1
api_1            | 2019/04/29 08:33:05 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1            | 2019/04/29 08:33:06 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
ui_1             | [WS] Error http://api:7500
ui_1             | Error: Connection terminated while waiting to connect
ui_1             | [WS] Disconnect from http://api:7500
ui_1             | { code: undefined,
ui_1             |   explanation: 'Unknown',
ui_1             |   reason: undefined,
ui_1             |   wasClean: undefined,
ui_1             |   willReconnect: true,
ui_1             |   wasRequested: false }
ui_1             | [WS] Will Reconnect = true
api_1            | 2019/04/29 08:33:07 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1            | 2019/04/29 08:33:08 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
ui_1             | [WS] Error http://api:7500
ui_1             | Error: Connection terminated while waiting to connect
ui_1             | [WS] Disconnect from http://api:7500
ui_1             | { code: undefined,
ui_1             |   explanation: 'Unknown',
ui_1             |   reason: undefined,
ui_1             |   wasClean: undefined,
ui_1             |   willReconnect: true,
ui_1             |   wasRequested: false }
ui_1             | [WS] Will Reconnect = true
api_1            | 2019/04/29 08:33:09 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1            | 2019/04/29 08:33:10 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1            | 2019/04/29 08:33:11 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1            | 2019/04/29 08:33:12 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
ui_1             | [WS] Error http://api:7500
ui_1             | Error: Connection terminated while waiting to connect
ui_1             | [WS] Disconnect from http://api:7500
ui_1             | { code: undefined,
ui_1             |   explanation: 'Unknown',
ui_1             |   reason: undefined,
ui_1             |   wasClean: undefined,
ui_1             |   willReconnect: true,
ui_1             |   wasRequested: false }
ui_1             | [WS] Will Reconnect = true
api_1            | 2019/04/29 08:33:13 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1            | 2019/04/29 08:33:14 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1            | 2019/04/29 08:33:15 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
^CGracefully stopping... (press Ctrl+C again to force)
Stopping articulate-v0220_duckling_1      ... done
Stopping articulate-v0220_ui_1            ... done
Stopping articulate-v0220_api_1           ... done
Stopping articulate-v0220_redis_1         ... done
Stopping articulate-v0220_rasa_1          ... done

**Comment by wrathagom** [comment]
From the Articulate directory run `sudo chown -R 1000:1000 local-storage/elasticsearch`.

**Comment by wrathagom** [comment]
Let us know if you have any other issues or if that doesn't get it going.

**Comment by bamwani** [comment]
```sudo chown username -R local-storage/elasticsearch``` worked for me
