### ISSUE TITLE
Chat Panel Green arrow Dock and Collapse functionality

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#713]
The green arrow on the chat panel will completely close the panel. I think if the user has resized the chat panel then the first click should dock it back to it's normal size. Then if clicked once docker it should collapse the panel.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/4d051a621cd26aa37142bce06b5d73cc45d75679
