### ISSUE TITLE
Delete an agent breaks the UI if there exists a connection for the deleted agent

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#718]

**Comment by dcalvom** [comment]
@wrathagom should we delete the connection to, or remove the agent from the connection?

**Comment by wrathagom** [comment]
I think it would be best if we remove the agent from the connection. Any chance we can turn the green checkmark/link on the connections list to a broken chain/red link?

**Comment by dcalvom** [comment]
Sure! Sounds good

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/691360050818750216414630c4ceb58288869184
