### ISSUE TITLE
Encrypt connection details

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#719]

**Comment by dcalvom** [comment]
Basic auth, need to be encrypted too

**Comment by milutz** [comment]
For secrets that will be provided to other services (AWS/database-access/external-APIs) our first plan is to _*ONLY CONNECT VIA HTTPS*_ but then leave the secrets as plain-text on the API side server.   For secrets to _us_ we will use salted-hashes so we don't locally store (user passwords, etc...)
