### ISSUE TITLE
Language dropdown is in the wrong place sometimes

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#720]
![image](https://user-images.githubusercontent.com/7228045/56993138-f1d3e280-6b58-11e9-9ff4-343fb6083c4b.png)

**Comment by wrathagom** [comment]
Should it move when we expand the chat panel? Or do we need to find a place for it that is more static. Maybe bottom left hand? @broham89

**Comment by dcalvom** [comment]
I think this was an issue related with the code being cached.

If you see it again, let me know

**Comment by wrathagom** [comment]
I was able to re-create this on a narrow screen, but doesn't really seem to cause problems.
