### ISSUE TITLE
I think nginx is causing a timeout

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#721]
If the training takes too long nginx throws a timeout sending an error that shouldn't be sent to the UI as the training process is still running. The training will finish successfully and the train status changes correctly but the user will have an error without knowing why.

**Comment by wrathagom** [comment]
https://serverfault.com/questions/777749/how-to-disable-timeout-for-nginx

**Comment by wrathagom** [comment]
@dcalvom might be nice of you to provide an export so that @malave can get this to happen on his machine. He might not have any agents the same size as yours.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b893ac11685ccdd5d7b0c1a4780559e7eff7308c
