### ISSUE TITLE
Getting Started Panel

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#722]
Add a getting started panel to main home page, ideally the close icon would dismiss the modal for forever (local/session storage?)

![image](https://user-images.githubusercontent.com/1779894/57006617-2757ea80-6bb0-11e9-8320-b1bcc7347908.png)

**Comment by broham89** [comment]
![v 2 - Agent main screen (1)](https://user-images.githubusercontent.com/11262149/58055730-5369ea00-7b24-11e9-8f1c-180ff5899002.png)

**Comment by wrathagom** [comment]
I like it. and am glad you called out the help buttons. As a side note @broham89 should we colorize the help buttons to draw people's attention to them?

**Comment by broham89** [comment]
Not really, cause it's a secondary button that's just there for help when
needed

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/f66054f2c2f1ed65c9bb2512abfc9fea455fc6ab

Still missing the important links that you want to add
