### ISSUE TITLE
We shouldn't allow the user to click on the training button when training is already underway.

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#724]
Also, we used to have a training animation @broham89

**Comment by dcalvom** [comment]
The block is ready. The animation is still missing.

**Comment by broham89** [comment]
I'll try to see if I can drop the animation to you today @dcalvom

**Comment by broham89** [comment]
[training-animation.svg.zip](https://github.com/samtecspg/articulate/files/3150078/training-animation.svg.zip)
@dcalvom  make sure the svg is 24px high to be proportionate with other icons

**Comment by wrathagom** [comment]
@dcalvom is there a way to make this block global? So that if any agent is training than no training is allowed?

Also, is your block only on the UI side? it would be nice if the block was also on the API side in case someone tries to start training that way.

**Comment by dcalvom** [comment]
The training block in the API is already set!

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/4b97971ad79a297bc10e259020524e834a6f82a5
