### ISSUE TITLE
Clicking the Save button before entering response, shows red, but after correcting turns to blank page. 

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#726]
### Issues
When Saving an action with blank response it gives the normal red marking for an error. However, once I enter the response for the action and hit the Save button, then Exit page goes blank.

Step 15.12 on Break Script 

No errors were detected on console. 
However, on Git Bash, I did notice several lines like these:
```
Epochs:  85%|????????? | 254/300 [00:00<00:00, 297.27it/s, loss=0.109, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 296.49it/s, loss=0.109, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 295.69it/s, loss=0.109, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 294.89it/s, loss=0.108, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 294.16it/s, loss=0.108, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 293.13it/s, loss=0.107, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 292.38it/s, loss=0.110, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 291.61it/s, loss=0.107, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 290.85it/s, loss=0.106, acc=1.000Epochs:  85%|????????? | 254/300 [00:00<00:00, 290.09it/s, loss=0.106, acc=1.000
```

Looks like packet loss to me

- Did you download a release or pull from Master? Which release?
release 21.1
- What operating system are you running?
10 Pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by wrathagom** [comment]
@RussellSPG can you try to reproduce on 0.22?

**Comment by RussellSPG** [comment]
No issues on 0.22
