### ISSUE TITLE
sometimes keyword does not highlight

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#727]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

When highlighting a word in sayings, sometimes the box does not appear. 
![image](https://user-images.githubusercontent.com/42249324/57076438-a84dd980-6cb7-11e9-9bae-9a6c8e0082bd.png)
the blue on the right is from highlighting the text, where the pop up to select the appropriate keyword assignment doesn't appear. 

no errors

Firefox
Win 10 pro
21.1 Release
local
----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by wrathagom** [comment]
@RussellSPG before we can do anything about this we really need to find what causes it. I haven't been able to reproduce it yet.

**Comment by RussellSPG** [comment]
I think its more of a UX issue, the mouse needs to be firmly on the text, if its slightly moved away after highlighting, the box doesn't come up.

**Comment by RussellSPG** [comment]
Reproduced, This is when the mouse isn't perfectly on the text when letting go of the left mouse button. Probably nothing can be done about it.
