### ISSUE TITLE
Save prompt crashes to api screen for keywords

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#729]
### Issues

When I entered values in for a keyword then click the exit button, prompt came up, I hit save then got this screen:

![image](https://user-images.githubusercontent.com/42249324/57111818-9138d700-6d0b-11e9-9b1e-965176405db4.png)

Seems no errors but did get this:
```
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (1915396 px). Occurrences of will-change over the budget will be ignored.
```
No errors on git bash

Step 3.27 on script

- Did you download a release or pull from Master? Which release?
release 22.0
- What operating system are you running?10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by RussellSPG** [comment]
repeat the issue, confirmed this is crash

**Comment by wrathagom** [comment]
what is the result of `docker-compose ps`?

**Comment by RussellSPG** [comment]
```
articulate-v0220_api_1             /bin/sh -c dockerize -wait ...   Exit 137    
articulate-v0220_duckling_1        /bin/sh -c stack exec duck ...   Exit 137    
articulate-v0220_elasticsearch_1   /usr/local/bin/docker-entr ...   Exit 143    
articulate-v0220_rasa_1            ./entrypoint.sh start --pa ...   Exit 0      
articulate-v0220_redis_1           docker-entrypoint.sh redis ...   Exit 0      
articulate-v0220_ui_1              yarn start:prod                  Exit 1      
```

**Comment by wrathagom** [comment]
Did you shut it down? That shows everything is down.

either way @dcalvom I can confirm this.

1. Create a keyword
2. Give it a name
3. Add some values
4. Click exit instead of save
5. in the exit prompt click save
6. page crashes.

**Comment by wrathagom** [comment]
@dcalvom @RussellSPG we should also check the other places we have those exit buttons (action screen? agent screen?)

**Comment by RussellSPG** [comment]
Checked for Actions and no problem. Agent screen doesn't have an exit button.

**Comment by RussellSPG** [comment]
Same problem for when hitting a delete for keyword

**Comment by RussellSPG** [comment]
```
Error: An internal server error occurred main.c636e3c573fa6f0f0ce9.chunk.js:1:52865
```

**Comment by RussellSPG** [comment]
Just to keep in mind, the keyword does delete, just crashes to the api screen and have to keep refreshing

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/009545f16156fb8844af98763fa1f388f01cdb51
