### ISSUE TITLE
Add Action button not functional in response

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#730]
### Issues
The Add action button is not functional when going to a response for an action, And adding a new action within there for a chained action. 

![image](https://user-images.githubusercontent.com/42249324/57184367-996a5100-6e88-11e9-87c2-54a639d8fb36.png)

Step 12.3 on script

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
release 22.0
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by wrathagom** [comment]
Fixed on master
