### ISSUE TITLE
training error (can't create chained action because it needs training phrases)

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#731]
### Issues
Pretty sure this a bug. on 22.0 looks like it treats a chained action like a normal saying. When I hit Train, I get the error "must have multiple training phrases for the action."

I was just creating a simple thanks, to be chained when an order was completed.

![image](https://user-images.githubusercontent.com/42249324/57184455-e00c7b00-6e89-11e9-9789-fbd2c23cf3f1.png)

And strange enough, it does have 2 examples in though they are not training phrases:

![image](https://user-images.githubusercontent.com/42249324/57184523-983a2380-6e8a-11e9-85f8-a2375b7c1a60.png)

I double checked back on 21.1, I did not have training phrases (sayings using the chained action) in order for the chained actions to work or train.

Also, it says there's only one training phrase which is also wrong, because there were none.

Had to add these training phrases in, for in order it to work:
![image](https://user-images.githubusercontent.com/42249324/57186285-91bba400-6eaa-11e9-8997-f25bd42bc663.png)
Again on the previous 21.1, did not have to do this.

Step 13.63 on script
Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
release 22.0
- What operating system are you running?
10 pro
- Are you running locally or in the cloud
local

**Comment by wrathagom** [comment]
I can't reproduce this. Can you try to reproduce and provide an agent export if you can?

**Comment by wrathagom** [comment]
I think this is related to #739

**Comment by RussellSPG** [comment]
Reproduced.

Export:


[pizzabot-0.22.zip](https://github.com/samtecspg/articulate/files/3186955/pizzabot-0.22.zip)

**Comment by RussellSPG** [comment]
Confirmed related to #739
