### ISSUE TITLE
repeat of  #447 (Category header still incorrect)

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#732]
### Issues
This is a repeat of  #447 milestone .15-3 which was closed, however, it still or has gone back to the wrong title:

![image](https://user-images.githubusercontent.com/42249324/57185625-27503700-6e9d-11e9-9d4b-66db978f1688.png)

The correct should be "category" or "Category."

v22.0 local

**Comment by dcalvom** [comment]
Fixed
