### ISSUE TITLE
Able to save slot without specifying keyword

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#733]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

The slot can be saved, without specying a keyword to be used:
![image](https://user-images.githubusercontent.com/42249324/57198975-73f04c80-6f47-11e9-8bd3-6e4e14535af3.png)

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
release 22.0
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

----

**Comment by wrathagom** [comment]
I can't reproduce this. Can you try? and if you can give us the agent export. I'm curious if it is some odd combination that circumvents the validation.

**Comment by RussellSPG** [comment]
Wasn't able to reproduce either, something must have happened, and I'm not sure what


[pizzabot-0.22.json.zip](https://github.com/samtecspg/articulate/files/3146362/pizzabot-0.22.json.zip)

**Comment by wrathagom** [comment]
Alright,well keep an eye out for it and I will as well.
