### ISSUE TITLE
Increase space for input saying tag

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#738]
Seems like we should give tags a bit more room.

![image](https://user-images.githubusercontent.com/1779894/57245907-ee81a080-7009-11e9-82e1-3584bfb9d69b.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e13723ed3ed70e7a006287d3cbb5e4cd96ee55b2
