### ISSUE TITLE
New action incorrectly attached to top sayings instead of saying input

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#739]

**Comment by dcalvom** [comment]
I reproduced this one in the past, but wasn't able to reproduced it anymore. Let me know if you see this again.

**Comment by wrathagom** [comment]
I can still get this to happen.

1. Click on the action tag of a sayings someplace in the sayings list.
2. Exit that action back to the sayings list
3. Create a new action by clicking the plus in the sayings input.

The new acton will be attached to the saying you last clicked on instead of the sayings input, even though you clicked the plus in the input.

**Comment by RussellSPG** [comment]
I was able to reproduce, though I did open a duplicate issue it seems. The error message is wrong too if thats worth noting.. It says there's only 1, but actually there is 0 for the chained action.

**Comment by wrathagom** [comment]
the error message isn't wrong there is one and it is in your sayings list if you look for it, but it can be on any saying, depending on where you clicked last.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/99d1503538a67bf67e38db35a9c3385c694de8f0
