### ISSUE TITLE
ellipsis under dropdown arrow

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#740]
I fixed this by adding `padding-right: 15px;` to the dropdown

![image](https://user-images.githubusercontent.com/1779894/57247504-078c5080-700e-11e9-974e-10f3d98173b5.png)

**Comment by wrathagom** [comment]
Happens on the category dropdown too:

![image](https://user-images.githubusercontent.com/1779894/57247526-170b9980-700e-11e9-9808-0d028c2ee796.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e13723ed3ed70e7a006287d3cbb5e4cd96ee55b2
