### ISSUE TITLE
Webhook not working for action which has no slots

### ISSUE THREAD

**Issue by ferozewaris** [samtecspg/articulate#742]
Hi I am using Articulate-api 0.21.0 and articulate-ui 0.21.0. The problem i am facing is that when action executed which has some filled slots then the webhook which i have given for that action is calling correctly but when the action which has no slots to fill is executed then its webhook is not being called and i am getting this response 
![Screen Shot 2019-05-08 at 1 09 54 PM](https://user-images.githubusercontent.com/22313397/57360013-9c1fbb80-7192-11e9-9852-a31f1293945b.png)

Here is the webhook in action which has slots. 
![Screen Shot 2019-05-08 at 1 13 38 PM](https://user-images.githubusercontent.com/22313397/57360273-29631000-7193-11e9-9cd6-b17fcd607f75.png)

and here is the webhook call for the action which has no slots
![Screen Shot 2019-05-08 at 1 13 01 PM](https://user-images.githubusercontent.com/22313397/57360300-3f70d080-7193-11e9-8e3c-74a950cea673.png)

**Comment by wrathagom** [comment]
We did have a few webhook related hugs swuashed in 0.22 if memory serves me right, so it may be worth updating.

But also, in the above images the body of the webhook with no slots is missing a curly bracket at the end of `{{{JSONstringify slots}}}` which could be causing problems. If the action doesn’t have any slots it would make sense to just remove that entire line from the body.

**Comment by ferozewaris** [comment]
Yes it worked when i removed {{{JSONstringify slots}}} it worked. Thanks. But even if the slots are not filled it should send empty array to webhook in case of no slots. Anyways It worked for now i am going to use this way around

**Comment by wrathagom** [comment]
Absolutely we'll try to reproduce and get it fixed.

**Comment by wrathagom** [comment]
I think this was actually related to the missing `}` in the second example.
