### ISSUE TITLE
Prompts for non-required slots

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#744]
Just as a contrived example I may want my bot to ask how someone is doing. I could do this with a keyword/modifiers that classify how they are into bad, okay, good. And then have an action that prompts for that slot 'How are you doing today', but I would be okay if they ignore that and don't answer since it's just small talk.

**Comment by wrathagom** [comment]
Here's what I am trying to prevent:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/1779894/57564780-ef0a9600-737f-11e9-8b3c-e6890294cd01.png">

**Comment by wrathagom** [comment]
We might also be able to accomplish this with a slot prompt lifespan. when set to 1 we will only prompt once. If no response is received on the very next action that action is considered fulfilled. If the lifespan is >1 we will prompt that many times.

**Comment by cloud1250x4** [comment]
What if there`s conditional slot.. if the user fulfill the closure/end slot, you don`t need to ask for the open/first slot.

**Comment by mordebip** [comment]
Or at least some way to cancel the query

**Comment by dcalvom** [comment]
Addressed with prompt limit
