### ISSUE TITLE
Add Action tab under dialogue to list actions and provide a better way to manage them

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#746]
Creating actions for chaining by clicking the plus icon in the sayings input seems stupid. Also, trying to update a chained action requires finding the action where it is chained... that's annoying.

**Comment by nickopris** [comment]
I was just about to create a similar ticket when I found this one. Here is a bit of a design:
<img width="609" alt="Screenshot 2019-05-15 at 15 48 36" src="https://user-images.githubusercontent.com/794552/57785280-55e5d180-7729-11e9-86b4-9cd78e3dd5fe.png">

<img width="1056" alt="Screenshot 2019-05-15 at 16 03 27" src="https://user-images.githubusercontent.com/794552/57786207-fe486580-772a-11e9-9d2b-478aea8f1ab2.png">

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/6687a6d8fd2694c4de1f7d245106851a58185f6b
