### ISSUE TITLE
Saying cannot be removed

### ISSUE THREAD

**Issue by nickopris** [samtecspg/articulate#748]
Listed saying cannot be removed. I added another one which can be removed but even after page reload the old one is still there and cannot be removed.

<img width="1545" alt="Screenshot 2019-05-14 at 17 40 32" src="https://user-images.githubusercontent.com/794552/57715895-a567c700-766f-11e9-96c0-0b7ecf0d751a.png">

Request URL: http://localhost:3000/api/agent/1/category/3/saying/13

Did you download a release or pull from Master? Which release?
Release v0.22.0
What operating system are you running?
Mac OSx
Are you running locally or in the cloud?
Locally with Docker
Which browser are you using?
Chrome - same response using Postman

**Comment by wrathagom** [comment]
hmm we've obviously got something that is causing sayings to become un-linked. Could be related to your other issue as well. Were these sayings created in the UI or API? how about the category? also, did you delete the category?

**Comment by wrathagom** [comment]
may be related to #605

**Comment by nickopris** [comment]
I created id using the UI. I did not delete the category.

**Comment by wrathagom** [comment]
I was able to reproduce, but not in a reliable way.

**Comment by wrathagom** [comment]
I can't reproduce this anymore on master @nickopris if you're still around let me know if you are still struggling with this error.
