### ISSUE TITLE
Intent: Error during creation without a Intent Responses will fail but still create the intent

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#75]
1. Fill the form except the `Intent Response`
2. Click on create
3. An error will show up saying that you should add a `Intent Response`

The intent will still be created at this point and even if you add the `Intent Response` it won't let you save it.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/653037747ca59843ff5b81939dc6c1ccff1dd286
