### ISSUE TITLE
Sayings page flashes/jerky movement when paging

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#750]
![2019-05-15_09-59-42](https://user-images.githubusercontent.com/1779894/57781530-5dd94d80-76f8-11e9-8399-8e953a7cd182.gif)

**Comment by wrathagom** [comment]
this is on safari

**Comment by dcalvom** [comment]
Closed byhttps://github.com/samtecspg/articulate/commit/2bd46790ca233c5465047877d0399557f9523c0e
