### ISSUE TITLE
Deleting only saying on sayings page leaves you with a blank page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#751]
Let's say you have the pagination best to 5 and you have 16 sayings. if you are on the last page and delete the only saying shown on that page you are left there with nothing showing and no way to navigate to a previous page.

**Comment by wrathagom** [comment]
![image](https://user-images.githubusercontent.com/1779894/57781836-f66fcd80-76f8-11e9-833f-78fff00ccae0.png)

delete only action

![image](https://user-images.githubusercontent.com/1779894/57781850-038cbc80-76f9-11e9-9a78-77993e4c66fb.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/2b333dd34d077bddd17c038174b840ce60f30e20
