### ISSUE TITLE
Typing in a saying and hitting enter with no category selected

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#752]
This behaves like everything is normal, except the saying doesn't get added to the list and disappears from the input. We should leave the text in the input and throw an error that a category needs to be selected first.

**Comment by dcalvom** [comment]
I wasn't able to reproduce this one, neither on chrome or safari

**Comment by wrathagom** [comment]
I was able to reproduce:

1. Create a brand new agent
2. Import the small talk category
3. Note on the sayings page the the category dropdown is empty
4. Try to type a saying and hit enter

![2019-05-30_11-48-03](https://user-images.githubusercontent.com/1779894/58645280-0aa6f380-82d1-11e9-9983-ca9ed8d9d85f.gif)

**Comment by wrathagom** [comment]
After I do this there are also a lot of errors in the terminal window. :(

**Comment by wrathagom** [comment]
```
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 404,
api_1            |      message: 'Category id=[undefined] is not linked to Agent id=[2]' },
api_1            |   message: null }
api_1            | Debug: handler, error 
api_1            |     Error: Category id=[undefined] is not linked to Agent id=[2]
api_1            |     at /usr/src/app/lib/routes/agent/agent.create-saying-in-domain.route.js:29:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.create-saying-in-domain.route.js:11:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.create-saying-in-domain.route.js:13:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by dcalvom** [comment]
I followed up the process 3 times and wasn't able to reproduce it :(

**Comment by wrathagom** [comment]
Can't reproduce anymore
