### ISSUE TITLE
Problem with creating domains, intents, entities

### ISSUE THREAD

**Issue by aizazqaisrani** [samtecspg/articulate#758]
I have downloaded latest articulate release from master and I am running it on ubuntu locally. When I run it using following command:

sudo docker-compose up. 

And I go to localhost port 8080 on firefox browser
![screenshot](https://user-images.githubusercontent.com/6060161/57832197-1b7f4180-77c8-11e9-98ce-dc11f08fc4e8.png)
. I see an articulate ui where it gives me option to create agent but I don't see any option to create domains, agents, etc. 

I can't figure out that what exactly am I doing wrong. Can someone please guide me. 

Thanks,

**Comment by wrathagom** [comment]
Can I get a screen shot of your sayings page?

**Comment by aizazqaisrani** [comment]
Sorry, I didn't get your question. I have already attached an image with my previous comment. Do you want me to upload anything else? Please bear with me as I am new. 

Thanks,

**Comment by wrathagom** [comment]
that is an image of the agent page, I want to see the screen where you define your sayings.

**Comment by wrathagom** [comment]
@aizazqaisrani did you see the help videos available in the UI? You can also find them [here](https://www.youtube.com/channel/UCLG3EJalaPKJfCei2sEjLJw).

Let us know if you can't get it figured out, we definitely want to help anyway we can.

**Comment by aizazqaisrani** [comment]
For defining saying, I will have to go to http://172.21.0.3:3000/. But when I go there, I don't see anything. It's basically a blank page. When I check in the browser, I see following error:

![browser](https://user-images.githubusercontent.com/6060161/57978526-81660600-7a20-11e9-87f1-e6e8288fdbfb.png)

Please inform me if I need to provide any further info. 

Thanks,

**Comment by aizazqaisrani** [comment]
My problem is fixed. I can use Articulate perfectly fine. Those videos were helpful. 

Thanks,

**Comment by wrathagom** [comment]
Good to hear!
