### ISSUE TITLE
Restart needed for each training

### ISSUE THREAD

**Issue by Deihim007** [samtecspg/articulate#759]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.
Each time i run articulate i only can teach my agent once, after that it fails the new training and returns following errors:
**Error: An internal server error occurred.**
**Error: An error ocurred (which is a typo :D) training The Agent**

- Did you download a release or pull from Master? Which release?
**pull**
- What operating system are you running?
**Debian9**
- Are you running locally or in the cloud?
**cloud**
- Which browser are you using?
**chrome**

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by Deihim007** [comment]
Which i realized that only happens if i talk to agent, (which the first message takes a few seconds) then after that i can't train the agent anymore

**Comment by Deihim007** [comment]
And also this is the error in the console:
rasa_1           | /usr/local/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
rasa_1           |   len(cache))
rasa_1           | 2019-05-16 11:02:04+0000 [-] 2019-05-16 11:02:04 WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'concurrent.futures.process.BrokenProcessPool'>: A process in the process pool was terminated abruptly while the future was running or pending.
rasa_1           | 2019-05-16 11:02:04+0000 [-] ]
rasa_1           | 2019-05-16 11:02:04+0000 [-] Unhandled Error
rasa_1           |      Traceback (most recent call last):
rasa_1           |      --- <exception caught here> ---
rasa_1           |        File "/app/rasa_nlu/server.py", line 361, in train
rasa_1           |          RasaNLUModelConfig(model_config), model_name)
rasa_1           |      concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Which leads to 500 error

**Comment by RussellSPG** [comment]
Can you provide an export of the agent? I'm thinking it may be the methodology the way you built the agent.

**Comment by wrathagom** [comment]
Broken process pool is a Rasa problem unrelated to training data. 

How much memory does your system have?

**Comment by wrathagom** [comment]
Here's a reference: https://github.com/RasaHQ/rasa/issues/1231

the very last line: `Closing this as more memory resolves the issue`

**Comment by Deihim007** [comment]
> Broken process pool is a Rasa problem unrelated to training data.
> 
> How much memory does your system have?

4gb
Also i just saw this warning:
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA

**Comment by RussellSPG** [comment]
Did you enable 4 gigs to be used in the docker settings? Seems that would be using all your memory, but your memory seems to be the issue

**Comment by Deihim007** [comment]
I don't think so, How much is the default setting? how can i increase it?

**Comment by Deihim007** [comment]
> Did you enable 4 gigs to be used in the docker settings? Seems that would be using all your memory, but your memory seems to be the issue

I don't think so, how much is the default settings? how can i increase it?

**Comment by RussellSPG** [comment]
I think default is 2. 
1. Right click on docker desktop, from the bottom taskbar. 
2. Click Settings. 
3. Click advanced. 
4. There you can select CPU dedication/RAM. For me I have CPU at 2, and my RAM is set to use 8960. For your case I would recommend setting it just a hair from 4096, since you said your system only has 4 gigs of RAM.
Let us know if that works for you.

**Comment by Deihim007** [comment]
> I think default is 2.
> 
> 1. Right click on docker desktop, from the bottom taskbar.
> 2. Click Settings.
> 3. Click advanced.
> 4. There you can select CPU dedication/RAM. For me I have CPU at 2, and my RAM is set to use 8960. For your case I would recommend setting it just a hair from 4096, since you said your system only has 4 gigs of RAM.
>    Let us know if that works for you.

It's not on my pc, It's alright i'll probably be able to find out by google. Thanks for the help 👍

**Comment by RussellSPG** [comment]
Ok, no problem :)

**Comment by RussellSPG** [comment]
Just curious are you using Docker desktop?

**Comment by Deihim007** [comment]
No, i'm using debian docker.

**Comment by RussellSPG** [comment]
Ok, if you do decide to switch to docker desktop, its heavily advised you have windows 10 pro running for it :/ In your case, it seems you are using your own OS, so thats outside our control ;)

**Comment by Deihim007** [comment]
> Ok, if you do decide to switch to docker desktop, its heavily advised you have windows 10 pro running for it. In your case, it seems you are using your own OS, so thats outside our control ;)

Thanks for the advice, Do you have discord or some other messenger?
I'm trying to use the api but  i'm running to some troubles.

**Comment by RussellSPG** [comment]
To answer your question (saw by email), we use gitter:
https://gitter.im/samtecspg/articulate

**Comment by wrathagom** [comment]
@Deihim007 on Debian the ram available to docker is usually all that your system has. Is it possible to increase the size of the VM you are running on? Or at the very least can you watch the RAM usage while training to see if it goes close to 4G?

We have Gitter linked above and a discord: https://discord.gg/yUwzBZW

**Comment by Deihim007** [comment]
> @Deihim007 on Debian the ram available to docker is usually all that your system has. Is it possible to increase the size of the VM you are running on? Or at the very least can you watch the RAM usage while training to see if it goes close to 4G?
> 
> We have Gitter linked above and a discord: https://discord.gg/yUwzBZW

Well now i'm 100% sure it's a memory problem, it seems it eats 4gb ram super easy, i had to upgrade to 8gb, but is this normal? using this amount of ram?

**Comment by wrathagom** [comment]
Yes, the machine learning models take quite a lot of memory. Glad to know you got it figured out.
