### ISSUE TITLE
chained action in response is not clickable, can only be deleted

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#760]
### Issues
When in the action screen on the response tab, a chained action once attached, does not go to edit screen once clicked:

![image](https://user-images.githubusercontent.com/42249324/57852138-63926a00-77b0-11e9-84ef-da5bc9f83071.png)

Only the x icon works. I think when I click on "chained thanks" it should be a button that allows me to edit the chained action.

- Did you download a release or pull from Master? Which release?
release 22.0 
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

----

**Comment by wrathagom** [comment]
I imagine we'll tackle this one along side of #734

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/362c36f70e01e30b7ad28503c0c2d4955799fa83
