### ISSUE TITLE
Improve the Action dropdown

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#766]
Something like the below, which adds a recent section and sorting by name to the remainder of the list.

![image](https://user-images.githubusercontent.com/1779894/58255056-22630280-7d3a-11e9-8693-029d7e90e171.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/57f7b61eaf29197012d307a7427310bc5c197b76
