### ISSUE TITLE
Creating an Action causes two network actions

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#767]
When I click the save button after creating an action I see two networks requests. A POST, which succeeds, and a PUT which fails and the PUT seems to be a malformed URL.

![image](https://user-images.githubusercontent.com/1779894/58327195-f3619500-7dfc-11e9-81cc-82fbdec7702e.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/ceec4a3aaa671c780fc637c416fc4dadadd4890c
