### ISSUE TITLE
Webhook Enhancements

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#77]
There are several components to this:

- [X] When specifying the URL for the webhook a user should be able to select the method
- [X] The URL should pass through a handlebars formatter. Allowing anything from the current context to modify the URL. For example:

```
http://node-red:1880/{{intent}}?username={{slots.username}}{{#if slots.field}}&field={{slots.field}}{{/if}}
```

- [X] A toggle-able JSON payload should be added, that also can be formatted via handlebars. For example:

```
{
  username: {{slots.username}},
  {{#if slots.field}}
    field: {{slots.field}}
  {{/if}}
}
```

- [ ] We should provide a "test" button. Ideally the test button would pull values from one of the training examples. if a training example isn't available that has all of the slots filled then we should prompt for all of the values necessary/possible.

@ewoo and I will work on the "default" POST payload.

@malave since you have handlebars experience @dcalvom may have some questions. Also, can you please review and see if there is anything here that seems like it wont work. The use case is very similar to Conveyor: using handlebars to format either strings or JSON for use with an API.

**Comment by wrathagom** [comment]
More information here https://public.3.basecamp.com/p/xirx3r6iQSBJmqeQGY1yy3tM

**Comment by wrathagom** [comment]
I'm moving the test button to a new issue and closing this one. Everything is functional.

**Comment by senthurRam33** [comment]
I'm having a basic knowledge in handlebars.I just want to know that where are the cases that we need to use the handlebars and webhooks and where are the cases that we should not use them. Can you guys explain those things here?

**Comment by wrathagom** [comment]
Anytime you want something the agent says to include a variable or be impacted by a variable you will need to use handlebars. This article is a bit out of date, but has some examples in it. https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241
