### ISSUE TITLE
Remaining life setting changed by itself

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#771]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*
Not sure if this is supposed to happen but when playing with toppings slot setting the keyword to confirm, I noticed the Remaining life automatically changed to 7. This was during the conversation phase with the bot. 

![image](https://user-images.githubusercontent.com/42249324/58362990-e203a180-7e6b-11e9-8fb8-ed0c88d57af9.png)

No errors

For the 22.0 release

**Comment by wrathagom** [comment]
What was it originally? and it changed in this screen? can you get it to happen again?

**Comment by RussellSPG** [comment]
originally it was at 0, let me try

**Comment by RussellSPG** [comment]
Can't reproduce but I remember this happened before in a previous release 21.1 maybe, just seems to be random behavior. Right now on the part of the break script im on, the confirmation is not set, where it just loops the slot prompt. I'm thinking if I mistyped 7 instead of 0, but I clearly remembered puting 0 in.

**Comment by wrathagom** [comment]
Okay just keep an eye our for it happening again as you test more. Maybe you scrolled with the mouse wheel while over it? I am not really certain.

**Comment by RussellSPG** [comment]
yes, maybe, I will keep a look out on it.
