### ISSUE TITLE
Dialogue Screen Goes Blank

### ISSUE THREAD

**Issue by aizazqaisrani** [samtecspg/articulate#772]
Hi, I am using latest release of Articulate on Ubuntu locally. I have added some keywords and modifiers. When I tried to save and exit, screen went blank. Now I can not go to dialogue screen as it goes black even if I restart. What should I do?

**Comment by wrathagom** [comment]
I actually think there is a chance we've seen this one before. Are you running from master or 0.22?

**Comment by wrathagom** [comment]
Closing for lack of feedback. Please feel free to open a new issue if you are experiencing issues.
