### ISSUE TITLE
Chat Panel closes when navigating to the agent tab

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#776]
When I am on the sayings page with the chat panel open. If I click on the tab that says `Agent: Agent Name` then the chat panel closes. It makes sense to close it when navigating to the home page, but not certain why it closes in this case.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/f3f3b02e7ddcbc2dea05f521449f0c42c1196643
