### ISSUE TITLE
Shared Chat panel

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#778]
I want a way to share the chat panel with other users and have them test the agent, but not have access or at least not be presented with the whole interface. We can worry about access once @malave is finished.

This chat panel should still use local storage of some sorts to track session IDs locally, but rather than allowing to clear them should be new session only. So that the developer can see all sessions even failed ones.

I am also choosing to display the agent description on the page and a help text area. For now the help text area can be static though eventually we will probably make it customizable.

![image](https://user-images.githubusercontent.com/1779894/58517437-6199b500-8179-11e9-90ea-d56a69d4cd6a.png)

Also, maybe the default chat panel should be 1/3 the screen rather than whatever it is now?

**Comment by broham89** [comment]
![Shared Chat v 1](https://user-images.githubusercontent.com/11262149/58919987-cf079180-86f5-11e9-9256-3c75a65902c1.png)

**Comment by wrathagom** [comment]
Looking good. I don't think I want the chat panel to have the eraser icon. There are several other things I think we should remove from the screen (settings button, new agent button, etc) but rather than custom remove them from this page alone we can wait for auth and just make it to where those things don't don't show unless you have the necessary permissions.

**Comment by dcalvom** [comment]
closed by https://github.com/samtecspg/articulate/commit/880c0d7203fd5ed4b7a3689931a93515ae273608
