### ISSUE TITLE
Enable/disable AUTH and Default user 

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#782]
- A pair of env-vars will be added to provide a user/pass to add to the add to the API on startup - unless forced, only does if there are no users in the db - these will have no defaults
- a new env-var to force the set of the above - default is off (don't force the add) - if enabled the user/pass will be added, even if it overwrites a user/ in the db - if this is set, but there is no user/pass and error/shutdown should happen
- If the API is started up in auth-enabled mode, *but* without an oauth provider set, and with no users in the db, and no user/pass env-vars then a big-error should be output from the API and it should shutdown

**Comment by wrathagom** [comment]
@malave this is completed correct?

**Comment by malave** [comment]
@wrathagom Yes this is complete
