### ISSUE TITLE
Address shared slots in action queue to avoid re-prompt

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#785]
Right now we are processing responses from actions in the queue and that doesn't allow to use a filled slot that should be used in two separate actions. Like `city` in `getWeatherReport` and `getTrafficReport`.

**Comment by wrathagom** [comment]
@dcalvom did this one get fixed with refactoring?

**Comment by wrathagom** [comment]
what about this one @dcalvom I was thinking it works now.

**Comment by dcalvom** [comment]
I think this one is fixed. Specially with the saved slots inclusion.
