### ISSUE TITLE
Executing options

### ISSUE THREAD

**Issue by Chiagoro-ahaotu** [samtecspg/articulate#787]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release? Release Version V0.22.0
- What operating system are you running? Windows 10
- Are you running locally or in the cloud? Locally
- Which browser are you using? Chrome

----

Hello there,

I am trying to build a flow using "action tagging". So far, my flow is looking good.

However, I need help with this: I am trying to present my user with a set of options (3 options)  for which he must pick one. Where choosing one of the options, triggers separate actions tagged to those options. 

Here is what I have done:

1) I created an action called "Options" for this which I tagged to the preceding flow. 
2) I created 3 different slots for the 3 different options. 
Note that, I used one keyword for the 3 different options. 

This does not seem to work. I am not sure what I am not doing correctly, 

Could you please assist me with a way of achieving this. 

See my attached snapshot for a clearer explanation of what I am trying to achieve.

![20190614_110446](https://user-images.githubusercontent.com/49977702/59501970-93f32400-8e94-11e9-8327-ed43a2b62779.jpg)

**Comment by wrathagom** [comment]
yeah you can't have multiple slots using the same keyword, nor should you need too. One slot, one keyword. Then in the responses use the value of the slot to route to the options.

So one of your responses would look like this:

```
{{#eq slots.options.value 'option1'}}Okay, Option 1{{/eq}}
```

which would be tagged with the action for option 1

```
{{#eq slots.options.value 'option2'}}Okay, Option 2{{/eq}}
```

which would be tagged with the action for option 2 and so on.

**Comment by Chiagoro-ahaotu** [comment]
Thank you so much
Just to be clear,
In the response field of the "Options action",  Are these responses to be typed in separately for whatever option that is chosen. That is, I would have 3 different responses entered in the response field of my action.  Does the system have a way of selecting the best response to match the slot that the user requested? I originally had thought the provision for multiple responses was to spice up things a bit to avoid the system having to use the same response every time.

**Comment by Chiagoro-ahaotu** [comment]
Also, 

Could you kindly explain the response statement?
I understand that
 'slots.Options.value' statement  gets the value of that slot
'option 1' is the value of the slot

I guess the 'okay' checks if the value entered matches with 'option 1'

The 'option 1{{/eq}}' is it part of the statement too or were you trying to tag the action for choosing option 1.

Pardon me if this is a syntax structure you expect me to already know. 

Thanks!

**Comment by wrathagom** [comment]
Correct, three separate responses each tagged with a different option. Articulate will choose the best one. There is some more information about how we choose responses at the bottom of this blog post: https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241

Multiple responses can be used to add variety, but it also plays a part here in branching dialog.

The `{{#eq slots.option.value 'option1'}}` takes the value of the options slot and compares it to the string value `option1` if they match then the text inside the handlebars will be used as the response. It's kind of like an if statement. So if it doesn't match there will be no response text and since there is no text Articulate won't choose to use that particular response.

**Comment by Chiagoro-ahaotu** [comment]
The blog post was very helpful. 
All I actually need is the {{#eq slots.option.value 'option1}} statement.

Good to learn that articulate also handles the responses as "if statements". 
Would try this out.

**Comment by wrathagom** [comment]
Keep in mind that if you don’t return something Articulate won’t choose that response. So you have to have something in between the handlebars.

**Comment by Chiagoro-ahaotu** [comment]
Sorry, I do not get the last part of what you said about returning something.

Let's say I want the bot to reply, "Alright, you have decided to go with option A",
How should the syntax go?

Would I be right to put it this way:

{{#eq slots.options.value 'OptionA}}, Alright, you have decided to go with option A

**Comment by wrathagom** [comment]
Pretty close:

```
{{#eq slots.options.value 'OptionA'}}, Alright, you have decided to go with option A{{\eq}}
```

I was just stating that something like the below won’t work.

```
{{#eq slots.options.value 'OptionA'}}{{\eq}}
```

**Comment by Chiagoro-ahaotu** [comment]
Thank you.
Well understood.
Just by the side, have you thought of compiling all these to produce full documentation for new users?
It would really go a long way to helping them gain mastery of articulate.

**Comment by wrathagom** [comment]
We do have someone working on docs. I am fairly certain this is all covered in the next batch that we will release.

**Comment by Chiagoro-ahaotu** [comment]
Alright. I look forward to the new release.

**Comment by Chiagoro-ahaotu** [comment]
Articulate does not seem to read it. It is skipping my response and moving to action tagged to the response.

Just to be sure, the value I am comparing the {{slot.options.value}} to, should be the value of the slot's keyword right?

**Comment by Chiagoro-ahaotu** [comment]
Also, I just thought of it.
Shouldn't it be {{slots.optionA.value}}, {{slots.optionB.value}},... for the 3 different responses
since they are 3 different slots with 3 distinct keywords and values.

**Comment by wrathagom** [comment]
They aren't three different slots, they are one slot with one keyword. That keyword has multiple values.

**Comment by wrathagom** [comment]
keyword name: options
values:
 - A
 - B
 - C

```
{{#eq slots.options.value 'A'}}, Alright, you have decided to go with option A{{\eq}}

{{#eq slots.options.value 'B'}}, Alright, you have decided to go with option B{{\eq}}

{{#eq slots.options.value 'C'}}, Alright, you have decided to go with option C{{\eq}}
```

**Comment by Chiagoro-ahaotu** [comment]
Hey @wrathagom, could you please take a look at these screenshots. I have implemented what you suggested but still not getting the desired response.

First snippet: Slot  creation
second snippet: Responses to slot 
third snippet: Keyword creation
fourth snippet: Sayings declarations
fifth snippet: Action tagging.
sixth and seventh snippet: chat flow
Thank you.
P.S : I'm trying to create a chat-bot that would guide people in making investments 
![image](https://user-images.githubusercontent.com/49977702/59699426-7651f180-91e9-11e9-9f07-5d79c0cafd34.png)

![image](https://user-images.githubusercontent.com/49977702/59699789-1445bc00-91ea-11e9-8253-120c4a1ab591.png)


![image](https://user-images.githubusercontent.com/49977702/59699671-e52f4a80-91e9-11e9-833d-157a17152525.png)

![image](https://user-images.githubusercontent.com/49977702/59699947-566efd80-91ea-11e9-885e-caae2cc33c29.png)

![image](https://user-images.githubusercontent.com/49977702/59700168-b82f6780-91ea-11e9-8ea5-3f035c29841d.png)

![image](https://user-images.githubusercontent.com/49977702/59700221-d39a7280-91ea-11e9-97a2-1fc2aefe2faa.png)

**Comment by wrathagom** [comment]
That's where modifiers come in. let me see if I can put together an example.

**Comment by Chiagoro-ahaotu** [comment]
Alright. That would be very helpful

**Comment by thiyaga24** [comment]
@wrathagom  Kindly let me know if its possible to provide an example for @Chiagoro-ahaotu  case.

I am stuck at the same thing

**Comment by dcalvom** [comment]
@thiyaga24 do you still need help, plase let us know by re opening this issue. Sorry for the late response.
