### ISSUE TITLE
Help with API document

### ISSUE THREAD

**Issue by thiyaga24** [samtecspg/articulate#790]
I would like to use API   exposed  to chatbot. So i need to create chatbot web ui that consumes articulate API. Could you please let me know is there any API documentation available to write such chat bot.

Thank you in advance

**Comment by dcalvom** [comment]
Hi @thiyaga24 we are working on this documentation. To consume Articulates API in your own chat UI you need to make a POST request to /api/agent/{your agent id}/converse with a payload that should have a sessionId and the text, it would look something like this:

```
{
  "sessionId": "string",
  "text": "string"
}
```

Have you already checked the swagger documentation available for the API?

**Comment by wrathagom** [comment]
swagger docs should be at http://localhost:7500/documentation if you're running locally.

**Comment by thiyaga24** [comment]
Thank you @wrathagom  @dcalvom
