### ISSUE TITLE
Organize actions by category

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#792]
### Feature Request
Was thinking that it would be much easier for the user if actions were only available to that category selected. For example, if I have the category drop down selected as "order", then the actions just pertaining to that category would be available. Then, there could be a selection for the category drop down that says "all" if the user once to see all available actions.  I realized this may be a good idea, once importing the premade made categories.

**Comment by wrathagom** [comment]
This isn't possible given the structure of Articulate. Categories are really just there for organization. And when you start thinking multi-actions this doesn't make sense. For example greet may belong to Small Talk and Order Pizza may belong to Food, but we want to be able to support phrases like `hello, can I get a pizza?`
