### ISSUE TITLE
Don't show agent icon and Name on side by side chat bubbles

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#795]
In this image there are two messages that come in one after the other from the agent (multi-messages) we shouldn't show the icon and agent name for the second one.

![image](https://user-images.githubusercontent.com/1779894/60315774-09033680-9936-11e9-9018-55cbcbcfbd66.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e5cb5f845dde9bafb86e71ffec4afbf83d317401
