### ISSUE TITLE
Action Dropdown Contract

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#797]
@broham89 I had Daniel add this recent section to one of the dropdowns, but I feel like the header sections need more contrast. Here's what it looks like now.

![image](https://user-images.githubusercontent.com/1779894/60316072-2b498400-9937-11e9-8d61-10ede9dbe499.png)

**Comment by wrathagom** [comment]
@dcalvom I also think we should restrict the height of this a bit more. Ideally maybe 5 of the "All" category would show and everything else would require scrolling.

**Comment by broham89** [comment]
![dropdown-title](https://user-images.githubusercontent.com/11262149/60367667-5c1bce80-99b4-11e9-9555-3fa93bf774c7.jpg)

Here are two versions to use. First is the lighter skinner title design to not draw too much attention and let the list-items stand out more with its bold color.

**The second one:**
- bolder standard black color
- same `font-size: 12px;`
- thicker `font-weight: 600;` semi-bold
- same padding height as the listed items, keep it consistent

I would go with the 2nd version.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/d113dfc29bce169de421b6180cd36b0ead0cc897
