### ISSUE TITLE
Pagination /Back/Previous buttons also have problems on modifier page

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#799]
### Issues
Also getting the same problem with the Back/Next, and pagination errors in modifers page. Must hit refresh to fix, and seems it happens as much as with slots and actions.

![image](https://user-images.githubusercontent.com/42249324/60520348-398afd80-9cb3-11e9-846f-b96995dd3797.png)

No errors in  console or git

0.25 release
local
win 10 pro

**Comment by wrathagom** [comment]
@dcalvom I was seeing this as well when on master. Have you been able to reproduce?

**Comment by RussellSPG** [comment]
seems to be fixed for 27.1, but still testing

**Comment by RussellSPG** [comment]
not fixed for 27.1 after retesting, error occurs deleting keywords, and it going back to dialouge page

**Comment by dakavisa** [comment]
Closed by 3adc7cbd57433d4a79e16569249406e39543ba3b
