### ISSUE TITLE
wrong keyword highlighted in modifiers

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#800]
### Issues

For some reason (this hasn't happened before), the word "good" is detected as a value, and must be crossed out. Again, modfier values for me have always been highlighting correctly but for this release, its made this mistake

![image](https://user-images.githubusercontent.com/42249324/60525133-d18ce500-9cbb-11e9-880d-2563ed6fa776.png)

No errors

0.25 release
win 10 pro
local
----

**Comment by wrathagom** [comment]
@dcalvom this sounds familiar. Didn't we make it to where the auto-highlight for modifiers only highlighted the applicable keywords.

**Comment by dcalvom** [comment]
I will check that @wrathagom, probably I miss that restriction

**Comment by dcalvom** [comment]
I forgot to close this one.

Closed by https://github.com/samtecspg/articulate/commit/86c679681d14e79518df4d21d8f5d85b9718c0ff
