### ISSUE TITLE
/api/auth/basic 404 (Not Found)

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#801]
Hello, i enabled authentication, and when i try to login (**/login)

the ui leads to 
**/api/auth/basic 404 (Not Found)

Swagger reveals that there is no "auth" controller

**Comment by wrathagom** [comment]
hey @mordebip I wouldn't consider auth stable or useable at the moment. Did you pull from master or run the latest release?

**Comment by Blue-Beam-com** [comment]
i pulled from stable and rebuilt the ui and the api using the dockerfile.
or should i recompile everything ?

**Comment by mordebip** [comment]
I Cloned from the master branch, and rebuilt from the ui as well as the api dockerfile.
then i updated the docker-compose file to use the local images.

Should i rebuild the rest too ?

**Comment by wrathagom** [comment]
May be related to #811

**Comment by malave** [comment]
@mordebip on #811 you mentioned that the login is working,  are you still getting this error?

**Comment by mordebip** [comment]
No, i'm not having that one anymore (but i have no clue how or why)
