### ISSUE TITLE
Implement a recongnize action by key stroke

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#802]
### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

When there are a ton of actions, it can take time to sort through them all, finding the right one. I suggest when a user hits "g" for example, it will scroll to those corresponding actions, just like in  basic windows.

**Comment by wrathagom** [comment]
the action dropdown has a search box right?

**Comment by RussellSPG** [comment]
ahh, didn't even notice the icon, could be a little less transparent.
