### ISSUE TITLE
Highlight keywords in existing sayings

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#803]
### Feature Request
> *If you've got a feature request we want to hear it*

I noticed that when building the multi actions, that I entered phrases in first, then keywords later. Because of this, the keyword values would not be automatically highlighted in sayings. Would be nice if they are, so it's compatible both ways. Might be asking for too much though, just throwing it out.

**Comment by dakavisa** [comment]
Closed by d423cb5de84096f8ff378186e23340fb93d0dce1
Put some documentation on basecamp
