### ISSUE TITLE
Improve Action Dropdown Search Input

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#805]
@broham89 @dcalvom I think this one pointed out by Russell could be improved. The search icon here isn't very obvious where the input is. To make it worse clicking directly on the search icon right now closes the window :( Another minor critique is that the entire input area highlights great on mouse over, it just looks like it's highlighting the header of a menu or something not an actual input.

![image](https://user-images.githubusercontent.com/1779894/60687495-e06ec580-9e7c-11e9-8dae-2187cad4c8dc.png)

![image](https://user-images.githubusercontent.com/1779894/60687533-101dcd80-9e7d-11e9-8617-609361fc89ad.png)

**Comment by dcalvom** [comment]
I forgot to close this one too.

Closed by https://github.com/samtecspg/articulate/commit/cd2fcbba1460c49c14172d1d3861c81079e988b9
