### ISSUE TITLE
Change success messages when finish edit

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#81]
When you successfully edit a record, the message is showing as it was created instead of edited.

**Comment by wrathagom** [comment]
Agree we want to fix and if it's simple then do it this week, but I'm also fine with it waiting until next week.

**Comment by dcalvom** [comment]
@malave I took this one

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3adc67ed1599b3ab2a82523e22db48501b97fca5
