### ISSUE TITLE
Articulate v0.25.0 Elasticsearch ERROR on MacOS X

### ISSUE THREAD

**Issue by pgavazzi** [samtecspg/articulate#810]
Running v0.25.0 on MacOSX, VirtualBox 6.0.8

docker-compose run works, no errors, when I try my first chat in the chat window, I get:

articulate_elasticsearch_1 exited with code 137
rasa_1           | 2019-07-08 19:30:04+0000 [-] "172.18.0.5" - - [08/Jul/2019:19:30:03 +0000] "POST /parse HTTP/1.1" 200 203 "-" "axios/0.18.0"
api_1            | Elasticsearch ERROR: 2019-07-08T19:30:04Z
api_1            |   Error: Request error, retrying
api_1            |   POST http://elasticsearch:9200/document/document?refresh=true => getaddrinfo ENOTFOUND elasticsearch elasticsearch:9200
api_1            |       at Log.error (/usr/src/app/node_modules/elasticsearch/src/lib/log.js:226:56)
api_1            |       at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:259:18)
api_1            |       at HttpConnector.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
api_1            |       at ClientRequest.wrapper (/usr/src/app/node_modules/lodash/lodash.js:4935:19)
api_1            |       at ClientRequest.emit (events.js:198:13)
api_1            |       at ClientRequest.EventEmitter.emit (domain.js:448:20)
api_1            |       at Socket.socketErrorListener (_http_client.js:392:9)
api_1            |       at Socket.emit (events.js:198:13)
api_1            |       at Socket.EventEmitter.emit (domain.js:448:20)
api_1            |       at emitErrorNT (internal/streams/destroy.js:91:8)
api_1            | 
api_1            | { error:
api_1            |    { Error: No Living connections
api_1            |        at sendReqWithConnection (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:226:15)
api_1            |        at next (/usr/src/app/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
api_1            |        at process._tickCallback (internal/process/next_tick.js:61:11)
api_1            |      message: 'No Living connections',
api_1            |      body: undefined,
api_1            |      status: undefined },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 500,
api_1            |      message: 'No Living connections' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 500,
api_1            |      message: 'No Living connections' },
api_1            |   message: null }
api_1            | Debug: handler, error 
api_1            |     Error: No Living connections
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            | Debug: internal, error 
api_1            |     Error: No Living connections
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
nginx_1          | 172.18.0.1 - - [08/Jul/2019:19:30:04 +0000] "POST /api/agent/1/converse?debug=true HTTP/1.1" 500 96 "http://localhost:8080/agent/1/dialogue?filter=&page=1&tab=actions" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15" "-"
rasa_1           | 2019-07-08 19:31:28+0000 [-] "172.18.0.5" - - [08/Jul/2019:19:31:28 +0000] "POST /parse HTTP/1.1" 200 203 "-" "axios/0.18.0"
api_1            | { error:
api_1            |    { Error: No Living connections
api_1            |        at sendReqWithConnection (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:226:15)
api_1            |        at next (/usr/src/app/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
api_1            |        at process._tickCallback (internal/process/next_tick.js:61:11)
api_1            |      message: 'No Living connections',
api_1            |      body: undefined,
api_1            |      status: undefined },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 500,
api_1            |      message: 'No Living connections' },
api_1            |   message: null }
api_1            | { error:
api_1            |    { isHandled: true,
api_1            |      statusCode: 500,
api_1            |      message: 'No Living connections' },
api_1            |   message: null }
api_1            | Debug: handler, error 
api_1            |     Error: No Living connections
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
nginx_1          | 172.18.0.1 - - [08/Jul/2019:19:31:28 +0000] "POST /api/agent/1/converse?debug=true HTTP/1.1" 500 96 "http://localhost:8080/agent/1/dialogue?filter=&page=1&tab=actions" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15" "-"
api_1            | Debug: internal, error 
api_1            |     Error: No Living connections
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)

Looks like an Elastisearch error.

**Comment by wrathagom** [comment]
Out of curiosity can I ask why you are using virtual box on Mac?

can I see the output of `docker-compose ps` and `docker-compose logs elasticsearch`

**Comment by pgavazzi** [comment]
cornicione:articulate paolo$ docker-compose ps
           Name                         Command                State              Ports         
------------------------------------------------------------------------------------------------
articulate_api_1             docker-entrypoint.sh /bin/ ...   Up         0.0.0.0:7500->7500/tcp 
articulate_duckling_1        /bin/sh -c stack exec duck ...   Up         0.0.0.0:8000->8000/tcp 
articulate_elasticsearch_1   /usr/local/bin/docker-entr ...   Exit 137                          
articulate_nginx_1           nginx-debug -g daemon off;       Up         0.0.0.0:8080->80/tcp   
articulate_rasa_1            ./entrypoint.sh start --pa ...   Up         0.0.0.0:5000->5000/tcp 
articulate_redis_1           docker-entrypoint.sh redis ...   Up         0.0.0.0:6379->6379/tcp 
articulate_ui_1              yarn start:prod                  Up         0.0.0.0:32769->3000/tcp


Attaching to articulate_elasticsearch_1
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1  | [2019-07-08T19:20:51,379][WARN ][o.e.c.l.LogConfigurator  ] [unknown] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:
elasticsearch_1  |   /usr/share/elasticsearch/config/log4j2.properties
elasticsearch_1  | [2019-07-08T19:20:52,004][INFO ][o.e.e.NodeEnvironment    ] [cziMjrs] using [1] data paths, mounts [[/usr/share/elasticsearch/data (osxfs)]], net usable_space [1tb], net total_space [1.8tb], types [fuse.osxfs]
elasticsearch_1  | [2019-07-08T19:20:52,004][INFO ][o.e.e.NodeEnvironment    ] [cziMjrs] heap size [494.9mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2019-07-08T19:20:52,015][INFO ][o.e.n.Node               ] [cziMjrs] node name derived from node ID [cziMjrsVT0aLLdOaonKXZg]; set [node.name] to override
elasticsearch_1  | [2019-07-08T19:20:52,016][INFO ][o.e.n.Node               ] [cziMjrs] version[6.5.1], pid[1], build[default/tar/8c58350/2018-11-16T02:22:42.182257Z], OS[Linux/4.9.125-linuxkit/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.1/11.0.1+13]
elasticsearch_1  | [2019-07-08T19:20:52,017][INFO ][o.e.n.Node               ] [cziMjrs] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.SXd0BTe0, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
elasticsearch_1  | [2019-07-08T19:20:53,255][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2019-07-08T19:20:53,255][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [analysis-common]
elasticsearch_1  | [2019-07-08T19:20:53,255][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [ingest-common]
elasticsearch_1  | [2019-07-08T19:20:53,255][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [lang-expression]
elasticsearch_1  | [2019-07-08T19:20:53,256][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [lang-mustache]
elasticsearch_1  | [2019-07-08T19:20:53,256][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [lang-painless]
elasticsearch_1  | [2019-07-08T19:20:53,256][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [mapper-extras]
elasticsearch_1  | [2019-07-08T19:20:53,257][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [parent-join]
elasticsearch_1  | [2019-07-08T19:20:53,257][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [percolator]
elasticsearch_1  | [2019-07-08T19:20:53,257][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [rank-eval]
elasticsearch_1  | [2019-07-08T19:20:53,257][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [reindex]
elasticsearch_1  | [2019-07-08T19:20:53,257][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [repository-url]
elasticsearch_1  | [2019-07-08T19:20:53,258][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [transport-netty4]
elasticsearch_1  | [2019-07-08T19:20:53,258][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [tribe]
elasticsearch_1  | [2019-07-08T19:20:53,259][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-ccr]
elasticsearch_1  | [2019-07-08T19:20:53,259][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-core]
elasticsearch_1  | [2019-07-08T19:20:53,259][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-deprecation]
elasticsearch_1  | [2019-07-08T19:20:53,259][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-graph]
elasticsearch_1  | [2019-07-08T19:20:53,260][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-logstash]
elasticsearch_1  | [2019-07-08T19:20:53,260][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-ml]
elasticsearch_1  | [2019-07-08T19:20:53,260][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-monitoring]
elasticsearch_1  | [2019-07-08T19:20:53,261][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-rollup]
elasticsearch_1  | [2019-07-08T19:20:53,261][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-security]
elasticsearch_1  | [2019-07-08T19:20:53,261][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-sql]
elasticsearch_1  | [2019-07-08T19:20:53,262][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-upgrade]
elasticsearch_1  | [2019-07-08T19:20:53,262][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-watcher]
elasticsearch_1  | [2019-07-08T19:20:53,263][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded plugin [ingest-geoip]
elasticsearch_1  | [2019-07-08T19:20:53,263][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded plugin [ingest-user-agent]
elasticsearch_1  | [2019-07-08T19:20:55,731][INFO ][o.e.d.DiscoveryModule    ] [cziMjrs] using discovery type [single-node] and host providers [settings]
elasticsearch_1  | [2019-07-08T19:20:56,110][INFO ][o.e.n.Node               ] [cziMjrs] initialized
elasticsearch_1  | [2019-07-08T19:20:56,110][INFO ][o.e.n.Node               ] [cziMjrs] starting ...
elasticsearch_1  | [2019-07-08T19:20:56,335][INFO ][o.e.t.TransportService   ] [cziMjrs] publish_address {172.18.0.8:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2019-07-08T19:20:56,384][INFO ][o.e.h.n.Netty4HttpServerTransport] [cziMjrs] publish_address {172.18.0.8:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2019-07-08T19:20:56,385][INFO ][o.e.n.Node               ] [cziMjrs] started
elasticsearch_1  | [2019-07-08T19:20:56,467][INFO ][o.e.g.GatewayService     ] [cziMjrs] recovered [0] indices into cluster_state
elasticsearch_1  | [2019-07-08T19:20:56,556][INFO ][o.e.l.LicenseService     ] [cziMjrs] license [50e32761-2d89-4957-a14e-05a9c734111d] mode [basic] - valid
elasticsearch_1  | [2019-07-08T19:21:01,576][WARN ][o.e.d.c.m.MetaDataCreateIndexService] [cziMjrs] the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template
elasticsearch_1  | [2019-07-08T19:21:01,647][INFO ][o.e.c.m.MetaDataCreateIndexService] [cziMjrs] [document] creating index, cause [api], templates [], shards [5]/[1], mappings []
elasticsearch_1  | [2019-07-08T19:21:07,765][INFO ][o.e.c.m.MetaDataMappingService] [cziMjrs] [document/9rYByNXcROy9peWGUAAGLA] create_mapping [document]
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
elasticsearch_1  | [2019-07-08T21:22:07,297][WARN ][o.e.c.l.LogConfigurator  ] [unknown] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:
elasticsearch_1  |   /usr/share/elasticsearch/config/log4j2.properties
elasticsearch_1  | [2019-07-08T21:22:07,834][INFO ][o.e.e.NodeEnvironment    ] [cziMjrs] using [1] data paths, mounts [[/usr/share/elasticsearch/data (osxfs)]], net usable_space [1tb], net total_space [1.8tb], types [fuse.osxfs]
elasticsearch_1  | [2019-07-08T21:22:07,834][INFO ][o.e.e.NodeEnvironment    ] [cziMjrs] heap size [494.9mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2019-07-08T21:22:07,968][INFO ][o.e.n.Node               ] [cziMjrs] node name derived from node ID [cziMjrsVT0aLLdOaonKXZg]; set [node.name] to override
elasticsearch_1  | [2019-07-08T21:22:07,969][INFO ][o.e.n.Node               ] [cziMjrs] version[6.5.1], pid[1], build[default/tar/8c58350/2018-11-16T02:22:42.182257Z], OS[Linux/4.9.125-linuxkit/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.1/11.0.1+13]
elasticsearch_1  | [2019-07-08T21:22:07,969][INFO ][o.e.n.Node               ] [cziMjrs] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.QLD7rZ7S, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
elasticsearch_1  | [2019-07-08T21:22:09,150][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2019-07-08T21:22:09,150][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [analysis-common]
elasticsearch_1  | [2019-07-08T21:22:09,151][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [ingest-common]
elasticsearch_1  | [2019-07-08T21:22:09,151][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [lang-expression]
elasticsearch_1  | [2019-07-08T21:22:09,151][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [lang-mustache]
elasticsearch_1  | [2019-07-08T21:22:09,151][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [lang-painless]
elasticsearch_1  | [2019-07-08T21:22:09,152][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [mapper-extras]
elasticsearch_1  | [2019-07-08T21:22:09,152][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [parent-join]
elasticsearch_1  | [2019-07-08T21:22:09,152][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [percolator]
elasticsearch_1  | [2019-07-08T21:22:09,153][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [rank-eval]
elasticsearch_1  | [2019-07-08T21:22:09,153][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [reindex]
elasticsearch_1  | [2019-07-08T21:22:09,153][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [repository-url]
elasticsearch_1  | [2019-07-08T21:22:09,154][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [transport-netty4]
elasticsearch_1  | [2019-07-08T21:22:09,154][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [tribe]
elasticsearch_1  | [2019-07-08T21:22:09,155][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-ccr]
elasticsearch_1  | [2019-07-08T21:22:09,155][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-core]
elasticsearch_1  | [2019-07-08T21:22:09,155][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-deprecation]
elasticsearch_1  | [2019-07-08T21:22:09,155][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-graph]
elasticsearch_1  | [2019-07-08T21:22:09,156][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-logstash]
elasticsearch_1  | [2019-07-08T21:22:09,156][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-ml]
elasticsearch_1  | [2019-07-08T21:22:09,157][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-monitoring]
elasticsearch_1  | [2019-07-08T21:22:09,157][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-rollup]
elasticsearch_1  | [2019-07-08T21:22:09,157][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-security]
elasticsearch_1  | [2019-07-08T21:22:09,157][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-sql]
elasticsearch_1  | [2019-07-08T21:22:09,158][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-upgrade]
elasticsearch_1  | [2019-07-08T21:22:09,158][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded module [x-pack-watcher]
elasticsearch_1  | [2019-07-08T21:22:09,159][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded plugin [ingest-geoip]
elasticsearch_1  | [2019-07-08T21:22:09,159][INFO ][o.e.p.PluginsService     ] [cziMjrs] loaded plugin [ingest-user-agent]
elasticsearch_1  | [2019-07-08T21:22:11,497][INFO ][o.e.d.DiscoveryModule    ] [cziMjrs] using discovery type [single-node] and host providers [settings]
elasticsearch_1  | [2019-07-08T21:22:11,904][INFO ][o.e.n.Node               ] [cziMjrs] initialized
elasticsearch_1  | [2019-07-08T21:22:11,904][INFO ][o.e.n.Node               ] [cziMjrs] starting ...
elasticsearch_1  | [2019-07-08T21:22:12,087][INFO ][o.e.t.TransportService   ] [cziMjrs] publish_address {172.18.0.3:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2019-07-08T21:22:12,149][INFO ][o.e.h.n.Netty4HttpServerTransport] [cziMjrs] publish_address {172.18.0.3:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2019-07-08T21:22:12,149][INFO ][o.e.n.Node               ] [cziMjrs] started
elasticsearch_1  | [2019-07-08T21:22:12,513][INFO ][o.e.l.LicenseService     ] [cziMjrs] license [50e32761-2d89-4957-a14e-05a9c734111d] mode [basic] - valid
elasticsearch_1  | [2019-07-08T21:22:12,516][INFO ][o.e.g.GatewayService     ] [cziMjrs] recovered [1] indices into cluster_state
elasticsearch_1  | [2019-07-08T21:22:13,731][INFO ][o.e.c.r.a.AllocationService] [cziMjrs] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[document][3]] ...]).
elasticsearch_1  | [2019-07-08T21:23:58,771][INFO ][o.e.c.m.MetaDataMappingService] [cziMjrs] [document/9rYByNXcROy9peWGUAAGLA] update_mapping [document]

**Comment by pgavazzi** [comment]
Worked once, then gave me error 137 exit. So I restarted docker, worked once...

**Comment by wrathagom** [comment]
Elasticsearch has exited, but the logs don't show any errors. How much RAM are you allocating to virtual box?

**Comment by pgavazzi** [comment]
I am not configuring anything, just use the v0.25.0 label, and ran `docker compose up`. So whatever is configured by default.

**Comment by pgavazzi** [comment]
So I bumped the image memory to 4GB. Will let you know if eleastiserach is more stable.

**Comment by pgavazzi** [comment]
This solves the issue.
