### ISSUE TITLE
Creating new agent results in error, fresh install

### ISSUE THREAD

**Issue by mathconnor** [samtecspg/articulate#815]
I am on a windows local machine running from the command line. 
I went to https://github.com/samtecspg/articulate and downloaded  the zip file. 
I unzipped, navigated to project directory `\articulate-master\articulate-master`  then used the command `docker-compose up`.

I opened a Chrome browser and navigated to `http://localhost:3000`.
I clicked on "Create Agent", completed the required fields and clicked "Save".
I received a message: "Error: There was an error creating your agent"
I opened Chrome developer tools and went to network and found the following message:
"{statusCode: 400, error: "Bad Request",…}
error: "Bad Request"
message: "child "gravatar" fails because ["gravatar" is required]"
statusCode: 400"

**Comment by wrathagom** [comment]
which version are you running, this was solved in newer versions.

**Comment by wrathagom** [comment]
The UI no longer runs on 3000, please try accessing from port 8080

**Comment by mathconnor** [comment]
![image](https://user-images.githubusercontent.com/18110140/61078324-60051300-a3ee-11e9-9d30-ab949d60b5a7.png)

**Comment by mathconnor** [comment]
Hos do I check which version?

**Comment by wrathagom** [comment]
Did you download the zip from master or a release?

Either way it runs behind a reverse proxy with Docker and compose thrown in the mix as well:

![image](https://user-images.githubusercontent.com/1779894/61078525-ca1db800-a3ee-11e9-8e1f-0bc8ad8b4841.png)

**Comment by wrathagom** [comment]
Have you had a chance to try this again? I think it will solve your problem, but it could still be something else.
