### ISSUE TITLE
Authentication when a user is deleted

### ISSUE THREAD

**Issue by Blue-Beam-com** [samtecspg/articulate#816]
When adding multiple users on keys

```
> articulate:hash:UserAccount:1
> articulate:hash:UserAccount:2
> articulate:hash:UserAccount:3
> articulate:hash:UserAccount:4
> articulate:hash:UserAccount:5
> articulate:hash:UserAccount:6
> articulate:hash:UserAccount:7
```

if you delete the user located on articulate:hash:UserAccount:4, the users on 

```
> articulate:hash:UserAccount:5
> articulate:hash:UserAccount:6
> articulate:hash:UserAccount:7

```
cannot be accessed anymore

in order to solve this issue, the search element should be switched from an incremental/existance type to an incremental from key type

it should look somehow like this (tested on .netcore test project)
```
            foreach (var key in server.Keys(pattern: "articulate:hash:UserAccount:*"))
            {
                db.HashGetAll(key);
            }
```

**Comment by wrathagom** [comment]
@Blue-Beam-com authentication isn't not in an official release yet so you are using un-tested features. Thanks for reporting this though, we'll get to it as fast as we can.

**Comment by Blue-Beam-com** [comment]
Yes obviously.
I'm trying to understand how to implement the solution on your project.

**Comment by malave** [comment]
@Blue-Beam-com How are you adding/deleting the users?

On the API we are using [nohm](https://maritz.github.io/nohm/) to manage the data in our redis db. If you directly remove keys from redis it could create some issues since nohm does other work to keep all indexes properly related.

**Comment by Blue-Beam-com** [comment]
i did the modification directly on the database (using a .net core app i made), but i didn't know about the nohm mapper.
I was trying to see how make a role guided user management system for articulate.

**Comment by wrathagom** [comment]
We'll be looking at adding roles/groups in the future and would be interested in collaboration on it. For the moment note that you can't modify redis directly.
