### ISSUE TITLE
Add Time selection to analytics page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#819]
Right now the analytics page shows everything from the beginning of time, but this isn't the most helpful. I would like to add a dropdown that has a few options:

- Last hour
- Last Day
- Last Week
- Last Month
- All Time

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/b2fa19072ae6b025a50a5ab021e5a193ac1ad107
