### ISSUE TITLE
Freeze Redis version in compose file

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#82]
Just in case anything changes we don't want to get caught by surprise.

**Comment by milutz** [comment]
Ugh! didn't catch that its set to latest! https://github.com/samtecspg/articulate/blob/master/docker-compose.yml#L49

I'll change when I'm running through packages if someone else doesn't change it before me

**Comment by milutz** [comment]
I haven't done the edit but redis 4.0.6 is likely the safest pick (given all the critical bugs that are in the earlier releases)

**Comment by milutz** [comment]
( @wrathagom added this into the compose on commit 6ba1f8799d1593b22285225b5527937d31c8d64f )
