### ISSUE TITLE
webhook  calling

### ISSUE THREAD

**Issue by eluru-rajesh-hubino** [samtecspg/articulate#825]
How to call the webhook 
i have enable the webhook , and given the url (localhost:5555/auto) select the post method . when this action triggered , this service is not going to hit .
what should i do

**Comment by wrathagom** [comment]
This is a Docker thing, `localhost` is inside the Docker container. So assuming you have some other service running locally on your machine you can't access it via `localhost` you would've to add it to the Docker network or change the Docker network to use the host network.

To test and make sure everything is working, try an external service like https://api.chucknorris.io

**Comment by wrathagom** [comment]
https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

**Comment by dcalvom** [comment]
Question answered
