### ISSUE TITLE
Follow up intents 

### ISSUE THREAD

**Issue by eluru-rajesh-hubino** [samtecspg/articulate#826]
how to add follow up intents 
 when user asks "what is the eligibility to watch  horror movies " ,
bot response "may i know your age "
if user give above 18 years bot should respond as eligible , else  bot response as not eligible .
how to add this type of followup intents ?????

**Comment by RussellSPG** [comment]
@eluru-rajesh-hubino  We call follow up intents, chained actions. So you create a new action, with response where you create the response.  This is on 27.2 release, so not sure what release u were posting on, but for example:

![image](https://user-images.githubusercontent.com/42249324/62740900-1583b000-ba07-11e9-9318-6e270f430260.png)

In the "thanks" action is the response "thanks for your order!". Basic example but you can see as it links down you can have as many follow up as you like.

Hope that helps

**Comment by senthurRam33** [comment]
What you've answered is just a response for that question. The case here is if the user randomly says 18 the bot will respond with "Yes you are eligible". But the bot only should answer in that way if the user asked the previous question "what is the eligibility to watch horror movies?" Otherwise the bot should respond with "I couldn't understand it"

**Comment by wrathagom** [comment]
Combine handlebars with action chaining.

```
{{#gte slots.age.value 18}}Yes, you are eligible.{{/eq}}
```

and then create another responses

```
{{#lt slots.age.value 18}}Sorry you have to be 18 to watch horror movies.{{/eq}}
```

**Comment by wrathagom** [comment]
This may help https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241

**Comment by dcalvom** [comment]
Closed due to inactivty. Plus the answer was responded.
