### ISSUE TITLE
deleting saying in dialouge page changes entries number shown

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#827]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Small bug, but when you delete a saying that is entered from the trash icon, the sayings displayed changes to all, so all sayings are shown. However, it will still say 5 entries.

No errors.

Reproduced with same result every time. 

![image](https://user-images.githubusercontent.com/42249324/61593088-20d28100-aba9-11e9-9d77-6dae6d4c29e6.png)

Step 4.19 on script

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
0.27
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by dcalvom** [comment]
Should solve this at the same time than #850

**Comment by dakavisa** [comment]
Closed by 752775c6fdf604f20cc1d0dae153573021646a74
