### ISSUE TITLE
Problem Connecting Articulate with Slack (Your URL didn't respond with the value of the challenge parameter.)

### ISSUE THREAD

**Issue by aizazqaisrani** [samtecspg/articulate#829]
Hi, I am trying to connect Slack with Articulate. I am using articulate in my local machine and I am using ngrok to expose my articulate. However, I am facing a problem in making the connection while adding the event subscriptions
![Slack Issue](https://user-images.githubusercontent.com/6060161/61613322-15975800-ac72-11e9-9613-619252a8478b.png)
. 
I am adding the screenshot below:

**Comment by wrathagom** [comment]
@aizazqaisrani that url doesn't look right, can I see the connection screen on the Articulate side? I would expect the url to be something like `https://asdasdf.ngrok.io/connection/{big long guid}`

**Comment by aizazqaisrani** [comment]
Hi, here is the image for the URL:
![Screenshot from 2019-07-24 12-48-52](https://user-images.githubusercontent.com/6060161/61779480-cd16a080-ae11-11e9-9bab-95c0d9bd26db.png)

But when I try adding it. I still get the same error:
![Screenshot from 2019-07-24 12-51-05](https://user-images.githubusercontent.com/6060161/61779511-def84380-ae11-11e9-843c-2200d5fff925.png)

Please have a look. Thanks

**Comment by dcalvom** [comment]
Hi @aizazqaisrani, please add /api before /connection.

Thanks

**Comment by aizazqaisrani** [comment]
![Screenshot from 2019-07-24 16-38-45](https://user-images.githubusercontent.com/6060161/61794106-8df84780-ae31-11e9-9d6b-7bc3d092f4b7.png)
It's still the same.

**Comment by aizazqaisrani** [comment]
Even after adding external. It's still the same
![Screenshot from 2019-07-24 16-39-55](https://user-images.githubusercontent.com/6060161/61794210-bb44f580-ae31-11e9-8b90-ab1e9913460b.png)

**Comment by dcalvom** [comment]
What was your ngrok command?

**Comment by wrathagom** [comment]
@dcalvom might be worth you walking through this process real quick on master to make sure we haven't accidentally broken anything (assuming you haven't already).

**Comment by nanotkarashish** [comment]
If @aizazqaisrani, you are using docker-compose up to run articulate, consider adding :8080 to your url.
your ngrok command will look like: ngrok http http://127.0.0.1:8080
Locally the Nginx container is exposed on 8080.

**Comment by dcalvom** [comment]
Closed due to inactivty. Please re open in case you need help.
