### ISSUE TITLE
Action chaining 

### ISSUE THREAD

**Issue by eluru-rajesh-hubino** [samtecspg/articulate#831]
how to add these type of intents 
when bot ask question " are you completed your Masters " , user may give reply as yes or no
if user says "yes" i have to call an action , if user says "NO" i have to call another action .
for this purpose how to add the intents .

**Comment by RussellSPG** [comment]
answered at #826

**Comment by RussellSPG** [comment]
Also, please don't repeat the same question multiple times, somebody will eventually get to your issue. Thank you!
