### ISSUE TITLE
Button Responses

### ISSUE THREAD

**Issue by NewtonJoaquim** [samtecspg/articulate#832]
Is there a way to add buttons to the chatbot responses? I see there is a 'Response Format' slider at the Response tab of the Action view, but how do i use it?

**Comment by dcalvom** [comment]
Hi, what are you using to chat with your agent? We do support structured inputs, but you will need to configure your buttons to send an structure text

**Comment by wrathagom** [comment]
@NewtonJoaquim the short answer is that this would have to be programmed by you for whatever chat platform you are using. 

We're are working to bring buttons to Articulate, but want to do it in such a way that it works for all platforms we integrate with if they support buttons.

**Comment by wrathagom** [comment]
This is now included on master and will be released in 0.28
