### ISSUE TITLE
Remember Slot option not showing after saving

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#836]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

When in slots menu, editing slot, and checking the "remember life", giving a value, there's a small glitch where when you edit the slot, and if you have checked and gave a value for "remembered life" it will not show the checkbox checked, even though you have done it. When you click it again, it brings up the value, which means it is remembered, just not shown. 
Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
27.0
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by cesarandreslopez** [comment]
Same Issue is seen hear in:

Did you download a release or pull from Master? Which release?
27.0
What operating system are you running?
Ubuntu 18.04
Are you running locally or in the cloud?
local
Which browser are you using?
Chrome

**Comment by wrathagom** [comment]
We'll take a look.

**Comment by dcalvom** [comment]
https://github.com/samtecspg/articulate/commit/e27072553d36fb54538c92531f71b9722eb0fb3a
