### ISSUE TITLE
multiple responses also given when using chained actions and modifers

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#838]
### Issues
I'm also getting extraneous responses when using modifiers/chained actions though the conversation flow is much more smooth.

![image](https://user-images.githubusercontent.com/42249324/61962116-d8470900-af96-11e9-9910-90cecc82a634.png)

Just though I'd make this known as well:

Source for agent response: (after saying "yup")

```
[
  {
    "docId": "wNHZLmwBa2vB5GT3L7Ob",
    "category": "pizzabot-0.27_modifiers",
    "project": "pizzabot-0.27",
    "model": "pizzabot-0.27_modifiers",
    "keywords": [],
    "action": {
      "name": "Accept",
      "confidence": 0.9457505345344543
    },
    "action_ranking": [
      {
        "name": "Accept",
        "confidence": 0.9457505345344543
      },
      {
        "name": "Good",
        "confidence": 0.13910570740699768
      },
      {
        "name": "remove toppings",
        "confidence": 0.10286112874746323
      },
      {
        "name": "set toppings",
        "confidence": 0.0010171383619308472
      },
      {
        "name": "Bad",
        "confidence": 0
      },
      {
        "name": "Deny",
        "confidence": 0
      },
      {
        "name": "Okay",
        "confidence": 0
      },
      {
        "name": "add toppings",
        "confidence": 0
      },
      {
        "name": "Affirmation",
        "confidence": 0
      },
      {
        "name": "Negation",
        "confidence": 0
      }
    ],
    "elapsed_time_ms": 102,
    "categoryScore": 0.9523638486862183
  },
  {
    "docId": "wNHZLmwBa2vB5GT3L7Ob",
    "category": "default",
    "project": "pizzabot-0.27",
    "model": "default_ef128957-6e13-ee1e-4cc7-b527d6eeba14",
    "keywords": [],
    "action": {
      "name": "",
      "confidence": 0
    },
    "action_ranking": [],
    "elapsed_time_ms": 110,
    "categoryScore": 0
  }
]
```
- Did you download a release or pull from Master? Which release?
release  27.0
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

----

**Comment by wrathagom** [comment]
please re-test with 0.27.2

**Comment by RussellSPG** [comment]
got it

**Comment by RussellSPG** [comment]
issues remain in 0.27.2 Same behavior. Re-produced with same results. Basic agent does the same thing as well so issue isn't with chained actions or modifiers.

**Comment by wrathagom** [comment]
What does the context look like?

**Comment by wrathagom** [comment]
and can we get an export? this one is interesting.

**Comment by RussellSPG** [comment]
![image](https://user-images.githubusercontent.com/42249324/62738812-3b0dbb00-ba01-11e9-9bbf-f2ccc22f791c.png)
Phrases before work ok. Behavior is the same as previous releases, always repeating the "how are you" action. This agent was the basic one, adding in/out different features, so goes to far as chained actions, but that doesn't seem to be the problem at all. Was getting same behavior with basic actions only, when testing before.

**Comment by RussellSPG** [comment]
[0.27.2.zip](https://github.com/samtecspg/articulate/files/3483764/0.27.2.zip)

**Comment by wrathagom** [comment]
What happens if you reply to the how are you? Do you have the small talk category in there?

**Comment by RussellSPG** [comment]
yes small talk category is there
![image](https://user-images.githubusercontent.com/42249324/62739274-6ba22480-ba02-11e9-80ef-ce019502aaec.png)

**Comment by wrathagom** [comment]
Can I see an image of the full conversation where it goes wrong, start to finish?

**Comment by RussellSPG** [comment]
unless I'm missing something, it seems there isn't even an action for how are you with a response, "that is good to hear."

**Comment by RussellSPG** [comment]
![image](https://user-images.githubusercontent.com/42249324/62739638-48c44000-ba03-11e9-972c-9d258d887190.png)

**Comment by wrathagom** [comment]
It's the `ask mood` action, which is chained together with the `Greet` action.

This is expected behavior, you never answered the how are you question so it will keep asking. We've got an issue open for making some prompts only happen once #818

**Comment by RussellSPG** [comment]
Ah I did answer, great then ordered pizza again, and it didn't appear. Ok, glad that can be put to rest

**Comment by wrathagom** [comment]
yeah, This result in un-natural conversation, which is why I want a way of saying "Only prompt for this once" sort of a thing.

**Comment by RussellSPG** [comment]
yeah I think so too, we have a limited life for slots, couldn't we implement the same kind of thing for actions/chained actions?

**Comment by rounakraj** [comment]
@wrathagom The double response issue which i am facing is same as the above. How did we fix this.
