### ISSUE TITLE
Need to handle languages better

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#84]
Ideally we would think of a way for the API to tell the UI which languages are available. Since Rasa doesn't have this functionality we will have to work through that part of it.

No hurry on this though.

**Comment by dcalvom** [comment]
Could this one be closed in favor of https://github.com/samtecspg/articulate/issues/175 or not yet?

**Comment by wrathagom** [comment]
Could also be related to #289 and #643

**Comment by dcalvom** [comment]
This already exists
