### ISSUE TITLE
Unable to delete an agent

### ISSUE THREAD

**Issue by RakibulAsheeque** [samtecspg/articulate#844]
### ISSUE
Unable to delete an agent from the Articulate UI.

**Comment by wrathagom** [comment]
Almost no information to go off of here: what version are you running, were there any errors creating the agent, what other things had you done to the agent?

**Comment by RakibulAsheeque** [comment]
I am using version 0.27.2. There were no errors while creating the agent. I was trying to connect a webhook with the agent.

**Comment by wrathagom** [comment]
@RussellSPG can you try to replicate this?

**Comment by RussellSPG** [comment]
sure thing

**Comment by RussellSPG** [comment]
@RakibulAsheeque did you create a webhook, then was not able to delete it? Can you upload an export?

**Comment by RussellSPG** [comment]
@RakibulAsheeque could you please fill the form, when posting for issues? It will help to rule out compatibility, and save time, thanks.

**Comment by RakibulAsheeque** [comment]
@RussellSPG 
**- Did you download a release or pull from Master? Which release?**
  I downloaded a release. version 0.27.2.
**- What operating system are you running?**
  Debian Linux
**- Are you running locally or in the cloud?**
  Cloud
**- Which browser are you using?**
  Chrome

**Comment by RakibulAsheeque** [comment]
I built the docker containers again in a new instance and the issue got resolved.
