### ISSUE TITLE
how to Set webhook response 

### ISSUE THREAD

**Issue by eluru-rajesh-hubino** [samtecspg/articulate#846]
when i call the wehook , I am getting this response [
  {
    "name": "John",
    "age": 30,
    "city": "New York",
    "elapsed_time_ms": 158
  }
]
Now i want to show only name and city for answer for that intent ???
How to do that .....????

**Comment by wrathagom** [comment]
@eluru-rajesh-hubino maybe [this blog post](https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241) will help.

You can use handlebars to include them in a response. Something like `{{webhook.response.name}} is {{webhook.response.age}} and from {{webhook.response.city}}`

**Comment by wrathagom** [comment]
Is this a continuation of your other issue or is this one resolved @eluru-rajesh-hubino
