### ISSUE TITLE
Management of languages in duckling and rasa in parse endpoint

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#85]
We want to send the language parameter in the call of parse so we can pass this parameter to duckling and rasa.

Probably the format for duckling is `curl -XPOST http://0.0.0.0:8000/parse --data 'lang=en&text=tomorrow at eight'`

**Comment by wrathagom** [comment]
@dcalvom did you test duckling in Spanish too? Seems to me you've have to use the API to do this properly right?

**Comment by dcalvom** [comment]
@wrathagom I have added the language parameter so now whenever you want to use any other language rather than the default `en` you need to send that in the request of `converse` or `parse`.

I tested Duckling and it returns the result depending on the language you sent it. 

I don't have clear if this cover your issue or not.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/8ce71a187edbe61d7ad6d3a1b6117871f50df698. Now the parse endpoint will use the language of the agent to call duckling
