### ISSUE TITLE
displaying all results error when deleting sayings

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#850]
This occurred doing some re-testing of functionality, though this behavior can be random. When deleting a test saying with assigned action, it will then display all sayings, while showing entries are only five:

![image](https://user-images.githubusercontent.com/42249324/62737066-f718b700-b9fc-11e9-9256-f0727ac561fc.png)

Couldn't reproduce
No errors in console

27.2
Win 10 Pro
FF

**Comment by RussellSPG** [comment]
Was able to reproduce! Seems it happens when deleting an unedited saying for the 3rd time.

**Comment by wrathagom** [comment]
so to reproduce we should just try to delete several sayings in a row?

**Comment by RussellSPG** [comment]
yea, try taking a made agent, with sayings already trained and not edited. After 3 or so, it happens.

**Comment by RussellSPG** [comment]
I'm going to see if that happens on other browsers

**Comment by dakavisa** [comment]
Being working on this and its related issue #897, It looks like a problem with the paging logic when deleting sayings, **if you are on page 1** and start deleting sayings, everytime the total sayings count hit a multiple of 5, this will happen, and **if you are on any other page** the paging mechanism will get you to the previous page when the total sayings count is a multiple of 5 ... 5 seems to be hardcoded so if you test with any other page size, the same problem will appear at multiples of 5... I think I got it working  now locally but I will commit after testing every scenario I can think of.

**Comment by dakavisa** [comment]
Closed by 752775c6fdf604f20cc1d0dae153573021646a74
