### ISSUE TITLE
Non liinear follow up  issue

### ISSUE THREAD

**Issue by eluru-rajesh-hubino** [samtecspg/articulate#851]
### Issues
{{if eq(slots.slotname.value 'major')}} you are major {{/if}}
{{if eq(slots.slotname.value 'minor')}} you are minor {{/if}}

When i try to use this things in response , I am not getting the expected result ...
How to handle it .

**Comment by wrathagom** [comment]
that's not valid handlebars I don't think. You would create two responses, each with one line of the below in it:

```
{{#eq slots.slotname.value 'major'}} you are major {{/eq}}
```

and a second response like:

```
{{#eq slots.slotname.value 'minor'}} you are minor {{/eq}}
```

For more handlebars info look here: https://blog.spg.ai/a-bot-with-a-handlebar-mustache-6b2e74edc241

**Comment by dcalvom** [comment]
Closed due to inactivity. Please re open in case you need help
