### ISSUE TITLE
Web-Demo Responses not coming through

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#855]
Testing the web demo and the responses aren't being received in the web-demo chat panel.

![image](https://user-images.githubusercontent.com/1779894/62836669-a6d76a00-bc33-11e9-9d65-303f9cec0edd.png)

but through some bizarre fluke, they are  being received by the chat panel inside Articulate:

![image](https://user-images.githubusercontent.com/1779894/62836665-a2ab4c80-bc33-11e9-834f-bb24776ac88d.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/e35a8f4099f33d750c5553e36da8ce4dd4a77382
