### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by eluru-rajesh-hubino** [samtecspg/articulate#856]
when try to train the bot only its allowed to train for the first time . after onwards its throwing interanal server error 5xx . please go through this one 
 api_1
api_1
api_1
api_1
api_1
api_1
rasa_1
2019H07H11H57 +0000] "POST /train? project=FWD&model=default_c4f4dc61-5cdc-5a46-2ba0-3ae5d730a9d8 HTTP/ 1.1" 403 62 "-" "axios/0.18.0"
| | | | | |
message: null } { error:
{ isHandled: true,
statusCode: 500,
message: 'Request failed with status code 500' },
message: null }
| 2019-08-13 07H11H57+0000 [-] "192.168.0.5" - - [13/Aug/
api_1
api_1
api_1
createError.js:16H15)
api_1 | at settle (/usr/src/app/node_modules/axios/lib/core/settle.js: 18H12)
| { error:
| { Error: Request failed with status code 403
| at createError (/usr/src/app/node_modules/axios/lib/core/
api_1 | at IncomingMessage.handleStreamEnd (/usr/src/app/ node_modules/axios/lib/adapters/http.js:201H11)
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
"intent_featurizer_count_vectors"\n - \n name: "intent_classifier_tensorflow_embedding"\n intent_tokenization_flag: true\n intent_split_symbol: "+__+"\n - \n name: "nlp_spacy"\n - \n name:
| at IncomingMessage.emit (events.js:194H15)
| at IncomingMessage.EventEmitter.emit (domain.js:441H20)
| at endReadableNT (_stream_readable.js:1125H12)
| at process._tickCallback (internal/process/next_tick.js:63H19) | config:
| { adapter: [Function: httpAdapter],
| transformRequest: [Object],
| transformResponse: [Object],
| timeout: 0,
| xsrfCookieName: 'XSRF-TOKEN',
| xsrfHeaderName: 'X-XSRF-TOKEN',
| maxContentLength: -1,
| validateStatus: [Function: validateStatus],
| headers: [Object],
| method: 'post',
| baseURL: 'http://rasa:5000',
| params: [Object],
| url: 'http://rasa:5000/train',
| data:
| '---\n language: "en"\n pipeline: \n
- \n
name:

 "tokenizer_spacy"\n - \n name: "ner_crf"\n - \n name: "ner_synonyms"\n - \n name: "ner_spacy"\n data: {\n "rasa_nlu_data": {\n "common_examples": [\n {\n "text": "hi",\n "intent": "Green",\n "entities": []\n },\n {\n
"text": "heya",\n "intent": "Green",\n "entities": []\n },\n {\n
"hey",\n "intent": "Green",\n "entities": []\n },\n {\n
"text": "text": "just
going to say hi",\n
"text": "howdy",\n
"text": "hey there",\n
"text": "hi there",\n
"text": "hello",\n
"long time no see",\n
"text": "greetings",\n
"text": "howdy",\n
"text": "lovely day isn\'t it",\n {\n "text": "i greet you",\n {\n "text": "hello again",\n
"entities": []\n },\n "entities": []\n },\n
"entities": []\n },\n "entities": []\n },\n
{\n {\n
"intent": "Green",\n "intent": "Green",\n
"intent": "Green",\n "intent": "Green",\n
{\n {\n
"text": {\n
{\n
"intent": "Green",\n "intent": "Green",\n
"intent": "Green",\n "intent": "Green",\n
},\n },\n {\n
"intent": "Green",\n "intent": "Green",\n "intent": "Green",\n
"entities": []\n },\n "entities": []\n },\n "entities": []\n },\n
{\n "text": "hi",\n
"text": "hello there",\n
"text": "a good day",\n
"text": "Am i deserved",\n
\n },\n {\n "text": "What is the eligibility to work remotely",\n "intent": "eligibility_resonse",\n "entities": []\n },\n {\n "text": "Am i qualified for work anywhere ?",\n "intent": "eligibility_resonse",\n "entities": []\n }, \n {\n "text": "Am i eligible",\n "intent": "eligibility_resonse",\n
"entities": []\n },\n {\n "text": "Am i eligible for work anywhere ?",\n "intent": "eligibility_resonse",\n "entities": []\n },\n {\n "text": "Am i
"intent": "Green",\n "intent": "Green",\n
"entities": []\n "entities": []\n
},\n {\n },\n {\n
"intent": "Green",\n
"intent": "eligibility_resonse",\n
qualified",\n "intent": "eligibility_resonse",\n "entities": []\n
"text": "I have completed",\n
"entities": []\n },\n {\n
"eligibility_yes_response",\n
"intent": "eligibility_yes_response",\n "entities": []\n },\n
"4",\n "intent": "yes_eligibility_rating",\n "entities": [\n
"start": 0,\n "end": 1,\n "value": "4",\n "entity": "number"\n }\n ]\n },\n {\n "text": "5",\n "intent": "yes_eligibility_rating",\n "entities": [\n {\n "start": 0,\n
"end": 1,\n "value": "5",\n "entity": "number"\n
{\n "text": "4",\n
{\n "start": 0,\n
"number"\n }\n
"yes_eligibility_rating",\n
"end": 1,\n "value": "5",\n "entity": "number"\n {\n "text": "1",\n "intent": "yes_eligibility_rating",\n {\n "start": 0,\n "end": 1,\n "value": "1",\n
{\n
}\n ]\n },\n "entities": [\n
"entity": "intent":
"entities": [\n "entity":
"entities": []\n },\n "entities": []\n "entities": []\n
"entities": []\n
{\n },\n
"intent": "eligibility_yes_response",\n "text": "yes",\n "intent":
"entities": []\n },\n {\n
"text": "yeah",\n {\n "text":
"intent": "yes_eligibility_rating",\n
]\n
"end": 1,\n },\n {\n
"value": "4",\n "text": "5",\n
"entities": []\n
},\n {\n "entities": []
"entities": [\n {\n "start": 0,\n
}\n ]\n },\n
},\n {\n

 "number"\n }\n ]\n },\n {\n "text": "2",\n "intent":
"yes_eligibility_rating",\n
"end": 1,\n "value": "2",\n "entity": "number"\n
{\n "text": "5",\n {\n "start": 0,\n "number"\n }\n "eli_no_response",\n completed yet",\n
}\n ]\n },\n "entities": [\n
"entity": "intent":
"entities": []\n
"intent": "eli_no_response",\n "entities": []\n },\n
"entities": [\n {\n "start": 0,\n
}\n ]\n },\n
"entities": [\n "entity":
"intent": "entities": [\n {\n "start": 0,\n
{\n "text": "3",\n
{\n "start": 0,\n
"number"\n }\n
"yes_eligibility_rating",\n
"end": 1,\n "value": "4",\n "entity": "number"\n
"intent": "yes_eligibility_rating",\n
"end": 1,\n },\n {\n
"value": "3",\n "text": "4",\n
]\n
"intent": "yes_eligibility_rating",\n
"end": 1,\n ]\n },\n {\n
"value": "5",\n "text": "No",\n
{\n "text": "no , i have not",\n "intent": "eli_no_response",\n "entities": []\n },\n {\n "text": "i have been working for 1 year",\n "intent":
"years_eligibility_response",\n
been working for 4 months",\n
"entities": []\n },\n {\n
"years_eligibility_response",\n
"end": 7,\n "value": "2 years",\n "entity": "experience"\n }\n ] \n },\n {\n "text": "4 months",\n "intent": "years_eligibility_response", \n "entities": [\n {\n "start": 0,\n "end": 8,\n "value": "4 months",\n "entity": "experience"\n }\n ]\n },\n {\n
"text": "1 day",\n "intent": "years_eligibility_response",\n "entities": [\n
},\n {\n "text": "No , I haven,t
"entities": []\n },\n {\n "text": "i have "intent": "years_eligibility_response",\n
"text": "2 years",\n "intent":
"entities": [\n {\n "start": 0,\n
{\n "start": 0,\n
"experience"\n }\n
to work from anywhere ?",\n
[]\n },\n {\n "text": "How does work anywhere helps?",\n "intent": "advantages_response",\n "entities": []\n },\n {\n "text": "How does work anywhere helps?",\n "intent": "advantages_response",\n "entities": [] \n },\n {\n "text": "Why work anywhere?",\n "intent": "advantages_response",\n "entities": []\n },\n {\n "text": "Benefits of
"end": 5,\n "value": "1 day",\n "entity": ]\n },\n {\n "text": "what are the advanatges
"intent": "advantages_response",\n "entities":
work anywhere",\n "intent": "advantages_response",\n
\n {\n "text": "Advantages of work anywhere",\n
"advantages_response",\n "entities": []\n },\n {\n
company",\n "intent": "adv_company_resp",\n "entities": []\n },\n {\n "text": "for company",\n "intent": "adv_company_resp",\n "entities": []
"text": "FOr \n },\n {\n "text": "comapny",\n "intent": "adv_company_resp",\n
"entities": []\n },\n {\n "text": "emplyoee",\n
"adv_empyoee_resp",\n "entities": []\n },\n {\n
\n "intent": "adv_empyoee_resp",\n "entities": []\n },\n {\n "text": "employee",\n "intent": "adv_empyoee_resp",\n "entities": []\n },\n {\n "text": "When can I request for work anywhere?",\n "intent":
"entities": []\n }, "intent":
"intent":
"text": "for emplyoee",

 "apply_before_response",\n "entities": []\n },\n {\n "text": "When can I request?",\n "intent": "apply_before_response",\n "entities": []\n },\n {\n "text": "How many days before can I apply for work anywhere?",\n "intent": "apply_before_response",\n "entities": []\n },\n {\n "text": "Apply work anywhere for tomorrow?",\n "intent": "apply_before_response",\n "entities": []\n },\n {\n "text": "Apply for work anywhere today?",\n "intent": "apply_before_response",\n "entities": []\n },\n {\n "text": "Who will be my approver?",\n "intent": "Approval_response",\n "entities": []\n },\n {\n "text": "Who will approve the work anywhere?",\n
"intent": "Approval_response",\n "entities": []\n },\n {\n "text": "How to submit the work anywhere request?",\n "intent": "Approval_response",\n "entities": []\n },\n {\n "text": "To whom should I submit the work anywhere request?",\n "intent": "Approval_response",\n "entities": []\n }, \n {\n "text": "Who is the final authority to approve the work anywhere?",\n "intent": "Approval_response",\n "entities": []\n },\n {\n "text": "What I need to do before work anywhere?",\n "intent": "Arrangements_response",\n
"entities": []\n },\n {\n
before work anywhere?",\n
"entities": []\n },\n {\n
work anywhere?",\n "intent": "Arrangements_response",\n
\n },\n {\n "text": "Who will take care of the costs?",\n "bussiness_equipments_response",\n "entities": []\n },\n
"Does the company provide an internet connection for work anywhere?",\n "intent": "bussiness_equipments_response",\n "entities": []\n },\n {\n "text": "Does the company provide a laptop for work anywhere?",\n "intent":
"bussiness_equipments_response",\n "entities": []\n },\n {\n
"Does the company provide business equipment for work anywhere?",\n "intent": "bussiness_equipments_response",\n "entities": []\n },\n {\n "text": "show me a button",\n "intent": "button_response",\n "entities": [] \n },\n {\n "text": "button",\n "intent": "button_response",\n
"text": "What arrangements should be made "intent": "Arrangements_response",\n
"text": "What arrangements should be made for "entities": []
"entities": []\n },\n
\n "entities": []\n
"bye_response",\n
"bye_response",\n
conditions to apply for work remotely?",\n
"entities": []\n },\n {\n "text": "What are the conditions to apply for work from home?",\n "intent": "conditions_response",\n "entities": []\n },\n {\n "text": "What are the conditions to apply for work anywhere?",\n
"intent": "conditions_response",\n "entities": []\n },\n {\n "text": "Confirmation for work anywhere request?",\n "intent": "confirm_response",\n "entities": []\n },\n {\n "text": "How can I confirm the work anywhere?",\n "intent": "confirm_response",\n "entities": []\n },\n {\n "text": "How will employee reached during office time",\n "intent": "contact_response",\n
{\n "text": "okay bye",\n "intent": "bye_response",
},\n {\n "entities": []\n "entities": []\n
"text": "Good Bye",\n "intent":
},\n {\n "text": "Bye",\n "intent": },\n {\n "text": "What are the
"intent": "conditions_response",\n
"intent":
{\n "text":
"text":

 "entities": []\n },\n {\n "text": "When will be employee contacted in work anywhere",\n "intent": "contact_response",\n "entities": []\n },\n {\n "text": "You are beautiful",\n "intent": "cute_response",\n "entities": []
\n },\n {\n
"entities": []\n
anywhere?",\n
"text": "How many days allowed for work from home?",\n "intent": "days_allowed",\n "entities": []\n },\n {\n "text": "How long can I take work anywhere?",\n "intent": "days_allowed",\n "entities": []\n },\n {\n "text": "will you marry me",\n "intent": "funny_love_response",\n "entities":
"text": "You are cute",\n "intent": "cute_response",\n },\n {\n "text": "How many days can I take work
"intent": "days_allowed",\n "entities": []\n },\n {\n
[]\n },\n {\n
"entities": []\n
anywhere?",\n
"text": "Important notes for the work anywhere?",\n
"important_notes",\n "entities": []\n },\n {\n
meetings?",\n "intent": "meetings_response",\n
"text": "Does meetings can be postponed while in work anywhere?",\n "intent": "meetings_response",\n "entities": []\n },\n {\n "text": "How can I call you?",\n "intent": "name_response",\n "entities": []\n },\n {\n
"text": "i love you",\n "intent": "funny_love_response",\n },\n {\n "text": "What are all important for work
"intent": "important_notes",\n
"entities": []\n },\n {\n "intent":
"text": "May I know your name?",\n "intent": "name_response",\n
"entities":
[]\n },\n {\n "text": "What is your name?",\n
"name_response",\n "entities": []\n },\n {\n
"intent": "okay_response",\n "entities": []\n },\n
you",\n "intent": "okay_response",\n "entities": []\n },\n {\n "text": "okay ., thank you",\n "intent": "okay_response",\n "entities": []\n },\n
{\n "text": "Show me a URL",\n
\n },\n {\n
\n },\n {\n
\n },\n {\n
"withdrawn_repsonse",\n "entities": []\n },\n {\n "text": "can i cancel work anywhere",\n "intent": "withdrawn_repsonse",\n "entities": []\n },\n
"intent": "url_reponse",\n "intent": "url_reponse",\n "intent": "url_reponse",\n
"entities": [] "entities": [] "entities": []
"text": "url",\n
"text": "url",\n
"text": "can i withdrawn work anywhere ?",\n
"intent":
"text": "When it will be withdrawn?",\n "intent": "withdrawn_repsonse", "entities": []\n },\n {\n "text": "Can work anywhere be canceled?",
{\n
\n
\n
"text": "may i know about work anywhere ?",\n "intent": "work_anywhere_response",\n "entities": []\n },\n {\n
work anywhere",\n "intent": "work_anywhere_response",\n
\n },\n {\n "text": "let me know about work anywhere",\n "work_anywhere_response",\n "entities": []\n },\n {\n
work anywhere?",\n "intent": "work_anywhere_response",\n
\n },\n {\n "text": "why work anywhere for the company?",\n "intent": "work_anywhere_company_response",\n "entities": []\n },\n {\n "text": "How does work anywhere helps the company?",\n "intent":
"intent": "withdrawn_repsonse",\n "entities": []\n
},\n
{\n
"text": "Can I cancel the "entities": []\n },\n {\n
"intent":
"text": "okay",\n
{\n "text": "thank
"text": "what is "entities": [] "intent":
"text": "What is "entities": []

 "work_anywhere_company_response",\n "entities": []\n
"how work anywhere is good for employee",\n "intent": "work_anywhere_employee_response",\n "entities": []\n
"text": "How does work anywhere helps the employee?",\n "intent":
"work_anywhere_employee_response",\n "entities": []\n
"text": "show me a video",\n "intent": "video_response",\n
\n },\n {\n "text": "video",\n "intent": "video_response",\n "entities": []\n },\n {\n "text": "video file",\n "intent":
"video_response",\n
"entity_synonyms": [\n {\n "value": "2 years",\n "synonyms": [\n "2
"entities": []\n }\n ],\n "regex_features": [],\n
]\n }\n}' },
year"\n
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
project=FWD&model=default_c4f4dc61-5cdc-5a46-2ba0-3ae5d730a9d8 HTTP/ 1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x- yml\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 16649\r\nHost: rasa: 5000\r\nConnection: close\r\n\r\n',
]\n }\n
| request:
| ClientRequest {
| domain: null,
| _events: [Object],
| _eventsCount: 6,
| _maxListeners: undefined,
| output: [],
| outputEncodings: [],
| outputCallbacks: [],
| outputSize: 0,
| writable: true,
| _last: true,
| chunkedEncoding: false,
| shouldKeepAlive: false,
| useChunkedEncodingByDefault: true, | sendDate: false,
| _removedConnection: false,
| _removedContLen: false,
| _removedTE: false,
| _contentLength: null,
| _hasBody: true,
| _trailer: '',
| finished: true,
| _headerSent: true,
| socket: [Socket],
| connection: [Socket],
| _header:
| 'POST /train?
},\n {\n "text":
},\n {\n
},\n {\n "entities": []

 api_1
api_1
api_1
api_1
api_1
api_1
api_1 project=FWD&model=default_c4f4dc61-5cdc-5a46-2ba0-3ae5d730a9d8',
| _onPendingData: [Function: noopPendingOutput], | agent: [Agent],
| socketPath: undefined,
| timeout: undefined,
| method: 'POST', | path:
| '/train?
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
api_1
"intent_featurizer_count_vectors"\n - \n name: "intent_classifier_tensorflow_embedding"\n intent_tokenization_flag: true\n intent_split_symbol: "+__+"\n - \n name: "nlp_spacy"\n - \n name: "tokenizer_spacy"\n - \n name: "ner_crf"\n - \n name: "ner_synonyms"\n - \n name: "ner_spacy"\n data: {\n "rasa_nlu_data": {\n "common_examples": [\n {\n "text": "hi",\n "intent": "Green",\n "entities": []\n },\n {\n
| _ended: true,
| res: [IncomingMessage],
| aborted: undefined,
| timeoutCb: null,
| upgradeOrConnect: false,
| parser: null,
| maxHeadersCount: null,
| _redirectable: [Writable],
| [Symbol(isCorked)]: false,
| [Symbol(outHeadersKey)]: [Object] },
| response:
| { status: 403,
| statusText: 'Forbidden',
| headers: [Object],
| config: [Object],
| request: [ClientRequest],
| data: [Object] } },
| message: null }
| { error:
| { isHandled: true,
| statusCode: 500,
| message: 'Request failed with status code 403' },
| message: null }
| '---\n language: "en"\n pipeline: \n - \n name:
"text": "heya",\n "intent": "Green",\n "entities": []\n },\n {\n
"hey",\n "intent": "Green",\n "entities": []\n },\n {\n going to say hi",\n "intent": "Green",\n "entities": []\n "text": "howdy",\n "intent": "Green",\n "entities": []\n "text": "hey there",\n
},\n },\n
"text": "text": "just
{\n {\n

 
![Screen Shot 2019-08-13 at 12 42 38 PM](https://user-images.githubusercontent.com/53073434/62922701-a96bc800-bdc9-11e9-8147-9d384e9103eb.png)
![Screen Shot 2019-08-13 at 12 42 38 PM](https://user-images.githubusercontent.com/53073434/62922715-b25c9980-bdc9-11e9-976f-6753369b6a1c.png)

**Comment by wrathagom** [comment]
Yikes, can you try to export your agent and upload it here. It looks like something has happened with the training data, but I have no idea what.

**Comment by dcalvom** [comment]
Closed due to inactivy. Please re-open in case you need help.
