### ISSUE TITLE
The agent is not being saved when the browser window is narrowed 

### ISSUE THREAD

**Issue by dakavisa** [samtecspg/articulate#857]
Happened in chrome, when the "save button" switch to a floppy disk

<img width="733" alt="Screen Shot 2019-08-13 at 10 15 00 AM" src="https://user-images.githubusercontent.com/53984674/62958101-45d6a000-bdb3-11e9-8c9a-3d129863f2ed.png">

After selecting it, it get stucked in a blank create page

**Comment by wrathagom** [comment]
@RussellSPG can you try to reproduce this one?

@dcalvom FYI.

**Comment by RussellSPG** [comment]
ok

**Comment by mordebip** [comment]
Yes i was able to reproduce on the actual master branch and this was the error (the agent got saved but the page stayed white)

<img width="1465" alt="Capture d’écran 2019-08-16 à 03 13 31" src="https://user-images.githubusercontent.com/4228370/63138872-ee634a80-bfd3-11e9-9de4-914f7a2b1dba.png">

**Comment by dakavisa** [comment]
Closed by 820eddda9cf7edeaea517b421ca18a5329519364
