### ISSUE TITLE
Save and Exit modal is showing in the agent despite no changes

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#858]
The behavior of the save and exit modal is being erratic on agent page. It would be good to check the behavior in other screens too.

**Comment by wrathagom** [comment]
@RussellSPG can you walk through each page that has a save/exit button and make sure the modal pops up when you try to close without saving, but only when there are actual changes on the page and vice versa?

**Comment by RussellSPG** [comment]
sure thing

**Comment by RussellSPG** [comment]
looks good for 27.2, but I'll test for the newer releases. Which release did this happen on?

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/2d16f45521032a1896d2b8f8df008526fe6cfa33
