### ISSUE TITLE
Better font color for highlighted keywords

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#859]
As a keyword could take different colors it would good to use the same library that we are using for buttons in the chat panel to pick between black and white for the font color depending on the background.

**Comment by wrathagom** [comment]
We have this same problem with cheat sheet colors too right?

@broham89 can you research or do you know how to choose high contrast font automatically from background colors?

**Comment by dcalvom** [comment]
Yep @wrathagon, we are using Arty color temporally. I'm using a library for picking between black and white, but there are others for high contrast combinations

**Comment by broham89** [comment]
Have the colors always light pastel colors with the standard dark font. 
![pastel-colors-hex-codes-pastel-colors](https://user-images.githubusercontent.com/11262149/63547958-de2afe00-c4f2-11e9-915a-4945d92c59ca.jpg)

**Comment by wrathagom** [comment]
@dcalvom I feel like this has already been addressed?

**Comment by wrathagom** [comment]
I could get any of the keywords to show up in a way that was hard to read.

**Comment by dcalvom** [comment]
Not yet @wrathagom

**Comment by wrathagom** [comment]
I see it now.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/68b8d2f9c51c5960c10ed954896438daaca91889
