### ISSUE TITLE
Rename `helpers-stuff` to `docker-storage` (or note why not)

### ISSUE THREAD

**Issue by milutz** [samtecspg/articulate#86]
`helpers-stuff` directory name doesn't make much sense.  @wrathagom is using `docker-storage` in new projects, so try that out in the 0.5 effort

**Comment by milutz** [comment]
`docker-storage` sucks as a name because it will be in the same dir as `docker-compose.yml` and hence screws with tab-autocomplete

Trying out 'local-storage' instead (@wrathagom cause you any heart-burn?)

**Comment by wrathagom** [comment]
none here.

**Comment by milutz** [comment]
As-of above commits directory is renamed, and the project has been started up, so the change is believed to be working correctly - closing
