### ISSUE TITLE
Extra training data for modifiers

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#860]
I consider that the generation of extra training data for modifiers should be always applied. Currently, we are only training modifiers with the examples the user are giving without generating permutations with the values and synonyms specified by the user.

With this new way, we will improve significantly the recognition of modifiers.

**Comment by wrathagom** [comment]
How is this one different from #596 

I still think it should be a toggle someplace.

**Comment by dcalvom** [comment]
Not at all different. My bad. I will ask @abeban for the best place for the toggle.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/3279902a15602db1096ce53e51ec126d73a8992a
