### ISSUE TITLE
Add a hint to let users know that they need to press enter in text prompts and action responses

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#861]
Currently, users type their text prompts and their responses for slots and actions respectively but, they don't know they have to hit enter to add the text to the list of prompts or responses.

In other places, we are using an enter hint to let users know that they should hit enter. Let us use this hint for these inputs too.

**Comment by dakavisa** [comment]
> Currently, users type their text prompts and their responses for slots and actions respectively but, they don't know they have to hit enter to add the text to the list of prompts or responses.
> 
> In other places, we are using an enter hint to let users know that they should hit enter. Let us use this hint for these inputs too.

@dcalvom could you please point me where do we use this hints for enter so I can have a reference?

**Comment by dcalvom** [comment]
You can check it in the modifiers form

![image](https://user-images.githubusercontent.com/7228045/63533150-77ddb580-c4c9-11e9-8f26-3dcc18f7cd7d.png)

https://github.com/samtecspg/articulate/blob/251ed724f9449e5a5344e9493ed272f9cb8533dc/ui/app/containers/KeywordsEditPage/Components/ModifierForm.js#L338

**Comment by dakavisa** [comment]
Closed by e805b5ff571589499176a0505463b9f6cfe912e4
