### ISSUE TITLE
UI navigation bug between they keywords and the dialogues.

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#862]
On the Latest master branch, after building all the images and executing the docker compose file provided.

After adding multiple keywords, but not enough dialogues. when i start switching back and forth between the the keyword tab and the dialog tab, the page stays blank and i get 

main.1b07817ee1fcf29e405b.chunk.js:1 Uncaught TypeError: Cannot read property 'keywordName' of undefined
    at 26.8de638060e384a76c5b7.chunk.js:1
    at Jo (main.1b07817ee1fcf29e405b.chunk.js:1)
    at Li (main.1b07817ee1fcf29e405b.chunk.js:1)
    at Ga (main.1b07817ee1fcf29e405b.chunk.js:1)
    at Va (main.1b07817ee1fcf29e405b.chunk.js:1)
    at _s (main.1b07817ee1fcf29e405b.chunk.js:1)
    at Ps (main.1b07817ee1fcf29e405b.chunk.js:1)
    at Ns (main.1b07817ee1fcf29e405b.chunk.js:1)
    at kn (main.1b07817ee1fcf29e405b.chunk.js:1)
(anonymous) @ 26.8de638060e384a76c5b7.chunk.js:1
Jo @ main.1b07817ee1fcf29e405b.chunk.js:1
Li @ main.1b07817ee1fcf29e405b.chunk.js:1
Ga @ main.1b07817ee1fcf29e405b.chunk.js:1
Va @ main.1b07817ee1fcf29e405b.chunk.js:1
_s @ main.1b07817ee1fcf29e405b.chunk.js:1
Ps @ main.1b07817ee1fcf29e405b.chunk.js:1
Ns @ main.1b07817ee1fcf29e405b.chunk.js:1
kn @ main.1b07817ee1fcf29e405b.chunk.js:1

**Comment by mordebip** [comment]
If i switch up the number of shown elements on the keywords tab in order to avoid having a second page, the error does not happen.
if i switch to the last page of the keyword list then switch tabs, the error does not happen.

**Comment by mordebip** [comment]
Happens also on Firefox 

TypeError: "p is undefined"
    q http://144.76.79.152:18080/26.8de638060e384a76c5b7.chunk.js:1
    Jo http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1
    Li http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1
    Ga http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1
    Va http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1
    _s http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1
    Ps http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1
    Ns http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1
    kn http://144.76.79.152:18080/main.1b07817ee1fcf29e405b.chunk.js:1

**Comment by dcalvom** [comment]
Thanks for your report @mordebip I will work on this one to get a fix

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/0321cd6a2792af0ef9914c356778b85838bee344
