### ISSUE TITLE
Remove Open Chat button in connections and settings page

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#863]
Given that no agent is being selected for these screens, the Open Chat button shouldn't be shown

**Comment by dakavisa** [comment]
This is ready for testing in 251ed724f9449e5a5344e9493ed272f9cb8533dc

**Comment by mordebip** [comment]
if you open an agent, then you click on the gear at the bottom left (the chat will disapear)
then you click on articulate logo to go back to the agent/connection selection page, the chat will reopen, while this patch was supposed to solve it.

if you are working on an agent, and you go to any tab that is not the "agent:agentName" and you refresh the page, the chat will be hidden, and if you click on the articulate logo, the chat will appear.
