### ISSUE TITLE
Slot using duckling email

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#864]
On articulate master (compiling the docker images and running docker compose for local images)
When creating a simple agent intended to reset a password (agent json attached)

[TestAgent.json.zip](https://github.com/samtecspg/articulate/files/3502879/TestAgent.json.zip)

i got a stranged answer as you can see on the attached screenshots.

Rasa is not able to fill the email slot with only the email, i have to say a sentence before.

<img width="648" alt="Capture d’écran 2019-08-14 à 20 06 43" src="https://user-images.githubusercontent.com/4228370/63048845-3fd5e180-becf-11e9-9730-ab91addc94fe.png">
<img width="293" alt="Capture d’écran 2019-08-14 à 19 51 08" src="https://user-images.githubusercontent.com/4228370/63048846-3fd5e180-becf-11e9-8118-bbf1ed6e45aa.png">

as you can see on the json file, i tried updating rasa settings by adding  
but nothing changed

{
    "name": "ner_duckling_http"
  },

[
  {
    "docId": "txd3kWwBZqdq33IgmwMk",
    "category": "default",
    "project": "TESTAgent",
    "model": "default_e08e0193-c482-f5f1-85b9-8a86cce64dfc",
    "keywords": [
      {
        "start": 0,
        "end": 23,
        "value": {
          "value": "mordebip@articulate.com"
        },
        "confidence": 0.8501236243155543,
        "extractor": "ner_crf",
        "keyword": "Bonjour"
      },
      {
        "end": 23,
        "keyword": "sys.duckling_email",
        "extractor": "duckling",
        "start": 0,
        "value": {
          "value": "mordebip@articulate.com"
        }
      }
    ],
    "action": {
      "name": "",
      "confidence": 0
    },
    "action_ranking": [],
    "elapsed_time_ms": 34,
    "categoryScore": 1
  }
]

**Comment by mordebip** [comment]
The behaviour is close to https://github.com/samtecspg/articulate/issues/551

**Comment by wrathagom** [comment]
Someone will take a look shortly.

**Comment by mordebip** [comment]
Thank you, i might be using it wrong.

**Comment by wrathagom** [comment]
I was able to reproduce this. @dcalvom is looking into it more now.

**Comment by dcalvom** [comment]
Hi @mordebip, please test the fix done in https://github.com/samtecspg/articulate/commit/042136352187f142c6e9783902088195d2eb6f25 and let us know how it works.

This is the test I did:

![image](https://user-images.githubusercontent.com/7228045/63112644-f678a700-bf4d-11e9-850c-9d9c31881e42.png)

**Comment by mordebip** [comment]
Oh yeahhh
Great, this even fixed an other issue where we got back the two answers that needed the email to be provided
