### ISSUE TITLE
not all routes redirect to Login page if not logged

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#868]
Rebuilding from the latest master branch and enabling authentication

if i open a link like http://192.168.100.15:8080/agent/1/dialogue?tab=keywords i'm not redirected to the login page (happens when you clear the cache and try to refresh)

the redirection works without the "?tab=keywords"

Ps : When it happens, the page stays empty with the loading animation, the console show the usual Uncaught (in promise) Error: Missing authentication

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/4ab44886ec30646824da0c33ea4f28e558eb65f5
