### ISSUE TITLE
Intents list's columns should be resized

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#87]
The columns on this list should be resized such that intents column is narrower--to make more space to display examples.

**Comment by wrathagom** [comment]
It's not supposed to display the examples in the first place :) unless you like it. It was originally intended to be a count. #56 

![intents-page](https://user-images.githubusercontent.com/1779894/35681009-0deb125c-072a-11e8-9d44-528c71b2b571.png)

**Comment by wrathagom** [comment]
This was somewhat addressed by changing list to count.
