### ISSUE TITLE
(Or Slots) having at least one slot addressed

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#882]
### Feature Request
At some point in the flows of a chatbot, we would need a user to provide at least one slot of multiple ones, for example a user that needs to reset his password will be asked to provide an email, a phone number or a username. we could put it that way on a single obligatory slot, but it will not allow us to use the duckling processing.
the most logical part is to have some way to do something like 
if (slot1.isnotempty() or slot2.isnotempty() or slot3.isnotempty())

i think it can be managed by the handlebars {{}}. 

Could maybe be merged with https://github.com/samtecspg/articulate/issues/744. in that case, we could just go with prompts over non required fields and then manage the values with handlebars.

**Comment by wrathagom** [comment]
You could already do this with action chaining, but it would be a bit of a hack. Essentially have multiple actions, each action collecting one piece and then a final action that used all of them.

@dcalvom we had this working at one point where if you had overlapping system keywords that it filled the first one. Then the next time it filled the second one, didn't we?

**Comment by mordebip** [comment]
oh yeah that's clever, i will give it a try 
thank you

**Comment by wrathagom** [comment]
please report back if you get it working or if another problem comes up as I am curious how well it works.

**Comment by mordebip** [comment]
I was not able to figure out a way to make it work.

What i want to achieve is something like:

- i forgot my password, can you help me ?
- Please provide your email or your phone number to retrieve your account
- (providing the email or the phone number and relying on ducking to check the validity of the email or the phone number)
- (answer related to the email or the phone provided)

**Comment by dcalvom** [comment]
I can think of an immediate solution for this with Articulate tools. I would do something like this:

![image](https://user-images.githubusercontent.com/7228045/63644863-56d6b980-c6af-11e9-845d-581ab4c51a8c.png)

This is my test agent:

[Account Helper.json.zip](https://github.com/samtecspg/articulate/files/3537793/Account.Helper.json.zip)

**Comment by mordebip** [comment]
Yeah that's a trick that work.
Thank you for the help

**Comment by wrathagom** [comment]
The latest release has some changes related to import/exports and keywords. Hopefully that last issue is addressed there.

**Comment by mordebip** [comment]
Got an idea that might work.
Having a statement that will require a phone or email slot.
On the answer, if one element have been filled, we can proceed, if not, we can give an answer saying that we need an email of phone number, then loop over (idk if it will non-stop loop, or if it will work)
Will test that next week.
