### ISSUE TITLE
Screen Goes blank, Missing keywords and actions

### ISSUE THREAD

**Issue by skylacking004** [samtecspg/articulate#891]
Hi I'm using articulate-v0.29.0
It is running on a VM on Google compute engine. 
I'm using chrome. 

When using Articulate after a while the entire screen goes blank. It is very similar to the issue here:
https://github.com/samtecspg/articulate/issues/764

To get articulate working again I use the command:  docker-compose restart

The issue is when articulate is back up and running, it is missing all of the Keywords, actions. The Sayings are still there. But, it is missing the keywords. 

Im not sure what is causing the issue of the page going blank.

**Comment by wrathagom** [comment]
Are there any errors in the browser console? Or how about the terminal? What’s is the result of `docker-compose ps`?

**Comment by skylacking004** [comment]
HI yes, the only error I see is 
Browserslist: caniuse-lite is outdated. Please run next command yarn upgrade caniuse-lite browserslist

**Comment by dcalvom** [comment]
Hi @skylacking004 is there any way to reproduce this issue step by step or it is just random?

**Comment by skylacking004** [comment]
@dcalvom 
Details:

Deploy on compute engine instance 

Image: ubuntu-1604-xenial-v20190816
Specs: n1-standard-4 (4 vCPUs, 15 GB memory)

Everything runs fine at first. The overtime it just goes blank. When I run docker-compose restart everything works again (I don’t think it’s deleting keywords the first time may have been a fluke?).

**Comment by wrathagom** [comment]
@skylacking004 did this happen on your first start-up of Articulate, or had you up'd and down'd it multiple times?

**Comment by skylacking004** [comment]
@wrathagom It started happening maybe an hour after the first startup. After using it for a while, adding saying, keywords etc.

**Comment by dakavisa** [comment]
Hi @skylacking004, is there any additional details you could give us like disk space of the VM? Or maybe if there was a specific action that triggers this or just randomly happened? An screenshot of the console maybe?

**Comment by wrathagom** [comment]
Closed due to inactivity.
