### ISSUE TITLE
Unable to connect with chat widget

### ISSUE THREAD

**Issue by RakibulAsheeque** [samtecspg/articulate#892]
### Issues
I am unable to connect my chat widget with the Articulate agent. I created a connection in articulate and gave the socket path and socket url in the chat widget [[**mrbot-ai/rasa-webchat**]](https://github.com/mrbot-ai/rasa-webchat), but the connection fails while trying to run the code in my machine.
- Did you download a release or pull from Master? Which release?
version 0.29
- What operating system are you running?
Debian 9
- Are you running locally or in the cloud?
Cloud
- Which browser are you using?
Chrome

**Comment by wrathagom** [comment]
Both of your issues are likely related. Do you have any sort of auth on your cloud instance, either basic auth through Nginx or the auth that comes with Articulate?

Also, are there any errors in the browser console or terminal that is running docker. What is the output of `docker-compose logs api`

**Comment by RakibulAsheeque** [comment]
No, I have not used any auth on my cloud instance.

I have not checked the logs yet.

**Comment by RakibulAsheeque** [comment]
The output of `docker-compose logs api`

```bash
Attaching to articulate_api_1_b60d93836063
api_1_b60d93836063 | 2019/08/30 14:39:55 Waiting for: http://elasticsearch:9200
api_1_b60d93836063 | 2019/08/30 14:39:55 Received 200 from http://elasticsearch:9200
api_1_b60d93836063 |
api_1_b60d93836063 | > articulate@0.28.2 start /usr/src/app
api_1_b60d93836063 | > cross-env NODE_ENV=development env-cmd server/.env nodemon server --exec babel-node
api_1_b60d93836063 |
api_1_b60d93836063 | [nodemon] 1.19.1
api_1_b60d93836063 | [nodemon] reading config ./package.json
api_1_b60d93836063 | [nodemon] to restart at any time, enter `rs`
api_1_b60d93836063 | [nodemon] or send SIGHUP to 53 to restart
api_1_b60d93836063 | [nodemon] ignoring: ./node_modules/**/*
api_1_b60d93836063 | [nodemon] watching: *.*
api_1_b60d93836063 | [nodemon] watching extensions: js,mjs,json
api_1_b60d93836063 | [nodemon] starting `babel-node server`
api_1_b60d93836063 | [nodemon] spawning
api_1_b60d93836063 | [nodemon] child pid: 66
api_1_b60d93836063 | [nodemon] watching 460 files
api_1_b60d93836063 | Debug: handler, error
api_1_b60d93836063 |     Error: Not Found
api_1_b60d93836063 |     at internals.notFound (/usr/src/app/node_modules/hapi/lib/core.js:618:16)
api_1_b60d93836063 |     at module.exports.internals.Manager.execute (/usr/src/app/node_modules/hapi/lib/toolkit.js:35:106)
api_1_b60d93836063 |     at Object.internals.handler (/usr/src/app/node_modules/hapi/lib/handler.js:50:48)
api_1_b60d93836063 |     at exports.execute (/usr/src/app/node_modules/hapi/lib/handler.js:35:36)
api_1_b60d93836063 |     at Request._lifecycle (/usr/src/app/node_modules/hapi/lib/request.js:263:62)
api_1_b60d93836063 |     at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by dcalvom** [comment]
How did you configured you chat widget?

**Comment by RakibulAsheeque** [comment]
I gave the Socket URL and Socket path from Articulate in the chat widget.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/9c3b1f6958d8d5dcb3c153b9ded73cddc6c56f52
