### ISSUE TITLE
The web-demo is not giving any responses

### ISSUE THREAD

**Issue by RakibulAsheeque** [samtecspg/articulate#893]
### Issues
I created a connection for web-demo in Articulate but it's not giving any output, instead it giving out an error. I have attached the screenshot of the error herewith.
![image](https://user-images.githubusercontent.com/39805510/64016313-45c0f900-cb44-11e9-837f-6565128a46e6.png)

- Did you download a release or pull from Master? Which release?
version 0.29
- What operating system are you running?
Debian 9
- Are you running locally or in the cloud?
Cloud
- Which browser are you using?
Chrome

**Comment by wrathagom** [comment]
Both of your issues are likely related. Do you have any sort of auth on your cloud instance, either basic auth through Nginx or the auth that comes with Articulate?

Also, are there any errors in the browser console or terminal that is running docker. What is the output of `docker-compose logs api`

**Comment by RakibulAsheeque** [comment]
No, I have not used any auth on my cloud instance.

The `docker-compose logs api` gives a 404(Not Found) error message.

 I don't have the logs at the moment, I will share them with you later.

**Comment by wrathagom** [comment]
can we get the complete 404 error? I was able to reproduce similar behavior, so we're looking into things as well.

**Comment by RakibulAsheeque** [comment]
The output of `docker-compose logs api`

```bash
Attaching to articulate_api_1_21d6b176578e
api_1_21d6b176578e | 2019/08/30 14:45:53 Waiting for: http://elasticsearch:9200
api_1_21d6b176578e | 2019/08/30 14:45:53 Received 200 from http://elasticsearch:9200
api_1_21d6b176578e |
api_1_21d6b176578e | > articulate@0.28.2 start /usr/src/app
api_1_21d6b176578e | > cross-env NODE_ENV=development env-cmd server/.env nodemon server --exec babel-node
api_1_21d6b176578e |
api_1_21d6b176578e | [nodemon] 1.19.1
api_1_21d6b176578e | [nodemon] reading config ./package.json
api_1_21d6b176578e | [nodemon] to restart at any time, enter `rs`
api_1_21d6b176578e | [nodemon] or send SIGHUP to 51 to restart
api_1_21d6b176578e | [nodemon] ignoring: ./node_modules/**/*
api_1_21d6b176578e | [nodemon] watching: *.*
api_1_21d6b176578e | [nodemon] watching extensions: js,mjs,json
api_1_21d6b176578e | [nodemon] starting `babel-node server`
api_1_21d6b176578e | [nodemon] spawning
api_1_21d6b176578e | [nodemon] child pid: 64
api_1_21d6b176578e | [nodemon] watching 460 files
api_1_21d6b176578e | Debug: handler, error
api_1_21d6b176578e |     Error: response is not defined
api_1_21d6b176578e |     at Object.<anonymous> (/usr/src/app/lib/channels/web-demo/post.js:33:14)
api_1_21d6b176578e |     at Generator.next (<anonymous>)
api_1_21d6b176578e |     at asyncGeneratorStep (/usr/src/app/lib/channels/web-demo/post.js:7:103)
api_1_21d6b176578e |     at _next (/usr/src/app/lib/channels/web-demo/post.js:9:194)
api_1_21d6b176578e |     at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by RakibulAsheeque** [comment]
So, the 404(Not Found) error is only when I try to connect the chat-widget.

The web-demo error is quite different.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/9c3b1f6958d8d5dcb3c153b9ded73cddc6c56f52
