### ISSUE TITLE
showing multiple entries where it says "5" deleting saying

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#897]
Please describe the issue you are having here and answer the question below.

This same issue seems to come back.. This happens when:

1. entering a saying with an action already selected in display box. In this case, the "get order" action was pre selected.
2. entering the saying
3. hiting the trash icon. 

Will then display 10 sayings showing "entires" is 5. Hiting the next button brings screen back to normal. 
Reproduced with same results.
![image](https://user-images.githubusercontent.com/42249324/64190045-7e621a80-ce43-11e9-91b8-64354899e460.png)

- Did you download a release or pull from Master? Which release?
29.0
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by dakavisa** [comment]
Closed by 752775c6fdf604f20cc1d0dae153573021646a74
