### ISSUE TITLE
Enable navigation links in Domains, Intent, Entities lists

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#90]
It would make navigation so much easier if within each table/list you can click on the item in the list to navigate to see the details of that item.

Examples:

- [x] Domain list: clicking on domain name navigates to Domain Intents list view
- [x] Domtain Intents: clicking on the intent navigates to intent create/edit view
- [x] Entity list: clicking on a "used-in" intent navigates to the intent/create/edit view

**Comment by wrathagom** [comment]
I removed this form 0.6 because I need the question answered on #89 first. Maybe a mock-up from @broham89 of what that would look like.
