### ISSUE TITLE
Free text slots / keyword

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#900]
### Feature Request

In many cases, free text slots seem to be a need in order to allow users to fill things like descriptions, messages, titles or many other things.

What is needed in order to properly implement this free text slots / keywords:

- That it should prompt
- It should recognize line breaks
- The keyword should be a system-defined keyword
- IMO this slot/keyword shouldn't be filled unless an action will use it, like if the agent enter in a listen mode after the slot prompted.

@dakavisa @wrathagom please leave your comments

**Comment by wrathagom** [comment]
@dcalvom I am thinking a few different things:

- What if this isn't a keyword at all, but rather some toggle to grab all text after prompt?
- Agreed to your last point, this is a very special case. If we prompted for this type of request, whatever comes next from the user gets captured.

Here's a sample screen if we didn't make it a keyword:
![image](https://user-images.githubusercontent.com/1779894/64394577-d1df8e80-d024-11e9-8ca5-6213d465ba19.png)


If we did it this way, then selecting free text would:
- disable slot memory
- force the slot to be required
- not allow it to be a list
- disable prompt limits

**Comment by dakavisa** [comment]
@wrathagom @dcalvom I was wondering why is it necessary to disable slot memory on free text slots, consider the following scenario:

User: -Post an issue
Bot: -Give me the title
User: -Problem with paging on sayings page
Bot: -Give me the description
User: -Paging fails every x deletes
Bot -OK done

When calling the required API, that action needs to have in memory both issue and title free text slots right?

**Comment by wrathagom** [comment]
Nope, that’s not what memory is. Your example would just be two slots on the same action.

Memory is when you want it to work for the next action or the nth action.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/2d18decb1894f1ef29682243ab466a44adcdfb83
