### ISSUE TITLE
Save icon on agent appears when something is entered in discription but other parameters blank.

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#905]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

The Save icon for creating a new agent I believe should appear after all the parameters are entered. As of now, it appears when just a description is entered, and others are blank

![image](https://user-images.githubusercontent.com/42249324/64743970-f083d080-d4cf-11e9-88ed-dc716b401999.png)

Please describe the issue you are having here and answer the question below.
release 29.0
- Did you download a release or pull from Master? Which release?
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by dcalvom** [comment]
This is the expected behavior. We designed that way.
