### ISSUE TITLE
Update Elasticsearch version to match filebeat

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#906]
This isn't critical and everything is working, but we should pull the ES version forward.

**Comment by mordebip** [comment]
Maybe we should also secure ES with a password, got an intrusion on my test server as i forgot to remove the mapping, wasn't funny 

found an xmrih-2.99.0.0-beta "REDIS0006 virus"

**Comment by dakavisa** [comment]
Closed by 02a50530a911c92f8cea5a167a0cb167bef2b9b7
