### ISSUE TITLE
Add Logs tab under Review

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#907]
The idea being that this tab shows the logs being stored by Elasticsearch, I think it needs:

- pagination, or if it's scrolling the ability to load in more automatically when we reach the bottom of the loaded logs.
- service filter (api, ui, redis, duckling, nginx, rasa) I see these as being toggle buttons.
- Either a refresh button or a refresh interval. If we have a refresh interval then we'll have to manage what happens when the user is no longer on the front page.

**Comment by mordebip** [comment]
Does the logs include the user that made a modification ?

**Comment by wrathagom** [comment]
These aren't those kind of logs. These are the system logs from the Docker containers.

At the moment we are not tracking which user made each change, certainly could be a future feature requests.

**Comment by dakavisa** [comment]
Closed and ready for testing with 2dd6cfac9127cf93b8ec79296fbd1716de6a7d21
