### ISSUE TITLE
ReferenceError: recognizedKeywords is not defined

### ISSUE THREAD

**Issue by Unbekannter** [samtecspg/articulate#909]
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) 
v0.29.0 Release
running locally

Iam trying to get an answer on: Hello Iam Jan
And rasa should answer: Hello Jan
So i have created a custom keyword with regex matcher: (?<=Hello Iam).*
The system matches users name successfully but throws an error on my console and no response is given.

![Screenshot from 2019-09-14 11-10-23](https://user-images.githubusercontent.com/13185672/64910001-5646a700-d6e0-11e9-9147-fd743725e8ed.png)

{ error:
api_1            |    ReferenceError: recognizedKeywords is not defined
api_1            |        at recognizedKeywords (/usr/src/app/lib/services/agent/agent.converse-fill-action-slots.service.js:278:63)
api_1            |        at Array.forEach (<anonymous>)
api_1            |        at AgentService.forEach (/usr/src/app/lib/services/agent/agent.converse-fill-action-slots.service.js:205:32)
api_1            |        at Generator.next (<anonymous>)
api_1            |        at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.converse-fill-action-slots.service.js:9:103)
api_1            |        at _next (/usr/src/app/lib/services/agent/agent.converse-fill-action-slots.service.js:11:194)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
api_1            | Debug: handler, error 
api_1            |     Error: recognizedKeywords is not defined
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dcalvom** [comment]
We fixed these one, but is in master. Haven't been released
