### ISSUE TITLE
Transparency bug in "Test your agent here" panel

### ISSUE THREAD

**Issue by ewoo** [samtecspg/articulate#91]
In Chrome, with a tall vertical view, the transparency in the "Test your agent here" panel is not rendered correctly. When you reduce the height of the browser, it corrects itself.

![image 2018-02-01 at 8 41 53 am](https://user-images.githubusercontent.com/278197/35681656-196f7c7e-072c-11e8-9a22-f62ac8068c01.png)

**Comment by wrathagom** [comment]
Closed in favor of #65
