### ISSUE TITLE
Clearing the auth cookie after resetting the project

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#911]
On the master branch, with authentication enabled.

You log in (sometime you have to try to login multiple times and refresh to login)
if you delete the database and refresh, the ui will stay on a loading state (trying to reconnect, having a cookie but not the right one to access)

**Comment by wrathagom** [comment]
This seems like a deployment issue more than anything Articulate should be worrying about. Also since we're talking about clearing client side data I don't know if there is a nice way to do this.

**Comment by mordebip** [comment]
Will keep an eye on it, because i think it's related to the log-in issues that happens from time to time.
