### ISSUE TITLE
[Feature] Delete review saying/session

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#912]
Add a button allowing to delete a saying or a full session on the review tab, in case of someone who said something inappropriate.

**Comment by dcalvom** [comment]
I'm not sure about this unless you are thinking on sensible data, docs shouldn't be deleted.

**Comment by mordebip** [comment]
Yes i was thinking about that.
At some point, some users will mistakenly type their card number on the chat, and you will need to delete that.

**Comment by wrathagom** [comment]
Makes sense to me. Though review is directly tied to analytics so deleting one would impact the other.

**Comment by mordebip** [comment]
Agree with you on that, so maybe a way to edit it could help, by removing only the sensitive part.
imo, it could be more a user choice to either remove a saying/session and get the stats affected, or edit the sayings to keep the stats.

**Comment by wrathagom** [comment]
I think we should just add delete buttons to the session and review page. We'll prompt with a "Deleting this _____ will impact analytics and can not be reversed." type message.

**Comment by dakavisa** [comment]
Closed by 6fb1d140baee3dd430adbdcac56ec5cb0d397391
