### ISSUE TITLE
Access json from POST REQUESTS in response by handlebars

### ISSUE THREAD

**Issue by Unbekannter** [samtecspg/articulate#913]
It is possible to access the json data from the POST-Requests directly in my response, which i sent to the API?

For example:
I send something like this to the converse-endpoint:
{
     "text": "Hello Iam Herbert",
     "user_id": "32183"
}

It is possible to get the user_id json field by handlebars in my agent response?
Like {{ request.user_id }}

Its possible for the slots, for the webhook response but i want to access the json data, which i send to the api.

**Comment by wrathagom** [comment]
Extra keys that you supply during the post request are available at the top level of the CSO. So if you're incoming request was:

```
{
  "text": "Hello Iam Herbert",
  "user_id": "32183"
}
```

You would access the user_id in responses with `{{user_id}}`
