### ISSUE TITLE
[Feature] logout button

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#914]
adding a Disconnection button in order to test the cookie clearing feature

**Comment by dcalvom** [comment]
you mean logout?

**Comment by mordebip** [comment]
Yes logout :D

**Comment by wrathagom** [comment]
@broham89 in the Articulat interface we need a place to show that the user is logged in and what user they are logged in as. Then naturally a way to log out.

**Comment by broham89** [comment]
![Profile flow](https://user-images.githubusercontent.com/11262149/65379871-6ee12f00-dc95-11e9-9df0-9487e401a4b8.png)

![Profile dropdown](https://user-images.githubusercontent.com/11262149/65379870-6ee12f00-dc95-11e9-839a-337179b19e72.png)

**Comment by wrathagom** [comment]
@broham89 does that upper right hand corner look busy to you? I wonder if we should add language into the user dropdown? Or move language somewhere else on the page? Maybe only on the landing page.

**Comment by broham89** [comment]
I'm guessing the language function isn't used so much, so it would make sense to move it to the landing page. However, Users could expect to find the language inside the settings.

**Comment by wrathagom** [comment]
also, we already have a little person icon in the bottom left hand corner now for user management. Should that me dual purposed for this? Should we add another icon there?

**Comment by broham89** [comment]
Are you talking about this?
<img width="219" alt="Screen Shot 2019-10-24 at 7 54 53 AM" src="https://user-images.githubusercontent.com/11262149/67487467-9ed47700-f633-11e9-9f71-f9ad44b00e51.png">

**Comment by mordebip** [comment]
Oh having a log out button there could be the smart way to do it

**Comment by wrathagom** [comment]
@broham89 yep

**Comment by broham89** [comment]
![User dropdown](https://user-images.githubusercontent.com/11262149/68795720-26038200-0617-11ea-9fbe-cc1ca5c6a00e.png)
![User dropdown - hover](https://user-images.githubusercontent.com/11262149/68795735-2c91f980-0617-11ea-9dc3-f784edd95c0d.png)
![User dropdown - click open](https://user-images.githubusercontent.com/11262149/68795747-33207100-0617-11ea-8401-9f46d265f7b3.png)
![User dropdown - Prompt](https://user-images.githubusercontent.com/11262149/68795755-37e52500-0617-11ea-96c4-bf395b1d11a2.png)

**Comment by wrathagom** [comment]
@broham89 @dcalvom I think I am a fan of moving the user list inside the settings page. this would mean there is just the gear icon and current user button in the bottom left corner. Does that sound like it simplifies things in a good way?

**Comment by broham89** [comment]
Is the user list something that a primary user only uses just to manage edit and delete people? And not really used as much? I just want to know the use case for that so it seems like a primary user would understand it to be located on the settings page.

**Comment by wrathagom** [comment]
I would say most everything under the settings page is for system admins. And the user list is the same. A sys admin may use the user list to create a new user or delete an old user. In the future they may use the user list to change the groups to which the user belongs.

**Comment by dakavisa** [comment]
Closed and ready for testing by 57e462a148fbcdf7188df41549da720182379685
