### ISSUE TITLE
Implement a message that says "keyword values not being used"

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#918]
### Feature Request
I think it would be a good idea, of having a message like "There are values that are not being used" or "There are keyword values not highlighted" after an Agent is trained (shown in conversation window) to make it easier for the user to catch forgetting to highlight some values. This is a useful message especially when there are many different keywords/multi actions etc.

**Comment by wrathagom** [comment]
Well, but if you have generate training data enabled then you may intentionally not be using them. Or you could also have them in the list for synonyms, but not need them in your training data if your model is well generalized.
