### ISSUE TITLE
Statistics dashboard limitations

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#921]
While stress testing articulate, i found a bug on the statistics page, the top action element does not go over 10 000

probably due to the query on /api/agent/1/doc?skip=0&limit=10000&dateRange=now-1d
and we can't really push it higher

`[query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.`

<img width="1019" alt="Capture d’écran 2019-09-20 à 03 12 16" src="https://user-images.githubusercontent.com/4228370/65294100-71d50600-db55-11e9-8779-5356ea351068.png">

Other than that, on the test seen on the screenshot, the file is 42MB, which is a bit heavy and not optimal.

Ps : if it can help, i tried https://www.echartsjs.com/en/index.html once and it gave better results with large data compared to https://www.chartjs.org/ 

Ps2 : I'm not using the latest version for this, so the problem might have been already fixed
To do my stress test, i edit the post.js file to return the agent response, and then make the tests using Jmeter (100 threads)

Ps2 : after letting the stress test running for 15 more minutes, it crashes chrome with a +78MB file

<img width="1537" alt="Capture d’écran 2019-09-20 à 03 42 15" src="https://user-images.githubusercontent.com/4228370/65295287-c463f180-db58-11e9-9238-f2289cf09214.png">

**Comment by wrathagom** [comment]
@dcalvom do I take this to mean that you're just fetching all of the docs and doing client/server side aggregation? I can help if we want to write an ES query that returns pre-aggregated data.

**Comment by dcalvom** [comment]
Yes to the first question.  And regarding  the  pre aggregated  query, that would help us a lot

**Comment by dakavisa** [comment]
Closed by f90a844e6130ba0a881303ed8759772c326625a6
