### ISSUE TITLE
Agent Screen cuts off in main page

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#925]
### Feature Request
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*
Instead of this:
![image](https://user-images.githubusercontent.com/42249324/65516915-df639800-deaf-11e9-9262-4ecde95ae9d4.png)

IMO it would be good headwork to implement a scroll UI to appear once there are multiple agents, because it may not be obvious to the user they just have to scroll.

----

**Comment by wrathagom** [comment]
Fixed in more recent versions.
