### ISSUE TITLE
Add search panel to sayings page

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#926]
Before we were trying to get fancy with Slack like search, but I want to implement a simpler search/filter panel. The one below is for the sayings page. it allows the user to type In something, which will filter the text of the sayings. But the user can also choose a category from the dropdown. I envision the actions being like a word cloud where the user can click on one or more of them.

@broham89 looking for your vision here to improve things.

![image](https://user-images.githubusercontent.com/1779894/65560631-70b52780-df0d-11e9-90ee-ff2142e02f51.png)

**Comment by broham89** [comment]
![Filter flow1](https://user-images.githubusercontent.com/11262149/65630090-4fe6e380-df9a-11e9-876e-74569b52b84f.png)
![Filter flow2](https://user-images.githubusercontent.com/11262149/65630091-4fe6e380-df9a-11e9-9179-2279ef7ddca0.png)
![Filter flow3](https://user-images.githubusercontent.com/11262149/65630092-4fe6e380-df9a-11e9-85de-1f3885573575.png)
![Filter flow4](https://user-images.githubusercontent.com/11262149/65630093-4fe6e380-df9a-11e9-8bef-6168ff290979.png)

**Comment by wrathagom** [comment]
Am I crazy or do icons placed above the list look bad because they add a ton of whitespace to their sides? I was trying to use already existing empty space rather than creating more.

**Comment by broham89** [comment]
![Filter flow1](https://user-images.githubusercontent.com/11262149/65704617-7b2a0b00-e04c-11e9-8253-b37a91a216fa.png)
![Filter flow2](https://user-images.githubusercontent.com/11262149/65704618-7b2a0b00-e04c-11e9-991e-efcccc738b06.png)
![Filter flow3](https://user-images.githubusercontent.com/11262149/65704619-7b2a0b00-e04c-11e9-9bab-e289bf3546e7.png)
![Filter flow4](https://user-images.githubusercontent.com/11262149/65704620-7b2a0b00-e04c-11e9-9ba2-6b71f3e9ab0a.png)
@wrathagom Yup, you're right. However, on the last screen, I have bumped down the User saying list and applied the filter to the container of sayings. Showing this tells the user the filter is applied here(sayings)

But, below imgs i have a different version that compromises what you're looking for. 

![Filter flow4 v 2](https://user-images.githubusercontent.com/11262149/65705518-3d2de680-e04e-11e9-8aed-6dc6df2d2c14.png)
![Filter flow4 v 2 - open filter flap](https://user-images.githubusercontent.com/11262149/65705521-3ef7aa00-e04e-11e9-9a63-0a6d9faa99f4.png)

**Comment by wrathagom** [comment]
Yep, I like the looks of this one:

![](https://user-images.githubusercontent.com/11262149/65705518-3d2de680-e04e-11e9-8aed-6dc6df2d2c14.png)

**Comment by dakavisa** [comment]
First version closed by 8ba03051a943527c5b9c567ff659eb98d68f2a8f
