### ISSUE TITLE
OCI runtime create failed: container_linux.go:345

### ISSUE THREAD

**Issue by Cesarcuna** [samtecspg/articulate#929]
Action: vscode-docker.containers.start
Error type: 400
Error Message: (HTTP code 400) unexpected - OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/c/GitClone/articulate-0.29.0/articulate-0.29.0/local-storage/nginx/nginx-http.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/overlay2/9a4aebc77b4c9fc79a0229b2d3e8e597ea935a11c5c6fe4f5053e94298074b6f/merged\\\" at \\\"/mnt/sda1/var/lib/docker/overlay2/9a4aebc77b4c9fc79a0229b2d3e8e597ea935a11c5c6fe4f5053e94298074b6f/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:157:703034extension.bundle.js:157:703034
extension.bundle.js:157:702997extension.bundle.js:157:702997
module.exports.m.buildPayload extension.bundle.js:157:703007
IncomingMessage.<anonymous> extension.bundle.js:157:702507
IncomingMessage.emit events.js:187:15
endReadableNT _stream_readable.js:1092:12
```

</details>

**Comment by wrathagom** [comment]
Why did you open this issue 3 times?
