### ISSUE TITLE
Dialogue flow  or stories 

### ISSUE THREAD

**Issue by azizullah2017** [samtecspg/articulate#931]
If would story customization that would be great.
I cannot the mood bot flow. but it working on that.

It would be great, I can create my own flow or story.

**Comment by wrathagom** [comment]
We don’ use stories like Rasa does. Other than that I’m not certain what you are after. Articulate supports deep branching dialogue through the use of action chains. Where the response on one action can be chained into anther action. Rasa has their own platform if you want a graphical interface to directly edit stories.

**Comment by azizullah2017** [comment]
Justed wanted to know how to make a flow/story.
I want to implement the below flow in articulate, and I do not know how to do it.
or may I should I ask, is this supported by articulate ?
```
## sad path 1               
* greet
  - utter_greet          
* mood_unhappy
  - utter_cheer_up
  - utter_did_that_help
* mood_affirm
  - utter_happy
```

Does articulate have any forum ???
