### ISSUE TITLE
install without docker

### ISSUE THREAD

**Issue by YairTavizon** [samtecspg/articulate#932]
### Issues
Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
Latest
- What operating system are you running?
Mac OS
- Are you running locally or in the cloud?
Locally
- Which browser are you using?
Chrome
----
Hi I want to run the project without using docker, is there any way to do this? I've tried to run the server of the api folder and the ui folder but i don't know what else to do :( Can anyone help me with this? this is my email yairtavizon@gmail.com. Thank you :)

**Comment by wrathagom** [comment]
The best way to figure out what you need to run would be to look at the Docker-compose file as well as the individual Docker files. We don’t necessarily support running outside of Docker as their is a lot of orchestration including mis-matched package versions.

Can I ask why you are trying to run outside of Docker?
