### ISSUE TITLE
Error Message when using a bad username/password

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#936]
On the last version, when you enable the authentication.

Nothing happens when you type in a bad username or password.

It could be nice to have an error message, and it could be even better to have some sort of timer after 3/5 bad attempts.

**Comment by wrathagom** [comment]
@malave can you look at this one.

**Comment by malave** [comment]
Fixed on https://github.com/samtecspg/articulate/commit/186ce5f339466aa49dda4524603c33ae82ef796b

Adding a timer that would require tracking user not logged in and then check how many time they tried to login, which at this point I don't think would be necessary.
