### ISSUE TITLE
Weather Category: disambiguate dates

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#937]
Right now we don't return dates of any sorts so it is hard to tell that this conversation worked:

![image](https://user-images.githubusercontent.com/1779894/66703288-9ea0b700-ecd6-11e9-896a-6c86ba85da02.png)

**Comment by dakavisa** [comment]
Closed by f227dc7f315466ac4ee961e6c27d6a872c21e947, added a mention for the date asked (slot)
