### ISSUE TITLE
Weather Category: next week and this weekend not working

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#939]
These requests aren't returning anything useful. Maybe I am using them wrong:

![image](https://user-images.githubusercontent.com/1779894/66703342-3b635480-ecd7-11e9-94a5-f77052d569d5.png)

**Comment by RussellSPG** [comment]
Yes, currently cannot really do anything with the weather premade category.

**Comment by dakavisa** [comment]
Closing because according to pricing https://openweathermap.org/price the maximun ammount of days we can get with the free plan is 5
