### ISSUE TITLE
Use of Immutable.js is not consistent 

### ISSUE THREAD

**Issue by malave** [samtecspg/articulate#94]
We are using a combination of Immutable objects and plain javascript objects causing us to validate if the object we are currently handling is immutable in order to properly access its values. This causes duplicate code and unnecessary complexity since we are doing the same login in two different ways.

For example this logic appear in two different places doing the same but one for immutable and one for a JS object

https://github.com/samtecspg/articulate/blob/master/ui/app/containers/IntentPage/reducer.js#L151

and 

https://github.com/samtecspg/articulate/blob/master/ui/app/containers/IntentPage/reducer.js#L164

We need to:

- Ensure that every time we load data from the DB this is converted to immutable
- Each time the user changes the state this is converted to immutable and then passed to the state
- Remove any validation if the object is immutable or not and assume it should be immutable

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/beefb390fd67f315461d27bce902974cef3c02ab
