### ISSUE TITLE
Github Category: oldest/newest open/closed issues

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#943]
Can we handle this in a generic way to go with #941 so oldest/newest are keywords as are open/closed?

![image](https://user-images.githubusercontent.com/1779894/66703461-8336ab80-ecd8-11e9-8ac7-2b21f8ed2568.png)

**Comment by dakavisa** [comment]
Closed by 70583eb58d981fce5c42ae3ae6179271dde70fd8
