### ISSUE TITLE
Widgets see only on firefox

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#948]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*
make an index.html with code fore widgets
See widget in firefox
Not see in chrome
Not see in IE

- Did you download a release or pull from Master? Which release? latest
- What operating system are you running? CentOS
- Are you running locally or in the cloud? Locally
- Which browser are you using?

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by wrathagom** [comment]
I unfortunately have no idea what you're asking for or talking about.

What widget?

**Comment by aermike** [comment]
chat widget
I have an connection between an agent and an widget
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes, shrink-to-fit=no">
    <title>cadastrescu</title>
    <link href="https://storage.cloud.google.com/articulate-webchat/articulate-webchat-0.0.1.css" rel="stylesheet" type="text/css">
    <script src="https://storage.cloud.google.com/articulate-webchat/articulate-webchat-0.0.1.js"></script>
  </head>
  <body>
    <div id="webchat"></div>
    <script>
      WebChat.default.init({
        selector: '#webchat',
        socketUrl: 'ws://IP:7500',
        socketPath: '/connection/66a73250-fa4d-11e9-beb0-91d426fd2dd8/external',
        converseUrl: 'http://IP:8080/api/connection/66a73250-fa4d-11e9-beb0-91d426fd2dd8/external',
        title: 'cadastrescu',
        subtitle: 'provided by 3clicks.ro',
        senderPlaceHolder: 'Type a message...',
        titleAvatar: 'https://static.thenounproject.com/png/815603-200.png',
        profileAvatar: 'https://static.thenounproject.com/png/815603-200.png'
      });
    </script>
  </body>
</html>

**Comment by aermike** [comment]
Here is error from chrome
<img width="732" alt="widgets" src="https://user-images.githubusercontent.com/4247309/67772177-4998cb00-fa62-11e9-83fe-9bc2715f81ba.PNG">

**Comment by aermike** [comment]
Uncaught ReferenceError: WebChat is not defined
    at (index):13

**Comment by aermike** [comment]
after clone latest release on git works on chrome
