### ISSUE TITLE
Problem with News Category

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#949]
Hello, i'm using the latest master version, it's working wayyy better than last time congratulations !

i was playing with the new news category and i found something a weird

if you ask 
"do you know the news about accidents ?" 
you get 
"Sorry, we didnt find any recent news"

but if you remove the question mark, like 
"do you know the news about accidents" 
you get the right answer 
"These are the news found: Title: ...."

i don't know if it's an issue with the langage engine, or just a problem with the given sample.

**Comment by wrathagom** [comment]
@dakavisa can you try to reproduce?

**Comment by wrathagom** [comment]
my guess is that the ? is throwing off the entity recognition. So adding an example with it may help.

**Comment by mordebip** [comment]
Yes adding an example with the ? just after the news topic fixed it.
