### ISSUE TITLE
Clicking on a suggested slot in the agent response moves the cursor

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#95]
When you select a slot from the pop-up that appears when writing agent responses the cursor is removed from the input box.  Ideally the purpose would stay in the input and be moved to the end of the string you are typing.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/7041aca74d924d668c442aca2499f58ecf3123cfC
