### ISSUE TITLE
Error: getaddrinfo enotfound rasa/rasa:XXXX

### ISSUE THREAD

**Issue by robonxt** [samtecspg/articulate#952]
Getting an error when trying to train after adding in small talk for the first time.

Running v0.29 on Windows 10 Pro, 4GB RAM, Intel Atom.

Any help regarding this will be greatly appreciated!

**Comment by wrathagom** [comment]
Wow, totally missed this one. If you still need help, I'm watching now.

I would want to know what the output of `docker-compose ps` is
