### ISSUE TITLE
all sessions have the same answer

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#954]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*
I open an session to an site with widget with an mobile phone, Chrome and firefox.
When i receive the answer, it appear on all screens
Please describe the issue you are having here and answer the question below.
I open an session to an site with widget with an mobile phone, Chrome and firefox.
When i receive the answer, it appear on all screens
- Did you download a release or pull from Master? Which release?
download latest git
- What operating system are you running?CentOS
- Are you running locally or in the cloud?Locally
- Which browser are you using?chrome, firefox, safari
![Image-1](https://user-images.githubusercontent.com/4247309/68398524-8f017a80-017d-11ea-9f55-145b1b787d96.jpg)
![Image-1](https://user-images.githubusercontent.com/4247309/68398539-94f75b80-017d-11ea-82db-841fcae2d7bb.jpg)

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by aermike** [comment]
<img width="2320" alt="major issue" src="https://user-images.githubusercontent.com/4247309/68398662-c4a66380-017d-11ea-9f92-e96af87090cb.png">

**Comment by aermike** [comment]
Any help?

**Comment by aermike** [comment]
server seems to work corectly, and problem is in snippet, i believe
<img width="1920" alt="eroare" src="https://user-images.githubusercontent.com/4247309/68526172-c38e4700-02e1-11ea-9345-93efe64dcc2c.png">

**Comment by wrathagom** [comment]
@dakavisa @dcalvom I've never used the chat widget. @aermike is saying that if he has multiple browsers using the chat widget the chat shows up on all of the browsers, obviously this isn't the intention. Each browser should be it's own session.

@dcalvom does he need to generate some sort of a session ID to make each chat unique?

**Comment by dakavisa** [comment]
Closed and ready to test by ceb0d0a121d40fc32e9ffbdc45641b52803293b7
