### ISSUE TITLE
Add Quick Replies to Action responses.

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#959]
Currently we have quick replies for slot prompts:

![image](https://user-images.githubusercontent.com/1779894/69433040-d739a480-0d08-11ea-8412-dd8662ea76a5.png)

I want this same sort of thing, but for when one action concludes.

Like this:

![image](https://user-images.githubusercontent.com/1779894/69434071-e9b4dd80-0d0a-11ea-8008-c510c914fc63.png)

I have a few caveats like:

- I want them to be compiled with handlebars
- They should follow the same rough selection as responses do in actions. They can't be empty, no handlebar compilation errors, etc.

Thinking of the pizza bot we often talk about up-sells from the bot like this:

![botframe](https://user-images.githubusercontent.com/1779894/69433908-8a56cd80-0d0a-11ea-8adb-fd2a79d7edd0.png)

which is really awesome, and the best flow for certain platforms like voice. However with things like Facebook messenger this could be just as good If not better:

![botframe-2](https://user-images.githubusercontent.com/1779894/69434020-ca1db500-0d0a-11ea-9891-3bbe3384efc1.png)

and this is what I am trying to enable.

**Comment by dakavisa** [comment]
Closed and ready for test by 86d69a91faf3eb73bf576906ee6c70cddf8c4c81
