### ISSUE TITLE
Allow Agent Fallback Response to be Modified

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#96]
When a text is not recognized by an agent a fallback will be throw.

The current fallback values are hardcoded in articulate. @broham89 we need some a new table maybe like agent response in the create agent screen to add as many fallbacks as the user wants.

**Comment by wrathagom** [comment]
@dcalvom just re-use the interface for agent responses.

@broham89 keep in mind that you will need to add this to your UI v2 designs.

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/83a5a713ca54c3b049143dafb510b061dd6da448
