### ISSUE TITLE
After last update review tab is not visible

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#961]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
last release from github
- What operating system are you running?
CentOS 7
- Are you running locally or in the cloud?
Locally
- Which browser are you using?
Chrome, Firefox
----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.
After last update review page is not shown, and sessions are same (open in firefox and chrome).
I choose new session from each side

**Comment by aermike** [comment]
Show an page for few seconds and disapear 
http://ip:8080/agent/2/review

**Comment by dakavisa** [comment]
Closed by 7a80b83036e1df9c3ce8a46f7bb87d0765e1d71e
