### ISSUE TITLE
Docker Stuck at "watching 490 files" 

### ISSUE THREAD

**Issue by Maadhav** [samtecspg/articulate#966]
![image](https://user-images.githubusercontent.com/21285859/70124534-0225e000-169b-11ea-8f66-7622ba514a90.png)
![image](https://user-images.githubusercontent.com/21285859/70125279-8b89e200-169c-11ea-9cac-1679505e2f8f.png)

this issue is appearing whenever I try to run articulate in my machine.

**Comment by wrathagom** [comment]
I replied to you on Gitter, can I see the output of ‘docker-compose logs elasticsearch‘?

**Comment by wrathagom** [comment]
@Maadhav let me know if you still need help on this one.

**Comment by Maadhav** [comment]
> @Maadhav let me know if you still need help on this one.

I moved from articulate to Rasa X. The main reason was that I was trying to run docker in windows home which is incompatible.

**Comment by Maadhav** [comment]
> @Maadhav let me know if you still need help on this one.

I moved from Articulate to Rasa X. The main problem was that docker was not compatible with windows home. Maybe that was something to do with the problem I was having.

**Comment by wrathagom** [comment]
If you made it as far as in the screenshots then that was not the problem as docker is clearly running.

**Comment by Maadhav** [comment]
Dont know but that was the reason I stopped using Articulate.
