### ISSUE TITLE
Webhook gets called twice and receive Double response.

### ISSUE THREAD

**Issue by rounakraj** [samtecspg/articulate#967]
When using quick response to show buttons in action during slot filling of required keywords, the webhook gets called twice and receive double response, once for each original request and quick response slot filling.
Have any one faced such issue earlier.

**Comment by wrathagom** [comment]
quick responses are new, so very likely to have a bug. @dakavisa your up again.

**Comment by dakavisa** [comment]
@rounakraj can you give us the example (or a similar one) of the flow of the problem... like :
Given Action A with Slot S that is required? and of type of Keyword K, when I say "this" Webhook W is called and then quick responses R1, R2 and R3 are shown ... etc ... so we can reproduce your exact problem? Thanks!

**Comment by rounakraj** [comment]
@dakavisa Before i could reproduce the above issue i ran into another problem, the webhook which was earlier working for me now giving me this issue:

{ error:
api_1            |    SyntaxError: Unexpected token u in JSON at position 0
api_1            |        at JSON.parse (<anonymous>)
api_1            |        at parse (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:74:33)
api_1            |        at Array.map (<anonymous>)
api_1            |        at AgentService.map (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:72:47)
api_1            |        at Generator.next (<anonymous>)
api_1            |        at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:9:103)
api_1            |        at _next (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:11:194)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
api_1            | Debug: handler, error 
api_1            |     Error: Unexpected token u in JSON at position 0
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
api_1            | Debug: internal, error 
api_1            |     Error: Unexpected token u in JSON at position 0
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dakavisa** [comment]
May I see how are you configuring your webhook? and the action response?

**Comment by rounakraj** [comment]
<img width="999" alt="Screenshot 2019-12-06 at 8 49 16 PM" src="https://user-images.githubusercontent.com/6190350/70334424-6d261100-186b-11ea-9c62-d5d76994be70.png">
<img width="1030" alt="Screenshot 2019-12-06 at 8 49 01 PM" src="https://user-images.githubusercontent.com/6190350/70334426-6dbea780-186b-11ea-8981-8c3e1b1de8d9.png">
<img width="1017" alt="Screenshot 2019-12-06 at 8 48 33 PM" src="https://user-images.githubusercontent.com/6190350/70334428-6dbea780-186b-11ea-9130-1aeadf562cf2.png">

**Comment by wrathagom** [comment]
Do you mean quick replies for slot filling? You didn't screen shot that part of the page.. Keep in mind that quick replies just send the value of the button back, your agent has to be able to recognize that button as a keyword.

**Comment by rounakraj** [comment]
@wrathagom Ya that part I understood, but now the issue is that the web hook which was working earlier started giving me the above issue. Therefore i was not able to reproduce what @dakavisa asked

**Comment by dakavisa** [comment]
@rounakraj it seems that your Webhook receives a JSON object in the POST, that you are providing with {"slots":{{{JSONstringify slots}}}} but are you sure you want to stringify the entire slots object and that your webhook can handle that? When setting an specific slot value inside the POST JSON object this has worked:
{
  "body": "{{{slots.body.value}}}"
}

That is Posting a JSON object with a field named body and is reading the value of the slot named "body" inside slots object.

I would guess that your webhook needs something like:

{
  "<NameYourWebhookSpects>": "{{{slots.zwaveDeviceType.value}}}"
}

**Comment by rounakraj** [comment]
But this was working earlier and this is what I was receiving on my web hook:
{"body":{"slots":{"zwaveDeviceType":{"value":"Siren","original":"security sensor"}}},"headers":{"connection":"upgrade","host":"training.tantiv4.com","content-length":"76","accept":"application/json, text/plain, /","content-type":"application/json","action":"zwaveAdd","user-agent":"axios/0.18.0"}}

It just stopped working all of sudden.

**Comment by wrathagom** [comment]
can you change you webhook body to just be:

`{
  "slots": "Test"
}
`

and tell us if the error goes away?

**Comment by rounakraj** [comment]
@wrathagom  yes the error is still there, the error is there even if I remove the body completely from webhook and call with only header

**Comment by dakavisa** [comment]
@rounakraj  What would be a valid POST JSON object to send to : training.tantiv4.com/webhook?

**Comment by rounakraj** [comment]
it can handle any json, right now I am just receiving the json and printing, no validation takes place in webhook code.

Also, to add to that I just downloaded and executed the agent in my local machine in the local instance and it works from there. This started happening on my cloud instance once I blocked the external access. Is there any specific port which webhook uses inside articulate to send data.

**Comment by rounakraj** [comment]
If I check the review section for details:
In local instance I get:
<img width="824" alt="Screenshot 2019-12-06 22 14 09" src="https://user-images.githubusercontent.com/6190350/70339980-df9bee80-1875-11ea-9435-de6a03c6d985.png">

But for same agent in cloud instance I get the error an din review section it show:
<img width="823" alt="Screenshot 2019-12-06 22 14 18" src="https://user-images.githubusercontent.com/6190350/70340011-f5a9af00-1875-11ea-9528-308a5e675f41.png">

**Comment by wrathagom** [comment]
What does the response form the webhook look like?

**Comment by rounakraj** [comment]
Webhook is not returning any response just 200 Ok Header

**Comment by wrathagom** [comment]
Ah, we've seen this problem before. Let me dig.

**Comment by rounakraj** [comment]
Sure, Thanks

**Comment by wrathagom** [comment]
Can you ping/curl the webhook server from the Articulate server?

**Comment by rounakraj** [comment]
yes I could curl request successfully from Articulate server to webhook

**Comment by wrathagom** [comment]
and they're both running the same versions? What its he output of the curl? This is a JSON formatting problem, we're just trying to track down who has the bad JSON.

**Comment by rounakraj** [comment]
Yes both are running 0.29.0.
When I Curl with curl -X POST \
  https://training.tantiv4.com/webhook \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 23' \
  -H 'Content-Type: application/json' \
  -H 'Host: training.tantiv4.com' \
  -H 'Postman-Token: e826fd03-ee31-427a-85cc-a4ecf0408aa4,91b02d9a-c965-4612-b432-be6cc366cab6' \
  -H 'User-Agent: PostmanRuntime/7.19.0' \
  -H 'action: testAction' \
  -H 'cache-control: no-cache' \
  -d '{
    "slots": "Test"
}'

It returns success and I receive this on webhook.

{"body":{"slots":"Test"},"headers":{"connection":"upgrade","host":"training.tantiv4.com","content-length":"23","accept":"/","accept-encoding":"gzip, deflate","cache-control":"no-cache, no-cache","content-type":"application/json","postman-token":"e826fd03-ee31-427a-85cc-a4ecf0408aa4,91b02d9a-c965-4612-b432-be6cc366cab6","user-agent":"PostmanRuntime/7.19.0","action":"testAction"}}

**Comment by rounakraj** [comment]
@wrathagom @dakavisa I have again captured the docker-compose log:


rasa_1           | 2019-12-06 17:51:25+0000 [-] "172.19.0.8" - - [06/Dec/2019:17:51:24 +0000] "POST /parse HTTP/1.1" 200 342 "-" "axios/0.18.0"
api_1            | { error:
api_1            |    SyntaxError: Unexpected token u in JSON at position 0
api_1            |        at JSON.parse (<anonymous>)
api_1            |        at parse (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:74:33)
api_1            |        at Array.map (<anonymous>)
api_1            |        at AgentService.map (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:72:47)
api_1            |        at Generator.next (<anonymous>)
api_1            |        at asyncGeneratorStep (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:9:103)
api_1            |        at _next (/usr/src/app/lib/services/agent/agent.converse-send-response-to-ubiquity.js:11:194)
api_1            |        at process._tickCallback (internal/process/next_tick.js:68:7),
api_1            |   message: null }
api_1            | Debug: handler, error 
api_1            |     Error: Unexpected token u in JSON at position 0
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
nginx_1          | 172.19.0.1 - - [06/Dec/2019:17:51:46 +0000] "POST /api/agent/1/converse?debug=true HTTP/1.1" 500 96 "http://13.233.43.14:8080/agent/1/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"
api_1            | Debug: internal, error 
api_1            |     Error: Unexpected token u in JSON at position 0
api_1            |     at /usr/src/app/lib/routes/agent/agent.converse.route.js:43:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.converse.route.js:19:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.converse.route.js:21:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
nginx_1          | 172.19.0.1 - - [06/Dec/2019:17:51:46 +0000] "GET /api/agent/1/session?skip=0&limit=5&field=modificationDate&direction=desc HTTP/1.1" 200 579 "http://13.233.43.14:8080/agent/1/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15" "-"
nginx_1          | 172.19.0.1 - - [06/Dec/2019:17:51:46 +0000] "GET /api/agent/1/session?skip=0&limit=5&field=modificationDate&direction=desc HTTP/1.1" 200 579 "http://13.233.43.14:8080/agent/1/review" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"

**Comment by rounakraj** [comment]
rasa_1 | 2019-12-06 17:51:25+0000 [-] "172.19.0.8" - - [06/Dec/2019:17:51:24 +0000] "POST /parse HTTP/1.1" 200 342 "-" "axios/0.18.0"

What does this line suggest?

**Comment by dakavisa** [comment]
@rounakraj may I get an export of your agent as well?

**Comment by rounakraj** [comment]
[test (2).json.zip](https://github.com/samtecspg/articulate/files/3933389/test.2.json.zip)
This is a simple test example which I am using between local and cloud.
It is working on local but not on cloud.

**Comment by wrathagom** [comment]
```
rasa_1 | 2019-12-06 17:51:25+0000 [-] "172.19.0.8" - - [06/Dec/2019:17:51:24 +0000] "POST /parse HTTP/1.1" 200 342 "-" "axios/0.18.0"
```

This line is just the call that Articulate does internally to Rasa, which performs our NLU for us.

This is the actual error line and suggests that when we try to parse the webhook response it is failing.

**Comment by wrathagom** [comment]
@rounakraj does your webhook page have the input for Webhook Key at the top of it?

![image](https://user-images.githubusercontent.com/1779894/70346014-4fd15280-182b-11ea-8c54-d08c4423d56f.png)

**Comment by rounakraj** [comment]
No, Webhook key is not there.
<img width="1189" alt="Screenshot 2019-12-06 23 53 17" src="https://user-images.githubusercontent.com/6190350/70346218-ca2dc100-1883-11ea-9244-0bcea793df2a.png">

**Comment by wrathagom** [comment]
Weren't you running 0.30 at some point?

**Comment by rounakraj** [comment]
Ya, I was trying 0.30 when debugging reds issue, later moved to official release 0.29.0.

**Comment by rounakraj** [comment]
I have now even added json response back in webhook response. But still no luck.
One thing which I am not able to understand is how it is working in local.

**Comment by rounakraj** [comment]
@wrathagom @dakavisa Guys, I just did a clean install on a fresh server and it is working fine. Don't know what changed or caused this. Now coming back to original issue of double response.
This is the screenshot of the flow:
<img width="284" alt="Screenshot 2019-12-07 01 01 42" src="https://user-images.githubusercontent.com/6190350/70350737-4ed10d00-188d-11ea-9771-55c0e890cc88.png">
Slot filling details:
<img width="1235" alt="Screenshot 2019-12-07 01 02 29" src="https://user-images.githubusercontent.com/6190350/70350762-627c7380-188d-11ea-8e93-d035041eed6d.png">
<img width="1180" alt="Screenshot 2019-12-07 01 02 21" src="https://user-images.githubusercontent.com/6190350/70350763-63150a00-188d-11ea-933c-6ce86acfec35.png">
<img width="1172" alt="Screenshot 2019-12-07 01 02 14" src="https://user-images.githubusercontent.com/6190350/70350767-63150a00-188d-11ea-9dda-5ff707c71b25.png">

**Comment by rounakraj** [comment]
As you can see in above flow zWaveAction is called which has mandatory field of zWaveDeviceType
User is presented with quick action buttons and when user selects one of the device type. the webhook and response comes twice once for original message other for slot filling value.

**Comment by dakavisa** [comment]
Great that the webhook is working now, could you please select "see source" in the last message and paste the content for the "Context" tab?

**Comment by rounakraj** [comment]
Yes fixed though not sure why it just stopped working  and started to work on fresh install.

Context Tab for "pair zwave" statement:
{
  "id": "14",
  "sessionId": "BotinProgress-session-c8feb4f4-785d-e09c-9878-1249489caf80",
  "savedSlots": {},
  "actionQueue": [
    {
      "name": "zWaveAction",
      "fulfilled": false,
      "slots": {
        "zwaveDeviceType": {
          "keyword": "zwaveDeviceType",
          "value": "",
          "original": "",
          "promptCount": 1
        }
      }
    }
  ],
  "docIds": [
    "MXXx3G4Bg2CiXVJWmf0I"
  ],
  "creationDate": "1575664841000",
  "modificationDate": "1575664841000"
}


Context Tab content for Bulb(Slot filling value)
{
  "id": "14",
  "sessionId": "BotinProgress-session-c8feb4f4-785d-e09c-9878-1249489caf80",
  "savedSlots": {},
  "actionQueue": [
    {
      "name": "zWaveAction",
      "fulfilled": true,
      "slots": {
        "zwaveDeviceType": {
          "value": "Bulb",
          "original": "Bulb"
        }
      }
    },
    {
      "name": "zwaveStartPairing",
      "fulfilled": true
    },
    {
      "name": "zWaveAction",
      "fulfilled": true,
      "slots": {
        "zwaveDeviceType": {
          "value": "Bulb",
          "original": "Bulb"
        }
      }
    },
    {
      "name": "zwaveStartPairing",
      "fulfilled": true
    }
  ],
  "docIds": [
    "MXXx3G4Bg2CiXVJWmf0I",
    "MnXx3G4Bg2CiXVJWpf1c"
  ],
  "creationDate": "1575664841000",
  "modificationDate": "1575664851000"
}

**Comment by rounakraj** [comment]
@dakavisa let me know if any other logs are needed

**Comment by rounakraj** [comment]
@dakavisa The issue i am facing is somewhat similar to https://github.com/samtecspg/articulate/issues/838#issuecomment-519698209

**Comment by rounakraj** [comment]
Just adding my test agent with exact issue:
[test.json.zip](https://github.com/samtecspg/articulate/files/3936116/test.json.zip)
<img width="280" alt="Screenshot 2019-12-08 at 4 11 06 PM" src="https://user-images.githubusercontent.com/6190350/70388286-ab3f4400-19d5-11ea-99de-d31342c6847b.png">

**Comment by dakavisa** [comment]
This solution should be now on master, closed by e347a225d2cbce6d6bcbffd9569f58d2c95674b5

**Comment by rounakraj** [comment]
@dakavisa Thanks, will test.

**Comment by rounakraj** [comment]
Hi @dakavisa I tested this on latest pull of master. The issue is still happening.
See the attached screen shot.
<img width="302" alt="Screenshot 2019-12-19 at 4 16 00 PM" src="https://user-images.githubusercontent.com/6190350/71167636-0f39f600-227b-11ea-8e98-c62e418e6c11.png">

Also, attached my test agent.

[test-4.json.zip](https://github.com/samtecspg/articulate/files/3983147/test-4.json.zip)

**Comment by dakavisa** [comment]
Are you sure you are getting the latest version and cleaning up all the docker stuff? I just tried your agent and see only one respone:

![image](https://user-images.githubusercontent.com/53984674/71183153-13472300-223d-11ea-85e9-d3e533c376fb.png)

**Comment by rounakraj** [comment]
I took latest pull from git and executed 
docker-compose down
docker-compose pull
docker-compose up -d

Anything else i am missing.

**Comment by rounakraj** [comment]
Thanks, checked this working fine in latest pull.
