### ISSUE TITLE
Adding new channel Like Messenger

### ISSUE THREAD

**Issue by rounakraj** [samtecspg/articulate#968]
Thanks to @dakavisa and @wrathagom  I am almost ready with my demo model using articulate master branch. I will keep testing the updated master.

One last thing which i would like to know is how to add new channel support. I would like to add line messenger and telegram as the chat channel for my agent.
Is there any document which i can follow to add these channels.
Also, Is there any plan to support these.

Thanks,
Rounak

**Comment by rounakraj** [comment]
Can you please point me to any document which can help add a new channel.

**Comment by aermike** [comment]
hi
Just choose your agent, choose which platform do you want link, and complete details
I test with chat widget

**Comment by rounakraj** [comment]
@aermike i want to add a new channel which is not there in the list. Like Line Messenger or Telegram

**Comment by aermike** [comment]
try with webhooks
https://www.youtube.com/watch?v=Xc1j2F1Em9M

**Comment by rounakraj** [comment]
i am already using webhooks to send the cso from articulate to my server.
I want to add a new front end to my chat like instead of slack or chat widget or FB i want to use line messenger.

**Comment by aermike** [comment]
Don't uset it

**Comment by rounakraj** [comment]
?? Sorry what are you suggesting here.

**Comment by wrathagom** [comment]
@dcalvom if I remember you had something typed up on adding new channels. Is that still true?

**Comment by dcalvom** [comment]
Yes @wrathagom, that's on basecamp

**Comment by rounakraj** [comment]
@dcalvom Can you please share.

**Comment by rounakraj** [comment]
@dcalvom @wrathagom sorry guys don't mean to rush you but can you share this doc with me, I would like to start working on adding the channels

**Comment by dcalvom** [comment]
@rounakraj take a look at this post https://public.3.basecamp.com/p/126LptVC1p2k4E8eKrSrWuYy and let us know any doubt. Please be conscious that this was written some time ago, so some things already changed, but at least you can get an overview of how it works.

**Comment by rounakraj** [comment]
Thanks @dcalvom
