### ISSUE TITLE
Dynamic quick response buttons have no effect .

### ISSUE THREAD

**Issue by rounakraj** [samtecspg/articulate#969]
When using the chatbot agent from Slack Channel , the click on buttons have no effect.
The data is not passed on to articulate.
It displays the button and i am able to click it but there is no event going to articulate.
Am i missing something?

Branch Used: Articulate Master Branch

**Comment by dakavisa** [comment]
Can I get your agent and a screenshot of the conversation please?

**Comment by rounakraj** [comment]
Attached my agent:
[ThingaOSBot-5.json.zip](https://github.com/samtecspg/articulate/files/3945483/ThingaOSBot-5.json.zip)
<img width="1146" alt="Screenshot 2019-12-10 at 8 27 40 PM" src="https://user-images.githubusercontent.com/6190350/70540750-ce135900-1b8b-11ea-9bca-8c0bf283dbf8.png">

The issue is only when using slack channel, it works fine from chat widget.

**Comment by dakavisa** [comment]
I was able to reproduce the error, please make sure that you are enable the following option in the apps page of slack and that you have set your server/connection URL correctly:

![image](https://user-images.githubusercontent.com/53984674/70855273-239e7d00-1e8e-11ea-8abd-a3bea6ec07a9.png)

https://api.slack.com/apps

I will close this but feel free to comment if this doesn't fix the problem.

**Comment by rounakraj** [comment]
Thanks @dakavisa i was missing the above statement.
