### ISSUE TITLE
Weather bot import error

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#971]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?Last
- What operating system are you running?CentOS 7
- Are you running locally or in the cloud?Locally
- Which browser are you using?Firefox

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.
If I want import weather category, dissapear all of screen and log says
 200 26 "http://10.33.0.42:8080/agent/6/addCategory?filter=&page=1&pageSize=5&tab=sayings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0" "-"
nginx_1          | 10.33.0.150 - - [18/Dec/2019:08:47:44 +0000] "GET /api/category HTTP/1.1" 200 689 "http://10.33.0.42:8080/agent/6/addCategory?filter=&page=1&pageSize=5&tab=sayings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0" "-"
api_1            | Debug: handler, error
api_1            |     Error: The Agent already has Action with the name(s) = Default Fallback Action.
api_1            |     at /usr/src/app/lib/routes/agent/agent.import-category.route.js:23:24
api_1            |     at Generator.throw (<anonymous>)
api_1            |     at asyncGeneratorStep (/usr/src/app/lib/routes/agent/agent.import-category.route.js:11:103)
api_1            |     at _throw (/usr/src/app/lib/routes/agent/agent.import-category.route.js:13:291)
api_1            |     at process._tickCallback (internal/process/next_tick.js:68:7)
nginx_1          | 10.33.0.150 - - [18/Dec/2019:08:47:47 +0000] "POST /api/agent/6/category/import HTTP/1.1" 404 123 "http://10.33.0.42:8080/agent/6/addCategory?filter=&page=1&pageSize=5&tab=sayings" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0" "-"

**Comment by wrathagom** [comment]
@dakavisa I think when you updated the weather bot you accidentally let tin the default action?

**Comment by dakavisa** [comment]
closed by 84877ed3c7abdc740ea50695d900cc658c409f08
