### ISSUE TITLE
New Session Button on web demo page does not work.

### ISSUE THREAD

**Issue by rounakraj** [samtecspg/articulate#973]
I am using master branch.
On the web demo URL the New session button does not create a session.

<img width="296" alt="Screenshot 2019-12-19 at 6 19 07 PM" src="https://user-images.githubusercontent.com/6190350/71174883-364cf380-228c-11ea-82bb-353e8535e407.png">

**Comment by wrathagom** [comment]
So what happens when you click it?

**Comment by rounakraj** [comment]
Nothing Happens. The icon does not change. no new session is created.

**Comment by wrathagom** [comment]
And the current conversation stays in the chat panel?

**Comment by rounakraj** [comment]
The current conversation is cleared, but the moment some else types anything in their session it appears in this window also.

**Comment by wrathagom** [comment]
Closed as a duplicate of #972
