### ISSUE TITLE
Rasa Forms Support

### ISSUE THREAD

**Issue by zee85** [samtecspg/articulate#975]
Does this project currently support forms? I didn't see anything in the docs about this. I assume not.

**Comment by wrathagom** [comment]
This project only uses Rasa NLU not core.

We have advanced slot filling for required/non-required and list/non-list slots and handlebar templating.

What are you trying to accomplish?

**Comment by zee85** [comment]
My ultimate goal is to build a bot for searching classifieds. I was looking at RASA core and came across forms which seems like the proper way to build such a bot. That said I've only been working on this for the last few days. Prior to that I had no knowledge of CAAP.

**Comment by wrathagom** [comment]
Rasa Core or Articulate would be very capable of making a bot as you describe.
