### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by rounakraj** [samtecspg/articulate#976]
@wrathagom  I would like to set a welcome message when chatbot starts. Is there something like Welcome Intent which i can use, or any other way to achieve this.

**Comment by wrathagom** [comment]
There is in the chat widget, but no where else I don't believe.

@dcalvom

**Comment by dcalvom** [comment]
Correct! This is a good feature to be added. A welcome message that will be used in case the channel accepts it.

**Comment by rounakraj** [comment]
Thanks, How do we modify this for chat widget.

**Comment by rounakraj** [comment]
@wrathagom How do we pass any parameter from chat widget and access it as part of CSO. For eg. i completed login and would like to send the userID back in CSO to be sent in header to my webhook. Is this possible?

**Comment by rounakraj** [comment]
@wrathagom @dcalvom any answer to my above queries

**Comment by dcalvom** [comment]
Hi @rounakraj, to let you know, right now @dakavisa is working on the welcome message feature. Regarding the way to send back something to your agent in the payload, you can just simply add it as a part of the payload in your request to converse and it will be forwarded to the CSO, so if you send userID in the payload you will be able to access it your action webhook with just `{{userID}}`

**Comment by rounakraj** [comment]
@dcalvom Thanks I could retrieve the payload.
Would love to tryout the new welcome message feature once ready.

**Comment by wrathagom** [comment]
@dakavisa can you give a run down of welcome message feature?

**Comment by dakavisa** [comment]
Now we have a default action like fallback but it's called welcome action. This action is created automatically on any new agent, for the old ones it should be added before save.
For every connection, for example the chat widget, in the details tab, there is an option for enabling it:
![image](https://user-images.githubusercontent.com/53984674/72379530-3c8e8e00-36d9-11ea-8dd3-cbf9f3f95366.png)
For the chat widget, for every new session or when they are restarted, the action is executed when the chat is opened
For all the other connections, the welcome action is executed after the first user message.

![image](https://user-images.githubusercontent.com/53984674/72379818-c6d6f200-36d9-11ea-9f47-d2d7cc2841d8.png)

**Comment by dakavisa** [comment]
Closed by ef084a9c9a52c429e5330661c1a9d643fe6f2b7c
