### ISSUE TITLE
Issues with running the docker-compose up command for starting articulate

### ISSUE THREAD

**Issue by VitaliyLutskyi** [samtecspg/articulate#979]
- Did you download a release or pull from Master? Which release? - Yes. The latest one v0.29.0.
- What operating system are you running? - Windows 10 Home.
- Are you running locally or in the cloud? - Locally.
- Which browser are you using? - Google Chrome.

--------------------------------------------------------------------------------------------------------------
    
Hi! I'm using Docker Toolbox because I can't install Docker for Windows on Windows 10 Home. I tried to run the Articulate locally. First times I got some errors. I increased RAM of VM from 1GB to 4GB and video memory to 64MB. Now I don't get any errors but the Articulate still doesn't run properly, localhost:8080 is unavailable. Here is my log:

C:\Users\Vitaliy\Articulate\articulate-v0.29.0>docker-compose up
Creating network "articulate-v0290_default" with the default driver
Creating articulate-v0290_duckling_1      ... done                                                                                                                                                                 Creating articulate-v0290_ui_1            ... done                                                                                                                                                                 Creating articulate-v0290_rasa_1          ... done                                                                                                                                                                 Creating articulate-v0290_api_1           ... done                                                                                                                                                                 Creating articulate-v0290_nginx_1         ... done                                                                                                                                                                 Creating articulate-v0290_redis_1         ... done                                                                                                                                                                 Creating articulate-v0290_elasticsearch_1 ... done                                                                                                                                                                 Attaching to articulate-v0290_duckling_1, articulate-v0290_ui_1, articulate-v0290_api_1, articulate-v0290_nginx_1, articulate-v0290_rasa_1, articulate-v0290_elasticsearch_1, articulate-v0290_redis_1
api_1            | 2020/01/06 11:43:54 Waiting for: http://elasticsearch:9200
redis_1          | 1:C 06 Jan 11:43:54.865 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1          | 1:C 06 Jan 11:43:54.874 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1          | 1:C 06 Jan 11:43:54.874 # Configuration loaded
redis_1          | 1:M 06 Jan 11:43:54.880 * Running mode=standalone, port=6379.
redis_1          | 1:M 06 Jan 11:43:54.882 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 06 Jan 11:43:54.883 # Server initialized
redis_1          | 1:M 06 Jan 11:43:54.884 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:M 06 Jan 11:43:54.923 * DB loaded from append only file: 0.038 seconds
api_1            | 2020/01/06 11:43:54 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
duckling_1       | no port specified, defaulting to port 8000
ui_1             | yarn run v1.17.3
api_1            | 2020/01/06 11:43:55 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:43:56 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
ui_1             | $ cross-env NODE_ENV=production env-cmd --no-override .env node server
ui_1             | Server started ! ✓
api_1            | 2020/01/06 11:43:57 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:43:58 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:43:59 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
rasa_1           | 2020-01-06 11:44:00+0000 [-] Log opened.
rasa_1           | 2020-01-06 11:44:00+0000 [-] Site starting on 5000
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
api_1            | 2020/01/06 11:44:00 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
elasticsearch_1  | [2020-01-06T11:44:01,566][WARN ][o.e.c.l.LogConfigurator  ] [unknown] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:
elasticsearch_1  |   /usr/share/elasticsearch/config/log4j2.properties
elasticsearch_1  | [2020-01-06T11:44:02,553][INFO ][o.e.e.NodeEnvironment    ] [MxtDTjP] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/c/Users)]], net usable_space [21.9gb], net total_space [118.1gb], types [vboxsf]
api_1            | 2020/01/06 11:44:01 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
elasticsearch_1  | [2020-01-06T11:44:02,554][INFO ][o.e.e.NodeEnvironment    ] [MxtDTjP] heap size [503.6mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2020-01-06T11:44:02,914][INFO ][o.e.n.Node               ] [MxtDTjP] node name derived from node ID [MxtDTjPAQJSwJbZhwxazVw]; set [node.name] to override
elasticsearch_1  | [2020-01-06T11:44:02,915][INFO ][o.e.n.Node               ] [MxtDTjP] version[6.5.1], pid[1], build[default/tar/8c58350/2018-11-16T02:22:42.182257Z], OS[Linux/4.14.154-boot2docker/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.1/11.0.1+13]
api_1            | 2020/01/06 11:44:02 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:03 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:04 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
elasticsearch_1  | [2020-01-06T11:44:02,916][INFO ][o.e.n.Node               ] [MxtDTjP] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.W98e3TPC, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar]
elasticsearch_1  | [2020-01-06T11:44:06,410][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2020-01-06T11:44:06,410][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [analysis-common]
elasticsearch_1  | [2020-01-06T11:44:06,411][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [ingest-common]
elasticsearch_1  | [2020-01-06T11:44:06,411][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [lang-expression]
elasticsearch_1  | [2020-01-06T11:44:06,411][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [lang-mustache]
elasticsearch_1  | [2020-01-06T11:44:06,412][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [lang-painless]
elasticsearch_1  | [2020-01-06T11:44:06,413][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [mapper-extras]
elasticsearch_1  | [2020-01-06T11:44:06,413][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [parent-join]
elasticsearch_1  | [2020-01-06T11:44:06,414][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [percolator]
elasticsearch_1  | [2020-01-06T11:44:06,414][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [rank-eval]
elasticsearch_1  | [2020-01-06T11:44:06,415][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [reindex]
elasticsearch_1  | [2020-01-06T11:44:06,415][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [repository-url]
elasticsearch_1  | [2020-01-06T11:44:06,415][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [transport-netty4]
elasticsearch_1  | [2020-01-06T11:44:06,418][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [tribe]
elasticsearch_1  | [2020-01-06T11:44:06,418][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-ccr]
elasticsearch_1  | [2020-01-06T11:44:06,420][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-core]
elasticsearch_1  | [2020-01-06T11:44:06,420][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-deprecation]
elasticsearch_1  | [2020-01-06T11:44:06,420][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-graph]
elasticsearch_1  | [2020-01-06T11:44:06,421][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-logstash]
elasticsearch_1  | [2020-01-06T11:44:06,421][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-ml]
elasticsearch_1  | [2020-01-06T11:44:06,423][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-monitoring]
elasticsearch_1  | [2020-01-06T11:44:06,424][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-rollup]
elasticsearch_1  | [2020-01-06T11:44:06,424][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-security]
elasticsearch_1  | [2020-01-06T11:44:06,425][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-sql]
elasticsearch_1  | [2020-01-06T11:44:06,425][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-upgrade]
elasticsearch_1  | [2020-01-06T11:44:06,426][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded module [x-pack-watcher]
elasticsearch_1  | [2020-01-06T11:44:06,427][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded plugin [ingest-geoip]
api_1            | 2020/01/06 11:44:05 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:06 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:07 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:08 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:09 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:10 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:11 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:12 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:13 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:14 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
elasticsearch_1  | [2020-01-06T11:44:06,430][INFO ][o.e.p.PluginsService     ] [MxtDTjP] loaded plugin [ingest-user-agent]
api_1            | 2020/01/06 11:44:15 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
elasticsearch_1  | [2020-01-06T11:44:15,786][INFO ][o.e.d.DiscoveryModule    ] [MxtDTjP] using discovery type [single-node] and host providers [settings]
elasticsearch_1  | [2020-01-06T11:44:16,785][INFO ][o.e.n.Node               ] [MxtDTjP] initialized
elasticsearch_1  | [2020-01-06T11:44:16,786][INFO ][o.e.n.Node               ] [MxtDTjP] starting ...
elasticsearch_1  | [2020-01-06T11:44:17,067][INFO ][o.e.t.TransportService   ] [MxtDTjP] publish_address {172.21.0.6:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2020-01-06T11:44:17,174][WARN ][o.e.b.BootstrapChecks    ] [MxtDTjP] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2020-01-06T11:44:17,235][INFO ][o.e.h.n.Netty4HttpServerTransport] [MxtDTjP] publish_address {172.21.0.6:9200}, bound_addresses {0.0.0.0:9200}
elasticsearch_1  | [2020-01-06T11:44:17,236][INFO ][o.e.n.Node               ] [MxtDTjP] started
elasticsearch_1  | [2020-01-06T11:44:18,156][INFO ][o.e.l.LicenseService     ] [MxtDTjP] license [34f0405e-d9e8-4414-9c04-c3a2b56de14f] mode [basic] - valid
api_1            | 2020/01/06 11:44:16 Problem with request: Get http://elasticsearch:9200: dial tcp 172.21.0.6:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/01/06 11:44:18 Received 200 from http://elasticsearch:9200
api_1            | yarn run v1.17.3
api_1            | $ cross-env NODE_ENV=development env-cmd server/.env nodemon server --exec babel-node
api_1            | [nodemon] 1.18.10
api_1            | [nodemon] reading config ./package.json
api_1            | [nodemon] to restart at any time, enter `rs`
api_1            | [nodemon] or send SIGHUP to 40 to restart
api_1            | [nodemon] ignoring: ./node_modules/**/*
api_1            | [nodemon] watching: *.*
api_1            | [nodemon] watching extensions: js,mjs,json
api_1            | [nodemon] starting `babel-node server`
api_1            | [nodemon] spawning
api_1            | [nodemon] child pid: 53
api_1            | [nodemon] watching 490 files
elasticsearch_1  | [2020-01-06T11:44:18,160][INFO ][o.e.g.GatewayService     ] [MxtDTjP] recovered [1] indices into cluster_state    

Sometimes there are no lines after 'watching 490 files'.
Sometimes I get 3 more lines after 'watching 490 files':
    
elasticsearch_1  | [2020-01-06T10:43:40,453][INFO ][o.e.g.GatewayService     ] [MxtDTjP] recovered [0] indices into cluster_state
elasticsearch_1  | [2020-01-06T10:43:49,894][WARN ][o.e.d.c.m.MetaDataCreateIndexService] [MxtDTjP] the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template
elasticsearch_1  | [2020-01-06T10:43:50,141][INFO ][o.e.c.m.MetaDataCreateIndexService] [MxtDTjP] [document] creating index, cause [api], templates [], shards [5]/[1], mappings []

**Comment by wrathagom** [comment]
I don't see any errors in the above, Articulate can take several minutes to fully start-up.  What makes you think it isn't working properly?

**Comment by VitaliyLutskyi** [comment]
Because neither http://localhost:8080/ nor http://localhost:7500/documentation are available. I tried once more an hour ago and got the same issue. Can Articulate take more then hour to start-up?

**Comment by wrathagom** [comment]
no, it shouldn't.

Can you give me the output of `docker-compose ps`?

**Comment by VitaliyLutskyi** [comment]
Системе не удается найти указанный путь.
              Name                            Command                State     Ports
------------------------------------------------------------------------------------
articulate-v0290_api_1             docker-entrypoint.sh /bin/ ...   Exit 137
articulate-v0290_duckling_1        /bin/sh -c stack exec duck ...   Exit 137
articulate-v0290_elasticsearch_1   /usr/local/bin/docker-entr ...   Exit 143
articulate-v0290_nginx_1           nginx-debug -g daemon off;       Exit 0
articulate-v0290_rasa_1            ./entrypoint.sh start --pa ...   Exit 0
articulate-v0290_redis_1           docker-entrypoint.sh redis ...   Exit 0
articulate-v0290_ui_1              yarn start:prod                  Exit 1

**Comment by VitaliyLutskyi** [comment]
The russian snippet means: 
The system cannot find the path specified.

**Comment by wrathagom** [comment]
Looks like you had already shut it down, I want to see which process dies on it's own. Can you run.

```
docker-compose up -d
```

wait 5 minutes and then run

```
docker-compose ps
```

**Comment by VitaliyLutskyi** [comment]
I got the same. First command took only a few sec.

C:\Users\Vitaliy\Articulate\articulate-v0.29.0>docker-compose up -d
Creating network "articulate-v0290_default" with the default driver
Creating articulate-v0290_nginx_1         ... done                                                                      Creating articulate-v0290_api_1           ... done                                                                      Creating articulate-v0290_elasticsearch_1 ... done                                                                      Creating articulate-v0290_duckling_1      ... done                                                                      Creating articulate-v0290_redis_1         ... done                                                                      Creating articulate-v0290_ui_1            ... done                                                                      Creating articulate-v0290_rasa_1          ... done                                                                      
C:\Users\Vitaliy\Articulate\articulate-v0.29.0>docker-compose ps
Системе не удается найти указанный путь.
              Name                            Command               State                Ports
------------------------------------------------------------------------------------------------------------
articulate-v0290_api_1             docker-entrypoint.sh /bin/ ...   Up      0.0.0.0:7500->7500/tcp
articulate-v0290_duckling_1        /bin/sh -c stack exec duck ...   Up      0.0.0.0:8000->8000/tcp
articulate-v0290_elasticsearch_1   /usr/local/bin/docker-entr ...   Up      0.0.0.0:9200->9200/tcp, 9300/tcp
articulate-v0290_nginx_1           nginx-debug -g daemon off;       Up      0.0.0.0:8080->80/tcp
articulate-v0290_rasa_1            ./entrypoint.sh start --pa ...   Up      0.0.0.0:5000->5000/tcp
articulate-v0290_redis_1           docker-entrypoint.sh redis ...   Up      0.0.0.0:6379->6379/tcp
articulate-v0290_ui_1              yarn start:prod                  Up      0.0.0.0:32770->3000/tcp

**Comment by wrathagom** [comment]
huh, everything is running fine. So if you go to localhost:8080 now what happens?

Are there any errors in the browser console?

**Comment by wrathagom** [comment]
Given that your on Windows 10 home, does that mean you're running Docker in a VM? If that's the case your url may not be localhost... it may be the IP of the VM.

**Comment by VitaliyLutskyi** [comment]
![image](https://user-images.githubusercontent.com/47832530/71930693-d66bad80-31a4-11ea-9f60-66de7ab004f8.png)

**Comment by wrathagom** [comment]
This isn't Articulate related.

this is when going to http://localhost:8080 ?

I would try to find the IP of the VM and use that.

**Comment by VitaliyLutskyi** [comment]
Yeah, yo're right. I'm running Docker in a VM. All I needed was to run Articulate using the VM's IP. It works using url [IP]:8080. 
Thanks a lot for help.

**Comment by wrathagom** [comment]
Great, sorry for your troubles!

**Comment by jerry6422** [comment]
Hello! Are you a Small Business Owner or know someone who is, that's tired of being turned down by the traditional banks not wanting to loan you money? If so, please let Mas Financial Services be of assistance to you! We'd love to help you get the capital you need! No collateral is required. Free application. No obligation to proceed! I welcome you to email  us via (masfinancialservices11@gmail.com) and see what we have to offer! Thank you for your time! 
Jim
