### ISSUE TITLE
elasticsearch error

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#981]
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release? latest
- What operating system are you running?CentOS7
- Are you running locally or in the cloud?Locally
- Which browser are you using?Firefox
[elasticsearch.pdf](https://github.com/samtecspg/articulate/files/4052643/elasticsearch.pdf)

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by wrathagom** [comment]
Did you already figure this one out? There have been multiple issues opened for this same error.

I’ll dig up the solution once I’m on a computer.

Please use Gists for long shell snippets, not PDFs.

**Comment by wrathagom** [comment]
Looks like you’ve already had this problem before and solved it...

https://github.com/samtecspg/articulate/issues/945#issuecomment-546966632
