### ISSUE TITLE
Keep getting "undefined" in agent response

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#99]
Here's what the chat looks like, note the last response
<img width="293" alt="2018-02-05_11-24-19" src="https://user-images.githubusercontent.com/1779894/35815696-1fe184f6-0a67-11e8-8219-cfd42982e2b9.png">

and here is the context:
[
  {
    "id": "5",
    "name": "Greet",
    "scenario": "Greet"
  },
  {
    "id": "6",
    "name": "Order Pizza",
    "scenario": "Order Pizza",
    "slots": {
      "Toppings": "null",
      "Delivery Method": {
        "value": "carry out",
        "original": "carry out"
      }
    }
  }
]

@dcalvom I think we have a problem with the Prompts in that they don't check if they received a valid response. So in the above example since it prompted for topping it just assumed that slot was filled even hough it wasn't.

I can fix this with my training, but we should still watch it before we return "undefined"

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/f46d0063f1baeb44b281f699a1096696e04e973e

**Comment by wrathagom** [comment]
@dcalvom what's the behavior now? does it loop until the slot is filled?

**Comment by dcalvom** [comment]
Yes, it randomizes prompt messages until the slot is filled. If the prompt is a template (use other filled slots values) those prompts have priority.
