### ISSUE TITLE
Can't delete News Pre-made category

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#990]
### Issues/suggestion
When I created a News pre-made category, trained tested, I can not delete the category hitting the edit button then delete. Nothing happens, after accepting YES to delete. 

31.1
[Chuck Norris API 2.zip](https://github.com/samtecspg/articulate/files/4186189/Chuck.Norris.API.2.zip)

![image](https://user-images.githubusercontent.com/42249324/74246228-2fea5f00-4cb2-11ea-8375-36747f46e04f.png)

An edit to this. after deleting all the actions attached and sayings of the category I was able to delete the category, however I don't think this is efficient at all. Especially with pre-made categories, its tedious to go and delete every individual action. If it must be like this, then there should be a message that says "can't delete category still sayings/actions attached" 

Windows 10
FF

**Comment by wrathagom** [comment]
There is an error message

![image](https://user-images.githubusercontent.com/1779894/74291988-c3e51680-4d04-11ea-8c30-edd91afe4347.png)

**Comment by RussellSPG** [comment]
I see, didn't notice until convo is pulled up
