### ISSUE TITLE
Error: I'm sorry. An error occurred calling Articulate's converse service. This is not an issue with your agent.

### ISSUE THREAD

**Issue by Neo032020** [samtecspg/articulate#997]
Issues--
*******************************

I created new Agent.. and was doing some changes defining global webhook connection.. 
and they got corrupt.. and became to unusable , in fact they were not being open to work.
as it was working fine when webhook connection defined per Action Wise. having error now after we deleted those corrupt Agent with the help of your this command.. DELETE ​/agent​/{agentId} 

Please help!

![Capture0](https://user-images.githubusercontent.com/62658685/77557554-e65f7780-6edf-11ea-8e83-21246a242c1a.PNG)
 

**Agent-Setting-Webhook tab**
![Capture](https://user-images.githubusercontent.com/62658685/77557163-718c3d80-6edf-11ea-999f-8c73ef2dd0a6.PNG)

  

### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
- What operating system are you running?
- Are you running locally or in the cloud?
- Which browser are you using?

----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by wrathagom** [comment]
Which release?

**Comment by wrathagom** [comment]
@dakavisa can you play around with the global webhook and see if it is obviously broken.

**Comment by Neo032020** [comment]
this one is Articulate v0.31.1 Release

**Comment by Neo032020** [comment]
@wrathagom,
Please will you help me about some points--
-Does Articulate has a training tool for real data? or just process provided **sayings** for training Agent
-Does Articulate Response latency depends on session data user created in Articulate 
-If i say Articulate Response latency goes on increasing on every next call, what could be the factor

**Comment by dakavisa** [comment]
Closed by 27376fb4d846f3686043d608b3308a35b6c38ad1
