### ISSUE TITLE
Values Not Being processed

### ISSUE THREAD

**Issue by stevemr03** [samtecspg/articulate#999]
Operating Environment:
Version 80.0.3987.149 (Official Build) (64-bit) Version 0.31.1  Ubuntu 18.04 running on Chrome over the cloud on a AWS C5.2xlarge instance. 

Articulate does not read all keywords after they have been saved and trained:
	Example:

	Keyword:
	Name: SeverityLevel
	Values and Synonym
	Mild,Mild
	Moderate,Moderate
	Severe,Severe

	Sayings:
	mild
	severe

	If I say "mild" or "severe", this will work
	otherwise(for moderate) it goes to fallback, but adding moderate as a saying then makes moderate work. Why are not all values getting saved to the model? We can not add sayings

	2. Ranking issue for saying

	Here we have two actions:
	1. SelfAction
	2. FamilyMemberAction

	and one keyword section:
	FamilyMember:
	keyword:
	son
	mother
	father
	daughter
	sister

	Sayings:
	my son has a problem (FamilyMemberAction)
	I have a problem (SelfAction)

	try:
	I have a problem===>This goes to FamilyMemberAction but should go into self
	my son has a problem===> works correct

	Why is the order of these causing this bug? What is causing this? Can you fix this so the order does not matter?

**Comment by wrathagom** [comment]
Sounds like you're confusing keywords and sayings. Have you looked at modifiers yet? https://blog.spg.ai/modifiers-in-articulate-86f128b80133

If you want me to help you need to provide me with an expat of your agent. I can't understand from he above what you have in sayings versus keywords versus modifiers. Nor do I understand what is expected and what is happening.

**Comment by stevemr03** [comment]
We see the issue and are switching this to modifiers. Thank you
